### PR TITLE
Upgrade to crossbeam 0.4

### PR DESCRIPTION
**Pull request by dwijnand**
Supersedes #5789

### CODE REVIEW

**Comment by matklad** [comment]
@bors r+

Thanks!

**Comment by dwijnand** [comment]
This is failing in the Rust 1.27.2 (which is the latest stable) job, with:

```rust
error: expected identifier, found `"std"`
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.1/rust/src/liblibc/lib.rs:79:46
   |
79 | #[cfg(feature = "cargo-build")] extern crate "std" as core;
   |                                              ^^^^^ expected identifier
```

while the stable job is passing fine, which is confusing.

@matklad can you make sense of it?

**Comment by matklad** [comment]
This is certainly https://github.com/rust-lang/cargo/pull/5757

r? @Eh2406 
:)

**Comment by dwijnand** [comment]
Thanks @matklad.

lol, from just [2 days ago](https://github.com/rust-lang/cargo/pull/5757#issuecomment-407078218):

> If it turns out that `--minimum-versions` is a constant painful effort to keep up to date then we could remove it again from CI.

Note: I'm not suggesting it's a constant painful effort or that we should remove it from CI, I just thought it was funny that within less than 24 hours it's affected a PR, albeit one about tweaking dependencies.

**Comment by Eh2406** [comment]
I was not able to reproduce locally. I do not have libc 0.1.1 in my lock file with `minimum-versions`. I am updating the latest nightly in the vain hope that that is why.

Can I get an automatic ping on @dependabot PRs?

**Comment by dwijnand** [comment]
Let's see if it fails after a rerunning (triggered by closing and reopening the PR).

For the record these are the failed CI runs:

* https://ci.appveyor.com/project/rust-lang-libs/cargo/build/1.0.5235
* https://travis-ci.org/rust-lang/cargo/builds/407920096
* https://travis-ci.org/rust-lang/cargo/builds/407923316

**Comment by Eh2406** [comment]
douw My bad. :-( I did not have the new branch checked out. Sorry.

**Comment by Eh2406** [comment]
it is a `log v0.3.0` problem. From `rand v0.3.0` From `parking_lot_core v0.2.0`

One fix is to add a synthetic dependency on `parking_lot_core = "0.2.11"`.

**Comment by dwijnand** [comment]
When you get a chance, if you could document how you figure that out, I think it would be useful.

If you have write permissions to the repo feel free to push to my branch, or continue in your own PR. I was just trying to unblock the original PR 🙂. If not I'll try and apply your comments.

**Comment by Eh2406** [comment]
I do not have write permissions, It is all yours!

**Comment by Eh2406** [comment]
https://travis-ci.org/rust-lang/cargo/jobs/408134134 is green! So that is a good sign!

**Comment by Eh2406** [comment]
I like upstreaming the fix, for now this works.

FYI I think it was @joshtriplett idea originally.

**Comment by alexcrichton** [comment]
Thanks for this! I think that the crossbeam crate has actually been split up a bit, could `crossbeam_utils` be brought in instead? I think we may just need the scoped thread support there and it should sidestep the minimal versions issue!

**Comment by dwijnand** [comment]
Oh that sounds plausible. I'll give it a try, Alex.

**Pull request merged**
