### PR TITLE
Add limit parameter to search command (fix issue #2402)

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by jespino** [comment]
This have a problem with a limit greater that 100 (this limit is in the crates.io API). Here I can do 3 things, allow only limits values between 1 to 100, allow any value and let it crash when value is greater than 100, or query as pages as needed for satisfy the limit.

Any suggestion?

**Comment by alexcrichton** [comment]
This looks good to me, I'm fine letting the maximum limit get defined by crates.io so we don't hardcode it in two places.

**Comment by alexcrichton** [comment]
Looks like a test may need to get updated as well?

**Comment by jespino** [comment]
The crates.io maximum is about API results pagination, I think isn't directly related with the maximum on cargo search command, but I think 100 results is enough for the command line interface. I will allow only values 1..100.

**Comment by alexcrichton** [comment]
Looks like the tests may still be failing?

**Comment by jespino** [comment]
Now tests are fixed, I think the problem is a temporary problem obtaining a package.

**Comment by alexcrichton** [comment]
@bors: r+ 53c9374c9f6a72e3c9db0d3c524233f2a04d58a6

Thanks!

**Pull request merged**
