### PR TITLE
Added aliases to subcommand typo suggestions.

### LINKED ISSUE #7278: Include aliases in `no such subcommand` suggestion search
**Describe the problem you are trying to solve**

I have a (perhaps ill-advisedly) large number of project-specific subcommands defined in `.cargo/config`. 

**Describe the solution you'd like**

When I misremember an alias, or typo it, I would love it if cargo included my project's aliases in the list of possible suggestions to use instead.

### PR DESCRIPTION
**Pull request by zachlute**
Fixes #7278.

Also adds tests for alias suggestions.

### CODE REVIEW

**Comment by zachlute** [comment]
This is an improved version of #7288 that uses the existing get_table instead of creating a new method for accessing alias subkeys.

I somehow made that PR insane through using git poorly, so this is just a clean version of that PR.

**Comment by zachlute** [comment]
r? @alexcrichton 

Since he reviewed the original PR.

**Comment by alexcrichton** [comment]
Sorry for the delay in getting to this @zachlute!

I forget if this was handled, but can the [`get` accessor be used instead](https://github.com/rust-lang/cargo/pull/7288#issuecomment-524907374) of `get_table`?

**Comment by zachlute** [comment]
@alexcrichton So, my initial change introduced a new `get_subkeys` (or something like that) method that looked up the individual subkeys on a key. You suggested not adding that new method and using `get` with a custom struct instead.

When I went to make that change, I realized that `get_table` already existed for exactly the purpose I wanted, so I just switched it to using that.

I can make further changes, of course, but this seemed to meet the requirements of 'gets the subkeys without introducing a new method' without also introducing the custom struct for that purpose?

**Comment by alexcrichton** [comment]
Oh sorry this is basically the same thing, just a different formulation. Instead of `get_table` you'd use `get::<BTreeMap<String, String>>`

**Comment by zachlute** [comment]
@alexcrichton Replaced the `get_table` usage as you recommended, and that is indeed nicer and more succinct. 👍

**Comment by alexcrichton** [comment]
@bors: r+

👍

**Comment by alexcrichton** [comment]
er oops

@bors: r+

**Pull request merged**
