### PR TITLE
Default test support's Execs to exit code 0

### PR DESCRIPTION
**Pull request by dwijnand**
Refs #5742

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice! If you'd like it's also fine to make the tests nightly only instead of adding a method to ignore the status too

**Comment by dwijnand** [comment]
Curiously bors didn't notify of the even newer merge conflict in `tests/testsuite/fix.rs`. I'll sort that now.

**Comment by dwijnand** [comment]
Looking for an r+ for old bors-y before this conflicts again :grinning:

**Pull request merged**
