### PR TITLE
Cap lints at warn when cargo installing

### LINKED ISSUE #3453: cargo install should use --cap-lints
I was installing `cargo edit` today, and this is how it failed:
```
error: unnecessary qualification
  --> /home/whitequark/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-edit-0.1.3/src/manifest.rs:13:1
   |
13 | quick_error! {
   | ^
   |
note: lint level defined here
  --> /home/whitequark/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-edit-0.1.3/src/lib.rs:4:176
   |
4  | #![deny(missing_docs, missing_debug_implementations, missing_copy_implementations, trivial_casts, trivial_numeric_casts, unsafe_code, unstable_features, unused_import_braces, unused_qualifications)]
   |                                                                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in a macro outside of the current crate
```
This seems undesirable.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #3453

### CODE REVIEW

**Comment by ehuss** [comment]
I've been pondering this, since I feel a little uncomfortable with how `CompileMode` is doing double-duty and is somewhat overloaded.  I find it confusing in lower-level code where some variants of `mode` are not applicable, and likewise in higher-level code some variants aren't valid.

However, I can't think of a clearly better way to handle it.  `CompileMode` could be split into two enums, but the majority of variants would be the same between them.  

What do you think about, instead of adding a new mode, add `--cap-lints=warn` to `BuildConfig::extra_rustc_args`?  It may not be very elegant, but I think it should work.  Alternatively, maybe in the future, there could be something that manages configuring lints (such as via external files), and that could have the ability to configure things like this.

**Comment by dwijnand** [comment]
I tried that approach first but there's a condition later that errors.  Something about single crates?  My use case passed if I torn out the condition, but I assumed it was there for a reason.

I don't get CompileMode either.

**Comment by ehuss** [comment]
> I tried that approach first but there's a condition later that errors. Something about single crates? My use case passed if I torn out the condition, but I assumed it was there for a reason.

Are you maybe thinking of `CompileOptions::target_rustc_args`?  That's another way of passing args (for `cargo rustc`), and has a side-effect of enforcing compiling a single target only. (It's a bit odd, and that could probably be done in a better way.).  `BuildConfig::extra_rustc_args` is currently unused directly by Cargo and is just a simple way to add more arguments to all rustc invocations.  It shouldn't cause any errors.

**Comment by dwijnand** [comment]
Yeah that sounds familiar.  Ok, I'll try the other way.

**Comment by dwijnand** [comment]
@ehuss this is now a 1-line change.  WDYT?

**Comment by ehuss** [comment]
Hm, I'm sorry, I was mistaken about something.  With this change, warnings will be displayed for all dependencies (normally they are cap-lint allow).  I was thinking that rustc would only honor the last `--cap-lints` on the command line, but it looks like it honors the first.  

Personally I would try to go with the simplest approach, at least for resolving the issue.  I'm thinking maybe just adding a flag to `BuildContext` that `BuildContext::show_warnings` could check.  Sort of a global way to set `--cap-lints=allow`.  It could be a simple bool, or something more sophisticated (like a way to control the lint level).  I would probably just go with a simple bool, and in the future if we add more sophisticated lint controls, it could be extended as needed.  How does that sound?

**Comment by dwijnand** [comment]
> I was thinking that rustc would only honor the last --cap-lints on the command line, but it looks like it honors the first.

I'm with you on that assumption.  Sounds like a bug in rustc.

> How does that sound?

I'm generally anti "boolean blindness".  Seeing as you describe it as "set cap lints allow" I'd just call it cap lints and represent allow as a value.  I'll propose it and we can go back to boolean if not.

**Comment by ehuss** [comment]
Just to be clear, this only affects `cargo install --path`?  Why should that behave particularly differently from `cargo build`, since it is a local project?  I don't see a reason it should behave differently in that case.
I feel like #3453 was fixed in 1.15, which started passing cap-lints (I think maybe as a side effect of #3221).

**Comment by dwijnand** [comment]
I _was_ testing with `cargo install --path .` but if you're saying that #3453 is already fixed then this PR isn't needed.  Thanks for working with me on this, @ehuss.

**Pull request closed without merging**
