### PR TITLE
Build UStar archives by default

### LINKED ISSUE #2326: Some recently built crates fail to unpack
Error observed so far with `selectors = "0.4.0"` and `glutin = "0.4.6"` dependencies.

Output of `cargo build --verbose`:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
unable to get packages from source

Caused by:
  failed to unpack package `selectors v0.4.0`

Caused by:
  No such file or directory (os error 2)
```

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading xml-rs v0.2.2
 Downloading gleam v0.2.3
 Downloading objc v0.1.8
 Downloading dlib v0.2.0
 Downloading dylib v0.0.1
 Downloading core-foundation v0.2.0
 Downloading core-graphics v0.2.1
 Downloading wayland-kbd v0.3.4
 Downloading crossbeam v0.1.6
 Downloading osmesa-sys v0.0.5
 Downloading tempfile v1.1.3
 Downloading byteorder v0.4.2
 Downloading wayland-window v0.2.2
 Downloading shared_library v0.1.2
 Downloading wayland-scanner v0.5.8
 Downloading x11-dl v2.3.0
 Downloading glutin v0.4.6
unable to get packages from source

Caused by:
  failed to unpack package `glutin v0.4.6`

Caused by:
  No such file or directory (os error 2)
```

### PR DESCRIPTION
**Pull request by alexcrichton**
The tar::Builder type by default will build GNU archives, but
unfortunately we force it here to use UStar archives instead. The
UStar format has more limitations on the length of path name that it
can encode, so it's not quite as nice to use.

Older cargos, however, had a bug where GNU archives were interpreted
as UStar archives. This bug means that if we publish a GNU archive
which has fully filled out metadata it'll be corrupt when unpacked by
older cargos.

Hopefully in the future after enough cargos have been running around
with the bugfixed tar-rs library we'll be able to switch this over to
GNU archives, but for now we'll just say that you can't encode paths
in archives that are *too* long.

Closes #2326

### CODE REVIEW

**Comment by alexcrichton** [comment]
gonna go ahead and merge so we can get this into the nightlies.

This is a regression in Cargo, but it's purely on the nightly channel of Rust (e.g. stable or beta channel Cargo versions are not affected). Along those lines, I don't think there's much we need to do here other than recommend authors republish crates with older Cargo installations or newer Cargo builds once this is merged.

@bors: r+ 5c0c21322c611a39b98c99bd8207cccc246917a0

**Comment by alexcrichton** [comment]
cc @brson

**Comment by brson** [comment]
Awesome fast fix. Scary bug.

**Comment by brson** [comment]
@alexcrichton Is this bug in the 1.7 beta's cargo?

**Comment by alexcrichton** [comment]
This bug was introduced in dd342960 when the tar-rs library was upgraded from 0.3.2 to 0.4.0 where 0.4.0 created GNU archives by default. That commit was not in 1.7 beta's cargo, so yay!

**Comment by sourcefrog** [comment]
> Hopefully in the future after enough cargos have been running around with the bugfixed tar-rs library we'll be able to switch this over to GNU archives

Do you think 4.5 years is long enough, or do you have a time frame in mind? I just hit the length limit.

**Pull request merged**
