### PR TITLE
Add favicon to doc.crates.io

### PR DESCRIPTION
**Pull request by jespino**
This fix the issue rust-lang/crates.io#245

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think that this may need to be embedded into the HTML as well, right?

**Comment by jespino** [comment]
Maybe, but a lot of browsers try to take the favicon.ico from the root of the url, anyway I can try to add the header tag to ensure the favicon.ico found.

**Comment by jespino** [comment]
Ok, here is my new proposal, I have moved the jquery loading to the headers too.

Another approach is to use the favicon directly from crates.io (using https://crates.io/favicon.ico) and removing the favicon.ico from the cargo repository.

**Comment by alexcrichton** [comment]
Hm actually for offline docs it probably makes sense to have here as well, so looks good to me, thanks!

@bors: r+ ea41edf3c32682e455161206a4095f4fadb8661b

**Pull request merged**
