### PR TITLE
[BETA-1.66] Fix wait-for-publish with sparse registry

### PR DESCRIPTION
**Pull request by arlosi**
Beta backport of #11356

r? @epage

### CODE REVIEW

**Comment by ehuss** [comment]
I'm a bit confused, can you say more about why this is being backported to beta if sparse registry only works on nightly?

**Comment by arlosi** [comment]
@epage asked to backport it, but since it's nightly only, let's just close it.

**Comment by epage** [comment]
Yeah, my bad for late night posting :). Was thinking through sparse users being impacted but overlooked that it would only be RUSTC_BOOTSTRAP users.

**Pull request closed without merging**
