### PR TITLE
cargo_generate_lockfile: use color to also indicate the change

### PR DESCRIPTION
**Pull request by mathstuf**
In English, `Updating` and `Removing` are the same length and scanning
the list for changes is hard. Use color to help indicate the kind of
change that is occurring.

### CODE REVIEW

**Comment by mathstuf** [comment]
Hmm, playing around with it, it seems that cyan for `Adding` and green for `Updating` might be better since `Updating` is green elsewhere.

**Comment by mathstuf** [comment]
Here's a screenshot with the colors switched as per my previous comment.

cargo-colors

**Comment by alexcrichton** [comment]
@bors: r+

Nice idea!

**Comment by mathstuf** [comment]
Oh, I hadn't done the color flip, sorry. New PR incoming.

**Pull request merged**
