### PR TITLE
Fix: "project" should be "package"

### LINKED ISSUE #11129: Unknown [project] table in cargo docs
### Problem

In the cargo docs there is a reference to a `[project]` table: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace 

I could not find anything about it. Is it maybe meant to say 'package'? Or is it only undocumented?

(I specifically could not find it in the manifest: https://doc.rust-lang.org/cargo/reference/manifest.html)

### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This was accidentially overlooked when writing the documentation.

Closes #11129

@Muscraft I hope I was faster than you!

### CODE REVIEW

**Review by Muscraft — APPROVED** [review]
Thank you for this! You definitely were faster than I was!

To give more context to this PR. There were a few docs that contained `[project]` instead of `[package]` which isn't documented anywhere and really shouldn't be used anywhere. In the early days of cargo (2014 IIRC can't find the change) [`[project]` was renamed to `[package]`](https://github.com/rust-lang/cargo/issues/3388#issuecomment-266504735) and its remnants can be found in different places to this day (a lot in the testsuite).

**Comment by ehuss** [comment]
Testing bors fix
@bors r-

**Comment by Muscraft** [comment]
There still seems to be an error with this. I'll cherry-pick the commit and add it to a branch of mine that needs it. That way it can get merged.

**Comment by weihanglo** [comment]
Close as CI seems broken with no reason (why appveyor revives?!), and the commit is cherry-picked by #11135. Thank you for the quick fix anyway!

**Pull request closed without merging**
