### PR TITLE
Added bash-completion script

### PR DESCRIPTION
**Pull request by critiqjo**
Lists:
- all "installed" commands
- options for basic commands

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice! I think we actually [already have bash completion](https://github.com/rust-lang/cargo/blob/master/src/etc/cargo.bashcomp.sh) and it should be [installed by default](https://github.com/rust-lang/cargo/blob/536c53987bf97d4a1df30d1d25aca6e5c976a61f/Makefile.in#L174) as well. I'm not super familiar with it though, but perhaps it needs to be updated?

**Comment by critiqjo** [comment]
Oh! Sorry, I didn't get that with the package from AUR. So I assumed otherwise. Just ignore this...

**Comment by critiqjo** [comment]
I tried the older just now... And it does need an update...
I've added a few more commands and options to it now. Please check it...

**Comment by critiqjo** [comment]
Please note that 239ce68 is the final version. Sorry for my clumsiness (lack of experience).

**Comment by critiqjo** [comment]
@alexcrichton please don't merge the 51b177c. There is a lag for each tab press. 239ce68 fixes that. I noticed it a minute late.

**Pull request merged**
