### PR TITLE
Fix for #3859

### PR DESCRIPTION
**Pull request by ehiggs**
Stop ignoring .gitnore files. Add a failing test which now passes..

### CODE REVIEW

**Comment by ehiggs** [comment]
Welp, it fails on my test but I'm puzzled how it works on almost every platform but one. Possibly a timing issue with flushing to disk? Or is that just a hunch from working with too many broken parallel file systems?

**Comment by alexcrichton** [comment]
Hm that does seem odd, but it looks like Travis on the PR is also failing for the same reason? It looks like it may be related to a race though as the builder failing is changing?

Perhaps some more debugging information could be added to help diagnose?

**Comment by ehiggs** [comment]
Sorry, I think I wasn't clear. It is failing on travis and the test that fails is the new code I added. I can't reproduce it locally on linux or OS X using `eatmydata` (which is a nice program which makes fsync into no-ops). But I do see failures with all the tests using templates if I just run them as `./target/debug/new-....` so maybe that's a thread to pull on.

**Comment by alexcrichton** [comment]
Interesting!

In the face of https://github.com/rust-lang/cargo/pull/3878 I think we may want to close this though, right?

**Comment by ehiggs** [comment]
With templates pulled out until we have an RFC that's passed, this PR is no longer valid.

**Pull request closed without merging**
