### PR TITLE
Make cargo export `CARGO_TARGET_DIR` to `build.rs` scripts

### PR DESCRIPTION
**Pull request by cbeck88**
Resolves issue #5457

https://github.com/rust-lang/cargo/issues/5457

### CODE REVIEW

**Comment by Eh2406** [comment]
Thank you for getting this conversation started. Looks like CI is failing. This will need to be added to the docs.

The bigger question is how does this work with the direction we are hoping to take the structure of the target directory. @ehuss Thoughts?

**Comment by cbeck88** [comment]
yeah i got a build failure, sorry, will iterate

**Comment by cbeck88** [comment]
so i can try to describe my use-case but it's not unlike what people describe here: https://github.com/rust-lang/cargo/issues/5457

for my purpose, an alternate solution might be not to do this, and instead do:

```
println!("cargo:artifact={}/foo.so", out_dir);
```

and that would tell cargo that something that we produced and placed in `out_dir` should get copied to the `target` dir, whatever it may be

**Comment by alexcrichton** [comment]
Thanks for the PR here @cbeck88, but the first thing that needs to be covered is whether the Cargo team thinks this should happen. Build scripts are intended to have a very scoped output (just in their `OUT_DIR`), and they're not currently really intended to be used as installation scripts for other sorts of files. In that sense this change was never intended for build scripts.

Now that's not to say that this can't happen, but this needs to be considered carefully. For example how would dependencies make use of this? Should this only be set for the "final package"? Is this really all that's necessary for installation? (etc, etc)

**Comment by cbeck88** [comment]
thanks @alexcrichton

**Comment by alexcrichton** [comment]
I'm going to go ahead and close this because I don't think this feature is fleshed out enough yet. I think that this still wants discussion to figure out the best way forward and how Cargo can cater to the use cases mentioned here and in https://github.com/rust-lang/cargo/issues/5457, and I don't think setting this one environment variable is going to be the full fix.

**Pull request closed without merging**
