### PR TITLE
Use poll instead of select to handle large fds

### PR DESCRIPTION
**Pull request by alexcrichton**
It may be the case that Cargo's running around with a lot of file descriptors,
and in this case we wouldn't be able to call `select` due to the file
descriptors being too large and not fitting in the bit array. This switches to
what the standard library is currently doing, using `poll`, which doesn't have
this limitations.

### CODE REVIEW

**Comment by matklad** [comment]
LGTM, but could we offload this all to some library? tokio_process should be able to do this.

**Comment by alexcrichton** [comment]
Perhaps eventually! I think we're not quite ready to pick up that dep yet

**Pull request merged**
