### PR TITLE
fix: make subcommands pick up [env]

### LINKED ISSUE #10094: cargo subcommands do not pick up [env]
### Problem

The [`[env] configuration section`](https://doc.rust-lang.org/cargo/reference/config.html#env) (https://github.com/rust-lang/cargo/issues/9539) does not currently impact subcommand invocations. It's not _entirely_ clear whether this is a bug or by design. My instinct is that it's the former, since otherwise setting, say, `PATH` in `~/.cargo/config.toml` won't affect which subcommands are available, but it could also be argued that it should be up to subcommands whether they _want_ to pick up the current configuration (e.g., they may to reload the config rooted somewhere else, which would mean _not_ picking up `[env]` from `./.cargo/config.toml`).

If this is a bug, it should be fixed.

If it's by design, the documentation should be updated to make it clear that these environment variables do _not_ affect subcommands.

### Steps

_coming soon_

### Possible Solution(s)

The code here

https://github.com/rust-lang/cargo/blob/ad50d0d266213e0cc4f6e526a39d96faae9a3842/src/bin/cargo/main.rs#L171-L174

needs to pick up environment variables from the config in the same way as is done for compilation invocations in

https://github.com/rust-lang/cargo/blob/ad50d0d266213e0cc4f6e526a39d96faae9a3842/src/cargo/core/compiler/compilation.rs#L348-L358

Or, if the decision is to update the documentation instead, this paragraph should be updated

https://github.com/rust-lang/cargo/blob/ad50d0d266213e0cc4f6e526a39d96faae9a3842/src/doc/src/reference/config.md?plain=1#L485-L486

### Notes

_No response_

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

### PR DESCRIPTION
**Pull request by lovesegfault**
### What does this PR try to resolve?

Fixes #10094

This also aims to address some of the issues pointed out in the issue, namely:

> This seems reasonable; we should set the environment variables for third-party subcommands too.

This happens by default now. Users can opt-out by setting `apply_to_subcommands = false` for the var.

> What happens if you set PATH? Does that affect finding the subcommands?

TODO

> What happens if you set CARGO_HOME? Do we read .cargo/config.toml from the new location?
> What happens if you set configuration environment variables?

Setting any `CARGO_` var from `[env]` is now forbidden, and will result in an
error. I'm not sure we want something so strict, so it probably warrants further
discussion.

### How should we test and review this PR?

I added tests `env_external_subcommands` and `env_no_cargo_vars`.

### Additional information

I didn't add any special handling of `PATH`, which means currently it will not
cause the subcommand to not be found, even if the specified `PATH` doesn't
contain the subcommand.

I think this _could_ lead to surprising behavior in a scenario like this:

1. User has `cargo-foobar` in their `PATH`
2. `cargo-foobar` relies on `foobar-cli` being in `PATH`
3. The user has `foobar-cli` in their `PATH`
4. They override `PATH` in `[env]` to one containing neither `cargo-foobar` nor
   `foobar-cli`
5. They can invoke `cargo-foobar`, but it will fail due to `foobar-cli` not bein
   in its `PATH`

Some options to solve this are:

1. We can make the vars apply prior to finding the subcommand, which should make
   `cargo-foobar` to not be found, which is a bit less surprising
2. We make `apply_to_subcommands` default to `false` (the current behavior)

### CODE REVIEW

**Comment by epage** [comment]
> This also aims to address some of the issues pointed out in the issue, namely:

While we understand and appreciate the work that has gone into this, we ask that design discussions happen on Issues first and implementations to wait on the issue being marked as "Accepted'.  Could we move this discussion over to the Issue?

In the mean time, I'm going to close this as there are still open issues on the design that need settling.

From [CONTRIBUTING.md](https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md)
> We encourage people to discuss their design before hacking on code. Typically, you [file an issue](https://github.com/rust-lang/cargo/issues) or start a thread on the [internals forum](https://internals.rust-lang.org/c/tools-and-infrastructure/cargo) before submitting a pull request

From [Process](https://doc.crates.io/contrib/process/index.html)

> Due to limited review capacity, the Cargo team is not accepting new features or major changes at this time. Please consult with the team before opening a new PR. Only issues that have been explicitly marked as accepted will be reviewed.

**Comment by jonhoo** [comment]
@epage I'm a little confused — this follows the suggestions from @joshtriplett in https://github.com/rust-lang/cargo/issues/10094#issuecomment-976791401. I suppose we can take the open questions over there for discussion if that's preferred, though I didn't actually see any disagreement there, so it feels as though these are less open questions and more "we'll need to pick a path and stick with it", with basic consensus on what that path should be.

**Comment by lovesegfault** [comment]
@epage could you chime in on what I should do next to get this fixed?

There is already an issue for this, and there's already been a discussion on how to solve it, with no one disagreeing. I implemented what was proposed there.

What do you think needs settling before I submit this PR?

**Comment by joshtriplett** [comment]
Clarifying something: we had discussions on 10094, and I suggested an approach that I thought would work. This PR, correctly, raised a few additional questions and open issues, as well as design possibilities that we need to decide between. For instance, `apply_to_subcommands`, or the strictness about `CARGO_`, and the issue of `PATH`.

From experience, the Cargo team has found that doing some discussion directly on a PR has been harder and higher-bandwidth for us to deal with than getting the discussion done *first* and then having a PR that implements the conclusion. That way, when we're reviewing the PR, we *just* need to worry about the implementation, and we don't have to simultaneously review design proposals in code form and not just prose form.

Closing this PR is *not* an indication that we don't want to see this change; on the contrary, we definitely want to see things finished and shipped. Rather, we'd just like to direct the design discussion back to the issue, deal with the open design questions, and once we have a settled design we'd be happy to see a PR.

**Comment by jonhoo** [comment]
@joshtriplett That makes sense, thanks for the clarification! Will follow up in the issue 👍

**Comment by epage** [comment]
Sorry for the delay in getting a response back to the confusion over my post.  I had just left on a road trip and wifi didn't work at any of our hotels.  Thanks @joshtriplett for clarifying things in my absence!

**Comment by jonhoo** [comment]
All good — a road trip without WiFi sounds wonderful!

**Pull request closed without merging**
