### PR TITLE
Add support for Azure DevOps

### PR DESCRIPTION
**Pull request by robertohuertasm**
Related to rust-lang/crates.io#1551 which is still pending to be merged.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! This looks good to merge once crates.io is ready, feel free to ping us here when that's merged!

**Comment by robertohuertasm** [comment]
@alexcrichton the PR has been merged but I'm not sure if it has been already deployed. I think @carols10cents is going to leave a message here once this happens.

**Comment by alexcrichton** [comment]
Sounds great, thanks for the ping!

@bors: r+

I'm sure crates.io will deploy before we manage to reach nightlies with this :)

**Comment by carols10cents** [comment]
The crates.io PR is live now :)

**Pull request merged**
