### PR TITLE
Fix fix_path_deps test error.

### PR DESCRIPTION
**Pull request by ehuss**

### CODE REVIEW

**Comment by ehuss** [comment]
This test has been failing a fair bit:

https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/17275967/job/a3g5pmwknyk7xiiq
https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/18375223/job/dt34b41jngxgqd3d
https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/18377838/job/vw9srbgwl6eygjpo
https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/18525511/job/tj5otfhhf01938j1
https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/18558150/job/l69ggfmdrs74x44y
https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/19478171/job/wpyw1vy3n50vngxb
https://ci.appveyor.com/project/rust-lang-libs/cargo/builds/19890689/job/xna48q6vt8moh2vi

I can't repro locally, but this should work.  There's a little race between which side says Checking vs Fixing first. An alternate solution might be to print `Checking` before spawning the thread like this:

```diff
diff --git a/src/cargo/core/compiler/job_queue.rs b/src/cargo/core/compiler/job_queue.rs
index 1bb654d1..5ee957d7 100644
--- a/src/cargo/core/compiler/job_queue.rs
+++ b/src/cargo/core/compiler/job_queue.rs
@@ -400,6 +400,12 @@ impl<'a> JobQueue<'a> {
             let res = job.run(fresh, &JobState { tx: my_tx.clone() });
             my_tx.send(Message::Finish(key, res)).unwrap();
         };
+
+        if !build_plan {
+            // Print out some nice progress information
+            self.note_working_on(config, &key, fresh)?;
+        }
+
         match fresh {
             Freshness::Fresh => doit(),
             Freshness::Dirty => {
@@ -407,11 +413,6 @@ impl<'a> JobQueue<'a> {
             }
         }

-        if !build_plan {
-            // Print out some nice progress information
-            self.note_working_on(config, &key, fresh)?;
-        }
-
         Ok(())
     }
```

**Comment by alexcrichton** [comment]
Ah yeah I think we probably want to guarantee that we print out the result first, want to go ahead and apply the alternative patch to ensure that status messages go out before we spawn work?

**Comment by ehuss** [comment]
> want to go ahead and apply the alternative patch

Sure!  Updated with the alternate approach.  I agree it is better, I was just concerned of unexpected consequences.

**Pull request merged**
