### PR TITLE
Clarify docs on workspace members

### PR DESCRIPTION
**Pull request by shahn**
This is to fix a part of #3966. I am not sure if the semantics are actually correct or if it's even more confusing, please consider that before merging :)

### CODE REVIEW

**Comment by matklad** [comment]
I believe the docs are technically correct, albeit a bit confusing. 

Membership is infered based on path dependencies. That is, if the root of workspace has a path dependency it is included as a member of the workspace, even if it is not in members list. 

In case of a virtual manifest, you don't have any dependencies, so the set of inferred members is empty. 


So what we want to say here is:

"additional non path-dependency members for usual manifest and all members for vritual manifest". 

Not sure how to express this clearly and concisely :)

**Comment by alexcrichton** [comment]
ping @shahn, any thoughts on the comments from @matklad?

**Comment by shahn** [comment]
Will provide new wording, but not before next Monday, been a busy week. Sorry for the delay. If your policy is to close in the interim, please go ahead and I'll reopen/make a new issue later

**Comment by alexcrichton** [comment]
No worries was just curious for an update, thanks!

**Comment by alexcrichton** [comment]
Closing due to inactivity, but please feel free to resubmit!

**Pull request closed without merging**
