### PR TITLE
Clarify error for repo-based dependencies when publishing.

### PR DESCRIPTION
**Pull request by Susurrus**
Elaborate on the exact error cause and directions on how to resolve it.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I do like that from before the message included the url of the source in question as I think that can be useful in tracking this down, perhaps that could still be included? Additionally, could this match what Cargo does for other longer error messages? The general guidelines are:

* A summary sentence with no uppercase letter or final punctuation
* A newline
* A longer summary typically wrapped at 80 chars w/ punctuation

**Comment by Susurrus** [comment]
Okay, my plan is to do:
``
crates cannot be published to crates.io with dependencies sourced from a repository
either publish `{}` as its own crate on crates.io and specify a crates.io \
version as a dependency or pull it into this repository and specify it with a \
path and version
```

But I don't see why the repo URL actually helps since the dependency is called out by name. I think that's just extraneous noise that will also be hard to read because it will probably be a long URL.

**Comment by alexcrichton** [comment]
That message looks good to me! Let's leave the repo URL in there just to be explicit though. Having it on a new line and not intermingled with the message should be ok

**Comment by Susurrus** [comment]
I've added the repo URL and ran all relevant tests locally, hopefully this looks good now.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
