### PR TITLE
Store dependencies as edges of the graph

### PR DESCRIPTION
**Pull request by matklad**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Awesome, thanks!

Much nicer now that it's always `Vec<T>` which has an "empty" state :)

**Comment by alexcrichton** [comment]
@bors: retry

??

**Comment by Eh2406** [comment]
I think I am confused by this. What is being stored? Why a `Graph<PackageId, Vec<Dependency>>` I'd have thought that the data for an edge is A `Dependency` not a `Vec` of them?

For some background I was trying to use this to improve the resolver error messages. Currently they are like:

https://github.com/rust-lang/cargo/blob/0b530c30867da26a4b59146f490c9f1d5377c20a/tests/testsuite/build.rs#L1356-L1358

But if we had a link to the dependency that caused the relationship it could be improved to: (wording needs improvement)

```
  previously selected package `bad v1.0.0`
    ... which is depended on by `bar v0.1.0` which requires `bad: "=1.0.0"`
    ... which is depended on by `incompatible_dependencies v0.0.1 ([..])` which requires `bar: "0.1.0"`
```

**Comment by alexcrichton** [comment]
Oh that'd be awesome to include this info in error messages!

I originally though it was gonna be `Dependency` as well and was surprised myself when it had to be `Vec`, the tl;dr; is basically:

```toml
[dependencies]
foo = "0.1"

[target.foo.dependencies]
foo = "0.1"

[build-dependencies]
foo = "0.1"

# ... etc
```

**Comment by Eh2406** [comment]
Ah, so it is a `Vec` of all the ways that `parent` depends on `child`. They should all apply, at least as resolver sees the world, so `child` must fulfill each of them. Thus the error messages can reasonably use any of them.

**Pull request merged**
