### PR TITLE
fix borrowck-migrate unused mut warnings.

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by dwijnand** [comment]
Oooh. How does one run `borrowck-migrate`?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by dwijnand** [comment]
Trying to answer my own question, it is / might be: `RUSTFLAGS="-Zborrowck=migrate" cargo check -j1`

**Comment by matthiaskrgr** [comment]
@dwijnand yes, you probably also want to add ````--all-targets --all-features```` when checking a crate.

**Pull request merged**
