### PR TITLE
[stable-1.74] chore: bump `cargo-credential-*` crates as e58b84d broke stuff

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

e58b84d3 changed the shape of response of cargo credential protocol trait,
so credential plugins crates effectively depend on `cargo-credential@0.4.0`.
However, `cargo@0.74.0` still depends on`cargo-credential@0.3.0`.
They must depends on the same major version of `cargo-credential`
otherwise incompatible.

Addresses <https://github.com/rust-lang/cargo/issues/13002>

In order to make CI pass, the following PRs are also cherry-picked:
- 3dcf93f20a0cfd2773499fe73afe0d793397ae96 from #12876
- c12c4c3f8d89f41534e51f9ee7641c7a410edf04 from #12921
- Bump `cargo-semver-checks` to 0.24.0 for supporting rustdoc json v27 (the version staring from Rust 1.74.0)

### How should we test and review this PR?

To-dos **after PRs against each branch get merged**:

* Under `rust-1.74.0` branch
    * Publish `cargo-credential-wincred@0.4.0`
    * Publish `cargo-credential-macos-keychain@0.4.0`
    * Publish `cargo-credential-li@0.4.0`
* Under `rust-1.75.0` branch
    * Bump the version to `cargo-credential-wincred@0.4.1`
    * Bump the version to `cargo-credential-macos-keychain@0.4.1`
    * Bump the version to `cargo-credential-li@0.4.1`
* Under `master` branch`
    * Bump the version to `cargo-credential-wincred@0.4.2`
    * Bump the version to `cargo-credential-macos-keychain@0.4.2`
    * Bump the version to `cargo-credential-li@0.4.2`
* Yank
    * Yank `cargo-credential-wincred@0.3.1`
    * Yank `cargo-credential-macos-keychain@0.3.1`
    * Yank `cargo-credential-libsecret@0.3.2`

Not sure if it is necessary to publish a new version of `0.3.x` crates for `cargo-credential-*` before yanking, so I didn't put it in this plan.

### CODE REVIEW

**Comment by ehuss** [comment]
I think that strategy sounds correct. Thank you!

@bors r+

**Comment by smoelius** [comment]
> * Yank
>   
>   * Yank `cargo-credential-wincred@0.3.1`
>   * Yank `cargo-credential-macos-keychain@0.3.1`
>   * Yank `cargo-credential-libsecret@0.3.2`

Sorry, I don't mean to look over your shoulder, but these steps still need to be performed?

**Comment by ehuss** [comment]
@smoelius, yes. It should happen in the next few days. You can follow #13002 to know when it is complete.

**Comment by smoelius** [comment]
Thanks!

**Pull request merged**
