### PR TITLE
Print file paths instead of file:// URLs.

### LINKED ISSUE #4661: "Documenting..." messages should use `\` on windows
Discovered in https://github.com/rust-lang/cargo/pull/4627#issuecomment-339289446, the "Documenting" messages aren't using `\` on windows and should be:

```
failures:
---- doc_multiple_targets_same_name stdout ----
	running `C:\projects\cargo\target\debug\cargo.exe doc --all`
thread 'doc_multiple_targets_same_name' panicked at '
Expected: execs
    but: expected to find:
[DOCUMENTING] foo v0.1.0 (file:///C:/projects/cargo/target/cit/t10/foo[/]foo)
did not find in output:
 Documenting bar v0.1.0 (file:///C:/projects/cargo/target/cit/t10/foo/bar)
 Documenting foo v0.1.0 (file:///C:/projects/cargo/target/cit/t10/foo/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.68 secs
', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by zachlute**
Fixes #4661.

This change ensures cargo will output file paths in the expected format
(C:\foo\... on Windows, /foo/... elsewhere). Previously it would output
file:// URLs instead.

To support this change, additional changes were made to the test suite
string processing such that [ROOT] is now replaced with the appropriate
file path root for the platform.

The CWD template was also updated to use [CWD] like other replacement
templates and to do the replacement on the expected value rather than
the actual value to avoid replacing things we don't expect with CWD.

### CODE REVIEW

**Comment by zachlute** [comment]
Huh. Those tests all pass for me on Windows. Firing up the old slow Mac to check things out there. I suspect it really is bad and my Windows tests pass because [..]:\ ends up happening to match the git path or something. Maybe to make it more robust I need ANOTHER token that is 'match only one character' instead of the existing [..] I have to use for drive root mapping.

Anyway, feel free to disregard this until I get that worked out. Sorry about the trouble.

**Comment by zachlute** [comment]
Though I guess that is a question work asking: I made the decision that git paths should still be file:// URIs, because I think people expect git paths to be URIs, and we tack extra junk on to the end of them that would make it weird as a file path anyway. So please let me know if that seems wrong.

Looks like things fail on my Mac, so I can use that to track down the issues.

**Comment by dwijnand** [comment]
Thank you, @zachlute!

**Comment by alexcrichton** [comment]
Indeed looks great to me, thanks @zachlute!

@bors: r+

**Comment by zachlute** [comment]
@alexcrichton This one should be good to go again if anybody wants to get this on the path to integration before somebody changes all the same strings I did *again*. :)

**Comment by alexcrichton** [comment]
@bors: r+

Of course!

**Comment by dwijnand** [comment]
Sorry for the clash.

**Comment by zachlute** [comment]
Oh no, what does that mean? There doesn't seem to be any way to view a log or anything to know what it was doing.

**Comment by alexcrichton** [comment]
@bors: retry

ah we just gotta try again

**Comment by zachlute** [comment]
Woohoo!

**Pull request merged**
