### PR TITLE
Fix `build-plan` causes everything to need recompiling

### PR DESCRIPTION
**Pull request by edwin0cheng**
This PR fix a [bug](https://github.com/rust-lang/cargo/issues/5579#issuecomment-546760770) which cause everything to recompiling after `cargo build --build-plan`.

Note: This is my first PR in `cargo` repo, so I please tell me if I missed anything.

CC: @CAD97

### CODE REVIEW

**Comment by CAD97** [comment]
cc @vlad20012

**Comment by CAD97** [comment]
The potential issue I see right off the bat is whether this breaks "run build plan" as a way of building. Specifically, if the cache busting behavior is required to make sure an external build system running these steps gets the correct output.

Maybe the solution is to insert the cache busting into the build plan?

**Comment by vlad20012** [comment]
Great! I just thought about how we can workaround this bug in IntelliJ Rust...

**Comment by edwin0cheng** [comment]
@CAD97 If I understand correctly :

1. The build-plan should not executing anything and touch any cache.
2. And I basically touched 3 parts of code, 2 are update the timestamp of files which seem to be harmless. One is removing a file which is not important. (If I understand the comment correctly)

But of course I didn't dig too deep about the whole build-plan flow...

**Comment by edwin0cheng** [comment]
@vlad20012 This bug is blocking us to implement `include!` macro in rust-analyzer too :)

**Comment by edwin0cheng** [comment]
Same as the [comment](https://github.com/rust-lang/cargo/pull/7602#issuecomment-554945602), it looks to be unrelated to my change too. And I tried it for `master` in my Windows machine, it failed too.

**Comment by alexcrichton** [comment]
The Cargo team discussed this PR yesterday and we're somewhat hesitant to merge this due to the state of build plans. I've opened https://github.com/rust-lang/cargo/issues/7614 to continue the discussion about that.

**Comment by edwin0cheng** [comment]
Okay, let this PR closed first and continue the discussion in there.

**Pull request closed without merging**
