### PR TITLE
contrib docs: update rfc and roadmap links

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Thanks.

I feel like it was misplaced under rust-lang org. It should be a repo-level project not org-level.
@ehuss, do you know why it became like this and what's your plan in mind?

**Comment by epage** [comment]
I wonder if this is a old vs new projects thing.  When I migrated to the new projects system, i wasn't given any choice of what it did (granted, migration itself is still in preview)

**Comment by weihanglo** [comment]
I see. I've prefixed all of them with "Cargo". Thank you.

**Pull request merged**
