### PR TITLE
New man pages.

### LINKED ISSUE #5729: man pages are out of date
Someone on IRC noticed that the cargo man pages are a little out of date or wrong.  In particular, `cargo-bench` documents a `--release` flag that does not exist.  Browsing through some of the other entries I see a few that are also out of date.  It might be worthwhile to review all of them and bring them up-to-date.

### PR DESCRIPTION
**Pull request by ehuss**
This is a rewrite and update of the man pages. This also adds them to the website documentation. They are now in Asciidoc format to make it easy to output multiple formats and have decent formatting. There is a Makefile with instructions on how to rebuild the man pages.

Closes #5729.

### CODE REVIEW

**Comment by ehuss** [comment]
This may be difficult to review since there is a lot of content. I recommend checking out this PR and reading it locally. Either run `mdbook serve` in `src/doc` or read the man pages with `man src/etc/man/cargo.1`.

The eventual goal is to be able to read these (somehow) with the verbose flag `cargo help -v build`.

**Comment by joshtriplett** [comment]
I'd like to avoid adding more tools to the toolchain just for manpages and similar. The man format (roff) isn't that hard to write directly when kept simple. And for generation, I'd love to autogenerate it from the command line argument parsing. clap, for instance, is working on manpage generation soon.

**Comment by ehuss** [comment]
I can sympathize with wanting to avoid additional tools for this.  I decided to go this route for the following reasons:
- I wanted to have thorough documentation for each command, with the necessary formatting to present it well.  This includes basic things like lists and tables.  I also wanted both the HTML and man output to look as good as it can, while keeping close to classic man page styling.
- There's no clear timeline for clap being able to do this.  My impression is that it may be a long time.
- Given that it is not using clap, I wanted something with basic templating abilities to reduce duplication.

It would be my preference to have it as part of the code, and I'd be happy to transition it once that's possible.

**Comment by dwijnand** [comment]
> I'd be happy to transition it once that's possible.

I'm all for incremental improvements, and this seems like an improvement on the status quo.

**Comment by nrc** [comment]
This seems fine to me (although it is not optimal, as Josh notes)

> The eventual goal is to be able to read these (somehow) with the verbose flag cargo help -v build.

This eventual goal sounds great.

**Comment by alexcrichton** [comment]
Ok I'm gonna r+ this because it seems like it's good to make incremental improvements, and we can continue to iterate in-tree!

@bors: r+

**Comment by dwijnand** [comment]
In case anyone is interested in reading/subscribing, this seems to be the clap issue for generating man pages: https://github.com/clap-rs/clap/issues/552

**Pull request merged**
