### PR TITLE
Fix custom_target_dependency test.

### PR DESCRIPTION
**Pull request by ehuss**
The feature was renamed in https://github.com/rust-lang/rust/pull/79336

### CODE REVIEW

**Comment by ehuss** [comment]
CI will fail until https://github.com/rust-lang/rust/issues/79459 is fixed.

**Comment by ehuss** [comment]
Also, I'm uncertain why the `Freeze` trait is being defined at all.  It is not needed to compile, but it looks like it was included with a purpose, maybe to verify that you can redefine a lang item?

**Comment by alexcrichton** [comment]
@bors: r+

I think at one point in the past it was required to be defined, but it seems like not anymore?

**Pull request merged**
