### PR TITLE
Remove stale git init comment

### PR DESCRIPTION
**Pull request by tcharding**
Cargo does not intialize a git repository by default.  The docs currently incorrectly state that this is the default behaviour.

Remove incorrect comment about default Cargo --cvs behaviour.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I think though that initializing a git repository is still the default, do you perhaps have configuration locally to turn it off though?

**Comment by tcharding** [comment]
On Thu, Jul 04, 2019 at 11:52:32AM -0700, Alex Crichton wrote:
> Thanks for the PR! I think though that initializing a git repository is still the default, do you perhaps have configuration locally to turn it off though?

Thanks for the response, you are correct it _is_ still the default
behaviour.  FTR the reason I was not seeing this is that the Cargo does
not initialize a git repo if the current directory is already under
source control.

Will update the PR to mention this.  Feel free to just close the PR if
you do not want the added explanation.

Thanks,
Tobin.

**Comment by tcharding** [comment]
If this PR is deemed useful we can probably squash the two commits and rewrite the commit log.  Will do if directed.

This is pretty trivial now, feel free to just drop it - I won't be offended.

**Comment by alexcrichton** [comment]
Ok makes sense the behavior you were seeing before! I think I'm gonna close this for now since this is the intro documentation and we don't necessarily need to call out all the gotchas immediately. We should for sure make sure this is documented in the reference though!

**Pull request closed without merging**
