### PR TITLE
Don't lie about what's Running

### LINKED ISSUE #5964: Command reported as "Running" is a lie
In trying to debug why `cargo +nightly -v fix` fails with:

```
...
error: failed to execute compile
caused by: Bad absolute path
error: failed to execute compile
caused by: Bad absolute path
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `/Users/dnw/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo rustc --crate-name libc /Users/dnw/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.43/src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=298f10ebfe4edf39 -C extra-filename=-298f10ebfe4edf39 --out-dir /d/hubcaps/target/debug/deps -L dependency=/d/hubcaps/target/debug/deps --cap-lints allow` (exit code: 2)
warning: build failed, waiting for other jobs to finish...
...
```

I ran the indicated command, which instead fails with:

```
08:54:12 ! /Users/dnw/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo rustc --crate-name libc /Users/dnw/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.43/src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=298f10ebfe4edf39 -C extra-filename=-298f10ebfe4edf39 --out-dir /d/hubcaps/target/debug/deps -L dependency=/d/hubcaps/target/debug/deps --cap-lints allow
error: Found argument '--crate-name' which wasn't expected, or isn't valid in this context

USAGE:
    cargo rustc [OPTIONS] [--] [args]...

For more information try --help

08:54:13 ! echo $?
1
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #5964

### CODE REVIEW

**Comment by dwijnand** [comment]
Hmm, looks like there are lots of tests that assert things on 

```
[RUNNING] `rustc ...
```

How do we want to resolve this?

**Comment by alexcrichton** [comment]
Oh I don't think we can remove emissions of `Running` entirely, but I was thinking that we may be able to apply a cargo-check specific fix. The `Running` directive is often useful for figuring out how to run rustc manually in quick debug situations.

**Comment by dwijnand** [comment]
What cargo-check specific fix did you have in mind?

**Comment by dwijnand** [comment]
I'm kind of torn about it. Lying is not good, but even a quasi-truth can be useful (as testified by its usage in the testsuite).

What would it take to make cargo-check's "Running" output accurately (or more accurately) reflect reality? For instance, what's the business about `--crate-name`?

**Comment by alexcrichton** [comment]
Technically speaking it's not actually lying, it's just speaking the quasi-truth you mention. Cargo sets a number of environment variables for itself which changes its behavior when executed, so to more accurately reflect what's going on we'd need to print env vars as well

**Comment by dwijnand** [comment]
Superseded by #6017.

**Pull request closed without merging**
