### PR TITLE
Support --quiet for --list subcommand

### PR DESCRIPTION
**Pull request by hrls**

### CODE REVIEW

**Comment by ehuss** [comment]
I don't think `--quiet` is the appropriate flag, since it says `No output printed to stdout` but this still prints to stdout.  I also don't equate "quiet" with "machine-parseable".  Can you say more about the motivation for this change?  There are several scripts which use the current format without problems.

**Comment by hrls** [comment]
I need something like `brew commands --quiet` – simple list of all commands without any headers or additional info. Just for generate some auto-completion list without any other tools.
FYI, `--list --quiet` will print just as `--list`, flag is ignored currently.

**Comment by dwijnand** [comment]
I'd be fine with this, but with the following changes:
* a change to the description of `--quiet`, maybe something like "Less output printed to stdout"
* a test capturing the behaviour, ideally including an external command
* perhaps comment the `args.is_present("quiet")` line explaining it's used for completions

**Comment by alexcrichton** [comment]
I'm gonna close this since it's been in active for some time now, but it can of course be resubmitted!

**Pull request closed without merging**
