### PR TITLE
homedir(): add special case for Haiku

### PR DESCRIPTION
**Pull request by jessicah**

### CODE REVIEW

**Comment by jessicah** [comment]
I'm not sure if this is really the best way to implement this, but Haiku generally avoids dotfiles in the user's home directory, and should be placed in the settings folder without a leading dot.

**Comment by alexcrichton** [comment]
I think this may be best suited for https://github.com/rust-lang/rfcs/pull/1615 perhaps? I'd be hesitant to merge this before that RFC is decided on

**Comment by jessicah** [comment]
Ah yes, I was considering using one of the XDG environment variables, as these point to correct locations on Haiku.

**Comment by alexcrichton** [comment]
Ok in light of that I'm going to close this for now, but hopefully it's easy to resubmit once the RFC is decided on!

**Pull request closed without merging**
