### PR TITLE
Force `cargo fix` to rebuild

### LINKED ISSUE #5736: Figure out how to force `cargo fix` to run
Moved over from https://github.com/rust-lang-nursery/rustfix/issues/79, I hear @killercup has a fix in mind!

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #5736

This is a resubmit of @killercup's #5750, rebased on current master.

@alexcrichton From browsing the code I feel like `-p` would still restrict the packages to rebuild, despite the rebuild flag added. But I might be misreading or not-fully-reading the code. Could you give me some mentoring instructions for the test cases you're concerned with?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ah yeah sure! I believe the pathological behavior can be seen by adding a dependency and I believe both invocations (in the test) will recompile the dependency, but only the requested crate (the one we're fixing) should be recompiled

**Comment by dwijnand** [comment]
Thanks @alexcrichton I was able to come up with a test. It fails with this PR because it aggressively rebuilds and fails without this PR because it doesn't rebuild anything. 😄

Now on how to fix the problem..

**Comment by alexcrichton** [comment]
Oh interesting, looks like CI passed? I personally prefer to use `with_stderr` as it's a more exhaustive match which may help?

**Comment by dwijnand** [comment]
Yep, I think this is fixed/done now! Good shout on using `with_stderr`, looks good now.

**Comment by dwijnand** [comment]
My friend `path::deep_dependencies_trigger_rebuild`

**Comment by alexcrichton** [comment]
@bors: r+

Clever!

**Pull request closed without merging**
