### PR TITLE
Warning when using features in replace

### PR DESCRIPTION
**Pull request by hi-rustin**
close https://github.com/rust-lang/cargo/issues/3034 
close https://github.com/rust-lang/cargo/issues/2582

r? @ehuss

### CODE REVIEW

**Comment by hi-rustin** [comment]
It seems difficult to trigger a warning here, so I simply rejected it.

It might be a better solution if we could add the warning elsewhere. Because rejecting it directly may affect users in a big way.

Also, we need a test for default-features and I will add it after we decide whether to warn or reject.

**Comment by ehuss** [comment]
Hm, instead of putting these checks deep in the query system, can both `patch` and `replace` checks be moved to `toml/mod.rs` when they are parsed? There should be some place to conveniently place a check there where the code can be shared for both of them.

**Comment by ehuss** [comment]
Hm, nevermind, I forgot about patch-in-config. 

Perhaps moving the check to somewhere like `resolve_ws_with_opts`?  There's already a warning there about unused `replace` entries.  I think a warning about unused features might also work there.

**Comment by hi-rustin** [comment]
@ehuss  Thanks for your help!

Addressed.

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
