### PR TITLE
Cargo CLI parameters added

### PR DESCRIPTION
**Pull request by kolipka**
Proposition for discussion in issue #3646

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR, but a change such as this I think definitely requires an RFC. There's a lot of unintended interactions with this feature and the rest of the CLI interface with Cargo, so I don't think that it's going to be so easy to add the feature. If you'd like assistance in writing an RFC though, please just let me know!

**Comment by kolipka** [comment]
I would love to write RFC, if you can point me where to start I will do it.

**Comment by alexcrichton** [comment]
Sure yeah, it would end up being a PR against this repo: https://github.com/rust-lang/rfcs

In general though you may wish to work through the design details first and I wouldn't mind taking a look ahead of time as well. I'm specifically worried about commands like `cargo test` and `cargo run` which already take arguments, so how would we know what arguments go to the build script? Additionally, how do we know which build script to send arguments to? Should we support sending arguments to more than one build script?

**Comment by kolipka** [comment]
I had less time to spend on it, so sorry for delay.
1. I am wrong and totally misunderstood docopt. It should be done exactly as `cargo test` and `cargo run`.
2. For now I have no idea how to pass args to custom_build.rs. I think that all args should be considered as a part of configuration, so should end up in Config. I suspect it still qualify for RFC?

I think that only one build script should get arguments. When I call `./test.sh -a` only `test.sh` will get `-a` argument. It will parse it and instrument it's dependencies in some way. When I want to instrument set of tools I will use environment variable (eg.: CC, CROSS_COMPILE).

**Comment by alexcrichton** [comment]
Right my question is where are arguments even specified? For `cargo test` all extra arguments to Cargo are already specified as going to the test

**Pull request closed without merging**
