### PR TITLE
Update linux-raw-sys to 0.3.2

### PR DESCRIPTION
**Pull request by heiher**
Adds support for LoongArch.

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Thanks for the pull request. I hope there are more contexts for Cargo maintainers to digest in the PR description. Specifically,

* Why issue did you encounter in Cargo with LoongArch?
* Why do you think bump this would fix the issue?
* Given ` loongarch64-unknown-linux-gnu` a tier-3 toolchain. AFAIK, Rust doesn't guarantee tier-3 toolchain to have stable host tools. In that regard, is this PR still relevant?

Anyway, it seems pretty straightforward and no harm for a bump. Just request for information. Thank you!

**Comment by heiher** [comment]
@weihanglo Thanks for your comments.

> Why issue did you encounter in Cargo with LoongArch?

In the current version of Cargo's dependency graph, there is an indirect dependency on linux-raw-sys which does not yet have support for LoongArch.

> Why do you think bump this would fix the issue?

The linux-raw-sys has been supporting LoongArch since version 0.3.2.

> Given  loongarch64-unknown-linux-gnu a tier-3 toolchain. AFAIK, Rust doesn't guarantee tier-3 toolchain to have stable host tools. In that regard, is this PR still relevant?

We are preparing to promote loongarch64-unknown-linux-gnu to Tier 2 and adding [CI support](https://github.com/rust-lang/rust/pull/110519) based on this PR will be necessary.

Thank you.

**Review by weihanglo — APPROVED** [review]
Make sense to me. Going to merge this. If you find anything wrong, say it and we can rollback if needed.

**Pull request merged**
