### PR TITLE
Bump miow dependency to not invalidly assume memory layout

### PR DESCRIPTION
**Pull request by faern**
See https://github.com/rust-lang/rust/pull/78802 and https://github.com/yoshuawuyts/miow/pull/39

### CODE REVIEW

**Comment by faern** [comment]
I don't think the CI failures are because of the changes in this PR?

**Comment by Eh2406** [comment]
Yes the CI problems are unrelated, cc https://github.com/rust-lang/cargo/pull/8907

**Review by alexcrichton — APPROVED** [review]
lgtm, we'll get this merged when CI is fixed.

**Pull request merged**
