### PR TITLE
Implement target-features flag

### PR DESCRIPTION
**Pull request by srijs**
This is a beginner's shot at #1137. Not sure this is the way you'd want to do this, but I'm happy to learn from mistakes ;)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Right now, however, Cargo isn't trying to expose an exhaustive set of flags from the compiler at the top level (that would be quite a few). Instead we've been holding out for extensible strategies to solve issues like https://github.com/rust-lang/cargo/issues/544 (for example https://github.com/rust-lang/cargo/issues/595).

It's also not 100% clear to me whether configuration like this belongs in the `Cargo.toml`'s `[profile]` sections or on the command line.

**Comment by srijs** [comment]
Admittedly, I am scratching my own itch here, but I think it is important to expose that particular flag, because it is actually influencing whether a build succeeds or not, while other arguments regarding "somehow passing flags" to the compiler have been revolving around adding flags to debug issues, or change subtleties in optimisation. The impression I had of the `[profile]` feature is that it serves the same purpose, specifying things like optimisation levels or debug information, which is why I think it might not be the right place for this flag.

**Comment by alexcrichton** [comment]
The unfortunate part is that the compiler exposes *many* options like this, and Cargo either needs to bind all of them or provide a generic means of specifying them to the compiler. This is the purpose of the `cargo rustc` command partly (generically specifying flags for any crate).

Configuration options such as this are very target-specific, and also arguably belong in a custom target specification that's read in by the compiler.

**Comment by srijs** [comment]
> Configuration options such as this are very target-specific, and also arguably belong in a custom target specification that's read in by the compiler.

Could you elaborate a bit on this? Is this a deliverable that would be independent from the "generic" solution `cargo rustc`?

**Comment by alexcrichton** [comment]
Ah indeed! [Custom target specifications](https://doc.rust-lang.org/rustc_back/target/) are a means of passing a custom `--target` flag which is described by a JSON file. The file describes how all artifacts for that target should be built, including the set of features which are passed down to LLVM.

**Comment by alexcrichton** [comment]
Closing due to may last comment,  plus `cargo rustc` is now implemented!

**Pull request closed without merging**
