### PR TITLE
fix(fingerpring): do not touch intermediate artifacts

### PR DESCRIPTION
**Pull request by schomatis**
Fixes https://github.com/rust-lang/cargo/issues/6972.

The newly introduced [test](https://github.com/rust-lang/cargo/pull/7050/commits/9aa7a4dce5f47e49c4100ff18a9dc0dc5a47efc4) is [failing](https://travis-ci.com/rust-lang/cargo/jobs/209849725#L2569-L2580) as discussed in https://github.com/rust-lang/cargo/issues/6972#issuecomment-502241124 (replicating the issue). Removing the `touching of intermediate artifacts` as suggested fixes the issue, but makes the old test `simple_deps_cleaner_does_not_rebuild` fail. The `simple_deps_cleaner_does_not_rebuild` test is not needed anymore so it's removed.

r? @Eh2406

### CODE REVIEW

**Comment by Eh2406** [comment]
Looks good! Let me know when you think it is ready!

**Comment by schomatis** [comment]
@Eh2406 Last commit is passing so ready.

**Comment by schomatis** [comment]
(forget to `rustfmt`)

**Comment by schomatis** [comment]
Thanks @Eh2406 for the guidance throughout this issue! And also thanks to @ehuss for the great document about [fingerprints](https://github.com/rust-lang/cargo/blob/142603ae222defed68b9daf5771bce85b005f84f/src/cargo/core/compiler/fingerprint.rs#L1-L188) which was what allowed me the insight to delve in this issue in the first place, I think is documentation like that one that empowers the community to take action in a project.

**Comment by Eh2406** [comment]
Thanks for the help! We agree and are trying to improve the internal documentation. As someone with a  fresh perspective what did you have trouble understanding / where can we improve the docs more?

**Comment by schomatis** [comment]
Well, if I have to name one off the top of my head the thing I struggled the most while navigating through the code was that I didn't have a clear high level perspective of where were the important bits of the system I had to follow to reason about how were the fingerprints used. I think something like that would belong in the [architecture](https://github.com/rust-lang/cargo/blob/782266aaeef3cbfac3de89aa69805668669b3307/ARCHITECTURE.md) documentation or a sub-document of it (the current information there is useful but I feel it falls short to match the huge system on interconnected components Cargo encompasses). But now that you mention you're interested, if I see a concrete opportunity to improve documentation on a certain topic I'll submit an issue about it.

**Pull request merged**
