### PR TITLE
Add uninstall target in makefile

### LINKED ISSUE #1068: No 'make uninstall"
Shouldn't there be a 'make uninstall'. If I were to manually remove all the files what would I need to do?

### PR DESCRIPTION
**Pull request by Dineshs91**
Fixes #1068.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Shouldn't this pass in the same prefix and destdir? Could this also modify `.travis.yml` to run `make uninstall` to make sure it works?

**Comment by Dineshs91** [comment]
I believe destdir and  prefix are options for setting installation root and setting installation prefix respectively. Are those really required for uninstallation ?

**Comment by Dineshs91** [comment]
Oh wait. I get it now, you are right. They are indeed required. I will add those.

**Comment by Dineshs91** [comment]
@alexcrichton I had to add sudo make install, before uninstalling as cargo is never installed.

**Comment by alexcrichton** [comment]
@bors: r+ ee47eda

Thanks!

**Pull request merged**
