### PR TITLE
Bail out when trying to link to a library that is not linkable.

### PR DESCRIPTION
**Pull request by lukaslueg**
There are more subtleties here than expected, as we can have situations where it is actually Ok to have no linkable targets: Build scripts are a common case, yet benchmark tests started to also fail. I have to say I'm not convinced if the situation "not one target is linkable, yet at least one target is a library (and therefor at least something should be linked)" is actually correct. All tests pass, however, including the one that checks for #3169

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks great, thanks! I would hesitate here, however, mostly due to backwards compatibility. For example today while this is guaranteed to fail for `extern crate` it *may* be used to ensure that set of dylibs are compiled, for example.

That may point to this wanting to be a warning rather than an error, but if we do that then we'd also need to provide some assurances that the warning can be suppressed as well. I'm curious, what do you think along this front?

**Comment by lukaslueg** [comment]
I wondered about that as well as the original test did not include the `extern crate` and passed just fine, so strictly speaking this change turns into a hard error what was previously accepted behaviour. Does it make sense to depend on a package that `is_lib()` but is not `linkable()` ? It could be acceptable behaviour to depend on something "just so it's there" without ever using it: If there is no `extern crate` everything is fine...

I did a quick survey of all ~71.000 crates on crates.io and siphoned the `crate-type` in the manifests:

     60 crate-type = ["dylib", "rlib"]
     33 crate-type = ["rlib"]
     32 crate-type = ["dylib"]
     11 crate-type = ["rlib", "dylib"]
      9 crate-type = ["rlib", "dylib", "staticlib"]
      6 crate-type = [ "dylib" ]
      6 crate-type = ["cdylib", "rlib"]
      4 crate-type = ["cdylib"]
      2 crate-type = ["staticlib"]
      2 crate-type=["rlib", "dylib"]
      2 crate-type = ["dylib"]
      1 crate-type = ["proc-macro"]
      1 crate-type = ["bin"]

So `staticlib` is exceedingly rare and probably a misstake in their respective first place. However I'd go with a Warning and decide wether to be able to suppress it or turn it into a hard error if the issue comes up.

**Comment by alexcrichton** [comment]
Thanks for the analysis!

Yeah I don't currently know of a use case of where you'd depend on a cdylib/staticlib via `[dependencies]`. That being said I've learned time and time again that just because I can't think of something doesn't mean someone else won't!

Maybe we can start with a warning (saying it'll become a hard error if you don't report an issue) and go from there?

**Comment by lukaslueg** [comment]
I've force-pushed the Warning. Notice that the test now ensures that cargo succeeds when there is no `extern crate`.

**Comment by lukaslueg** [comment]
failing travis seems unrelated

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by novafacing** [comment]
@alexcrichton and @lukaslueg I have a use case for which this becoming a hard error would be a blocker: fuzzing (actual use case: sanitizers). When building a fuzzer, we want to only sanitize the target, so I very frequently will make my target (the software under test) `crate-type = ["staticlib"]`. I'll then use a build script like this:

```rust
use std::{env::var, process::Command};

fn main() {
    let status = Command::new("cargo")
        .arg("rustc")
        .arg("-p")
        .arg("first-target")
        .arg("--target-dir")
        .arg("target/first-target/")
        .arg("--")
        .arg("-C")
        .arg(format!(
            "opt-level={}",
            var("OPT_LEVEL").expect("No OPT_LEVEL variable set")
        ))
        .arg("-C")
        .arg("prefer-dynamic")
        .arg("-C")
        .arg("passes=sancov-module")
        .arg("-C")
        .arg("llvm-args=-sanitizer-coverage-level=3")
        .arg("-C")
        .arg("llvm-args=-sanitizer-coverage-inline-8bit-counters")
        .arg("-C")
        .arg("llvm-args=-sanitizer-coverage-prune-blocks=0")
        .arg("-C")
        .arg("link-dead-code")
        .arg("-C")
        .arg("lto=no")
        .arg("--emit=dep-info,link")
        .status()
        .expect("Failed to spawn Cargo");

    assert!(status.success(), "Target build command failed");

    println!("cargo:rustc-link-lib=first_target");
    println!(
        "cargo:rustc-link-search={}/target/first-target/debug/",
        env!("CARGO_MANIFEST_DIR")
    );
}
```

To produce a `.a` staticlib from that crate (which *is* a dependency, because that lets me avoid having to do a bunch of explicit path nonsense), so that I can call into the coverage sanitized library like:

```rust
extern "Rust" {
    fn decode(encoded_input: &[u8]) -> Vec<u8>;
}

fn main() {
  unsafe { decode("AAAAA".as_bytes()) };
}
```

I beg you, please don't make this a hard error, I'm doing it on purpose!

**Comment by weihanglo** [comment]
@novafacing, I don't think commenting on a 5-year-old pull request would help. I'd recommend filing a new issue to raise the visibility to the current maintainers.

**Comment by novafacing** [comment]
Sure, this PR is linked in a *lot* of places so I figured it's what people have watched, but I'll make a new issue.

**Pull request merged**
