### PR TITLE
Required dependencies are not features

### LINKED ISSUE #4363: Warn or error when using mandatory dependencies as a feature
Currently, Cargo warns when I ask for a feature of another crate that does not exist. However, it seems that it treats all dependencies also as features. For optional dependencies, this makes sense, and indeed the documentation says "A feature of a package is either an optional dependency, or a set of other features."

So, I can depend on `regex = { version = "0.2.2", features = ["memchr"]}` and there is no warning or error that this (a) doesn't make any sense, and (b) `memchr` is not technically a feature according to the definition of the docs (and indeed, it should not be).

### PR DESCRIPTION
**Pull request by RalfJung**
Also, while I was at it, I fixed an error message which complained about something not being an optional dependency, when really what mattered was that it was not a dependency at all.

I made a bunch of guesses about how things work. These guesses ended up as comments in the commit (so hopefully, the next reader of these files has to guess less). I am not totally certain these comments are all correct, so please yell if not. :)

In particular, for resolve_features, I observed that dependencies get compiled even when they are not returned from that function. But judging from how the function used to behave, it actually returns all dependencies, even those that have nothing to do with any features. (Making the name rather misleading, TBH...)

Fixes #4363

### CODE REVIEW

**Comment by RalfJung** [comment]
As @sfackler [pointed out](https://github.com/rust-lang/cargo/issues/4363#issuecomment-320400089), this is a breaking change. I have no idea what the process is for that with cargo.

**Comment by alexcrichton** [comment]
This looks great to me, thanks for finding and fixing this! I agree with @sfackler though that we'll likely want to ease this transition through warnings rather than errors to start out with. Right now we unfortunately don't have a *great* way of doing this during resolution, but I think we'll want to do something that looks like:

* Add an `RcList<String>` to [`Context`'s struct fields](https://github.com/RalfJung/cargo/blob/fa1ef65f396ef722531ae46d3f016bc4091160ad/src/cargo/core/resolver/mod.rs#L319)
* Store warnings in a `Context` as we see them
* [After we're done resolving](https://github.com/RalfJung/cargo/blob/fa1ef65f396ef722531ae46d3f016bc4091160ad/src/cargo/core/resolver/mod.rs#L349) emit all warnings that were found for the graph we selected

Does that sound reasonable?

**Comment by RalfJung** [comment]
I can try doing that. However, I am not sure when I will have the time, so this may take a week or so.

**Comment by RalfJung** [comment]
I think I mostly got this, but there is one problem: The warning is emitted twice for the second of my testcases (`invalid10`). Probably resolution is called multiple times?

**Comment by alexcrichton** [comment]
@RalfJung ah yeah resolution is currently called twice, but it's fine to just emit the warning once, perhaps just a new boolean to the resolution function?

**Comment by RalfJung** [comment]
It seems to be called twice for one test, but only once for another test? Also, how would I even distinguish the two calls? I mean I could use a `static mut` but that just sounds wrong.^^ The code calling `resolve` is a complete mystery to me.

Is it even guaranteed that the two calls to resolution will use all the same settings and everything, and hence show the same warnings?

**Comment by alexcrichton** [comment]
[This is the one location](https://github.com/rust-lang/cargo/blob/d3366336bbeca205ae5187b5a40cbaef8380647b/src/cargo/ops/resolve.rs#L44-L82) where resolution happens twice. If the first `resolve_with_registry` executes then the second `resolve_with_previous` doesn't need to emit warnings. Otherwise `resolve_with_previous` needs to emit warnings.

**Comment by RalfJung** [comment]
Can I assume in general that when `resolve_with_previous` is called with a non-`None` `previous: Option<&'a Resolve>`, then no warnings need to be printed?

**Comment by alexcrichton** [comment]
Maybe? Don't know that off the top of my head. One way to find out!

**Comment by RalfJung** [comment]
Well, I will see if that's the case of the two test cases I have. That doesn't leave me very confident.

But I guess this doesn't actually work -- looking at `resolve_with_registry`, it passes `ops::load_pkg_lockfile(ws)?.as_ref()` for the `previous`.

**Comment by RalfJung** [comment]
All right, I got something that makes the tests pass. However, I had to actually let the second resolution in this function you pointed to print warnings -- the first one would not print anything.

**Comment by RalfJung** [comment]
Dang. Seems like getting access to the shell here conflicts with someone else already having taken access. I'll try to refactor this, maybe that helps.

**Comment by RalfJung** [comment]
It seems that did it :)

**Comment by alexcrichton** [comment]
@bors: r+

Thanks so much!

**Pull request merged**
