### PR TITLE
Update two tests for changes in rustc output

### PR DESCRIPTION
**Pull request by petrochenkov**
Required for landing https://github.com/rust-lang/rust/pull/63250.

(I'm not sure what is the process for landing synchronous changes like this.)

### CODE REVIEW

**Comment by alexcrichton** [comment]
The easiest thing here is probably to relax the assertion by changing `module` to `[..]`, and that should pass on both I think?

**Comment by petrochenkov** [comment]
Updated with `[..]` instead of `crate`.

**Comment by ehuss** [comment]
@petrochenkov Feel free to update the cargo submodule in your PR if you think it will get merged within the next week or so.  Or if you'd prefer, I can post an update PR, but you'll have to wait for it to make its way through the bors queue.  Just let me know.

**Pull request merged**
