### PR TITLE
Bump cargo library to 0.72.2 for CVE patches

### LINKED ISSUE #12460: missing 0.72.2 tag
👋 while [upgrading rust to 1.71.1 on the homebrew side](https://github.com/Homebrew/homebrew-core/pull/138466), we found that the 0.72.2 tag is missing? Is that intentional, thanks!

### PR DESCRIPTION
**Pull request by weihanglo**
Fixes #12460 

In order to make CI pass, these pull request has been cherr-picked:

* #12213
* #12413
* #12429
* #12450

### CODE REVIEW

**Comment by ehuss** [comment]
I imagine there are going to need to be some backports to get CI passing. Can you identify how many will be needed?

**Comment by weihanglo** [comment]
Wish we could have ##12181…

I'll ping you when ready :)

**Comment by weihanglo** [comment]
I guess that's it. Feel uncomfortable with nightly changes, especially `internal_features` stuff.

cc @ehuss

**Comment by ehuss** [comment]
Those look fine to me, since they are mostly for tests which aren't important for publishing the library. The clone change seems harmless.

Thanks!

@bors r+

**Pull request merged**
