### PR TITLE
Packages can inherit fields from their root workspace

### PR DESCRIPTION
**Pull request by Muscraft**
Tracking issue: #8415
RFC: rust-lang/rfcs#2906

All changes were heavily inspired by #8664 
A big thanks to both @yaymukund  and @ParkMyCar. I pulled a lot of changes from their branches.

All changes have been made according to the RFC as well as @alexcrichton's [comment](https://github.com/rust-lang/cargo/pull/8664#issuecomment-704878103). 

This makes it so that typically a workspace is found before parsing any manifests into packages. Allowing for reduced searching for a root workspace to pull things from. When looking for a path dependency's version (if not specified) there are situations where you have to find the root workspace to find the version but this appears to be very rare. 

There are [a](https://github.com/Muscraft/cargo/blob/3327880c6e38fd2e78fff220ff2b91cddb168d50/src/cargo/util/toml/mod.rs#L253-L287) [few](https://github.com/Muscraft/cargo/blob/3327880c6e38fd2e78fff220ff2b91cddb168d50/src/cargo/util/toml/mod.rs#L2452-L2523) [problem](https://github.com/Muscraft/cargo/blob/3327880c6e38fd2e78fff220ff2b91cddb168d50/src/cargo/util/toml/mod.rs#L2169-L2240) areas in [cargo/src/cargo/util/toml/mod.rs](https://github.com/Muscraft/cargo/blob/3327880c6e38fd2e78fff220ff2b91cddb168d50/src/cargo/util/toml/mod.rs) where things get a bit clunky and verbose. I wasn't quite sure how to fix those spots and any help to those areas is appreciated. I also pulled how to [join relative paths](https://github.com/Muscraft/cargo/blob/3327880c6e38fd2e78fff220ff2b91cddb168d50/src/cargo/util/toml/mod.rs#L2014-L2063) from [this repo](https://github.com/Manishearth/pathdiff/blob/30bb4010a7f420d8f367b0a0699ca42b813ce73d/src/lib.rs). I couldn't find a way within Cargo to join the relative paths correctly so I used that. 

Please let me know if this isn't how you expected the changes to be made. I'll be happy to rework anything necessary.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks so much for helping to push this forward!

I've done a once-over of the PR and here's some thoughts I've got so far:

* Could you add some tests for success about using dependencies from separate workspaces? It looks like there's a bunch of negative tests (for compile failures) which is great, but I think it'd also be good to test things where a git or a path dependency is used to make sure they load workspace values from the right place. Additionally I think it'd be good to test that there's two workspaces which have two different definitions of a workspace dependency `foo`, and we should be able to use those two workspaces together (e.g. the second is used via a git or a path dependency).
* Could you add a test to ensure that the published manifest on crates.io has all of the workspace fields elaborated and filled in? I see there's tests for the JSON metadata but I think we'll probably want one for the manifest as well.
* I was a bit sad how many places needed `InheritableFields` to get threaded around. This feature feels like it should ideally be largely isolated to TOML parsing and not have a ton of impact on other portions of the codebase, but threading this field around feels sort of error-prone and difficult to manage. It's also stored in structures like `PackageRegistry` which feels odd since that in theory doesn't configure TOML parsing much. One possible alternative to this I can think of is to have a cache of "manifest path to workspace fields" located in the `Config`. That way the toml parsing could consult this cache and lazily populate it as necessary.
* I haven't read too too closely or confirmed this, but I'd be a little worried that TOML files are parsed multiple times with this implementation (namely the workspace root). Would you be up for adding some instrumentation to confirm that we parse manifests at most once?

I'm not 100% certain if it'll work out to pass this context around in fewer places, but if you have difficult trying it out I can try to dig in more as well.

**Comment by Muscraft** [comment]
- I'll try and add more tests to address those things. I'm not quite sure what you mean by having two different workspaces to be pulled from. Do you mean one package has two workspaces?

- I'll add the test for the published manifest when I do the other tests

- I agree that `InheritableFields` gets passed around too much and is in too many places. I couldn't come up with a good way to have it not be passed around as much. I'll look over my notes again to see if I can make having it in `Config` work or if there is another way I missed it. I think mapping how `InheritableFields` is being passed as well as why might yield some results into how to fit it in better.

- You could parse a workspace root multiple times currently, this is mostly because we can't tell if it has been parsed before as well as even if it has you don't have a way to access the fields of it unless they are passed. I know a cache of what has been parsed has been turned down in the past but I think it may be helpful to have one like you described where you have a manifest path and then the fields associated in a map so you could look up if it has been parsed and either parse it or grab the fields. You could extend this to keeping the members of it so that if you encounter a manifest that does not specify a workspace but has a `{workspace = true}` you could check if it is stated as a member from the previous workspace and act accordingly. If done correctly I think that would allow you to get rid of most of the passing around of things as well as reduce the number of times you parse things overall. This would have a slightly higher memory consumption but it might be a worthwhile trade to not incur the penalty of parsing things multiple times. This feels very similar to @yaymukund's branch, so before I go ahead with this I would like to know if this is what you want or if I should search for another way.

**Comment by alexcrichton** [comment]
Oh for two workspaces I mean a crate depending on a crate in a separate workspace. For example you could use a git dependency which is using these workspace directives, so for that dependency to work we'd have to elaborate the manifest of the git dependency. Similarly if you're using a path dependency (or, e.g. a [patch] pointing to a path) which is a member of a separate workspace then you'd also have to do workspace manifest elaboration on that second workspace.

For caches and such, I think that the exact shape of the solution doesn't matter too too much, but I think the main priorities should be:

* Each TOML file is parsed at most once.
* Handling of `workspace = true` should be a relatively low-level operation that doesn't affect the whole codebase.

I suspect that this implementation as-is might parse TOML files multiple times, and while the `workspace = true` stuff is pretty contained there's more passing around of `InheritableFields` than would otherwise be ideal. This isn't necessarily critical to fix but the parse-only-once I think is a blocker for merging.

I haven't tried to implement this myself so I don't know exactly what a solution might look like. I naively envisioned in #8664 that a cache wouldn't be necessary since in theory TOML parsing might be done within the context of "here's your workspace fields already for you" or something like that. That may not be true and a cache may be the easiest to implement. I don't want to give the impression that I'm expecting a specific shape of PR, though! If a cache works best I don't think there's any need to avoid it, I mostly just think the above two points are the main things to consider for implementing this.

**Comment by Muscraft** [comment]
I know you mentioned how in `PackageRegistry` `InheritableFields` are there and they really shouldn't be. That is mostly because we aren't using a cache or something to hold things that have been parsed, so you must pass things around. For the most part, you will get `InheritableFields` before you parse a manifest. Most of the time they are used where there is one workspace and you parse it in the beginning and everything gets passed the correct things during parsing. Where all of the extra passing around comes from is when you need to parse it when you don't have access to the workspace before it. The cache may be able to reduce this some by being put in `Config` like you said since it is in most places already and for the most part, you have a `Config` available to look for the things you need. I'll look into this and update what I find early next week. I'll look specifically to make it so each TOML is only parsed one time and try and reduce where `InheritableFields` are.

**Comment by alexcrichton** [comment]
I think a cache will work best here because workspaces can show up in lots of various locations. With path dependencies Cargo could have multiple path dependencies into a different workspace, and we wouldn't want to re-parse the workspace each time we discover that. Similarly if we have multiple dependencies on a git repository we wouldn't want to re-traverse and re-parse the workspace manifest in a git repo each time as well.

To handle these things I think a cache buried in `Config` will be relatively clean, basically a mapping from absolute path to `InheritableFields` which is lazily populated as we discover entries that have a specific workspace. This does mean that toml parsing will have to find the workspace root (or someone similar in that area will need to find a workspace root). That's an operation that Cargo doesn't currently do today. For example Cargo doesn't try to find a workspace root in a transitive path dependency or a git repo dependency. To get that working I think that the logic to find the workspace root will need to be tweaked, since the "ceiling" for where the workspace root can be is the root of the git repo for git checkouts, although for path dependencies there should be no ceiling.

I do think that we'll need to be careful to handle workspace root discovery in a somewhat clever fashion as well or otherwise all path and git dependencies will trigger their own search for a workspace root which may be inefficient.

**Comment by Muscraft** [comment]
Currently, in [src/cargo/util/toml/mod.rs](https://github.com/Muscraft/cargo/blob/43487e97e59589d2463e6d5334980e7357643c02/src/cargo/util/toml/mod.rs#L2449-L2521), we search for the root workspace if needed, is this what you mean we should be doing? 

One solution to searching each time for the root workspace could be to keep a list of a workspace's members so when you go to look for a root manifest you would first check if it's in a map of something identifying the member to the root manifest path. You could use that path to find the `InheritableFields` from the cache in `Config`. This could be populated after you parse a workspace root. I'm not sure if this is the most elegant solution but it would allow us to make progress until a better solution can be found.

**Comment by alexcrichton** [comment]
Indeed yeah that's one location that I think may be multi-parsing manifests and multi-searching for a workspace root. I agree though that a cache can help the searching problem as well since we can record various paths in the cache as Cargo works its way upward in the filesystem

**Comment by ehuss** [comment]
Hey @Muscraft, I just wanted to check in and see where you're at with this PR.  I was just curious if you had any questions or major blockers.

**Comment by OmniDigitalGroup** [comment]
I've been busy with work and school but that should resolve itself this week. I have the cache for inheritable fields done, but when looking over the code I noticed that there are a few places that are parsing things multiple times beyond that, that need to be addressed. I'm hoping to be able to get those changes done in the next week or so.

**Comment by Muscraft** [comment]
I've been busy with school and work but those things should resolve this week to allow me time to work on this. I have the initial implementation for the inheritable fields cache done. While doing that it appeared to me that with how things were being done currently there are a few more places that will still cause multiple parses of a toml file. I have found those areas and am hoping to be able to push all of the changes in the next week or so.

**Comment by Muscraft** [comment]
I am going to leave the final decision of splitting this up or not to you. That being said I agree that this needs to be done in a careful way as it touches many of the core parts of cargo. That is one of the main problems with this RFC. It takes a system that works in a linear fashion and adds components of nonlinearity. This makes changes to many cores areas and causes a lot of the headache. 

I am willing to deal with the changes but I understand that it is a lot to comment on so I will be happy to split this up to make it easier to review. If we were to split this up I would like more of a description of what is to be done in each part. My current understanding is in part 1 we would 

- Introduce `InheritableFields` be that as an empty struct
- Set up the resolving of `InheritableFields` to always return none
- Change `TomlManifest` to be similar to the intermediate version or something similar as you suggested
- We would leave the fields as `MaybeWorkspace<T>` within the manifest and then whenever they're read in this function they call the `resolve` function as you suggested

I think this might be able to be expanded upon so that

- `InheritableFields`  would be introduced but be the same as now
- `TomlManifest` would be changed into the "intermediate" version or something similar as you suggested
- We would leave the fields as `MaybeWorkspace<T>` within the manifest and then whenever they're read they call the `resolve` function as you suggested
- The resolve function actually "resolves" the field, since no manifest currently will have a `{ workspace = true }` and if it does it will return an error

I think it makes this whole process a bit more testable as we can test the parsing of  `InheritableFields` for a workspace as well as test for `{ workspace = true }` by looking for an error in the test. You also could make it so that if the package is the workspace root it could have `{ workspace = true }`. This would also allow testing of the resolve behavior to some degree giving more confidence that things are working.

That then leaves finding the workspace root and `InheritableFields`. This makes it so all that is needed in part 2 is to set up finding the workspace root, set up the cache of `InheritableFields` as well as the cache for known members of a workspace to reduce the searching for a workspace root. All of that functionality could be added to resolve since it would be called one at a time and it could search for the workspace root and add it to the cache.

I may have oversimplified things a bit but I am happy to discuss this more either on here, in Zulip, on a call, or another communication method.

**Comment by blairjam** [comment]
Is this PR still being worked on?

**Comment by Muscraft** [comment]
Yes, I am hoping after the holiday season I can open the new PR

**Comment by alexcrichton** [comment]
Thanks for the PR, but I'm going to be [stepping down from the Cargo team](https://github.com/rust-lang/team/pull/712) so I'm going to un-assign myself from this. The Cargo team will help review this when they get a chance.

**Comment by Muscraft** [comment]
Closed in favor of [This PR](https://github.com/rust-lang/cargo/pull/10497)

**Pull request closed without merging**
