### PR TITLE
Show progress of crates.io index update even `net.git-fetch-with-cli` option enabled

### LINKED ISSUE #11574: Updating crates.io index with `net.git-fetch-with-cli `option enabled should show progress
### Problem

If user doesn't use `net.git-fetch-with-cli` option, cargo shows the progress bar.
However it doesn't show anything if user uses that option.

It may make users feel anxious, so I think it should show progress somehow too.

```
❯ cargo add tokio
    Updating crates.io index
       Fetch [                         ]   2.28%, 258.75KiB/s

❯ CARGO_NET_GIT_FETCH_WITH_CLI=true cargo add tokio
    Updating crates.io index
```

### Proposed Solution

I think redirecting `git`'s stdout to user is reasonable solution.

It is the best if we could parse `git`'s output and show the progress bar used in normal fetch, but it might be too expensive to implement.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by kawaemon**
### What does this PR try to resolve?

This PR fixes #11574 .

### How should we test and review this PR?

Please run `cargo` with `net.git-fetch-with-cli` option enabled.
It should show `git fetch`'s progress output like below.
```
❯ CARGO_NET_GIT_FETCH_WITH_CLI=true ./target/debug/cargo b
    Updating crates.io index
remote: Enumerating objects: 139821, done.
remote: Counting objects: 100% (2226/2226), done.
remote: Compressing objects: 100% (769/769), done.
receiving objects:   0% (1/139821)
```

### CODE REVIEW

**Comment by weihanglo** [comment]
@rfcbot fcp merge

Since this is a UI change, I'd like to reach a consensus among team members.

When `net.git-fetch-with-cli` is enabled, `git` process now is spawned with inherited stdin/stdout/stderr in order to show the fetch progress.

There is an alternative approach, showing the progress bar by parsing output of `git fetch`. I don't see the necessity to do so with such a complexity.

**Comment by epage** [comment]
For me, I wouldn't want to parse the `git fetch` output.

My main concern over this solution is the extra noise from fetch:
```
rom [..]
 * [new ref]                    -> origin/HEAD
``

However, if that is all the output gives but we get a progress bar in return, I feel like its worth it.  Granted, I am not using this setting.

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Going to skip the FCP, as this is not really a controversial change. It can always be reverted if needed, like what epage pointed out.

Thank you for your contribution, @kawaemon!

@bors r+

**Comment by weihanglo** [comment]
Congrats @kawaemon! Your change has been made into the latest nightly toolchain (since `nightly-2023-01-18` I believe). Thank you for this useful console enhancement!

**Comment by kawaemon** [comment]
I really wanted to contribute this brilliant tool sometime, and It became real now!
Thank you @weihanglo for instructions! It helped me so much.

**Pull request merged**
