### PR TITLE
fix(json-msg): use pkgid spec in in JSON messages

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

In #12914 we stabilized pkgid spec as unique package identifier for
`cargo metadata`. However, we forgot to make the same change to
JSON message format[^1]. This PR does so.

Note that the `package_id` field in JSON message is not clearly stated
as "opaque", so it might be considered as a breaking change to some extent.

[^1]: https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html#compiler-messages

### How should we test and review this PR?

If we aren't sure about stabilizing this, we may need to revert #12914 as well.

### Additional information

Zulip "miri" stream: https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/Cron.20Job.20Failure.20.28miri.2C.202024-01.29

### CODE REVIEW

**Comment by epage** [comment]
I can see the value of keeping these consistent and we've already standardized the syntax, so lets go for it

@bors r+

**Comment by weihanglo** [comment]
[Spurious network issue](https://github.com/rust-lang/cargo/actions/runs/7558812123/job/20581210665?pr=13311#step:10:3855): 

```
test failed running `/Users/runner/work/cargo/cargo/target/debug/cargo publish --registry crates-io`
error: stderr did not match:
1   1         Updating crates.io index
    2    +warning: spurious network error (3 tries remaining): [35] SSL connect error (Recv failure: Connection reset by peer)
2   3     warning: unused config key `registry.unexpected-field` in `[..]config.toml`
3   4     error: no token found, please run `cargo login`
4   5     or use environment variable CARGO_REGISTRY_TOKEN
```

It basically [succeeded](https://github.com/weihanglo/cargo/actions/runs/7558811371) on my fork.

**Comment by vlad20012** [comment]
I noticed that id format differ in `cargo metadata` and `cargo check` output in today's nightly:
```
rustc --version
rustc 1.77.0-nightly (6ae4cfbbb 2024-01-17)
```

Does this version not yet include this fix? Or it is another bug?

**Comment by epage** [comment]
https://github.com/rust-lang/rust/pull/120071 needs to be in your nightly to have them align.

**Comment by sunshowers** [comment]
Thanks for fixing this! Just wanted to mention that nextest matches up the package IDs from cargo metadata with the ones from JSON messages, so having consistency between the two is essential.

**Comment by weihanglo** [comment]
The fix is now available on `cargo 1.77.0-nightly (1ae631085 2024-01-17)`.

Sorry for overlooking the consistency issue in the first place 😞.
Regression tests are added in <https://github.com/rust-lang/cargo/pull/13322> and hope it won't happen again.

**Pull request merged**
