### PR TITLE
fix(vendor): Use tables for sample config

### LINKED ISSUE #10345: `cargo vendor` suggests vendor source config in inline form instead of separate tables
### Problem

This is not actually a **bug** but the original form is more readable IMO.

With 1.60.0-nightly:

```
To use vendored sources, add this to your .cargo/config.toml for this project:

source = { crates-io = { replace-with = "vendored-sources" }, vendored-sources = { directory = "vendor" } }
```

With 1.58.1 stable:

```
To use vendored sources, add this to your .cargo/config.toml for this project:

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```

### Steps

1. `cargo +nightly vendor` in any crate with dependencies.
2. Will see suggested vendor config in inline form.

### Possible Solution(s)

I guess it is due to the [switch to `toml_edit` from `toml`]. It should output in the same form as  before, though I am afraid the fix might not be too easy.  

cc @epage since you're an expert of toml_edit 😆 

[switch to `toml_edit` from `toml`]: https://github.com/rust-lang/cargo/pull/10086

### Notes

There might be other places got this kind of **bug** but I haven't had a time to scan all of them.

### Version

```text
cargo 1.60.0-nightly (1c034752d 2022-01-25)
release: 1.60.0-nightly
commit-hash: 1c034752de0df744fcd7788fcbca158830b8bf85
commit-date: 2022-01-25
host: x86_64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.77.0 (sys:0.4.51+curl-7.80.0 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 12.2.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by epage**
Fixes #10345

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Mind adding a small test for this as well?

**Comment by epage** [comment]
> Mind adding a small test for this as well?

Done.

**Review by alexcrichton — APPROVED** [review]
Looks good to me, but I think a test is failing?

**Comment by epage** [comment]
The test failure is independent of this change but is from a toml_edit bug fix.  I forgot you all don't use a lock file and originally included the fix in #10349 but I split it out into #10350 so it can be reviewed and merged without anything else impeding it.

**Comment by alexcrichton** [comment]
Ok!

@bors: r+

**Pull request merged**
