### PR TITLE
Problem: make install fail on non-existing rust-installer

### PR DESCRIPTION
**Pull request by vyskocilm**
Solution: add a note about calling git submodule to README.md

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could this remove the `src/rust-installer`? That way all submodules should be updated

**Comment by vyskocilm** [comment]
I am not an expert on git submodules, so how is removal of src/rust-installer supposed to work? Reading man git clone the only option is to call git clone --recursive, so I can update the PR by this advice.

**Comment by alexcrichton** [comment]
Removal? Isn't this about cloning it?

**Comment by vyskocilm** [comment]
Then I did not understand your comment at https://github.com/rust-lang/cargo/pull/1857#issuecomment-125762462 I though you have proposed an alternative way of solving the problem ...

**Comment by alexcrichton** [comment]
Oh sorry I just meant changing

```
git submodule update --init src/rust-installer
```

to

```
git submodule update --init
```

**Comment by vyskocilm** [comment]
Dammed - it'd be faster you'll commit your own change. Thanks for your patience with me!

**Comment by alexcrichton** [comment]
@bors: r+ 17c1f870931ea228f36c4b0fd0309862d1c618f5 

Thanks!

**Pull request merged**
