### PR TITLE
Make cargo-rustc crate-type-aware

### LINKED ISSUE #7339: cargo rustc -- --crate-type cdylib stopped working
Right now on stable `cargo rustc -- --crate-type cdylib` correctly produces the cdylib.
Nightly fails since cargo tries to pass the dependencies as `.rmeta` instead of `.rlib`.

### PR DESCRIPTION
**Pull request by lu-zero**
This fixes #7339 and makes the usage of `cargo rustc` less surprising overall.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I personally don't think it's a good idea for Cargo to be parsing rustc's flags, and I would prefer to not land this. The `cargo rustc` command is intended somewhat for debugging and tweaking things as opposed to first-class control of everything. While `--crate-type` is one thing we have to watch for today it's likely not the only one and I'd rather not have to play a constant came of catch-up with rustc.

**Comment by lu-zero** [comment]
I see what you mean, I can drop the last patch. As long I have an API mean add the crate types I'm happy.

**Comment by alexcrichton** [comment]
Yeah I think having an internal API in Cargo should be fine!

**Comment by lu-zero** [comment]
Updated accordingly :)

**Comment by alexcrichton** [comment]
I think this may need to be rebased on the `anyhow` changes to get tests passing?

**Comment by lu-zero** [comment]
Yes it needed that :)

**Pull request merged**
