### PR TITLE
Proptest 0.9.0, minimal Rust 1.32.0

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me w/ green CI

**Comment by dwijnand** [comment]
Ah, breaking changes in rand making a (transitive?) dependency on rand_isaacs break.  Oh well.

**Comment by Eh2406** [comment]
This is unfortunate, I was looking forward to using some of the new toys in 0.9.1

**Comment by dwijnand** [comment]
How are problems like this resolved in Rust?

**Comment by Eh2406** [comment]
It looks like it is just `minimal-versions` that is not passing. As this is an [unstable feature ](https://github.com/rust-lang/cargo/issues/5657) there is not yet much advice on how to fix it. Fundamentally, `rand_isaac-0.1.0` is lying about the minimum version of `SeedableRng` that it supports.

**Comment by Eh2406** [comment]
From a quick look rand 0.6.x is a hot mess with incorrect `minimal-versions`.

**Comment by dwijnand** [comment]
Ok I spent a long time trying to make it work, following your guide in https://github.com/rust-lang/cargo/issues/5657#issuecomment-407819624 and reading lots of commits, comments and threads, and couldn't figure it out.  If you have an advice I can continue trying.

**Comment by Eh2406** [comment]
Thanks for spending the time! I spent some time trying to figure it out as well, but did not get far.

**Pull request closed without merging**
