### PR TITLE
bump to newer semver version

### PR DESCRIPTION
**Pull request by steveklabnik**
I've just released semver `0.4.0`. Locally, the tests mostly passed, but not some of the cross-compilation tests. So I'm opening this PR to see what CI says.

### CODE REVIEW

**Comment by steveklabnik** [comment]
https://ci.appveyor.com/project/alexcrichton/cargo/build/1.0.1846/job/8lt4mljlge06rqf3 looks to be spurious; I don't have access to restart it.

**Comment by steveklabnik** [comment]
Other than that, looks like this passed! :confetti_ball: 

This release of `semver` moves entirely to the new parser. I hope to get it to 1.0.0 now that the fundamentals are refactored, I can focus on the interface.

**Comment by alexcrichton** [comment]
Thanks! Can you also run `cargo build` to regenerate the lockfile? Also, could you give a summary as to the updates from 0.2 to 0.4? (or a link where I can find)

**Comment by steveklabnik** [comment]
> Thanks! Can you also run cargo build to regenerate the lockfile?

Yes, I will do that soon.

> Also, could you give a summary as to the updates from 0.2 to 0.4? (or a link where I can find)

They're almost entirely internal:

* 0.2 had the hand-written parser @wycats wrote long ago
* 0.3 switched partially to `nom`, in an effort to fix things
* 0.4 I decided that I didn't like `nom` for this use case; semver versions are very regular. As such, I converted to a new parser based on `regex`, and @BurntSushi even helped out a bit :smile: 

After this stuff lands, I want to review the interface to see if I'm happy with it, and then put out a `0.9` release with whatever changes I may or may not make. If people are happy with it, I intend to turn that into `1.0`.

**Comment by steveklabnik** [comment]
I pushed the lockfile changes. I had run `cargo test` only, forgot that it wouldn't do that :sweat: 

Oh, and one last change with this new code: You'll see that `semver-parser` is there now too; I split out the parsing code from the rest of it, it felt like something that'd be useful on its own, and I might try making C bindings to both crates. That's not particularly relevant to Cargo, though :smile:

**Comment by alexcrichton** [comment]
@bors: r+

Ok cool, thanks for the update!

**Comment by steveklabnik** [comment]
:confetti_ball:

**Pull request merged**
