### PR TITLE
fix: encode URL params correctly for SourceId in Cargo.lock

### LINKED ISSUE #11085: SourceId serialization is ambiguous due to lack of escaping
### Problem

I noticed this when `cargo update` (in `compare_dependency_graphs`) kept notifying me of spurious changes when referring to a branch name with a `'+'` character.  Due to poor serialisation, deserializing a branch name from Cargo.lock gives a branch that doesn't match the one in Cargo.toml.

It's also possible to give a branch name that will spill into the 'precise' commit hash when deserializing.

### Steps

_No response_

### Possible Solution(s)

Will send a PR that fixes serialization to use the expected encoding, which is unambiguous.

### Notes

_No response_

### Version

```text
cargo 1.65.0 (bd99c043c 2022-09-09)
release: 1.65.0
commit-hash: bd99c043ceeaa0318f1ce4633f796110ae182002
commit-date: 2022-09-09
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.81.0 (sys:0.4.56+curl-7.83.1 system ssl:NSS/3.68.2)
os: Ubuntu 22.04 (jammy) [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Fixes #11085, also as a part of #12120.

When serialize `Resolve` for `Cargo.lock`, previously Cargo relys on `SourceId::as_url`, which is good for user-facing string. However, it leads to an incorrect deserialization since `url` crate always assume the given string is correctly url-encoded.

https://github.com/rust-lang/cargo/blob/0d5370a9ae0e97f000e63e416bafbf2abb57e41d/src/cargo/core/source/source_id.rs#L527-L538

This fixes by adding a wrapper for encoding `SourceId` during the serialization for `Cargo.lock`.

### How should we test and review this PR?

This is a conitnuation of #12279. #12279 should be reviewed first.

We use [`form_urlencoded::byte_serialize`](https://docs.rs/form_urlencoded/1.2.0/form_urlencoded/fn.byte_serialize.html), which is re-exported by `url` crate. Tests are copied from <https://github.com/rust-lang/cargo/pull/11086>. Kudos to the original author!

### CODE REVIEW

**Comment by ehuss** [comment]
I'm a little uncertain about having different serializations of `SourceId`. Can you say more about why it wouldn't have the same form as what is in Cargo.lock? I'm a little concerned about having them out of sync, though I don't have a specific scenario where that would be an issue.

**Comment by weihanglo** [comment]
My original thought was to keep the human-readable message as good as possible. That was my mistake not thinking too much on `cargo metadata` and JSON messages.

Now I lean toward making all of them use URL encode, except lockfile version 3. Old lockfiles will remain in the “wrong” format to avoid unnecessary churns. Do you think this new approach would be a compatibility hazard for `cargo metadata` and others?

**Comment by ehuss** [comment]
> Do you think this new approach would be a compatibility hazard for cargo metadata and others?

No. I don't think the package ID's and such have stability guarantees.

**Comment by ehuss** [comment]
I think I'd like to go ahead and kick of an fcp to merge this, though not strictly necessary since this is still unstable. I think we should be extra cautious about lockfile changes. Also, please confirm my rehashing of the issue.

@rfcbot fcp merge

@rust-lang/cargo This is an unstable change to `Cargo.lock` encoding. This will be part of the version 4 encoding, which is currently unstable and can only be used with `-Znext-lockfile-bump` on nightly. We may accumulate other changes to roll up in the version 4 change to reduce churn (described in #12120).

For a rollout, eventually in the future we will stabilize the ability for cargo to read the version 4 lock files, but cargo won't create them. Eventually, after at least 6 months after that, cargo will start writing version 4 lock files when creating them from scratch. Otherwise, lock file versions are sticky, and they aren't updated automatically (which we may want to reconsider, at least for this specific case).

This change involves changing the serialization of git dependencies. Git dependencies are encoded as a URL in the lock file:

```toml
[[package]]
name = "regex"
version = "1.8.4"
source = "git+https://github.com/rust-lang/regex.git?branch=branchname#5a34a39b72d85730065d3ffe4ce3715f2731e49a"
```

Unfortunately the serialization code blindly includes the git branch, tag, or revision as a string in the URL without properly escaping the contents (with % encoding). But the deserialization is expecting a URL and does proper decoding. This results in a few different problems:

* A `+` symbol gets changed to a space. When cargo loads that, it sees `?branch=foo+bar` does not match `?branch=foo bar` and assumes it has changed, forcing it to fetch the git repo and rewrite `Cargo.lock` every time. 
* A `#` symbol confuses the fragment parser. `?branch=foo#bar#SHA1` is interpreted as `branch=foo`. This causes cargo to think `Cargo.lock` is out of date (because the branch is actually `foo#bar`), and re-fetches the git repo, and rewrites `Cargo.lock` (again with the broken `#`). 
* A `%` symbol is interpreted as % encoding when it shouldn't. If the next two letters are hex-like, then it will decode them. For example, `foo%bar` would be decoded as `foo�r`, causing the same refetch/rewrite cycle as mentioned above.

We can't just change this without a lock version bump, because older versions of Cargo will see the `%` encoding and convert it back to the non-% encoding, overwrite `Cargo.lock`, and start the cycle of refetching and updating Cargo.lock.

**Comment by ehuss** [comment]
@rfcbot concern consistency

Raising a concern to have SourceId serialized consistently in JSON messages to match that in Cargo.lock mentioned at https://github.com/rust-lang/cargo/pull/12280#issuecomment-1599363050. I'm not sure how feasible that is to do properly. For example, should it be dependent on the current version of `Cargo.lock`? Or should it always use the new format?  For simplicity, I would lean towards always using the new format, but I'm uncertain about what considerations are needed here.

**Comment by weihanglo** [comment]
> concern consistency

If we see it as a bug, I think it is fine that we just fix JSON message and `SourceId` display right away. We don't do that for `Cargo.lock` just because it will mess up version control systems. 

However, maybe we shouldn't change until we are going to stabilize lockfile v4?

**Comment by weihanglo** [comment]
> No. I don't think the package ID's and such have stability guarantees.

Does that mean user should see `id` and `source` file in [`cargo metadata`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-metadata.html) output as opaque strings? If this is the case, should we document it?

> concern consistency

Agree with ehuss on always using the new format. If we see it as a bug, it should be fine just fixing JSON message and `SourceId` serialization together. We don't do that for `Cargo.lock` because it may mess up version control systems.

However, maybe we shouldn't change until we are going to stabilize lockfile v4? That could make things more consistent.

**Comment by ehuss** [comment]
> Does that mean user should see `id` and `source` file in [`cargo metadata`](https://doc.rust-lang.org/nightly/cargo/commands/cargo-metadata.html) output as opaque strings? If this is the case, should we document it?

I was thinking be essence that it is specified as a "unique ID" and nothing else that it is otherwise not defined. It might be good to explicitly say it is opaque (I did include that in the [unit graph](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#unit-graph) docs).

> However, maybe we shouldn't change until we are going to stabilize lockfile v4? That could make things more consistent.

That seems fine with me. Is there some way we can track that so it isn't forgotten? Maybe just in #12120?

**Comment by weihanglo** [comment]
> That seems fine with me. Is there some way we can track that so it isn't forgotten? Maybe just in #12120?

Does that mean this pull request is good to go if we can remember set them to `true` when stabilizing?

BTW, just added a new commit for reminding us inline in source code. Also left a comment there in <https://github.com/rust-lang/cargo/issues/12120#issuecomment-1607753875>.

**Comment by ehuss** [comment]
Seems good enough to resolve my concern.

@rfcbot resolve consistency

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
