### PR TITLE
Replaced 'project' with 'package' in Cargo documentation.

### PR DESCRIPTION
**Pull request by zachlute**
Partial fix for #6056.

I tried to make a distinction between places that were talking about Cargo 'projects' vs. a generic concept of a 'project' or a github 'project'. It's entirely possible I was overzealous, so please tell me if some of these changes look dumb.

### CODE REVIEW

**Comment by dwijnand** [comment]
Are we concerned in breaking old URLs?  Is there prior art for renamed doc pages?

**Comment by ehuss** [comment]
> Are we concerned in breaking old URLs?

I'd like to see some sort of redirects set up (including the renamed sections).

**Comment by zachlute** [comment]
Ah, meant to ask about that and forgot. Yeah, the way I saw it there were a few options:

1. Leave the pages the same and just change what they say. This is the easiest way to not break anything if we don't care that the names of the pages are still 'project'.
2. Rename the pages and leave pages with the old names that just have a link to the new ones. This is a pretty straightforward manual redirect. Sections are harder, but I guess any renamed sections could have sections on the redirector page that redirect to the appropriate section on the new page? The only non-first section that got renamed was "The package layout." Everything else was at the top so shouldn't require any redirection.
3. Not care if external links break. This is the current state and I agree it's not ideal.

Anybody have strong feelings about 1 or 2? Or some other option I'm not thinking of?

**Comment by ehuss** [comment]
There was a recent PR at #5975 that added redirects for the website that handled fragments.  I'm not sure how difficult it would be to use a similar approach in mdbook, though.

**Comment by zachlute** [comment]
So, I've been thinking about this, and I think tonight I'm going to just do the thing in (1) where I update all the documentation but don't rename any of the files yet. That gets us most of the benefit of this change by making the documentation use the right terms and lets us delay figuring out the redirect problem until later.

**Comment by zachlute** [comment]
I reverted any of the changes that would case URLs or anchors to change. That means that one header still has to be called "The project layout" but everywhere else should be changed, so it's at least an improvement?

**Pull request merged**
