### PR TITLE
Pass -Ctarget-cpu=native during cargo install

### LINKED ISSUE #4150: Pass -Ctarget-cpu=native during cargo install
This lets LLVM assume that the binary will be run on a machine with all the features as the host machine (and thus optimize more e.g. with better SIMD/AVX). Which is true for `cargo install`, and we should pass it by default, perhaps with a flag to turn it off.

cc @rust-lang/cargo

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #4150

### CODE REVIEW

**Comment by wesleywiser** [comment]
Looks like various tests are failing with:

> error: failed to compile `foo v0.0.1`, intermediate artifacts can be found at `/tmp/cargo-install.4WGTjtYcftna`
Caused by:
  extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target

It looks like this is something cargo [enforces](https://github.com/rust-lang/cargo/blob/402d8454f86e514fa00e4f13f051f08620d6a9a7/src/cargo/ops/cargo_compile.rs#L252). I don't exactly understand *why* cargo does this so I'm not sure what the best way to fix this is. Any pointers?

**Comment by alexcrichton** [comment]
The argument used here is intended for usage with `cargo rustc`, which only operates over one target, I think you'll need to find a different mechanism for transmitting this information to the compilation phase of Cargo.

cc @rust-lang/cargo as well about this change.

I'm personally not sure that this is the best default. The failure mode here is very subtle and can be very difficult to debug, when you `cargo install` on one CPU and run on another. I could imagine this happening in CI services which are run across a variety of cpus, or perhaps on package installation scripts for distributions which may be using `cargo install` today. There's certainly a flag for them to all use but the flag is non-obvious.

I'd be curious to hear what others think though!

**Comment by sfackler** [comment]
I think it'd be a bit strange to generate dist artifacts via `cargo install` rather than `cargo build`.

**Comment by matklad** [comment]
Am I correct that the best way to achieve this effect nowadays would be to put this config into `~/.cargo/config`:

```toml
[build]
rustflags = "-C target-cpu=native"
```
?


I think I am in favor of `cpu=native` by default, for the two reasons:

* almost everyone wants this, and the benefits might be substantial (I am thinking about ripgrep),

* I agree with @sfackler that using `cargo install` for the distribution is probably a misuse, and documenting that `cargo install` assumes current machine only pushes users to the more appropriate `cargo build`. 


That said, I think I have a concrete use case where this feature may cause problems. For IntelliJ Rust, we need `rustfmt` in CI and because compiling it from source is slow, we add `~/.cargo/bin` to caches, which are shared across different travis machines. I'll be ok with adding an extra flag to install though (and ideally, I'd love to download the binary of `rustfmt`:) )!

**Comment by alexcrichton** [comment]
That's sort of my worry, yeah. Especially with CI I'd imagine that `cargo install` is somewhat common (or maybe even networked shares at home?) where a `cargo install`'d binary goes across different machines and as a result has a relatively high likelihood of breaking.

**Comment by matklad** [comment]
>I think I am in favor of cpu=native by default,

Hm, now I've changed my mind :) I think that I am wrong claiming that `the benefits might be substantial`. On daily basis, most of us never use software compiled with `--cpu=native` (aside from JITed code maybe).  If for your particular use-case `--cpu=native` turns out to be really important, you can add it to `~/.cargo/config`.

**Comment by wesleywiser** [comment]
I think it would be great if Cargo could install the most optimized programs by default. Do you think the other concerns could be resolved with some additional documentation?

**Comment by alexcrichton** [comment]
Unfortunately I don't think documentation will help this problem. I agree with @matklad that this can always be specified locally but still isn't something we should do by default. My mental model is that "`cargo install` builds crates with `--release`" and that doesn't change codegen settings by default.

**Comment by matklad** [comment]
To expand on what @alexcrichton said, the trade off here is between potentially faster code and potentially mysterious crashes. 

While getting "the fastest possible" binaries is a noble goal, it's not obvious that "the fastest possible" and "just fast" are significantly different in practice for most of the `cargo installed` programs.

**Comment by wesleywiser** [comment]
That seems completely reasonable to me. Is there any interest in a opt-in version of this flag or should we just close this PR and the related issue?

**Comment by alexcrichton** [comment]
Isn't the opt-in version `RUSTFLAGS` and/or `.cargo/config` configuration?

**Comment by wesleywiser** [comment]
That's true I suppose.

**Pull request closed without merging**
