### PR TITLE
Simplify more tests

### PR DESCRIPTION
**Pull request by matklad**
This is the followup of #2670 

It contains [one](https://github.com/rust-lang/cargo/commit/28887beee054bfa9b56207667df3f5ae38a8ac6f#diff-ebcf8bfb935037902f135a7c225479b5L322) more or less significant change, everything else is just search/replace.

r? @alexcrichton

### CODE REVIEW

**Comment by matklad** [comment]
>It contains one more or less significant change, everything else is just search/replace.

Hm, I don't understand how this tests was working on Windows. It used `bar/Makefile`, but shouldn't it be `bar\Makefile` on windows?

**Comment by alexcrichton** [comment]
Ah `/` and `\` are treated as "mostly the same" on Windows, so maybe that's why it was passing?

**Comment by matklad** [comment]
And it failed on Mac OS! Turns out there is a reason why that test was written like that :)

Now it looks [like this](https://github.com/rust-lang/cargo/pull/2678/commits/fee4308bedae69c397b8514c64e5435506776311#diff-ebcf8bfb935037902f135a7c225479b5R305).

**Pull request merged**
