### PR TITLE
Add information about package caching

### PR DESCRIPTION
**Pull request by sbeckeriv**
Per https://github.com/rust-lang/cargo/issues/1609 "clarify how the cache works"

Added in a single line that states that the cached packages are only
removed by running the clean command.

Please let me know if this is the wrong spot, incorrect information or just silly.
Thanks
becker

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh in the case of `~/.cargo`, the clean command doesn't actually remove anything (only in the target directory), so perhaps it could clarify that Cargo never cleans out this cache?

**Comment by sbeckeriv** [comment]
Updated the text. 

Is there a way to build via cargo with just the local cache crates or does the cache just prevent a duplicate download per project? 

If I have no internet connect and remove a crate from my dependency list I can run cargo build fine. 
If I add the same removed dependency <cached, same version and all> back to the list I can no longer build because it tries to update the registry.

**Comment by alexcrichton** [comment]
@bors: r+ 76958696db6caf053d23240157dda79e67333fad

Thanks!

Yeah right now there's no way to say "use local cache, and only if that fails update the registry". That's covered by https://github.com/rust-lang/cargo/issues/1882

**Comment by sbeckeriv** [comment]
Sorry it looks like I wrote the commit message incorrectly for bors to closed the related issue.  Please close https://github.com/rust-lang/cargo/issues/1609

**Pull request merged**
