### PR TITLE
Use `extend` instead of `push`ing in a loop

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR, does this show up in profiling? Or otherwise how were these found? If it's just changing code for changing sake I might say we shouldn't do this?

**Comment by notriddle** [comment]
I haven't bencharked it, no.

Mostly, it just seems like code cleanup: if it can be phrased as a `collect()`, it should be, even if it doesn't make things faster, because it better reflects the code's intent.

**Comment by alexcrichton** [comment]
Hm ok well personally I do not agree and do not want to merge this PR. If others on the Cargo team feel differently they can r+, otherwise I'll close this if no one else wants to pick this up.

**Comment by Eh2406** [comment]
I do like the `collect` over the `push` in a loop. But don't know if it is worth the code cherne.

**Comment by weihanglo** [comment]
I merged one (https://github.com/rust-lang/cargo/pull/10453) days ago 😅
Although I like the change, I'd suggest not to submit too much this kind of PR unless the readability or performance gains a lot, since it's more like a personal preference.

**Comment by notriddle** [comment]
> Although I like the change, I'd suggest not to submit too much this kind of PR unless the readability or performance gains a lot, since it's more like a personal preference.

That's fine. I understand the concern about wanting to keep the git history readable.

**Pull request closed without merging**
