### PR TITLE
Improve resolve error messages

### LINKED ISSUE #6199: Resolvers error messages should include the version requirements.
Currently, if the resolver fails the error messages give lots of information on the paths that caused the problems, like:

https://github.com/rust-lang/cargo/blob/0b530c30867da26a4b59146f490c9f1d5377c20a/tests/testsuite/build.rs#L1356-L1358

It would be nice to have the version requirements like: (wording needs improvement)

```
  previously selected package `bad v1.0.0`
    ... which is depended on by `bar v0.1.0` which requires `bad: "=1.0.0"`
    ... which is depended on by `incompatible_dependencies v0.0.1 ([..])` which requires `bar: "0.1.0"`
```

The data is easily available thanks to #5428 we just need to get it into the correct place, and find good wording. We almost had this working in #5452 before it bit-roted.

I am willing to mentor someone on getting this done. It may be a good place to start looking at the resolver without having to stare into the void at its core. If it would be useful I can rebase #5452 so that only the wording is left.

cc @necaris would you be interested?

### PR DESCRIPTION
**Pull request by spacekookie**
Continuation of PR #6374, including all previous commits
Now also includes the rebased changes from origin/master

Closes #6199

r? @Eh2406
cc/@Dylan-DPC

### CODE REVIEW

**Comment by Eh2406** [comment]
Looks like the commits are from before we moved to edition=2018, so the rebase may have left incoherent code.

I like the use of the word `satisfy`! Do you have thoughts on how to make it less diagonal?

**Comment by spacekookie** [comment]
The last commit should resolve the CI issues.

Also, reading through the feedback in the other thread, I really quite like [this](https://github.com/rust-lang/cargo/pull/5452#issuecomment-386417141) suggestion for structuring the error output.

I might give implementing that a go and see how it feels in pracise

**Comment by Eh2406** [comment]
Hay anything I can do to help you with this?

I just remembered another source of inspiration on resolver error messages. [Dart's package manager](https://medium.com/@nex3/pubgrub-2fb6470504f) has great error messages, we do not ([yet](https://github.com/rust-lang/cargo/issues/5284)) have the data structure to steal it wholesale, but it may be a great place to get inspiration.

**Comment by alexcrichton** [comment]
I'm gonna close this to help clear out our queue, but it can of course be resubmitted!

**Pull request closed without merging**
