### PR TITLE
Document Support for GitHub Actions Badges

### PR DESCRIPTION
**Pull request by CryZe**
This is implemented here: https://github.com/rust-lang/crates.io/pull/1838

### CODE REVIEW

**Comment by ehuss** [comment]
Should maybe wait until the implementation is merged?

**Comment by alexcrichton** [comment]
@bors: r-

Er sorry, I'm not exactly what one would call "overly perceptive"

**Comment by CryZe** [comment]
Looks like badges on crates.io are now considered deprecated. Closing this.

**Pull request closed without merging**
