### PR TITLE
Swap std::sync::mpsc channel with crossbeam_channel

### LINKED ISSUE #7840: Cargo is entering an infinite loop
Cargo is randomly entering an infinite loop in some rare cases. Noticed in CI:

* https://github.com/rust-lang/cargo/pull/7836#issuecomment-578529146 — [azure](https://dev.azure.com/rust-lang/cargo/_build/results?buildId=19415&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=d4864165-4be3-5e34-b483-a6b05303aa68)
* https://github.com/rust-lang/rust/pull/68580#issuecomment-578996407 — [azure](https://dev.azure.com/rust-lang/rust/_build/results?buildId=19498&view=logs&j=34a2f069-38a6-567f-c087-79a147504c7a&t=bc5564b7-719c-565b-a0f0-03fa5ba953c5)

I've been able to reproduce it locally by putting Cargo's own test suite into a loop (`while cargo test; do :; done` after about 30 minutes on my machine).  It seems to randomly affect different tests.  Attaching with a debugger, I see it caught in [this loop](https://github.com/rust-lang/rust/blame/08594515926df9b23b912628d9f8c814a30edcb7/src/libstd/sync/mpsc/shared.rs#L390-L405), where dropping an mpsc receiver seems to be confused.

I strongly suspect this is caused by some change in #7731.  Perhaps there is some odd interaction between crossbeam's scope() and mpsc?  The only relevant change that I see is that `DrainState` is now *moved* into the crossbeam scope, and thus dropped inside the scope, whereas previously the mpsc channels residing inside `JobQueue` were dropped much later.

@Mark-Simulacrum Are you very familiar with mpsc or crossbeam's scope?  mpsc seems wildly complex, and I don't know where to start trying to figure out what's wrong.

I might try removing `FinishOnDrop` and see if I can repro again, as that seems a little fishy.

### PR DESCRIPTION
**Pull request by spastorino**
Hoping it closes #7840

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by ehuss** [comment]
I don't think we can make this change.  When combined with #7838, it causes a very dramatic performance hit.  Fresh builds can be many times slower (9 times slower with 500 units).

**Comment by Mark-Simulacrum** [comment]
That's quite unexpected from my perspective at least -- have we done any profiling to suggest why that would be the case? Generally crossbeam-channel suggests in docs and such that it's faster/better all around than std's impl, but I guess that's not the case?

**Comment by ehuss** [comment]
I might try digging into it more later.  It looks like it is having a strange interaction with the jobserver helper thread.  I can measure dropping the helper thread takes over 1s (but not always).  `Helper::join` is a little funky in the way it uses signals, but it is not clear to me what's going on.

**Comment by alexcrichton** [comment]
I don't believe we can switch to crossbeam's channels since they do not have a blocking send function which #7838 will require, so this'll likely just require more churn otherwise. I was working on https://github.com/rust-lang/cargo/pull/7845 yesterday but didn't get a chance to polish it until this morning, but that's the route I think we should take (just write our own simple queue).

I'll comment over there about the performance though

**Comment by ehuss** [comment]
The issue I was seeing is dropping the job server can take up to 1 second, see https://github.com/alexcrichton/jobserver-rs/issues/23.  I'm guessing that the change to crossbeam is just altering the behavior slightly enough for it to trigger that.

> I don't believe we can switch to crossbeam's channels since they do not have a blocking send

I'm not sure what you mean by this.  Crossbeam has a `bounded` channel, and [`Sender::send`](https://docs.rs/crossbeam-channel/0.4.0/crossbeam_channel/struct.Sender.html#method.send) should block if the queue is full.

**Comment by alexcrichton** [comment]
Ok the jobserver issue should be fixed now, sorry about that and thanks for helping to diagnose it @ehuss!

Also apologies, I was looking at the documentation for `crossbeam-queue` rather than `crossbeam-channel`, and yeah looks like `crossbeam-channel has what we want.

Here's my proposed plan of action (which I'll go ahead and enact at the bottom)

* Let's merge this PR. Super simple, fixes a known bug.
* Independently we can figure out https://github.com/rust-lang/cargo/pull/7838
* If necessary we can reconsider https://github.com/rust-lang/cargo/pull/7845 if needed by #7838 


@bors: r+

**Pull request merged**
