### PR TITLE
Add Windows support for `cargo install`

### PR DESCRIPTION
**Pull request by bombless**
Add Windows support for https://github.com/rust-lang/cargo/pull/1318

### CODE REVIEW

**Comment by globin** [comment]
Be aware that my PR is by far not ready to be merged as there are neither sane exception handling nor any tests currently.

**Comment by bombless** [comment]
Okay, thanks for noticing :)

**Comment by globin** [comment]
I'll merge this into #1318

**Comment by bombless** [comment]
It's embarrassing that I misspelled "suffix" :)

**Pull request closed without merging**
