### PR TITLE
Check empty input for login

### PR DESCRIPTION
**Pull request by hi-rustin**
### What does this PR try to resolve?

close https://github.com/rust-lang/cargo/issues/11144
Check empty input for login.

### How should we test and review this PR?

- unit test
- cargo login and enter

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
What I am going to say might sound stupid: Is it possible that a registry accepts empty tokens to login?

For some reason, I know that some websites permit login with empty passwords. I cannot guarantee there isn't a private registry does the same thing at this moment.

**Comment by hi-rustin** [comment]
> Is it possible that a registry accepts empty tokens to login?

I think the empty password makes sense, but the empty token doesn't make much sense.

**Comment by hi-rustin** [comment]
Also, how do we pass an empty token using cli? Won't it enter the read logic? If we accept an empty token, then why do we need to add read logic here?

**Comment by weihanglo** [comment]
> > Is it possible that a registry accepts empty tokens to login?
> 
> I think the empty password makes sense, but the empty token doesn't make much sense.

Agree with you that empty token seems like a weird existence. This patch IMO is with a good intent. I just want to make sure no one's compilation is broken with it.

**Comment by arlosi** [comment]
This only affects `cargo login`. Users who needed to send an empty token (seems really unlikely) could still manually use the `credentials` file.

**Comment by weihanglo** [comment]
Supposedly because the scenario of sending an empty token is rare, and `cargo login` should be used mostly in interactive sessions, I propose to merge this. This will prevent people from adding empty tokens by accident. The risk is that someone needing to pass an empty token via CLI cannot work anymore.

As [@arlosi said](https://github.com/rust-lang/cargo/pull/11145#issuecomment-1258865255), people could still add empty tokens through `credentials` file if they intend to do so.

@rfcbot merge

**Comment by weihanglo** [comment]
Supposedly because the scenario of sending an empty token is rare, and `cargo login` should be used mostly in interactive sessions, I propose to merge this. This will prevent people from adding empty tokens by accident. 

The risk is that someone need to pass an empty token via CLI cannot work anymore. As [@arlosi said](https://github.com/rust-lang/cargo/pull/11145#issuecomment-1258865255), people could still add empty tokens through `credentials` file if they intend to do so.

@rfcbot merge

**Review by weihanglo — APPROVED** [review]

**Pull request merged**
