### PR TITLE
Add android build support

### PR DESCRIPTION
**Pull request by malbarbo**
This add android build support, including openssl.

### CODE REVIEW

**Comment by malbarbo** [comment]
There is some interest on using rust on android (termux/termux-packages#261). rustup [already](https://github.com/rust-lang-nursery/rustup.rs/pull/1000) has android build support.

Even if cargo is being build with rust, I think it is good to have a docker image to build cargo.

What about the travis android build? Should I remove it?

**Comment by alexcrichton** [comment]
Thanks for the PR! 

Note though that the builds in this repository are going to be retired very soon. We're not actually making releases based on these builds any more right now, so these artifacts will just get gc'd at some point.

It looks like no code changes happened here though? In that case I'd be ok to add a builder to verify that we can keep compiling for android, but otherwise maybe we should hold off until a PR can be made to rust-lang/rust?

**Comment by malbarbo** [comment]
There is no code change.

>  In that case I'd be ok to add a builder to verify that we can keep compiling for android

Verify that cargo can be compiled for android (before rust-lang/rust/ is updated) is a good thing.

I made a PR to add android host builders: https://github.com/rust-lang/rust/pull/41149.

**Comment by alexcrichton** [comment]
Ok, perhaps we can pare this down to just one Android target? I suspect we won't need to test all android targets in full before changes reach rust-lang/rust

**Comment by malbarbo** [comment]
> Ok, perhaps we can pare this down to just one Android target?

That makes sense. I update the PR.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
