### PR TITLE
Removing hash from output files when using MSVC

### PR DESCRIPTION
**Pull request by snf**
This is the fix for https://github.com/rust-lang/cargo/issues/7358 suggested by @alexcrichton . Tested and working.

I see a few tests failling but seem unrelated. I'll investigate them tomorrow.

### CODE REVIEW

**Comment by snf** [comment]
Failing tests are:

- build::uplift_pdb_of_bin_on_windows
- collisions::collision_example
- collisions::collision_export
- freshness::changing_bin_features_caches_targets

Will dig into the issues later.

**Comment by alexcrichton** [comment]
Thanks for the PR here @snf! This is technically a breaking change for MSVC, which is why some tests are failing. To explain a bit more with the purpose of those hashes, the intention is that if you do a sequence of commands like:

```
$ cargo build --features a
$ cargo build --features b
$ cargo build --features a
```

The last command ideally should have everything fully cached. To do that we tell the compiler that for `--features a` and `--features b` we actually produce entirely distinct executables (different hash blobs at the end). What this change is doing is saying that specifically for MSVC executables we *don't* produce a big "hash blob" and we instead natively generate the final executable. Typically Cargo just hard-links the final executable to the actual name (like `foo.exe` instead of `foo-xxxxxx.exe`). For some platforms (as listed in this `if` statement) the final executable depends on the filename that it produces, so we can't do this trick and we have to actually produce the final executable.

When I say "breaking change" though that's still fine, this is only breaking in that the exact behavior of Cargo is changing, but it's unlikely to affect too too many folks. We could also fix this behavior in time I believe, just emitting `foo.exe` to a unique output directory and caching that. In any case, I think it's fine to just update the tests here and get them passing with respect to this change!

As for each test:

* build::uplift_pdb_of_bin_on_windows - this I'm not entirely sure what's going on, so some investigation would be needed. We likely just need a tweaked assertion though.
* collisions::collision_example - this is fine to just ignore the test on MSVC now, or just update it to have different assertions on MSVC
* collisions::collision_export - similar to above, this should be fine to ignore and/or have target-specific assertions
* freshness::changing_bin_features_caches_targets - again like above, this is fine to ignore on MSVC since its rules for executables are different

**Comment by snf** [comment]
Thanks for the detailed explanation Alex! A lot of assumptions ahead, please verify them.

I'm thinking that the problem is that the linker will generate the internal names to match the output files. If we want the file names with hashes in the intermedary directory, it could be possible to link `foo.exe` there and then move it to `foo-hash.exe`. The internal names, then, will all have `foo.exe` without the hashes. And everything else should be the same without breaking changes right?

If this works, I'm not even sure where should I start but I can give a shot at it next week. Also, confirm if this might be a too complex solution.

**Comment by alexcrichton** [comment]
That... I think could work! It'd be a bit wonky though because we would generate `foo.exe`, then copy/link it to `foo-xxxxx.exe` when we actually build something. If we determine it's fresh, though, we'd copy `foo-xxxxx.exe` to `foo.exe` (as well as the pdb files and such). I think that should work in terms of using the right caches and such, but it may not be the easiest to implement with the way Cargo is written today. In any case I'm fine either updating the test cases or updating the strategy here, whichever you would prefer!

**Comment by snf** [comment]
Thanks! Given my current load, I'll work on fixing the failling tests and I can check for the "better" solution later when I have more cycles available.

**Comment by snf** [comment]
Fixed the tests. Please let me know if they look ok. Commits squashed.

**Comment by alexcrichton** [comment]
@bors: r+

👍

**Comment by ehuss** [comment]
(Sorry, I'm a bit behind on reviews.)

I'm concerned this changed the semantics of the `--out-dir` feature.  Examples on MSVC are no longer possible to export to a directory.  The uplift code uses the `hardlink` value to know whether or not something should be exported. But since examples are no longer hard linked, they won't be exported.  Can that behavior be retained?  (This is relevant to the `collision_export` test.)

**Comment by alexcrichton** [comment]
@ehuss I'm not sure I quite understand, but it sounds like I'm missing some consequences of switching to using no metadata here perhaps?

**Comment by ehuss** [comment]
I filed #7493 with some more detail explaining the scenario.
Also filed #7492 to re-enable some tests here.

**Pull request merged**
