### PR TITLE
cargo_test: remove test roots after success

### PR DESCRIPTION
**Pull request by cuviper**
The test directories under `.../cit/` can take up a lot of space, and
they're not useful to keep around for successful tests. The test guard
now removes each "root" directory, using `panicking` as a proxy for
failure to instead leave it for inspection.

### CODE REVIEW

**Comment by cuviper** [comment]
For context, I was looking around in our distro builds of Rust to see what takes up so much space, and Cargo's test `/cit/` was over 12GB! That's using `std` compiled with full debuginfo, so it's probably not so bad normally, but it's also easy to clean up.

**Comment by ehuss** [comment]
As you can see from the test failure, I don't think this can land as it doesn't work on Windows.  There's more information at #9585 and #7042.  It would be great to figure out how to deal with Windows, but I'm uncertain how.

FWIW, I very frequently run commands inside test directories as I am doing development, even after success.  Perhaps this could be an option?  Or maybe the distro scripts can just delete it after the tests run?

**Comment by cuviper** [comment]
> Or maybe the distro scripts can just delete it after the tests run?

I'll see if I can manage that. It does mean there will still be that 12GB spike in disk usage throughout the build, but combined with other transient cleanup I'm adding, it may be good enough.

(Ideally, I'd just provision our builders to always have plenty of total space, and just let all cleanup happen afterward, but we don't always have that flexibility across all targets.)

**Comment by ehuss** [comment]
12 seems a lot larger than I would expect.  Now you've got me curious where all that space is being wasted. On my linux system, it is 7GB, and on macOS it is 2.2GB.  That seems like a crazy difference.  

Hmm.  One test has a hard-link to cargo itself which is 200MB (!).

Test binaries are almost 6MB each, whereas on macos they are 1.5MB (with debuginfo)!  Why are linux binaries so much heavier?

**Comment by alexcrichton** [comment]
Oh I thought the macos/linux differences would be "unpacked" debuginfo? On Linux we duplicate libstd's debuginfo everywhere but on macOS it's never duplicated since it's left to all reside in libstd itself

**Comment by cuviper** [comment]
Yeah, I think split debuginfo explains macOS, and then I suspect our respective Linux differences may be due to building `std` with `debuginfo=1` (as distributed by rustup`) or `debuginfo=2` (as we currently do in the distro).

**Comment by ehuss** [comment]
Closing since this has become a bit stale, and this can't be accepted as-is due to the Windows issue.  I suggest if possible to delete the `tmp` directory after running tests to reduce disk space usage.  It would be nice to have some kind of solution here, but it is not clear what that would look like.  It would also be great if the tests didn't use so much space to begin with, but that's also challenging.

**Pull request closed without merging**
