### PR TITLE
Add native dependencies to doctest

### LINKED ISSUE #1245: Native dependency not inserted in link args when running doctest
I have a dependency which is generated by pkg-config in a custom build script.

The output of the buildscript is:
```
cargo:rustc-flags=-L native=/vol/home/s0828599/stow/portaudio/lib
cargo:rustc-flags=-l portaudio
cargo:rustc-flags=-l asound
cargo:rustc-flags=-l m
cargo:rustc-flags=-l pthread
```

When running `cargo run --example demo` the native dependency (`-L native=/vol/home/s0828599/stow/portaudio/lib`) is correctly inserted:
```
rustc examples/demo.rs --crate-name demo --crate-type bin -g --out-dir /vol/home/s0828599/playground/rust/portaudio-rs/target/examples --emit=dep-info,link -L dependency=/vol/home/s0828599/playground/rust/portaudio-rs/target -L dependency=/vol/home/s0828599/playground/rust/portaudio-rs/target/deps --extern portaudio-sys=/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libportaudio-sys-7cbaf4ea274a2241.rlib --extern bitflags=/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libbitflags-57b03d5337bba57b.rlib --extern portaudio=/vol/home/s0828599/playground/rust/portaudio-rs/target/libportaudio-98112834b31c715f.rlib -L native=/vol/home/s0828599/stow/portaudio/lib
```

However, when running `cargo test` it will fail. The 'normal' tests run ok, but the doc tests output an error. As you can see below, the native dep is not inserted here.

Error:
```
error: linking with `cc` failed: exit code: 1
note: cc '-Wl,--as-needed' '-m64' '-L' '/vol/home/s0828599/stow/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-o' '/tmp/rustdoctest.IUiecnTvoPsU/rust-out' '/tmp/rustdoctest.IUiecnTvoPsU/rust_out.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-Wl,--gc-sections' '-pie' '-nodefaultlibs' '/vol/home/s0828599/playground/rust/portaudio-rs/target/libportaudio-98112834b31c715f.rlib' '/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libbitflags-57b03d5337bba57b.rlib' '/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libportaudio-sys-7cbaf4ea274a2241.rlib' '-L' '/vol/home/s0828599/stow/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-llog-4e7c5e5c' '-L' '/vol/home/s0828599/stow/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lstd-4e7c5e5c' '-L' '/vol/home/s0828599/playground/rust/portaudio-rs/target' '-L' '/vol/home/s0828599/playground/rust/portaudio-rs/target/deps' '-L' '/vol/home/s0828599/stow/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-L' '/vol/home/s0828599/playground/rust/portaudio-rs/.rust/lib/x86_64-unknown-linux-gnu' '-L' '/vol/home/s0828599/playground/rust/portaudio-rs/lib/x86_64-unknown-linux-gnu' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-lportaudio' '-lportaudio' '-lasound' '-lm' '-lpthread' '-ldl' '-lpthread' '-lrt' '-lgcc_s' '-lpthread' '-lc' '-lm' '-lcompiler-rt'
note: /usr/bin/ld: cannot find -lportaudio
/usr/bin/ld: cannot find -lportaudio
collect2: ld returned 1 exit status
```

Compiler flags:
```
rustdoc --test /vol/home/s0828599/playground/rust/portaudio-rs/src/lib.rs --crate-name portaudio -L /vol/home/s0828599/playground/rust/portaudio-rs/target -L /vol/home/s0828599/playground/rust/portaudio-rs/target/deps --extern portaudio-sys=/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libportaudio-sys-7cbaf4ea274a2241.rlib --extern pkg-config=/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libpkg-config-be6313c85913bcf0.rlib --extern bitflags=/vol/home/s0828599/playground/rust/portaudio-rs/target/deps/libbitflags-57b03d5337bba57b.rlib --extern portaudio=/vol/home/s0828599/playground/rust/portaudio-rs/target/libportaudio-98112834b31c715f.rlib
```

If I add the `-L native ...` argument then it runs fine.

### PR DESCRIPTION
**Pull request by mvdnes**
This will traverse all native dependencies and add them to the rustdoc command when running tests.

Fixes #1245

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh good catch! Does this also fix https://github.com/rust-lang/cargo/issues/1469? Also, could this pass `-L native=` instead of just a bare `-L`?

**Comment by mvdnes** [comment]
The 'native=' is already present in the native_dep variable.

Also #1469 and #1245 look very similar, so I believe that it does.

**Comment by alexcrichton** [comment]
Oh right, good point!

@bors: r+ 55d7086012de36c9101013545dc0901932e0173d

Thanks!

**Comment by hauleth** [comment]
Still fails for me (`cargo 0.3.0-nightly (a2dd2ac 2015-06-24) (built 2015-06-23)`).

I have OpenSSL libraries installed via LinuxBrew and build `cargo test` is failing on doctest ("normal" test are passing all green.

`cargo test --verbose` output:
https://gist.github.com/hauleth/7ca65dd5d046f2528910

When I manually run `rustdoc --test <rest flags> -L native=$HOME/.linuxbrew/Cellar/openssl/1.0.2c/lib` then everything passes green.

Project: https://github.com/hauleth/ucl-rs

**Pull request merged**
