### PR TITLE
test(metadata): Show behavior with TOML-specific types

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

The goal is to know if/when these change so we can have a conversation about what to do.

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
How was this dicovered and do we have any prior discussion of it?

**Comment by epage** [comment]
> How was this dicovered and do we have any prior discussion of it?

I discovered it when I merged `toml`s functionality into `toml_edit`.  I've previously glossed over this.  In office hours, this came up for a couple of reasons
- Caching of `Cargo.toml` parsing in alternative formats which could end up persisting this
- Being prepared for a day when a cargo team member isn't maintaining `toml`

**Comment by weihanglo** [comment]
> Being prepared for a day when a cargo team member isn't maintaining toml

I hope everything is okay 🙏🏾.

**Comment by epage** [comment]
No announcements, more being prepared

**Pull request merged**
