### PR TITLE
Migrate to some Rust 2018 idioms

### PR DESCRIPTION
**Pull request by alexcrichton**
Run a few lints, hand-edit a few things, otherwise try to help push Cargo into the 2018 edition!

### CODE REVIEW

**Comment by ehuss** [comment]
Looks like there are some issues?

**Comment by dwijnand** [comment]
I wonder what I didn't get those dyns and anonymous lifetimes in my #6387.

LGTM pending fixups.

**Comment by alexcrichton** [comment]
@dwijnand oh that may be `cargo fix --edition` vs `cargo fix --edition-idioms`

**Comment by alexcrichton** [comment]
Had to fixup some minimum-version build requirements as well as some Windows-specific code that wasn't idiomatic. Let's see what CI says now...

@bors: r=dwijnand

**Comment by dwijnand** [comment]
No, my first commit was `cargo fix --edition` while the second was `cargo fix --edition-idioms`.  Oh well 🤷‍♂️

**Pull request merged**
