### PR TITLE
Add build script warnings, streaming output from build scripts to the console

### LINKED ISSUE #1106: Request not to suppress the output of build script
Sometimes the build script may fail, leaving some useful information (such as the output of GCC) in stdout or stderr.
However, I found that Cargo is not displaying the output of my build script.

I request a feature, that the stderr is displayed by default and stdout is displayed when `--verbose` is on.

Thanks.

### PR DESCRIPTION
**Pull request by alexcrichton**
These commits add a few features to Cargo:

* Cargo now recognizes the `warning` key in build scripts and will print warnings *after a build script has completed* if the build script is for a path dependency. That is, if a build script prints `cargo:warning=foo` then Cargo will forward that to the console if the crate's being developed.

* Cargo now accepts multiple `-v` flags for all commands. The `-vv` flag prints warnings for *all* upstream crates, not just the local ones.

* When the `-vv` flag is passed Cargo will stream the output of all build scripts to the console, allowing more easy debugging of what happened if the build fails later on.

More details can be found in each commit, and otherwise this 

Closes #1106

### CODE REVIEW

**Comment by alexcrichton** [comment]
Discussed during the tools triage yesterday, it was concluded that this seems like good functionality to have, but it also shows more need to targeting configuration at certain portions of the dependency graph (perhaps in the form of command line arguments)

**Comment by alexcrichton** [comment]
ping r? @brson

**Comment by gnzlbg** [comment]
Does this still work? 

I am trying to debug a build script by passing `-vv` without any luck :/

**Comment by alexcrichton** [comment]
This PR is over a year old at this point so it's best to open an issue with a reproduction if it's not working

**Pull request merged**
