### PR TITLE
Bump to 0.28.0

### PR DESCRIPTION
**Pull request by alexcrichton**
Looks like we've forgotten to do this so far on nightly!

### CODE REVIEW

**Comment by matklad** [comment]
This was intentional I think?

**Comment by matklad** [comment]
https://github.com/rust-lang/cargo/pull/5247

Though, if we don’t bump here, we should tweak version printing stuff to remove minis one :)

**Comment by alexcrichton** [comment]
Oh I figured we'd only do that retroactively if we just so happened to avoid making any breaking changes (or if we went out of our way to not make breaking changes). I think we've made a bunch though this time?

**Comment by matklad** [comment]
Yeah, we did a lot of breaking changes :) We could just skip publishing a release to crates.io perhaps? Anyway, I don’t have strong opinion here: version difference is a very minor issue, although very annoying, as all small things are :)

**Comment by alexcrichton** [comment]
Ah I'd prefer to keep publishing and otherwise just wait for a cycle down the road to bring the two in sync

**Comment by matklad** [comment]
> just wait for a cycle down the road to bring the two in sync

It's highly unlikely that we'll make a cycle without breaking changes to the library )

@bors r+

**Pull request merged**
