### PR TITLE
Fix the Travis CI badge

### PR DESCRIPTION
**Pull request by dwijnand**
And with this PR trigger the first travis-ci.com build! :D

### CODE REVIEW

**Comment by ehuss** [comment]
I don't think Cargo ever builds on master, so I don't think the icon will update properly.  I'll r+ another PR and see what it looks like.

**Comment by dwijnand** [comment]
Hmm, bors builds the commit, attaches the result to the SHA and then fast-forwards master to it (on success), so I think it should show up.  It would be always green though, actually. 😄

**Comment by ehuss** [comment]
Travis only knows about the branches it tests.  As you can see, the new url doesn't work (says "unknown"):
https://travis-ci.com/rust-lang/cargo.svg?branch=master

I *think* it will need to be auto-cargo, like this: https://travis-ci.com/rust-lang/cargo.svg?branch=auto-cargo

But, yea, it should never be not-green.

**Comment by dwijnand** [comment]
Yep, agreed.

**Comment by Eh2406** [comment]
`auto-cargo` is left in a failed state for long periods of time, betean a test fail and the next r+

**Comment by alexcrichton** [comment]
I wonder if we could just link to an always green badge because master is alwasy green anyway...

Alternatively we could do something like run `cargo check` on master perhaps? Or maybe just run one builder on the master branch to get a badge there?

**Comment by dwijnand** [comment]
Good idea.  Pushed.  It could fail, because of the flaky resolution tests, but maybe that'll drive us to fix that situation.

**Comment by dwijnand** [comment]
Broken pending https://github.com/rust-lang/rust/pull/57484 or nightly rollback.

**Comment by ehuss** [comment]
Looks like homu missed the notification again.

**Comment by alexcrichton** [comment]
Yep, a webhook notification failed, redelivered via github interface and looks good now

**Pull request merged**
