### PR TITLE
Add a field to the build plan for packages with relevant buils script outputs

### PR DESCRIPTION
**Pull request by chmanchester**
Build script outputs contain necessary flags for dependent compilations, so
for some relying on the build plan output they need to track these outputs
and re-construct the right flags. Cargo employs some amount of logic to
determine which build script outputs are relevant to a certain compilation, so
this forwards that information to build plan consumers so they don't have to
attempt to replicate it themselves.

### CODE REVIEW

**Comment by chmanchester** [comment]
@mshal this is the change I mentioned that will let us simplify some of the things we added for the tup backend and build scripts, let me know if you have any feedback here!

**Comment by alexcrichton** [comment]
Looks good to me! I'll give @mshal a chance to take a look at this though

**Comment by alexcrichton** [comment]
@chmanchester is this still needed by Gecko? Should we re-ping @mshal?

**Comment by chmanchester** [comment]
> @chmanchester is this still needed by Gecko? Should we re-ping @mshal?

This isn't a priority for now. I'll come back to it if need be.

**Pull request closed without merging**
