### PR TITLE
Feature/quiet mode

### PR DESCRIPTION
**Pull request by pwoolcoc**

### CODE REVIEW

**Comment by FlashYoshi** [comment]
This seems to be an interesting addition is their any intererst in continuing the development? @sinistersnare @pwoolcoc this would also solve #653 which has been open for some time.

**Comment by pwoolcoc** [comment]
I would definitely update the code if I thought it had a chance of getting merged, but twice now it has been blocked on input from wycats, so I would rather see interest from the cargo devs before working on it further

**Comment by FlashYoshi** [comment]
@wycats You never actually responded to the -s suggestion pwooloc made, do you have any time to share your comments on this?

**Comment by sinistersnare** [comment]
Another +1 for this, @wycats or @alexcrichton  please provide feedback?

**Comment by wycats** [comment]
I am happy with `-s` / `--silence-cargo` :smile:

**Comment by alexcrichton** [comment]
@pwoolcoc or @sinistersnare, do one of you want to reopen a rebased version of this? I'd request that `-s` was added to all commands instead of just `cargo run`, but other than that it looks good to me.

**Comment by pwoolcoc** [comment]
Sure, I will try to get something pushed tonight

**Comment by sinistersnare** [comment]
I just want it done :) go for it @pwoolcoc

**Comment by pwoolcoc** [comment]
sorry I didn't push this soon, been dealing with a sick kid this weekend. Rebased the changes on top of the current `master`, just need to go through and add it in to the other commands next.

**Comment by alexcrichton** [comment]
@pwoolcoc could you open a new PR as well? Thanks!

**Pull request closed without merging**
