### PR TITLE
Use same find -perm syntax as rustc

### LINKED ISSUE #822: Invalid `find -perm` test in the Makefile
On Fedora, when I run `make no-exes` (which is triggered `make test`), I see this error go by:

```
$ make no-exes
find $(git ls-files) -perm +111 -type f \
        -not -name configure -not -name '*.sh' -not -name '*.rs' | \
        grep '.*' \
        && exit 1 || exit 0
find: invalid mode ‘+111’
```

At least this doesn't stop testing, because the grep sees nothing.

That's using GNU findutils-4.5.11-4.fc20.x86_64, and the manpage says:

```
-perm +mode
       This  is  no  longer  supported  (and  has been deprecated since 2005).
       Use -perm /mode instead.
```

That suggestion works fine for me, but I don't think OSX will like it.  There's also a `find -executable` test which works by checking access rather than mode bits, but OSX doesn't have that either.  (I don't have access to OSX, btw, just looking at the online manpage.)  Maybe this should just be `$(OS)` conditional.

### PR DESCRIPTION
**Pull request by alexcrichton**
Closes #822

### CODE REVIEW

**Comment by huonw** [comment]
It seems this is a step backwards? https://github.com/rust-lang/rust/issues/19981

**Comment by alexcrichton** [comment]
I guess it may be a little better than +111, but https://github.com/rust-lang/rust/pull/19983 didn't land b/c it didn't work on windows. I'm not actually sure how to do this cross platform-wise...

**Comment by huonw** [comment]
Oh. :cry: 

@bors: r+ fd781a1

**Pull request merged**
