### PR TITLE
Improve `check_not_dirty` git repo detection and status shell output of results.

### LINKED ISSUE #5823: No git repo found on windows (only) for package_verbose test
This was discovered with testing for #5786. See that discussion. At present on master, the package::package_verbose test is not engaging, on windows only, the `check_not_dirty` function of `cargo_package` for a sub-package, even though the sub-package *is* in a git repo.  On other platforms the (parent) repo is found and the dirty check occurs.

### PR DESCRIPTION
**Pull request by dekellum**
Fixes #5823 

Also fix associated tests. This is an attempt to clarify windows+git package behavior as uncovered in #5786.  ~~This is a Work In Progress not yet ready for merge.~~

This conflicts with #5786, but either could be merged first, requiring a rebase/merge in the other.

### CODE REVIEW

**Comment by dekellum** [comment]
Checks pass and this fixes the windows disparity. This conflicts with #5786, but its probably best if this is merged to master first, then I'll merge and resolve conflicts in #5786, avoiding the need for a `cfg(windows)` specific test variant. 

@alexcrichton: r? Merge?

**Comment by dekellum** [comment]
Ping @alexcrichton, this bug fix should be easy to review and merge, no?

**Comment by ehuss** [comment]
This looks to be the same as https://github.com/alexcrichton/git2-rs/pull/335.  I did a quick check, and converting the \ to / in `status_file()` fixes it.  I would say the correct fix is to have git2-rs convert all paths, or (wishful thinking) have libgit2 handle windows-style paths.

**Comment by dekellum** [comment]
I want a reasonable workaround that (probably, let me know otherwise) can't change the minimum release of *git2-rs* as a *cargo* dependency. Could I just add that `\` to `/ conversion [here on L171](5820/files#diff-e23c793746a7be78139a4e37509a74acR171)?  The reason I suggest adding it, is that the verbose console logging, and the fall-back-to-workspace is I think value add, even if you are correct on the cause, @ehuss.  Thoughts?

@alexcrichton minimal changes to tests in this PR is correct, but your point in alluding me however. As to *what is going on*: Most of the tests use the verbose console output, or files included in the package. While on **master** `check_not_dirty` doesn't include verbose console output and doesn't influence the files included (sans #5786), so given that, `check_not_dirty` and its git-repo detection, hasn't really been thoroughly tested, beyond the limited dirty/not-dirty case. I hope that makes sense? I'm not sure its what you are asking for however.

**Comment by ehuss** [comment]
@alexcrichton the repro is:
1. `cargo new foo`
2. `cd foo`
3. `cargo new bar`
4. `cd bar`
5. `cargo package`

Step 5 should fail, but it passes on Windows because it uses the path `bar\\Cargo.toml` to `git_status_file()`, and it returns None instead of `WT_NEW`.

**Comment by alexcrichton** [comment]
Hm so do we have a failing test on Windows *today*? How come these tests aren't failing on CI?

**Comment by ehuss** [comment]
> Hm so do we have a failing test on Windows today? How come these tests aren't failing on CI?

No, there are no current tests that exercise this code path with a slash in it.  The closest is `package_verbose`, but it specifies `--no-verify` which turns it off.  @dekellum used the code in `check_not_dirty` to implement the new feature, and in the process uncovered the problem because it failed to get the git info in the `package_verbose` test on windows.

**Comment by dekellum** [comment]
@ehuss isn't answering my questions, but perhaps there a multiple possible fixes (@ehuss's experiment, and this PR)?  I'm not sure at present what is best: one, the other, or both?

**Comment by ehuss** [comment]
> @ehuss isn't answering my questions

Oh, sorry I missed that.  My vote is to update `git2-rs` to use the correct path type.  I also might be willing to help audit the api to see if there are any other places that need updating, but I probably won't get to that soon.  What would be the benefit of running discover twice, once with an incorrect path?

**Comment by dekellum** [comment]
Thanks @ehuss, as I said, yes, fix git2-rs for the root cause; but if we can workaround it here first, that is helpful.  I went from detected-broken-on-windows (adc5074) to fixed-on-all-platforms (ad0b252) in this PR. Would you suggest any other changes for this fix?  Why couldn't I just convert the slashes on that line?

**Comment by ehuss** [comment]
If `git-rs` is fixed, these changes wouldn't be necessary, correct?  Personally I prefer to fix root issues if possible rather than work around them.  Also, I'm not sure I understand why `discover` is being called twice.

**Comment by alexcrichton** [comment]
I agree with @ehuss that if the issue is in `git2` we should fix it there as it ideally would be fixed in libgit2 but `git2` is our best bet for now.

**Comment by dekellum** [comment]
So do you just want to close this?  The verbose console logging changing includes here make the conditional at least testable, which seems healthy.  Perhaps  you are less concerned about that?

**Comment by alexcrichton** [comment]
Sure yeah, closing this is ok for now. Would you like to create a dedicated PR for the UI changes? Would you be interested in making the change to git2-rs?

**Comment by dekellum** [comment]
Based objectively on this experience of two rejected PRs, with little to no reasonable cause, *no I do not*.

**Comment by dekellum** [comment]
**Oh, and note**: the tests for this potential new PR will necessarily depend on a real fix in git2-rs.

**Comment by alexcrichton** [comment]
@dekellum oh you mentioned that the console logging changes seemed like a good idea regardless so we can always have PRs for things like that, and having a workaround is fine for now as well if you'd prefer to not make a fix to git2-rs

**Pull request closed without merging**
