### PR TITLE
Add snapshot for DragonFly

### PR DESCRIPTION
**Pull request by mneumann**
http://www.ntecs.de/downloads/rust/cargo-nightly-x86_64-unknown-dragonfly.tar.gz

This is the 0.5 version of cargo as it's much harder to build an old snapshot.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could this be used to build the same version of Cargo from before? I'd be a little worried that subtle differences in the nightlies would cause problems later on down the road.

**Comment by alexcrichton** [comment]
e.g. could this be used to build the nightly from 2015-04-02?

**Comment by mneumann** [comment]
Hm, I didn't try that. The question is why would you want to build that snapshot? I am using the snapshot to build  0.4.0.20150720 (the version in FreeBSD ports tree), and it works (with some minor patching). The problem with building 2015-04-02 is that this would require an old version of rustc (pretty hard to get, maybe lots of patching...) and also some libraries cargo depends on would need patches to be applied. I'd rather kindly ask you to roll out a new cargo snapshot :).

**Comment by alexcrichton** [comment]
Ah ok yeah if you have to backport a bunch of patches and such it's definitely not worth it, I'll upload this and call it 2015-04-02 and pray no one notices :)

**Comment by mneumann** [comment]
@alexcrichton : Thanks!

**Pull request merged**
