### PR TITLE
Run the cross-compile disable check ASAP

### LINKED ISSUE #5141: run cross_compile::build_deps_for_the_right_arch  test first
cross_compile::build_deps_for_the_right_arch fails on my system and it always prints
````
This failure can be safely ignored. If you would prefer to not see this
failure, you can set the environment variable CFG_DISABLE_CROSS_TESTS to "1"
....
````
and then I re-run the tests with CFG_DISABLE_CROSS_TESTS=1

Can we run this test before all other tests to make sure we don't have to rerun the half the testsuit if it fails?

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #5141

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

Hm I'll need to look into that failure, almost certainly spurious...

**Comment by ehuss** [comment]
@alexcrichton What do you think about turning off the master branch for travis and appveyor?  Every merge gets built twice, and I'm not sure it's really useful.  I don't know if that would help the appveyor timeouts, since it looks like builds get stuck waiting in the queue.

**Comment by alexcrichton** [comment]
@bors: retry 

Sounds like a solid idea to me! Definitely agreed the tests aren't necessary

**Pull request merged**
