### PR TITLE
Correct bad syntax in cfg_rustflags_precedence test

### PR DESCRIPTION
**Pull request by SpaceManiac**
Cargo is failing and thus this test is passing due to a syntax error in the `Cargo.toml`, and not due to the bogus flag.

Actually, I can't get this feature to work period, even though these tests appear to pass, but maybe that's me and not bunk tests.

EDIT: I'm convinced this feature is just broken. I'd have to study Cargo for some time to try to fix it, but if desired I can submit test cases that show so.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think actually the arguments here are quoted (explicit `\"` around the argument) but removing those may get it "passing for real" ?

**Comment by SpaceManiac** [comment]
I think the quotes are intentional; they work elsewhere. Looking closer, these tests are very bogus, e.g. `cfg_rustflags_normal_source` is passing because there's no feature in the `Cargo.toml` named `feat`, so all the invocations fail, and *not* because the flags are actually being applied.

CC @tee-too

**Comment by alexcrichton** [comment]
No the quotes here are not working as intended. Do you get an error when removing them?

**Comment by alexcrichton** [comment]
You're right in that there's no feature, you may need to add such a feature to ensure it fails correctly. It may be worth specifying the failure stderr while you're at it to narrow down the whitelisted set of failures here.

**Comment by SpaceManiac** [comment]
You're right, I misunderstood what you were referring to. I have corrected the two existing tests and added two new ones. All four fail. I may try to look at the implementation, but I'm not familiar with it at all, so it may take some time. If it's important, I can figure out how to add error message checking for the failure cases.

**Comment by alexcrichton** [comment]
Looks like CI may still be failing?

**Comment by alexcrichton** [comment]
Closing due to inactivity, but please feel free to resubmit with a rebase!

**Pull request closed without merging**
