### PR TITLE
Adding target support to cargo package and cargo publish

### PR DESCRIPTION
**Pull request by nisargthakkar**
Fixing Issue #4012 
I was not able to run the tests locally. Hence, need to check if the Travis builds complete successfully

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks great, thanks! Can you be sure to add a test for this as well?

**Comment by nisargthakkar** [comment]
@alexcrichton Sure. I'll add some tests for this change.

**Comment by nisargthakkar** [comment]
Sorry this has taken so long for me to add tests for. I was away from internet cnnectivity for the past 10 days. I will work on this over the weekend and try to send the PR with the tests

**Comment by alexcrichton** [comment]
No worries! Feel free to just ping here when it's ready

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with some tests attached!

**Pull request closed without merging**
