### PR TITLE
Add --ignore-rust-version flag to cargo install

### LINKED ISSUE #11718: add `--ignore-rust-version` for `cargo install`
### Problem

Subcommands like `build` allow to ignore the minimum rust version of dependencies by the `--ignore-rust-version` flag.

Because `build` is a step of `cargo install`, this flag should be available there too.

### Proposed Solution

```diff
Index: cargo/src/bin/cargo/commands/install.rs
===================================================================
--- cargo.orig/src/bin/cargo/commands/install.rs
+++ cargo/src/bin/cargo/commands/install.rs
@@ -78,6 +78,7 @@ pub fn cli() -> App {
                 .conflicts_with_all(&["git", "path", "index"]),
         )
         .arg_message_format()
+        .arg_ignore_rust_version()
         .arg_timings()
         .after_help("Run `cargo help install` for more detailed information.\n")
```

### Notes

_No response_

### PR DESCRIPTION
**Pull request by chaitanyav**
@weihanglo Added the flag to cargo install 
fixes #11718

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Hi, could you update the manpage of `cargo install` as well?
Please take [this](https://github.com/rust-lang/cargo/blob/4a3c588b1f0a8e2dc8dd8789dbf3b6a71b02ed49/src/doc/man/cargo-build.md?plain=1#L43) as a reference and follow [this](https://github.com/rust-lang/cargo/tree/master/src/doc#building-the-man-pages) to regenerate docs.

**Comment by chaitanyav** [comment]
> Hi, could you update the manpage of `cargo install` as well? Please take [this](https://github.com/rust-lang/cargo/blob/4a3c588b1f0a8e2dc8dd8789dbf3b6a71b02ed49/src/doc/man/cargo-build.md?plain=1#L43) as a reference and follow [this](https://github.com/rust-lang/cargo/tree/master/src/doc#building-the-man-pages) to regenerate docs.

@weihanglo updated the docs

**Review by weihanglo — APPROVED** [review]
Looks good. Thanks!

BTW, I found that `--ignore-rust-version` is missing in both zsh and bash completion for all commands having such flag. If you're still interested in helping out, I would appreciate a pull request for adding them. Could probably take [this](https://github.com/rust-lang/cargo/pull/11204/files) as a reference.

**Comment by weihanglo** [comment]
The bug in `nightly-2023-03-16` [was fixed](https://github.com/rust-lang/rust/pull/109183) a couple hours ago on master and will be available tomorrow.

**Comment by chaitanyav** [comment]
> Looks good. Thanks!
> 
> BTW, I found that `--ignore-rust-version` is missing in both zsh and bash completion for all commands having such flag. If you're still interested in helping out, I would appreciate a pull request for adding them. Could probably take [this](https://github.com/rust-lang/cargo/pull/11204/files) as a reference.

sure, will make a pull request with bash and zsh completion

**Review by weihanglo — APPROVED** [review]
Thanks for the contribution!

---

For whom wants to test the completion


zsh: 
```zsh
# under cargo project directory
fpath+=$PWD/src/etc
compinit

# test it
cargo rm <tab>
```

bash

```bash
# install any bash completion from your distro and source their init script
# e.g. brew install bash-completion && . "/path/to/pbash_completion.sh"

# under cargo project directory
. ./src/etc/cargo.bashcomp.sh

# test it
cargo rm <tab>
```

**Pull request merged**
