### PR TITLE
Add support for fetching git refspecs

### PR DESCRIPTION
**Pull request by gh2o**
This would allow e.g. fetching pull requests directly from Github:

```
[dependencies.foo]
git = "https://github.com/user/foo"
refspec = "refs/pull/42/head"
```

The "refs/" prefix is optional.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR!

This is definitely a weighty-ish feature so we'll want to get @rust-lang/cargo's sign off before merging, but in any case I've always personally been a bit hazy about what refspecs are and how we're fetching and whatnot. For example here it looks like the `refs/` prefix is special (optional?) and I'm not sure we'd want to treat it specially. Additionally updating the specs we fetch from a remote seems reasonable but I'd have to take a closer look. It seems like we're updating/fetching more refs than before in some situations? 

Is there a way we could defer 100% of refspec parsing to libgit2? Or perhaps tweak how cargo fetches refs and make it a bit smaller by default?

**Comment by joshtriplett** [comment]
@alexcrichton It's definitely possible to just use libgit2 and have it DTRT for you, yes. Just hand the refspec to `git_remote_download`, then check it out when you're done and use it as the source.

You'll want to have *many* tests for variations on refspecs. And I would suggest limiting the ability to use arbitrary receive-side parts on the refspecs.

**Comment by alexcrichton** [comment]
ping @gh2o, out of curiosity any updates on this?

**Comment by gh2o** [comment]
I will fix up the refspdcss

**Comment by alexcrichton** [comment]
I'm gonna close this for now due to inactivity, but feel free to resubmit!

**Pull request closed without merging**
