### PR TITLE
Rename `--all` to `--workspace`

### PR DESCRIPTION
**Pull request by k-nasa**
## Background

close: https://github.com/rust-lang/cargo/issues/6977

## Description
- Warn when using the 'all' option
- Changed help text

### CODE REVIEW

**Comment by k-nasa** [comment]
Ok! I'll change `src/doc`, but I probably don't have time. May make you wait...

**Comment by k-nasa** [comment]
@ehuss I changed `src/doc` and delete warnning! How about?

**Comment by k-nasa** [comment]
I fixed conflict

**Comment by k-nasa** [comment]
@ehuss ?

**Comment by ehuss** [comment]
I added some updates.  There were some parts that were missing updates (like the man pages).  I also slightly reworded the help text.  I also rebased on the latest master.

@bors r+

**Comment by est31** [comment]
@ehuss what happened to my suggestion?

**Comment by ehuss** [comment]
> @ehuss what happened to my suggestion?

I'd like to avoid using short flags unless it is an option that is heavily used.  There are some options to reduce the burden of longer flags (shell completion, aliases, etc.).  The `--all` flag will also stay forever, so if you really want to, you can continue to use it.  We'd also like to better understand all the scenarios where this flag is even needed, and see if it can be avoided altogether in more situations.  We can also always add a short flag at any time in the future.

**Comment by est31** [comment]
In one of my multi-crate projects, `cargo test` only tests the default crate. I didn't realize this so one of my tests regressed. I only noticed much later. Then I switched to always doing `cargo test --all` manually after each commit. I'm not sure but I think I also need to do `cargo check --all` to be able to also check some binary targets that the default crate is using as library. Aliases are cool but personally I try to avoid customizing my computer as little as possible. But thanks for giving an explanation at least.

**Comment by sharksforarms** [comment]
I also use `--all` on most of all my cargo commands since the project I work on is a workspace of over 5 modules/crates

Mainly these:
`cargo build --all`
`cargo test --all`
`cargo fmt --all`

Glad `--all` is staying, it's also shorter to type.

**Comment by lnicola** [comment]
Is it intentional that `cargo fmt --workspace` doesn't work while `cargo fmt --all` does?

**Comment by ehuss** [comment]
@lnicola Are you sure you have 1.39 (just released today) or newer?  It seems to work for me.

**Comment by lnicola** [comment]
```
$ cargo --version      
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
$ cargo fmt --all      
$ cargo fmt --workspace
error: Found argument '--workspace' which wasn't expected, or isn't valid in this context

USAGE:
    cargo fmt [FLAGS] [OPTIONS] [-- <rustfmt-options>...]

For more information try --help
```

**Comment by ehuss** [comment]
Oh, sorry, I misread `fmt` as `fix`.  `cargo fmt` is an external command with its own arguments. You may file an issue at https://github.com/rust-lang/rustfmt/issues to follow up.

**Comment by lnicola** [comment]
D'oh, I should have realized that. Sorry for spamming.

**Comment by CAD97** [comment]
To perfectly mirror the behavior of cargo, the behavior should be

- `cargo fmt`: format the [default members](https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#package-selection) of the workspace (and workspace-local path dependencies)
- `cargo fmt --workspace`: format all of the members of the workspace (and workspace-local path dependencies)

Even if rustfmt decides that `--all` is the canonical flag for rustfmt, `cargo fmt` should probably allow both `--all` and `--workspace` so that people who are using `cargo check --workspace` can then also use `cargo fmt --workspace` without having to learn that, actually, `cargo fmt` uses `--all` even though that's a deprecated flag for `cargo check`.

**Pull request merged**
