### PR TITLE
Support crate renames in `cargo metadata`

### PR DESCRIPTION
**Pull request by matklad**
This adds information about (currently unstable) crate renames to metadata. Unfortunately, we already expose dependencies as a list of package ids (which are strings), so we can't easily add a `rename` field easily. For this reason, I've added a parallel `deps` key, which basically deprecates `dependencies` field. 

So, the new format looks like this

```JavaScript
{
    "dependencies": [
        "bar 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
        "bar 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
    ],
    "deps": [
        {
            "extern_crate_name": "baz", // this one is actually renamed
            "id": "bar 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)"
        },
        {
            "extern_crate_name": "bar",
            "id": "bar 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
        }
    ],
    "features": [],
    "id": "foo 0.5.0 (path+file://[..])"
},
```

Questions:

* Is there a better name for `extern_crate_name`? This name is precise, but it's longer than I like, and might become opaque in meaning if we remove `extern crate` from the language :) 
* Should we feature gate this (i.e, only produce `deps` if we have a feature in `Cargo.toml`)? I think the answer is yes, but that'll require threading `Features` to `Workspace`...

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
I wonder if we could hit a few birds with one stone by changing the output to something like:

```
{
  "dependencies": [ ... ],
  "rename": {
    "foo": "package id here",
  },
  ..
}
```

We could only include `rename` if at least one dependency is renamed (automatically feature-gating this) and also avoids the `extern_crate_name` naming I think?

**Comment by matklad** [comment]
Hm, this sounded really neat, and I was really excited about using a map instead of a list, but now I think it won't fly :(

There are two problems:

First, you can't use renames as keys, because of examples like this

```
[dependencies]
rand = "0.3"

[build-dependencies]
rand = "0.4"
```

Second, we already really need to add more info to dependencies (like, is it a normal dep or a build-dep), and we would need to add even more info, if we implement target-specific deps. 

I also would love to include not only explicit renames, but non-renamed crate names as well: that way, clients won't have to figure out that library name might be different from the package name, and that `-` should be translated to `_`. 

I guess I'll just feature gate this properly, and will try to find a better name for `extern_crate_name` :)

**Comment by alexcrichton** [comment]
Ah ok that makes sense to me, sounds like we'll need an auxiliary array no matter what to express the kind of dependencies, so seems fine by me!

**Comment by sfackler** [comment]
cc #4632 and #4631 for other other dependency-related info that'd be good to add when refactoring!

**Comment by matklad** [comment]
Updated!  The strategy now is to basically dump edges of resolve, which were introduced recently. 

`extern_crate_name` is just `name` now, and I think we don't need to feature-gate it, because it does not expose `rename` key directly anyway. That is, even if rip `rename` of, having `name: pkg.lib_target().unwrap().crate_name()` would still be useful. 

https://github.com/rust-lang/cargo/issues/3984 is fixed
https://github.com/rust-lang/cargo/issues/4631 is fixed

https://github.com/rust-lang/cargo/issues/4632 is **not** fixed, because we don't know `cfg`s when producing metadata, and the command itself even lacks the `--target` option.

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Could this also update https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html with relevant information?

**Comment by matklad** [comment]
>Could this also update https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html with relevant information?

Sure! We historically have been bad with keeping that page really comprehensive. What do you think about saying: "this is API intended for developers of tools, so it is documented via doc comments in the source code, [link to some revision of `ExportInfo`]"?

**Comment by alexcrichton** [comment]
Yeah I think that's ok if the previous documentation is deleted, b/c I think after this PR it'd be out of date

**Comment by matklad** [comment]
>Yeah I think that's ok if the previous documentation is deleted, b/c I think after this PR it'd be out of date

Ok! Let's then merge this PR first, and then update the separately, so that I have an url with reasonable revision to put into the docs!

**Comment by alexcrichton** [comment]
@bors: r+

Sounds good to me!

**Comment by sfackler** [comment]
> #4632 is not fixed, because we don't know cfgs when producing metadata, and the command itself even lacks the --target option.

Cargo doesn't need to know which cfgs would be active if it was building the crate, it just needs to say that the dependency is only loaded for target X or cfg Y in the metadata JSON.

**Comment by matklad** [comment]
I am having second thoughts here. Currently, we expose raw dependencies and make the clients to the work of figuring out which dep applies to which target. A theoretically better solution would be to directly produce, for each target, its dependent targets. The problem here is that we don't have a `target_id` concept, to refer to a particular target of a package. I've filed https://github.com/rust-lang/cargo/issues/5508 about that.

**Pull request merged**
