### PR TITLE
Making tests less strict so they won't break on output changes

### PR DESCRIPTION
**Pull request by mersinvald**
Required for https://github.com/rust-lang/rust/pull/41910

cc @Mark-Simulacrum
cc @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Changes generally look good to me. I'll leave for @alexcrichton though since I'm not familiar with Cargo.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by mersinvald** [comment]
@alexcrichton failed jod seems to have empty log. Can you restart it maybe?

**Comment by alexcrichton** [comment]
@bors: retry

How odd!

**Pull request merged**
