### PR TITLE
Add tests for `cargo owner -a/-r` / `cargo yank --undo`

### PR DESCRIPTION
**Pull request by giraffate**
Follow up 5e15286.

There were no tests for `cargo owner -a/-r` and `cargo yank --undo`. However, These commands in tests had empty response. So I also update response handling with reference to https://github.com/rust-lang/cargo/pull/3301/commits/7dd0f932a864d97bef5da26a0e148fca3f06d448.

### CODE REVIEW

**Comment by giraffate** [comment]
I don't know if it's appropriate to update the response handling here for adding tests. If this is not appropriate, feel free to close this PR.

**Comment by alexcrichton** [comment]
Thanks for the PR!

For crates.io I suspect it always says `ok:true`, but are you thinking of working with a registry that returns `ok:false`? If so I think that's fine but we probably won't be able to add many tests for this due to the empty responses received in test mode (and I'd prefer to not have the empty-response-handling in Cargo).

**Comment by giraffate** [comment]
No. Thanks for your information. I didn't know crates.io says always `ok:true`.

I agree with you. I just wanted to add a test, not a fix for response handling. It seemed to fix the response handling for empty responses in https://github.com/rust-lang/cargo/commit/7dd0f932a864d97bef5da26a0e148fca3f06d448 (these lines https://github.com/rust-lang/cargo/blob/master/crates/crates-io/lib.rs#L221-L225 ) for testing, so I made this fix as well.

I reverted fixes of response handling and fixed tests. Could you review this again?

**Comment by alexcrichton** [comment]
Ah ok, thanks for this! If this is just updating tests, then I think the documentation change isn't necessary any more as well, right?

**Comment by giraffate** [comment]
Thanks for your review!
Oh sorry, I forgot to revert updating a doc. I fixed this.

**Pull request merged**
