### PR TITLE
Add an explanation of the labels

### PR DESCRIPTION
**Pull request by carols10cents**
As requested @matklad! ❤️ Are there any questions you have about the labels that remain unanswered?

### CODE REVIEW

**Comment by matklad** [comment]
Wow, that is much more thorough explanations than I had expected! Thanks a lot @carols10cents , I'be definitely learned more about our issues now ❣️ 

@bors r+

**Comment by matklad** [comment]
@carols10cents what does `E-mentor` mean? I can think of at least to explanations:

1) an issue with an actual live mentor, whom you can ping on IRC, ask questions, etc.
2) an issue with some instructions on how to fix it (like, where's the relevant code, where are the tests, what should be changed).

Specifically, I've just created https://github.com/rust-lang/cargo/issues/4563 and I think it's mentor in the 2) sense, but not in the 1), so I don't know if I should apply the label :)

**Comment by carols10cents** [comment]
@matklad to me, it means at least 2) and optionally 1) if 2) is insufficient :) I don't know if my interpretation is common though!

**Pull request merged**
