### PR TITLE
Update lock file encodings on changes

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit alters Cargo's lockfile encoding update strategy from its
previous incarnation. Previously Cargo had two versions, one for new
lock files and one for old lock files. Each of these versions were
different and would affect how Cargo manages lock file updates. The
intention was that we'd roll out defaults to new lock files first and
then later to preexisting lock files. This requires two separate
changes, though, and it's not necessarily clear when to start updating
old lock files. Additionally when old lock files were opted in it would
break builds using `--locked` if they simply updated Cargo because Cargo
would would want to bring the lock file versions forward.

The purpose of this change is to solve these issues. The new strategy
for updating a lock file's encoding is to simply preserve what's already
existing on the filesystem until we actually decide to write out a new
lock file. When Cargo updates a lock file on-disk then it will, at that
time, update the lock file encoding to whatever the current default is.
This means that there's only one version number to keep track of (the
default for encoding). Cargo will always preserve the preexisting
encoding unless another change is required to the lock file.

### CODE REVIEW

**Comment by Eh2406** [comment]
I like the idea! The fact that we have not force updated to the current logfile makes me thing that this policy matchs what we were willing to do better than the nominal old policy. Over all +1.

I have made too many mistakes lately to approve on my own. But the code looks good.

I do have one thought, what amount of change triggers the update to the version? `cargo update`, or adding a `dep`, or any change, or only when there is not a previous lockfile?

**Comment by alexcrichton** [comment]
Oh no worries! Let's r? @ehuss here to get a second set of eyes.

The intention of this change is that if Cargo is writing a lock file it always writes it in the maximum of the default encoding version and the version of the previous lock file. Cargo only writes a lock file if it changes (or didn't exist) which means that only when lock files change is the lock file encoding updated. The lock file can change for any of the reasons you mentioned, basically. To try to list them as a bulleted list:

* Adding a dependency
* Removing a dependency
* Changing a version requirement on a dependency
* Running `cargo update`
* Running `cargo update -p`
* Deleting the previous lock file (or if there isn't one)
* Changing names of crates

A bug this is fixing is that if you take an old project (as of this Cargo version) and run `cargo build --locked` it won't update the lock file even if the default encoding is updated (unlike Cargo as of before this PR), yay!

**Comment by Eh2406** [comment]
@bors r? @ehuss

I do love the code and docs simplicity of the "any change" answer. But I wonder if the users will expect some changes to be "so small" as to not justify being upgraded. So do we want the bug reports or do we want the more complicated code. 🤷

**Comment by ehuss** [comment]
Seems reasonable to me. v2 was introduced in 1.38 (09-26-2019), made the default in 1.41 (01-30-2020) and this would hit stable in 1.47 (10-08-2020), giving over a year span of stable releases. If anyone wants to support older versions, they can stay on v1, and do updates with any cargo older than 1.47.

@bors r+

**Comment by mathstuf** [comment]
> If anyone wants to support older versions, they can stay on v1, and do updates with any cargo older than 1.47.

Unfortunately, some useful nightly flags still exist (`-Z minimal-versions`) which this has now broken.

**Pull request merged**
