### PR TITLE
pass `-C ar`/`-C linker` when building native dylibs/plugins

### LINKED ISSUE #1515: config: `-C ar=`/`-C linker=` are not passed to `rustc` when building dylib crates
### STR

On a new binary project, add these

``` toml
# .cargo/config
[target]
ar = "x86_64-pc-linux-gnu-ar"
linker = "x86_64-pc-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
ar = "x86_64-pc-linux-gnu-ar"
linker = "x86_64-pc-linux-gnu-gcc"
```

``` toml
# Cargo.toml
[package]
name = "foo"
version = "0.0.1"
authors = ["me"]

[dependencies]
debug_unreachable = "*"
```

``` bash
$ cargo build --verbose
   Compiling debug_unreachable v0.0.4
     Running `rustc /home/japaric/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/debug_unreachable-0.0.4/src/lib.rs --crate-name debug_unreachable --crate-type dylib -C prefer-dynamic -g -C metadata=aad5c32c36d9ddf5 -C extra-filename=-aad5c32c36d9ddf5 --out-dir /home/japaric/tmp/foo/target/debug/deps --emit=dep-info,link -L dependency=/home/japaric/tmp/foo/target/debug/deps -L dependency=/home/japaric/tmp/foo/target/debug/deps -Awarnings`
error: could not exec the linker `cc`: No such file or directory (os error 2)
error: aborting due to previous error
fatal runtime error: Could not unwind stack, error = 5
Could not compile `debug_unreachable`.
```

(Note: For this example, there are no `cc`/`ar` symlinks in `PATH`)

`-C ar`/`-C linker` are not passed to `rustc` when building `debug_unreachable`.

But if I remove the `debug_unreachable` dependency, then the crate compiles correctly.

``` bash
$ cargo build --verbose
   Compiling foo v0.0.1 (file:///home/japaric/tmp/foo)
     Running `rustc src/main.rs --crate-name foo --crate-type bin -g --out-dir /home/japaric/tmp/foo/target/debug --emit=dep-info,link -C ar=x86_64-pc-linux-gnu-ar -C linker=x86_64-pc-linux-gnu-gcc -L dependency=/home/japaric/tmp/foo/target/debug -L dependency=/home/japaric/tmp/foo/target/debug/deps`
```

because `-C ar`/`-C linker` are passed in this case.

### Version

```
cargo 0.0.1-pre-nightly (72c2e3d 2015-04-10) (built 2015-04-10)
```

### PR DESCRIPTION
**Pull request by japaric**
closes #1515 

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you add a test for this as well?

**Comment by japaric** [comment]
@alexcrichton I've added a test

**Comment by alexcrichton** [comment]
@bors: r+ e2c0a9d

Thanks!

**Comment by tamird** [comment]
http://buildbot.rust-lang.org/builders/cargo-win-64/builds/608/steps/test/logs/stdio:

```
failures:

---- test_cargo_compile_plugins::native_plugin_dependency_with_custom_ar_linker stdout ----
	thread 'test_cargo_compile_plugins::native_plugin_dependency_with_custom_ar_linker' panicked at '
Expected: execs
    but: differences:
  2 - |   Compiling bar v0.0.1 (file:///C:/bot/slave/cargo-win-64/build/target/x86_64-pc-windows-gnu/debug/cit/test-165/bar)|
    +

  3 - |     Running `rustc [..] -C ar=ar -C linker=cc [..]`|
    +


other output:
`error: could not exec the linker `cc`: The system cannot find the file specified.
 (os error 2)
error: aborting due to previous error
Could not compile `foo`.

Caused by:
  Process didn't exit successfully: `rustc C:\bot\slave\cargo-win-64\build\target\x86_64-pc-windows-gnu\debug\cit\test-165\foo\src\lib.rs --crate-name foo --crate-type dylib -C prefer-dynamic -g -C metadata=5de7eb88bf78301b -C extra-filename=-5de7eb88bf78301b --out-dir C:\bot\slave\cargo-win-64\build\target\x86_64-pc-windows-gnu\debug\cit\test-165\bar\target\debug\deps --emit=dep-info,link -C ar=ar -C linker=cc -L dependency=C:\bot\slave\cargo-win-64\build\target\x86_64-pc-windows-gnu\debug\cit\test-165\bar\target\debug\deps -L dependency=C:\bot\slave\cargo-win-64\build\target\x86_64-pc-windows-gnu\debug\cit\test-165\bar\target\debug\deps` (exit code: 101)
`', C:\msys64\slave\cargo-win-64\.cargo\git\checkouts\hamcrest-rust-38ec3a2c2573160a\master\src/hamcrest\core.rs:22



failures:
    test_cargo_compile_plugins::native_plugin_dependency_with_custom_ar_linker

test result: FAILED. 322 passed; 1 failed; 0 ignored; 0 measured
```

maybe just use `cat` as a linker?

**Pull request merged**
