### PR TITLE
serialize version directly

### PR DESCRIPTION
**Pull request by matklad**
Streamline serialization more, cc #6511

### CODE REVIEW

**Comment by matklad** [comment]
Failure seems unrelated? travis & appverour on the PR are green :man_shrugging:

**Comment by dwijnand** [comment]
Oh yeah, PR validation is broken: https://github.com/rust-lang/cargo/pull/6510#issuecomment-450831721

**Comment by ehuss** [comment]
@bors retry

`fixes_missing_ampersand` flakey test.  I'll try to fix it today.

**Pull request merged**
