### PR TITLE
Implemented string lookup for `build.rustflags` config key

### PR DESCRIPTION
**Pull request by ibabushkin**
This addresses the immediate issue described in #3052 .
I am, however, unsure about the current state of the deeper issues mentioned in that issue, but if needed, I can take stab at them as well. :)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Could you add a test for this as well?

**Comment by ibabushkin** [comment]
Sure, will do!

**Comment by ibabushkin** [comment]
Sure, will do!

Also, it would make sense to allow for the same syntax in the `target.<...>` section, I think I'll add that as well.

**Comment by ibabushkin** [comment]
While building the test case, I noticed that some moving part outside of cargo is doing config file validation, killing the process with an error message before my code runs:

```
error: invalid configuration for key `build.rustflags`
expected a list, but found a string for `build.rustflags` in /path/here
```

I'll look into it now.

**Comment by alexcrichton** [comment]
Oh I think it's the `get_list(key)?`, you'll want to change that to handle the error by looking up a string instead

**Comment by ibabushkin** [comment]
Yes, I figured as much :)

**Comment by ibabushkin** [comment]
Hm, after fiddling around with the code a bit, I think this is the cleanest implementation:

```Rust
    match config.values()?.get(&key) {
        Some(&ConfigValue::String(ref arg, _)) => {
            return Ok(arg.split(' ').map(str::to_string).collect());
        },
        Some(&ConfigValue::List(ref args, _)) => {
            let args = args.into_iter().map(|a| a.0.clone());
            return Ok(args.collect());
        },
        Some(value) => return config.expected("list or string", &key, value.clone()),
        None => (),
    }
```

**Comment by alexcrichton** [comment]
Ah I prefer to use `get_string` and `get_list` wherever possible as it works with the env vars (where the `values()` method doesn't right now

**Comment by ibabushkin** [comment]
Yes, that's indeed a pitfall. I guess it won't work without a third lookup for the value, however, if we want a custom error message (which I think would make sense). Or I could implement something like `get_string_or_list` with all the functionality as in `get_string` and `get_list` and use that, but I'm not sure whether that's worth it, given that there would be only these two calls to it. It might prove handy in the future, however.

**Comment by alexcrichton** [comment]
Oh runtime we don't really have to worry about here, just errors and such.

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Want to go ahead and refactor this to perhaps `get_list_or_maybe_string` or something like that?

**Comment by ibabushkin** [comment]
Sure. I also still need to figure out the details around the second test failing.

**Comment by ibabushkin** [comment]
This should, when passing all tests, be a complete solution in my book ^^.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by ibabushkin** [comment]
Thanks for having me!

**Pull request merged**
