### PR TITLE
Upgrade to Rust 2018 & fix edition idioms

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Similarly, we could take the time to fix the whole codebase's format and clippy lints.  WDYT?

**Comment by dwijnand** [comment]
Oh yeah this break our Rust 1.28.0 CI setup.  Do we care?

**Comment by alexcrichton** [comment]
Nah seems fine to increase the minimum Rust version. Let's land this then do a rustfmt?

**Comment by dwijnand** [comment]
Not sure if that's not the right syntax, or if bors is waiting for Travis CI validation to pass first, or what.  Let's try plain:

@bors: r+

**Pull request merged**
