### PR TITLE
Add a note for the 32 bit flag

### PR DESCRIPTION
**Pull request by sbeckeriv**
Per https://github.com/rust-lang/cargo/issues/1375

Just add a note around the python script BIT flag.

### CODE REVIEW

**Comment by sbeckeriv** [comment]
[rendered link](https://github.com/sbeckeriv/cargo/blob/document-bit-env-flag-1375/README.md)

**Comment by alexcrichton** [comment]
Thanks! Could you move this note below the code block? I think the environment variable may also be called `BITS` instead of the singular `BIT`

**Comment by sbeckeriv** [comment]
I have moved the line and confirmed it is BITS. 
Thanks
Becker

**Comment by alexcrichton** [comment]
@bors: r+ 2cdaa41929f0f51905cb6b3f48950d2d9843b773 

Thanks!

**Comment by sbeckeriv** [comment]
Sorry it looks like I wrote the commit message incorrectly for bors to closed the related issue.  Please close https://github.com/rust-lang/cargo/issues/1375

**Pull request merged**
