### PR TITLE
Add year to project template variables

### PR DESCRIPTION
**Pull request by jryans**
This adds the current year as a `year` variable for project templates. Some license files / headers include the year, so this should make it easier to include those in a template.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I wonder, is there perhaps a way to learn about the current year without pulling in all of chrono/time?

**Comment by jryans** [comment]
> I wonder, is there perhaps a way to learn about the current year without pulling in all of chrono/time?

Good question! (New to Rust, so I just grabbed `chrono` at first as suggested by the `stdx` repo.)

Looks like we can peel away one layer at least and use `time` only, with something like:

```rust
(time::now().tm_year + 1900).to_string()
```

@alexcrichton, would that be acceptable? I think if we try to dump `time` as well, we'd have to handle OS specific time formats, so keeping the `time` dependency seems nice to avoid that work here.

**Comment by alexcrichton** [comment]
@jryans yeah seems reasonable to me! I suspect `time` is the "lowest level" for now that's reasonable to start out with

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
