### PR TITLE
Switch to using --edition

### LINKED ISSUE #5406: Switch to using --edition
In https://github.com/rust-lang/rust/issues/49591 we introduced and official `--edition` flag to the rust compiler. Let's start using that in cargo now.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #5406

### CODE REVIEW

**Comment by matklad** [comment]
@bors r+

Thanks!

**Comment by dwijnand** [comment]
looks like even though https://github.com/rust-lang/rust/pull/50080 landed 2 days ago there's no nightly doesn't include it?

just updated my local nightly and it's from 4 days ago - is this normal?

```bash
$ rustc +nightly --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
```

**Comment by matklad** [comment]
Yep, nightlies are produced only when RLS and rustfmt work, and that is not always the case

**Comment by dwijnand** [comment]
Ah, I see! is there a dashboard or log somewhere to track/see that?

**Comment by matklad** [comment]
I don’t know, I just rustup update nightly to check.

Closing in favor of https://github.com/rust-lang/cargo/pull/5410:)

**Comment by dwijnand** [comment]
uhh....

:(

**Comment by dwijnand** [comment]
following the same spirit as [this comment](https://github.com/rust-lang/cargo/pull/5358#issuecomment-382310323) I don't understand why my PR was closed in favour of an almost identical one opened hours after mine.

it's not a major issue, particularly with a 3 line PR, but maybe it's even better to be mentioned in this trivial case instead of in a more important, large PR.

**Comment by matklad** [comment]
The two PRs indeed were almost identical, so at least one of them had to be closed. There’s no real reason to prefer one to the other, so I’ve picked the other one for semi-arbitrary reason that it changed comments to not refer to the Z flag.

It’s the nature of loselelly coordinated open source projects that duplicate or contradictory work sometimes happen, [I’ve been there myself](https://github.com/alexcrichton/curl-rust/pull/208) :(

**Comment by dwijnand** [comment]
Btw I had considered the comment. I'm not expert on rustc options, but the `-Zedition` to `--edition` moved seemed to me to be about it going from being unstable to stable, and therefore I wondered if the comment should be amended, or even scrapped. Simply replacing `-Zedition` with `--edition` in the comment I perceived to be the worst option as it probably made the comment "more wrong" than just leaving it as is. It was something I expected to discuss with someone with better knowledge and foresight than myself.

About more general coordination and collaboration efforts on GitHub I recently found out (perhaps in [this](https://blog.github.com/2018-03-28-improved-organization-project-permissions/) update) that you can create GitHub teams with (just) read access to repos, and by doing so you can assign issues to those team members. Could be useful to setup (here or elsewhere).

**Comment by ehuss** [comment]
> Ah, I see! is there a dashboard or log somewhere to track/see that?

The dashboard is here: https://rust-lang-nursery.github.io/rust-toolstate/

**Comment by dwijnand** [comment]
thank you! I also found in the playground you can see the timestamp of nightly, assuming it's kept fairly up-to-date.

**Pull request closed without merging**
