### PR TITLE
Add a changelog.

### PR DESCRIPTION
**Pull request by ehuss**
I plan to periodically update this for each release.

I went back about 6 months just to fill it up a little.

[Rendered](https://github.com/rust-lang/cargo/blob/2cbb701b9205213a2864edf2daa314e7ad225f4c/CHANGELOG.md)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice! This looks fantastic to me :)

Could you speak a bit as well to what the experience was generating this? Did you find it difficult to filter down to what PRs should be included? (aka was it obvious what should be included or were a lot of PRs "on the fence") How much time did it take you to skim the history to generate this? (etc)

From a content perspective this feels just about perfect as a Cargo changelog. The 🔥 items are an easy highlight to extract for rust-lang/rust blog posts and otherwise this is still good and interesting for those who are more interested!

**Comment by ehuss** [comment]
Each release took a little over an hour, with the older ones took a little longer since I couldn't always remember why each change was made.  Future releases should go faster.  I wouldn't say it was difficult, and I kinda enjoyed the walk down memory lane. 

This only includes about 40% of the PRs. I skipped ones that were just testsuite, doc fixes, refactorings, minor tweaks, and other non-user-visible changes.  I quickly accepted that this will be imperfect; I'll miss some things, include some things that aren't interesting, and mischaracterize some.  I was on the fence on many of them, but just made a quick decision and moved on.

**Comment by alexcrichton** [comment]
@bors: r+

Ok that all sounds great to me!

**Pull request merged**
