### PR TITLE
Add man pages for cargo subcommands

### PR DESCRIPTION
**Pull request by munyari**
From #2789 

- [x] fetch
- [x] login
- [x] metadata
- [x] pkgid
- [x] rustc
- [x] rustdoc
- [x] uninstall
- [x] version
- [x] yank
- [x] generate_lockfile

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks @munyari! You can probably skip commands like verify-project, locate-project, git-checkout, and read-manifest as well.

Do you want to hold off on r+'ing until this has all of the commands you listed? (I don't mind r+'ing now)

**Comment by munyari** [comment]
Hey Alex. I guess by r+'ing, you're referring to merging? Whichever you prefer :smile: I may try to complete the rest tomorrow

**Comment by munyari** [comment]
Should be ready for r+'ing now @alexcrichton

**Comment by alexcrichton** [comment]
@bors: r+ 7ca06e7b8fde56caa8a748b495f5989b2b99000a

Thanks @munyari!

**Pull request merged**
