### PR TITLE
Add more labels to triagebot

### PR DESCRIPTION
**Pull request by ehuss**
This adds some more labels to the allowed triagebot list.

### CODE REVIEW

**Comment by hi-rustin** [comment]
Looks good to me. Thanks!

**Review by hi-rustin — APPROVED** [review]

**Review by weihanglo — APPROVED** [review]
Thanks!

**Comment by weihanglo** [comment]
Could be something related to recent CDN changes: https://blog.rust-lang.org/inside-rust/2023/01/24/content-delivery-networks.html

@bors retry

**Pull request merged**
