### PR TITLE
Fix the shell_quoting test

### PR DESCRIPTION
**Pull request by mikeyhew**
r? @alexcrichton 

add-on to #5666 
- Added `mod shell_quoting;` to testsuite/main.rs, so it actually runs
- fixed bugs in the test

### CODE REVIEW

**Comment by mikeyhew** [comment]
The test is failing on windows because `shell-escape` uses backslashes on windows, and single-quotes on unix. I'm not sure what the best thing is to do here. We could
- use `#[cfg]` attributes to use one version on windows, and a different one on unix, or
- check that the command is runnable. That's really the important thing here. One way to do that could be to figure out which part of the cargo output is from rustc, and then run the rustc command and make sure the output and exit code is the same.

What do you think?

**Comment by alexcrichton** [comment]
I think [env vars can be used](https://github.com/sfackler/shell-escape/blob/81621d00297d89c98fb4d5ceb55ad3cd7c1fa69c/src/lib.rs#L18) to trick it into always doing unix escaping, so perhaps that could be used?

**Comment by mikeyhew** [comment]
Sure, I'll try that. Should be the easiest fix.

**Pull request merged**
