### PR TITLE
Formatting for output of locate-project

### LINKED ISSUE #8009: Command-line-friendly version of locate-project
**Describe the problem you are trying to solve**
`cargo locate-project` and `cargo metadata` both return JSON output, which may be easiest when writing programs to parse it, but it is much more difficult to use in simple shell scripts.

**Describe the solution you'd like**
A `--output-format` flag or similar might be the neatest way to solve this. For example, `cargo locate-project --output-format minimal` (or something similar) would return **just** the path to `Cargo.toml`. It could also be formatted as <code>root *path*</code> or something similar, allowing the use of `grep` + `cut` for parsing, and would be more generalizable and allow for future extension `locate-project`.

Additionally, this sort of flag could also be extended to other commands and formats, as needed.

### PR DESCRIPTION
**Pull request by dtolnay**
This PR brings `cargo tree`'s existing --format flag to `cargo locate-project`.

```console
$ cargo locate-project --format '{root}'
/git/cargo/Cargo.toml

$ PROJECT_ROOT=$(cargo locate-project -f{root})
```

This allows scripts to select a script-friendly output representation. All the logic for interpreting such format flags already exists and is used by `cargo tree --format`. This solution is straightforwardly forward-compatible with introducing additional entries into what locate-project can produce, unlike such alternatives as `cargo locate-project --output-format plain`.

I like `jq` (am the third biggest contributor to it) but in 2020 we can't count on it being installed on target systems.

Closes #8009.

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks for the PR! This definitely seems useful.  Can you say more why you went with a free-form "format" option?  We were thinking it might be better to use a fixed-format flag like `--message-format` which would be more consistent with other subcommands.  It could default to `json` (which is a little inconsistent, but is what it is), and then support another option like maybe `script`?

**Comment by dtolnay** [comment]
I was hoping to propose a way to locate the workspace's Cargo.toml, something I needed in https://github.com/dtolnay/cargo-rm and realized the only way to get it from a script is jq or a heroic sed.

For just the current crate root a new `--message-format` with a plain path output would be good, possibly adding flags for other project locations that get supported by locate-project later.

**Comment by phil-opp** [comment]
This PR (or some `--message-format root-only` option) would be also very useful for my [`locate_cargo_manifest`](https://docs.rs/locate-cargo-manifest/0.2.2/locate_cargo_manifest/) crate, which currently parses the single line of JSON returned by `cargo locate-project` using the `json` crate. If there was some way to get only the path as output, we could make the crate completely dependency-free to further improve compile times.

(@dtolnay As an unrelated side note: The popular [`cargo-edit`](https://github.com/killercup/cargo-edit) project also adds a `cargo rm` subcommand, so maybe you want to choose a different name for your project to avoid conflicts.)

**Comment by ehuss** [comment]
> For just the current crate root a new `--message-format` with a plain path output would be good, possibly adding flags for other project locations that get supported by locate-project later.

Yea, I think I would probably prefer that. Would you be ok with making that change?

**Review by dtolnay — COMMENTED** [review]
Closing in favor of #8707.

**Pull request closed without merging**
