### PR TITLE
Add an option to include crate versions to the generated docs

### PR DESCRIPTION
**Pull request by aleksator**
Fixes https://github.com/rust-lang/cargo/issues/1681

### CODE REVIEW

**Comment by ehuss** [comment]
Looks great!

Can you add a section to the bottom of [`unstable.md`](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/unstable.md) briefly describing the feature?  I created a tracking issue you can link to: `https://github.com/rust-lang/cargo/issues/7907`

**Comment by aleksator** [comment]
> Looks great!
> 
> Can you add a section to the bottom of [`unstable.md`](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/unstable.md) briefly describing the feature? I created a tracking issue you can link to: `https://github.com/rust-lang/cargo/issues/7907`

Thank you! I have added it as a separate commit (please indicate if you would prefer it squashed), linked to the issue and rebased the branch on master.

**Comment by ehuss** [comment]
Thanks!  A separate commit is probably fine, I normally only squash if there are a bunch of commits, or commits are changing previous ones in the same PR.

@rust-lang/cargo FYI, this is a really minor new nightly-only feature, so I'm not going to bother with FCP.  If there are changes (or if we think we should never do this), feel free to leave comments on the tracking issue.

@bors r+

**Comment by ehuss** [comment]
@bors retry
Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch

**Pull request merged**
