### PR TITLE
Make host_root return host.root(), not host.dest()

### LINKED ISSUE #8817: fingerprint.rs uses different target roots when serializing/deserializing
Originally found in https://github.com/EmbarkStudios/rust-gpu/issues/120, I'll use paths from my debugging there 

On this line of code, serializing the dep file, `target_root` == `/home/khyperia/me/rust-gpu/target`

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/fingerprint.rs#L1834-L1835

On this line of code, parsing the dep file, `target_root` == `/home/khyperia/me/rust-gpu/target/release`

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/fingerprint.rs#L1669

This causes extremely bizzare incorrect paths to show up in `target/spirv-unknown-unknown/release/example_shader.d`, for example, `/home/khyperia/me/rust-gpu/target/release/debug/deps/librustc_codegen_spirv.so` (note the `release/debug`)

---

I believe this is because when serializing, the root is taken from `cx.bcx.ws.target_dir().into_path_unlocked()`, which is the simple `target` dir.

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/mod.rs#L221

But when parsing the dep file, the root is taken from `cx.files().host_root()`, which is the specific target directory `target/release`.

https://github.com/rust-lang/cargo/blob/358ee548c792f730faf14963066f9c742f658f48/src/cargo/core/compiler/output_depinfo.rs#L66

I think the only reason this hasn't been noticed before is that before https://github.com/rust-lang/rust/pull/77565, absolute paths converted to relative paths never went through the `TargetRootRelative` codepath, it was always kept as absolute paths. Maybe? I don't know.

---

I would submit a PR to fix this, but I don't know which path is correct to use here.

### PR DESCRIPTION
**Pull request by khyperia**
Also create host_dest function to let other callsites retain their old functionality. Fixes #8817, verified it works on the original problem reported in the `rust-gpu` repo.

I did two things here:

1) Rename `host_root` (which returns `self.host.dest()`) to be `host_dest`. This has three callsites. I did this to make it more clear that it returns dest, not root.
2) For the callsite that's relevant in #8817, I created a "new" `host_root` function (that returns `self.host.root()`). This means that the callsite that this PR is actually fixing doesn't show up in this diff :/ - but I thought it was more clear this way.

(Also copied the example path docs over from `layout.rs` to hopefully avoid this mistake again in the future)

I tried to look into if the other two callsites should actually be calling `host.root()` instead of `dest`, because I imagine the same mistake could have been made again, but it quickly grew out of my understanding (this is my first time in the cargo codebase). Feel free to let me know if they should also call `host.root()` too, and I can update them.

Thanks! (oh gosh I have no idea what I'm doing, I hope this is right)

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nah this looks great, thanks! Would it be possible to add a test of some form for this as well?

**Comment by ehuss** [comment]
Thanks!

Do you think you could add a test for this? It would probably go in [`freshness.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/freshness.rs). There is some documentation on running and writing tests at https://doc.crates.io/contrib/tests/index.html.  I can also help answer questions or help with writing it.

I'm a little uncertain what exactly the issue is, though.  Is there a command I can run in the `rust-gpu` repo to reproduce the problem?

**Comment by khyperia** [comment]
> I'm a little uncertain what exactly the issue is, though. Is there a command I can run in the `rust-gpu` repo to reproduce the problem?

There's a bit of setup before you can build `rust-gpu`, overviewed in the [getting started](https://embarkstudios.github.io/rust-gpu/book/) guide - tl;dr install the pinned nightly version, add `rust-src rustc-dev llvm-tools-preview` components, install [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools#downloads) binaries to PATH, then `cargo build`.

There's a few fiddly dependency bugs, but theoretically, from a clean build, running `cargo build` followed by `cargo build` will *not* be a no-op, but rather rebuild a couple crates. This is because the dep file in `target/spirv-unknown-unknown/release/example_shader.d` has the nonexistent path `/.../target/release/debug/deps/librustc_codegen_spirv.so` (it should be `target/debug/deps`, not `target/release/debug/deps`), and so cargo says "oh, missing file in the deps, better rebuild".

It certainly is a massive and bizzarely-set-up project, though (building a compiler _and_ using it requires shenanigans), which obscures things a bit.

> Do you think you could add a test for this?

Yeah!

**Comment by khyperia** [comment]
Oh, I just realized, cargo itself doesn't consume the incorrect `.d` file, that's probably why this bug has gone unnoticed - it's intended to only be used by external build systems (which is _technically_ what's happening in `rust-gpu`, even though the "external build system" is actually another cargo) https://github.com/rust-lang/cargo/blob/becb4c282b8f37469efb8f5beda45a5501f9d367/src/cargo/core/compiler/output_depinfo.rs#L16-L23

In any case, test written! fails before this commit, succeeds afterwards.

**Comment by ehuss** [comment]
Looks good, thanks!

@bors r+

**Pull request merged**
