### PR TITLE
Fix missing messages when --message-format=json is deeply nested

### LINKED ISSUE #5992: `--message-format=json` doesn't emit every error message
Steps to reproduce:

```
$ cargo new foo
$ cd foo
$ echo 'yew = "= 0.4.0"' >> Cargo.toml
```

Replace `src/main.rs` with this:

```
#[macro_use]
extern crate yew;

fn main() {
    html! {
        <div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
        </div>
    }
}
```

Then if you build it:

```
$ cargo build --target=wasm32-unknown-unknown
```

you'll get the following error:

```
error: recursion limit reached while expanding the macro `stringify`
  --> src/main.rs:5:5
   |
5  | /     html! {
6  | |         <div>
7  | |             <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
8  | |             <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
...  |
17 | |         </div>
18 | |     }
   | |_____^
   |
   = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `foo`.
```

however if you build it with:

```
cargo build --target=wasm32-unknown-unknown --message-format=json
```

then the error message is missing from the output. I'd expect `cargo` to emit a line with `{"reason": "compiler-message", ...}` just as it usually does for errors; instead it emits no `"compiler-message"`s, e.g. the output of this (to match only `"compiler-message"`s):

```
$ cargo build --target=wasm32-unknown-unknown --message-format=json | ruby -ne 'require "json"; require "pp"; j = JSON.parse( $_ ); if j["reason"] == "compiler-message"; pp j; end'
```

is empty.

### PR DESCRIPTION
**Pull request by dtolnay**
This PR demonstrates using [miniserde](https://github.com/dtolnay/miniserde) for the JSON messages emitted by `machine_message::emit`. Miniserde does not rely on recursion so this approach supports messages with any arbitrarily large amount of nesting.

Pulling in a dependency on two different serialization libraries is not ideal, especially as this one is generally more verbose and annoying as a consequence of no recursion. We will need to discuss whether this tradeoff makes sense or whether the bug can be resolved a different way.

I confirmed that this fixes #5992. @ehuss

### CODE REVIEW

**Comment by ehuss** [comment]
Oh, this is awesome!  Sorry, I meant to respond to you.  I had played around with miniserde but I didn't get too far.  I'll take a closer look tomorrow, but it does seem to fix the issue.  I was wondering if you had an idea on how to easily make a test for it.  I just made a 150 line macro, but I imagine there should be an easier way to exhibit the issue.

**Comment by dtolnay** [comment]
I added a brief test and confirmed that it fails before this PR.

**Comment by ehuss** [comment]
Nice!  I ran it through some tests without problems.  LGTM!  If you're saying it is more verbose if there is an error, I think that should be rare, so I personally don't worry about that.

**Comment by alexcrichton** [comment]
Nice!

In terms of maintenance though I'd probably prefer to not have two json parsers if we can as well as dual implementations of serialization. The underlying issue here seems somewhat niche to me in the sense that it doesn't necessarily justify the "hammer" of a dual serde implementation.

**Comment by dtolnay** [comment]
Makes sense, I can see the downsides.

**Pull request closed without merging**
