### PR TITLE
Spot the crate typo easily

### PR DESCRIPTION
**Pull request by gilescope**
ego tweak to make it easy to spot typos:

Before:
```
error: no matching package named `sc-consensus-primitivies` found
location searched: /Users/bit/p/substrate1/client/primitives/consensus/common
perhaps you meant: sc-consensus-primitives
required by package `sc-network v0.9.0 (/Users/bit/p/substrate1/client/network)`
```
After:
```
error: no matching package named `sc-consensus-primitivies` found
perhaps you meant:                sc-consensus-primitives
location searched: /Users/bit/p/substrate1/client/primitives/consensus/common
required by package `sc-network v0.9.0 (/Users/bit/p/substrate1/client/network)`
```

### CODE REVIEW

**Comment by gilescope** [comment]
(Guessing some tests need fixing up. For some reason they were all failing on my machine so will let the CI tell me which I need to fix)

**Comment by gilescope** [comment]
Would be pretty cool if we could output the line in the Cargo.toml where the crate was referenced so you could click on the terminal output in vscode and go right there....

**Comment by Eh2406** [comment]
I Like the change.

**Comment by alexcrichton** [comment]
Looks great to me, thanks!

With CI passing I think this is good to go

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
