### PR TITLE
Fix fetching crates on old versions of libcurl.

### LINKED ISSUE #6155: "error: [48] An unknown option was passed in to libcurl" on nightly only
I'm on OS X 10.9.5 (I know) and attempting to install any package using the nightly version (cargo 1.31.0-nightly (ad6e5c003 2018-09-28)) results in:

```
$  cargo install cargo-cov
    Updating crates.io index
error: [48] An unknown option was passed in to libcurl
```

Adding `-v` doesn't reveal the source of error.
`curl crates.io` with or without https works.

Stable cargo 1.29.0 (524a578d7 2018-08-05) and cargo 1.30.0-beta (05e9b01fc 2018-09-21) work fine.

I first suspected network censorship was the reason and tried to configure a proxy in ~/.cargo/config, but that didn't have any effect.

I'm not an active rust user, so I'm not sure if/how I can troubleshoot this further without delving in too deep.

### PR DESCRIPTION
**Pull request by ehuss**
CURLOPT_PIPEWAIT was added in 7.43 but MacOS 10.9 has 7.30.

Fixes #6155

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh dear, good catch!

Currently though the performance of fetches does actually rely on PIPEWAIT because we issue all HTTP requests to libcurl simultaneously and it would otherwise flood crates.io with new TCP connections (one per crate) if PIPEWAIT weren't set.

Ideally we'd throttle sending requests to libcurl without PIPEWAIT available, but perhaps it's best to get something working before we game that out? (I think adding that will be difficult)

**Comment by ehuss** [comment]
Doesn't `set_max_host_connections` handle that?  I ran with debugging, and it only opens 2 connections.

**Comment by alexcrichton** [comment]
@bors: r+

Aha right yes of course!

**Pull request merged**
