### PR TITLE
Update libc to 0.2.144

### PR DESCRIPTION
**Pull request by heiher**
### What does this PR try to resolve?

cargo cannot build successfully on LoongArch:

```
error[E0425]: cannot find value `FICLONE` in module `c`
   --> /home/hev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.37.15/src/backend/libc/io/syscalls.rs:356:16
    |
356 |             c::FICLONE as _,
    |                ^^^^^^^ not found in `c`
```

This is caused by some constants are missing in libc and [fixed](https://github.com/rust-lang/libc/pull/3237) after `libc 0.2.143` release.

libc changelog: https://github.com/rust-lang/libc/releases/tag/0.2.143
https://github.com/rust-lang/libc/releases/tag/0.2.144

### How should we test and review this PR?

```bash
cargo build && cargo test
```

### Additional information

None

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Hello. It would be better if we could have more context of this pull request, or an well-written issue tracking something else. Otherwise it is easy to get lost in version bumps.

Some good examples:

* https://github.com/rust-lang/cargo/pull/12096
* https://github.com/rust-lang/cargo/pull/12014#issuecomment-1519111576
* https://github.com/rust-lang/cargo/pull/11307
* https://github.com/rust-lang/cargo/pull/11871

**Comment by heiher** [comment]
Thanks for your good suggestions! The descriptions has been updated, I will try to do better.

**Review by weihanglo — COMMENTED** [review]
Given Cargo doesn't directly use the code failing to compile, I would suggest bump the version over there. Perhaps `rustix` instead?

**Comment by heiher** [comment]
I thought so too. The interesting thing is rustix does not lock to `libc 0.1.142`. In other words, rustix can build successfully immediately after `libc 0.1.143` is released. I will try more about how to bump it. Thanks for your good suggestions.

**Comment by heiher** [comment]
@weihanglo Even if we update rustix (though it doesn't lock libc), eventually the cargo project's Cargo.lock needs to be updated, right? Would it be possible to do like https://github.com/rust-lang/cargo/pull/12014? Thank you.

**Review by weihanglo — COMMENTED** [review]
Just be clear. I was concerned about this thing happening again: <https://github.com/rust-lang/cargo/pull/11840#discussion_r1180164250>.

We should also bump libc in Cargo's Cargo.toml as well.

**Comment by heiher** [comment]
I apologize for my previous misunderstanding. I noticed that there was a difference in the dependency definition of libc between the `Cargo.toml` and `Cargo.lock` files, and mistakenly assumed that they shouldn't be strictly synchronized. However, I'm still unclear about the reasons. I would greatly appreciate it if you could enlighten me on this matter.

**Comment by weihanglo** [comment]
`Cargo.lock` is only considered when building the `cargo` executable. What about community cargo subcommands and plugins? I was wanting to ensure a smooth user experience throughout the whole ecosystem. Also, to prevent any accidental _downgrade_ of locked dependencies in the future.

**Comment by heiher** [comment]
Thanks for your explanation.

**Review by weihanglo — APPROVED** [review]
Thanks for the update and the patience!

**Pull request merged**
