### PR TITLE
Handle the case where the name of a library is different from the package's

### LINKED ISSUE #5568: An inconsistency in paths between target/doc/crate and `doc --open`
… which comes out when the `[package.name]` is different from the `[lib.name]` in a Cargo.toml.

Point of interest is the path that is used to open index.html:

https://github.com/rust-lang/cargo/blob/5986492773e6de61cced57f457da3700607f4a3a/src/cargo/ops/cargo_doc.rs#L71-L82

https://github.com/rust-lang/cargo/blob/5986492773e6de61cced57f457da3700607f4a3a/src/cargo/ops/cargo_doc.rs#L97-L99

It tries to open `target/doc/crate_name/index.html` while the documentation is generated in `target/doc/crate_lib_name/index.html`. That's why in such situations `cargo doc --open` does nothing (no errors, no messages, because of silent [` if `](https://github.com/rust-lang/cargo/blob/5986492773e6de61cced57f457da3700607f4a3a/src/cargo/ops/cargo_doc.rs#L99)).

### PR DESCRIPTION
**Pull request by esteve**
Resolves #5568

### CODE REVIEW

**Comment by esteve** [comment]
@matklad I've added the tests you asked me offline, thanks for your patience :-)

**Comment by matklad** [comment]
@bors r+

Thanks!

I don't know if we have `echo` on windows, let's just check!

**Comment by esteve** [comment]
I just disabled the tests on Windows and macOS because it's only on Linux where the `BROWSER` environment variable has any effect. See https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_doc.rs#L117

**Pull request merged**
