### PR TITLE
Make `-Cmetadata` consistent across platforms

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates how `-Cmetadata` is calculated for each unit to optionally exclude the `host: ...` line that rustc prints for cross-compiled builds. Previously the full `verbose_version` was hashed for stable builds and the `host` was explicitly hashed for non-stable builds. For a build using `--target`, however, that means that the `-Cmetadata` will be different when producing the same target on different hosts (e.g. producing the binary once on Linux and once on macOS).

This can hinder reproduction of a binary across different platforms even when the `--target` flag is used. For example in rust-lang/rust#117597 it was seen that a WebAssembly binary produced on different platforms was slightly different and this appears due to the differing `-Cmetadata` flags. After this commit the `-Cmetadata` flag is the same for two different platforms meaning that different platforms produce the same binary.

I've tested locally and a simple project produces a different binary before this change but produces the same binary on two platforms after this change. Unfortunately automated testing of this change will be difficult since it requires two different host compilers, though.

### CODE REVIEW

**Comment by weihanglo** [comment]
Does this fix the same issues in <https://github.com/rust-lang/cargo/issues/8140> and <https://github.com/rust-lang/cargo/issues/13922>?

**Comment by alexcrichton** [comment]
Ah good catch! I suspect this fixes #13922 but I think there's more concerns brought up in #8140 so while this may fix some of the issues there I don't think it would fix all of them

**Comment by ehuss** [comment]
Thanks! I'm not 100% certain that different host compilers will always produce the exact same output, but I imagine that should be considered a bug in rustc if it does not.

@bors r+

**Comment by BlackAsLight** [comment]
A bit off topic, but how does one know when this merge will show up in the stable or nightly release?

**Comment by bjorn3** [comment]
I believe cargo gets updated on nightly once a week or so. And from there it will ride the release train to stable, which can take anywhere from 6-12 weeks depending on where in the release cycle a change gets merged.

**Comment by alexcrichton** [comment]
> Thanks! I'm not 100% certain that different host compilers will always produce the exact same output, but I imagine that should be considered a bug in rustc if it does not.

I definitely agree yeah. Getting deterministic output across different host platforms for the same target to me is basically a big game of whack-a-mole. This PR is probably one piece of the puzzle but I also have the same hunch that there are many other pieces for completely full fidelity.

**Comment by joshtriplett** [comment]
Adding the `relnotes` label here. Sketch of release notes:

The Rust compiler now uses the same metadata for symbol ABI compatibility regardless of the host the Rust compiler was compiled for. This makes it possible for cross-compiles to the same target from different hosts to produce identical binaries. (There may still be other issues with doing so, which we hope to resolve over time.)

**Pull request merged**
