### PR TITLE
fix `cargo test` of dylib projects for end user runs too

### PR DESCRIPTION
**Pull request by mcgoo**
Fixes running `cargo test` and `cargo test --target <target>` for dylib projects.

Moves the logic just landed in https://github.com/rust-lang/cargo/pull/3996 into cargo itself, so cargo sets the dylib path for anyone running `cargo test` or `cargo run`. Current master sets the dylib path only for  `cargo test` on cargo itself.

This PR pins to rustup 1.2.0 for the purposes of testing. If https://github.com/rust-lang-nursery/rustup.rs/pull/1093 ends up working out, then this PR would only be important for non-rustup users and people doing cross testing, `cargo test --target <target>`.

Arguably https://github.com/mcgoo/cargo/blob/ed273851f8bc76f726eda4a2e2a7bb470c3718bc/src/cargo/ops/cargo_rustc/context.rs#L249-L253 should point to lib/rustlib/\<host triple\>/lib instead of sysroot/lib, because I think if the libs are different, you will never be able to compile a working plugin anyway, and for the host=target case you get the  lib/rustlib/\<host triple\>/lib anyhow. Is there ever a case where the lib/rustlib/\<host triple\>/lib and sysroot/lib versions of the libs would be expected to differ?

This is not a huge deal for me one way or the other - it doesn't impact my workflow at all. I nearly dropped it when I saw @alexcrichton had made it all work in 3996, but I think it's worth doing because it removes a surprise. It certainly would have saved me a couple of days of confusion. Either way, thanks for looking it over.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nah I think this seems reasonable to land in Cargo regardless, thanks for the PR!

My only worry here is the extra invocation of `rustc`, which can be a pretty weighty process (on the order of tens of milliseconds). Would it be possible to eschew that in favor of just one rustc invocation?

**Comment by mcgoo** [comment]
Sure. I had to fold it in with a run using --cfg because it would not work in the same run as -vV.

--print sysroot appears to predate --cfg (Dec 2014) so this should work whenever --cfg does.

**Comment by mcgoo** [comment]
ping @alexcrichton

**Comment by mcgoo** [comment]
oh, sorry - it's only the force updates that don't notify you, right?

**Pull request merged**
