### PR TITLE
feat(reslve): Respect '--ignore-rust-version'

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

This is a part of #9930.

### How should we test and review this PR?

I had considered several ways of implementing this.  I first looked at passing this into `ops::resolve*`.
.This would get a bit annoying with the function signature, so I considered moving it to a builder..
Each of the entry points is slightly different with different ownership needs, making it hard to have a common abstraction.
In doing this, I noticed we currently pass some state around to the resolver via `Workspace`, so I mirrored that.

The nice thing about this location is it provides a good place to hook in config and `package.resolve` so they affect this.

### CODE REVIEW

**Review by Muscraft — APPROVED** [review]
Thanks!

**Comment by Muscraft** [comment]
I think the failure is similar to the one I described in [#13740](https://github.com/rust-lang/cargo/pull/13740#issuecomment-2050565325)

**Review by weihanglo — APPROVED** [review]
Scott beat me by speed

**Pull request merged**
