### PR TITLE
refactor(toml): Improve consistency

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

As I was working towards #12801, these inconsistencies bothered me.  Hopefully this will also make it easier to discover special cases in the schema and deal with them properly.

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
Looks good to me. Thanks!

**Comment by Muscraft** [comment]
Ci failed due to the [Docker registry being down](https://www.dockerstatus.com). Once it is fixed, this can be retried.


Note: there is a [`t-infra` thread](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Docker.20down.2C.20CI.20borked) that mentions this is the cause of other `rust-lang` projects' CI failing.

**Pull request merged**
