### PR TITLE
pass features to doctest binary

### PR DESCRIPTION
**Pull request by apasel422**
This is a WIP for #1277. I would like to add a test for the new behavior in `tests/test_cargo_test.rs`, but I'm having a hard time getting the output to match.

Some feedback would be great to see if this is even the right approach.

### CODE REVIEW

**Comment by apasel422** [comment]
This is definitely not correct as is, because it doesn't handle default features.

**Comment by alexcrichton** [comment]
Could you add some tests for this as well? I think that this does handle default features but it would be good to have a test showing so. You may also want to store a sorted `Vec<String>` to match against the exact output.

**Comment by apasel422** [comment]
Sure. I'm just trying to figure out how to use the test stuff correctly. What I have right now is failing (see the second commit):
```sh
---- test_cargo_test::doctest_feature stdout ----
	thread 'test_cargo_test::doctest_feature' panicked at '
Expected: execs
    but: differences:
  9 - |running 1 test|
    + |running 0 tests|

 10 - |test bar_0 ... ok|
    + ||

 11 - ||
    + |test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured|

 12 - |test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured|
    + ||
```

**Comment by apasel422** [comment]
This doesn't appear to be the solution, or, at least, there is a separate bug in rustdoc:
```sh
Doc-tests foo
     Running `rustdoc --test /home/andrew/foo/src/lib.rs --crate-name foo -L /home/andrew/foo/target -L /home/andrew/foo/target/deps --cfg feature="bar" --extern foo=/home/andrew/foo/target/libfoo-7cf71ac9a7d9fc8e.rlib`

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by alexcrichton** [comment]
If this is an upstream `rustdoc` bug we may want to fix it there before adding support in Cargo first.

**Comment by apasel422** [comment]
I think I've narrowed the problem down to the way cargo is building the library and then invoking rustdoc with it, just gathering some more evidence.

**Comment by apasel422** [comment]
See rust-lang/rust#22131.

**Comment by apasel422** [comment]
I should be able to add a test for this after Cargo updates to Rust master.

**Comment by alexcrichton** [comment]
If you edit `src/rustversion.txt` to have today's date it should do the trick (update to master)

**Comment by apasel422** [comment]
Updated with a test.

**Comment by alexcrichton** [comment]
@bors: r+ b522d0f 

Thanks!

**Comment by apasel422** [comment]
Not sure what's going on with the test failure.

**Comment by alexcrichton** [comment]
I believe this is a bug in the compiler: https://github.com/rust-lang/rust/pull/22197

**Comment by apasel422** [comment]
Rebased on #1300.

**Pull request merged**
