### PR TITLE
add total work to timings

### PR DESCRIPTION
**Pull request by tschuett**
Adding the total work gives an idea of how much was actually made. I have mild interest
 in the length of critical path, but that is for another day.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh nice idea! I'm not familiar with the term "work" per se though for this measurement, historically I've seen comparisons of CPU time and Wall time (where "work" here is CPU time and what Cargo prints is "wall time" right now. Perhaps the names in the table could more align with that?

**Comment by tschuett** [comment]
> Oh nice idea! I'm not familiar with the term "work" per se though for this measurement, historically I've seen comparisons of CPU time and Wall time (where "work" here is CPU time and what Cargo prints is "wall time" right now. Perhaps the names in the table could more align with that?

See https://en.wikipedia.org/wiki/Analysis_of_parallel_algorithms.  When I built cargo the total work was 317.2s, but the total time was 90.2s. The average parallelism was 3.5.

**Comment by alexcrichton** [comment]
Right yeah this change looks good and I think it's a good statistic to add, I'm just worried about nomenclature. I've never heard of "work" as used for this measurement. The most frequent I've heard of are "wall time" (what Cargo already prints today) and "CPU time" (what you're adding here). I think that at the very least some sort of clarification should be added to the output about work/time, if like a tooltip or something.

**Comment by tschuett** [comment]
Well, it is really the *work* you did. The non-obvious part is that it also gives you an idea how long the job would run on one single core.

Please let me know, how to add  tooltip.

**Comment by alexcrichton** [comment]
Sorry, yeah, I know what the statistic that's being added here means. My point is exclusively about terminology, not whether or not we should have it or what it is. 

I unfortunately don't know how to do tooltips off  the top of my head.

**Comment by ehuss** [comment]
I'm gonna close this due to inactivity. Feel free to reopen or create a new PR when you've got time to work on this again. Thanks!

**Pull request closed without merging**
