### PR TITLE
Add -vv to the list of options printed by cargo --help.

### PR DESCRIPTION
**Pull request by ereichert**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This is the intention of the `...` after the `-v, --verbose`, but perhaps we should call it out explicitly?

**Comment by ereichert** [comment]
It should explicit. I've been working on a real tough build script for about 3 weeks and had no idea that option existed. In my case, waiting for the output file to be written cost me a lot of time. With the -vv option my compile cycle is down to nothing before I get feedback.

I only found out about -vv while researching a completely unrelated issue and, post discovery, I haven't figured out a good search term that would have helped me discover it earlier.

**Comment by alexcrichton** [comment]
I wonder if we could perhaps re-word this as:

```
      -v, --verbose ...   Use verbose output (-vv for very verbose)
```

?

**Comment by ereichert** [comment]
I had that same thought with the addition of a mention of the build script output.

`-v, --verbose ...   Use verbose output (-vv for very verbose/build.rs output)`

**Comment by alexcrichton** [comment]
Ah I'd just want to keep the help text under 80 columns, but otherwise seems fine to me. Could you also change all other help messages as well?

**Comment by ereichert** [comment]
> Could you also change all other help messages as well?

What needs to be changed on which messages?

**Comment by alexcrichton** [comment]
Oh there's just a bunch more help messages, e.g. all of `src/bin/*.rs`

**Comment by ereichert** [comment]
Given a little more guidance I can put in some time on those messages. I don't want to waste time fixing things that aren't broken.

I looked through some of the src/bin/*.rs files and the ones I looked include help messages. 

Are you saying they need to be updated? Are they missing options?

Direct me, Maestro.

**Comment by ereichert** [comment]
Updated the PR. Kept it under 80.

**Comment by alexcrichton** [comment]
Thanks` I think the `...` is still required though for docopt to parse it? Also, can you update the other help texts in `src/bin/*.rs`?

**Comment by ereichert** [comment]
@alexcrichton check out the PR now. Is that what you were looking for?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by ereichert** [comment]
@matklad You're welcome.

**Pull request merged**
