### PR TITLE
chore(ci): Automatically test new packages by using `--workspace`

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

This is a part of #11987 that was unblocked by #12321 and #11993

### How should we test and review this PR?

Relying on CI to verify this

I'd prefer to move the `cargo test --workspace` step earlier but we run out of disk space if we do (we currently only have 661 MB of headroom of windows-gnu)

See the individual commits for smaller chunks and explanations for why changes were made.

### CODE REVIEW

**Review by weihanglo — APPROVED** [review]
One drawback for testing all members in a `cargo test` invocation is that the feature resolution is unified. If we aim to make each subcrate work more independently in the future, we may not want to unify features.

That being said, I have no issue merging them at this stage.

**Comment by weihanglo** [comment]
Oh no. I didn't notice it was still a draft.

**Comment by epage** [comment]
It was just a draft until it could successfully build

**Pull request merged**
