### PR TITLE
prepare for cargo for mips and powerpc

### PR DESCRIPTION
**Pull request by japaric**
with these changes I can cross compile Cargo for these targets:

- mips-unknown-linux-gnu
- mipsel-unknown-linux-gnu
- powerpc-unknown-linux-gnu
- powerpc64-unknown-linux-gnu
- powerpc64el-unknown-linux-gnu

using these commands:

```
$ ./.travis.install.deps.sh
$ ./configure --local-rust-root=$(pwd)/rustc --enable-nightly --target=$TARGET
$ make
```

in Ubuntu 16.04 using the standard cross toolchains

r? @alexcrichton 
cross compiling Cargo for the mips targets requires rust-lang/libc#378

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ d581274c957f751876f25c790fcf881559b667e0

Oh how I wish we could just build all this on Travis...

**Comment by japaric** [comment]
> Oh how I wish we could just build all this on Travis...

We can't? Is the time limit a problem? or is the problem something else? the cross toolchain? we are using Ubuntu's cross toolchain on the buildbots as well.

**Comment by alexcrichton** [comment]
Nah unfortunately the reason is much more lame than that. We haven't figure out the best way to build binaries on Travis but still cryptographically sign them. Once we solve that problem it should be trivial to move over!

@bors: retry

**Comment by japaric** [comment]
Oh, hmm. How about [this solution](https://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci) (see step 3) of storing an encryted version of secring.gpg in this GitHub repository and then decrypting it in the travis worker? Gotta admit that handing over your secret key (even if encrypted -- it has to be decrypted at some point) to someone else sounds scary to me.

**Comment by alexcrichton** [comment]
Yeah that's what we'd likely end up doing if we were to do it. Just need to decide to do it at this point!

We'd probably have a signing subkey and such with a revocation cert and various bells and whistles. We'd also want to think through about landing code on master in terms of what implications it has as to what CI runs have the key available to look at.

**Pull request merged**
