### PR TITLE
cargo build --out-dir

### PR DESCRIPTION
**Pull request by matklad**
This is intended to fix https://github.com/rust-lang/cargo/issues/4875. Very much work in progress, just to figure out how exactly `--out-dir` should work :) 

The path of least resistance for implementing `out-dir` would be to just link everything from `target/debug` to the `out-dir`. However, the problem with this approach is that we link *too much* to the `target/debug`. For example, if you run `cargo build --bin foo`, you'll find not only the `foo` itself there, but also rlibs from the same workspace. 

I think it's rather important not to copy extra stuff to out-dir, so it is implemented as a completely new parameter, which is threaded through various config structs and applies *only* to the top-level units (i.e, to the stuff user explicitly requested to compile on the command line).

I also plan to add platform specific tests here, to check that we get .pdb on windows and .dSYM on macs for various crate-types. 

Because, in general, a single target may produce multiple files, `out-dir` has to be a directory, you can't directly specify the output *file*. 

Note that artifacts are still generated to the `target` dir as well. 

Also cc @nirbheek, I hope that this might be useful for Meson integration, because `--out-dir` should be more straightforward to use than `--message-format=json`. 

The end result, for `cargo build --bin rustraytracer --out-dir out` on windows looks like this:

image

Note how we have fewer files in the `out` :) 

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me! Technically new features start unstable but I'd be ok having this start out as a stable option

**Comment by matklad** [comment]
cc @sfackler, I think this should allow you to avoid `--message-format=json`.

**Comment by matklad** [comment]
Featuregated, cleanedup and added more tests! Should be ready for review now, although mac tests would probably fail because I don't have a mac machine nearby :-)

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

**Comment by epage** [comment]
Is this flag made available to build scripts so that we can get completions and other generated files into this directory? I'm coming at this from the packaging angle.

**Comment by epage** [comment]
Sorry, I wasn't clear. Packaging is happening outside of cargo. I was more referring to making all build artifacts intended to be packaged in an easily identifiable location.

**Comment by matklad** [comment]
So, `--output-dir` is indeed intended to make all build artifacts, produced by Cargo, available to the outside world. However, the set of artifacts, produced by Cargo, is determined by the crate type and is not extensible.

In particular, it is not possible (in theory) to make a build script, which produces some additional artifacts, like man pages and completions, and puts them somewhere in the target/output dir. In practice of course you can do *anything* in the build scripts, it just may not work in some circumstances, and might break if we change implementation details of Cargo :-) 

So, sure, `--output-dir` is intended for packaging as well, but generating completions via build.rs is probably not what you want to do, and it is orthogonal to --output-dir I would think.

**Comment by elichai** [comment]
Is there a tracking issue for the stabilization of this?

**Pull request merged**
