### PR TITLE
Update semver to 0.2.0

### PR DESCRIPTION
**Pull request by steveklabnik**
I realized that Cargo wasn't using the latest semver. This doesn't include my big nom refactoring, that will be 0.3.0.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Just to double check, but there weren't any major semantic differences between 0.1 and 0.2, just API changes?

**Comment by steveklabnik** [comment]
One sole api addition, no changes to existing code. https://github.com/steveklabnik/semver/compare/f939e91...1b6550f

**Comment by alexcrichton** [comment]
@bors: r+ 94cc5e1eabe9f24676f966eca323cdf3812b7314

Neat!

**Comment by steveklabnik** [comment]
:+1: 

I'm working on finishing off the nom-based one, I'll  be testing cargo with it before 0.3.0.

**Pull request merged**
