### PR TITLE
Remove error code check in doc test

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Needed by https://github.com/rust-lang/rust/pull/53933

cc @alexcrichton

### CODE REVIEW

**Comment by ehuss** [comment]
This isn't going to pass because the test harness asserts that cargo returns 0 by default.  There currently isn't a way to ignore the return code, though that can be easily added.

**Comment by GuillaumeGomez** [comment]
Is it a check performed in cargo or in rustc? (if in rustc, I'll send the PR there which will give a nice cascade of PRs haha).

**Comment by ehuss** [comment]
The check is in the testsuite code.  The default is set [here](https://github.com/rust-lang/cargo/blob/a5d82949485802abb45f888d5b8b7f23927f031d/tests/testsuite/support/mod.rs#L1292).  I think it would be reasonable to add another method next to [`with_status`](https://github.com/rust-lang/cargo/blob/a5d82949485802abb45f888d5b8b7f23927f031d/tests/testsuite/support/mod.rs#L564-L567) that sets `expect_exit_code` to `None`.

**Comment by GuillaumeGomez** [comment]
Agreed. Adding it to this PR as well.

**Comment by dwijnand** [comment]
Maybe we can revert the test changes in https://github.com/rust-lang/cargo/pull/5852/commits/b1d6a7e11d9cc0dc623cfc7e45f10b3d6eef0b8b then ;-)

**Comment by GuillaumeGomez** [comment]
Euh... Ok! New commit incoming!

**Pull request merged**
