### PR TITLE
Fix 404

### PR DESCRIPTION
**Pull request by lukaslueg**
Small fix for link that once was there and is now no longer there.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! These anchors though are intended for the rendered versions which I believe do end in `*.html`?

**Comment by dtolnay** [comment]
Looks like the link works at http://doc.crates.io/environment-variables.html. It may also work with .md, don't know.

**Comment by alexcrichton** [comment]
Yeah unfortunately I don't think our `*.md` links are auto-translated to `*.html`

**Comment by alexcrichton** [comment]
Closing due to https://github.com/rust-lang/cargo/pull/3683#issuecomment-279110528

**Pull request closed without merging**
