### PR TITLE
Backport #9102 to the 1.50 release branch

### PR DESCRIPTION
**Pull request by Eh2406**
As per https://github.com/rust-lang/cargo/issues/9124#issuecomment-771941676 here is a backport of #9102

### CODE REVIEW

**Comment by ehuss** [comment]
This will also need a version bump to 0.51.1.

**Comment by alexcrichton** [comment]
Oops, indeed! @Eh2406 mind following up with a version bump?

**Comment by alexcrichton** [comment]
Er scratch that, this doesn't need a bump b/c this Cargo wasn't published yet, just the stable channel needed the bump!

**Pull request merged**
