### PR TITLE
doc: improve word usage

### PR DESCRIPTION
**Pull request by shivdhar**

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
Can you please offer additional context regarding the reason for your desire to make this change?

I have no strong option about changing it or not. Just curious the reason because the PR body is empty.

Thanks!

**Comment by shivdhar** [comment]
Hey, sure. The word `fanciful` isn't used correctly; perhaps the author meant `fancier`. In any case, `complex` seems to get the message across.

"Fanciful" definition from [Merriam-Webster](https://www.merriam-webster.com/dictionary/fanciful):
```
fanciful
adjective
fan·​ci·​ful ˈfan(t)-si-fəl 
Synonyms of fanciful
1
: marked by fancy or unrestrained imagination rather than by reason and experience
a fanciful person
a fanciful tale of a monster in the woods
2
: existing in fancy (see FANCY entry 2) only
a fanciful notion
the falsehoods about some fanciful secret treaties
—F. D. Roosevelt
3
: marked by or as if by fancy or whim
gave their children fanciful names
```
Probably not the appropriate word in this context?

**Review by weihanglo — APPROVED** [review]
Fair enough. As a non-native English speaker, complex is way better to understand. Thank you.

**Comment by shivdhar** [comment]
Thank you, quite appreciate the swift workflow as well!

**Pull request merged**
