### PR TITLE
Fix some clippy warnings

### PR DESCRIPTION
**Pull request by shentok**

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks for the PR!  I'm a bit confused though, as this seems to resubmit a previous PR (#9323)?

Generally I would prefer to not make most of these changes, as they seem to be either subjective stylistic changes and things that don't really improve readability to me.

**Comment by shentok** [comment]
Thanks for your reply! My PR is independent of #9323; it extends it.

Which changes are you referring to? Clippy warnings in general or those of my PR in particular? I've chopped my changes into dedicated commits which allows for selecting those that are good to push. What do you think of my two commits involving "field_reassign_with_default"?

**Comment by shentok** [comment]
Ah, I get what you mean... Why is the commit from PR #9323 mentioned in this one? I have no idea...

**Comment by ehuss** [comment]
I'm going to close this out as we are not accepting clippy PRs at this time.  Thanks again, though.

**Pull request closed without merging**
