### PR TITLE
Fix issue 5345

### LINKED ISSUE #5345: `pretty-env-logger = 0.2` fails to `cargo doc`
This is caused by a dependency on different versions of the same crate, depending on target. See [rust issue 49002](https://github.com/rust-lang/rust/issues/49002). I made a small project to reproduce the problem [on github](https://github.com/derekdreery/rust_49002).

I need to work out 2 things
 1. How to fix it
 2. How to write a regression test

I don't know how to write a test without using crates.io, because trying to depend on 2 different versions using a local path is rejected:

```
error: failed to parse manifest at `/home/rdodd/devel/non-work/rust_49002/Cargo.toml`

Caused by:
  Dependency 'dep' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
```

Or maybe the manifest should fail to compile also for differing versions on crates.io?

### PR DESCRIPTION
**Pull request by derekdreery**
Fixes #5345.

Also adds some docs and Debug impls.

### CODE REVIEW

**Comment by derekdreery** [comment]
I know what the problem is!

`core/compiler/context/unit_dependencies.rs:L217: `filter(|d| d.name() == dep.name())`: it filters on name, so it captures both packages.
`core/compiler/context/unit_dependencies.rs:L218: `any(|dep| match dep.kind() {`: the correct package matches, and because this is `any` it matches for both packages.

**Comment by derekdreery** [comment]
Ready for review.

**Comment by matklad** [comment]
Excellent, thanks @derekdreery !

@bors r+

**Comment by derekdreery** [comment]
:smiley:

**Pull request merged**
