### PR TITLE
Simplify inferred binary names

### PR DESCRIPTION
**Pull request by matklad**
Fix for https://github.com/rust-lang/rust/issues/42365, which probably breaks other stuff :(

### CODE REVIEW

**Comment by matklad** [comment]
The particular case that can break with this PR is that `src/foo.rs` will be infered as a binary in a crate without `lib.rs` if it has `[[bin]] name=foo` in Cargo.toml. Looks like we allow for binaries to live directly inside `src` if there's no library, which seems bizarre...

**Comment by alexcrichton** [comment]
@bors: r+

Thanks! Hopefully we're just monotonically accumulating tests to prevent regressions here...

**Comment by matklad** [comment]
>Thanks! Hopefully we're just monotonically accumulating tests to prevent regressions here...

I actually wouldn't mind doing something more proactive here because some of these conventions seems strange, and they are certainly not documented. In particular, allowing `src/foo.rs` as a binary name if there's no lib, or fallback to `src/main.rs` for binary with any name seem fishy.

**Comment by alexcrichton** [comment]
Sounds good to me!

**Pull request merged**
