### PR TITLE
Add config-based path shorthands

### PR DESCRIPTION
**Pull request by jonhoo**
When doing local development, users may wish to specify many `path`
dependencies that all live in the same local directory. If that local
directory is not a short distance from the `Cargo.toml`, this can get
unwieldy.

This patch introduces the notion of path "prefixes", which are defined
in `.cargo/config.toml`:

```toml
[base]
devdir = "/home/jon/dev/rust/"
```

Which can then be used as the root for path dependencies. For example:

```toml
foo = { path = "foo", base = "devdir" }
bar = { path = "bar", base = "devdir" }
baz = { path = "ws/baz", base = "devdir" }
```

would fetch `foo` from `/home/jon/dev/rust/foo`, `bar` from
`/home/jon/dev/rust/bar`, and `baz` from `/home/jon/dev/rust/ws/baz`.

This feature also serves as a convenient way for external build systems
to mask build-dependent paths from the user. Consider a build system
that vendors first-party dependencies into

```
/home/user/workplace/feature-1/build/first-party-package/first-party-package-1.0/x86_64/dev/build/private/rust-vendored/
```

Instead of requiring users to hard-code that path, or the relative
equivalent, into their `Cargo.toml`, the build-system can instead
produce a project-local `.cargo/config.toml` that defines that path as
`base.vendored`, and the user can then use vendored dependencies using

```toml
foo = { path = "foo", base = "vendored" }
```

### CODE REVIEW

**Comment by jonhoo** [comment]
The test failure doesn't look right — the indicated test command runs just fine on my machine.

**Comment by bjorn3** [comment]
The CI failure is due to a new lint that landed on nightly very recently. https://github.com/rust-lang/cargo/pull/9118/commits/2c9b26eba778f8424e40f56d13c49f6ad4cf0ae9 (part of my pr #9118) should fix it.

**Comment by ehuss** [comment]
Thanks @bjorn3, would you mind posting that commit as a separate PR and I can merge it now?

**Comment by bjorn3** [comment]
Sure, https://github.com/rust-lang/cargo/pull/9148.

**Comment by Eh2406** [comment]
This is a very interesting approach! So far I think I like the idea. I think it will need an RFC before we can stabilize, and Team sign off before we merge.

**Comment by jonhoo** [comment]
I'd be happy to write up an RFC if there's a rough consensus from the team that an approach like this might be acceptable!

**Comment by jonhoo** [comment]
I had some time and wrote [RFC 3074](https://github.com/rust-lang/rfcs/pull/3074).

**Comment by ehuss** [comment]
Closing as there is now an open RFC for this. Feel free to reopen after that has been accepted. Thanks!

**Pull request closed without merging**
