### PR TITLE
Rename main thread from '<main>' to 'main'.

### PR DESCRIPTION
**Pull request by WiSaGaN**
This pull request resolves the test failure in rust pull request 33803
https://github.com/rust-lang/rust/pull/33803

### CODE REVIEW

**Comment by alexcrichton** [comment]
Unfortunately this won't be able to land as this doesn't work on stable rust, perhaps the assertions could be relaxed by using a `[..]` placeholder instead of matching the text exactly?

**Comment by WiSaGaN** [comment]
Right. Let me fix that first.

**Comment by WiSaGaN** [comment]
Hmm, it fails to build on Linux. Anything I can do here?

**Comment by alexcrichton** [comment]
@bors: r+

Nah it's just something I need to investigate soon, thanks!

**Pull request merged**
