### PR TITLE
Do not exit prematurely if anything failed installing.

### PR DESCRIPTION
**Pull request by horacimacias**
Fixes https://github.com/rust-lang/cargo/issues/9180

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks!  Do you think you can add a test for this?  It should probably go in [`testsuite/install.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/install.rs), and there's a bunch of examples in there. There is documentation for running and writing tests at https://doc.crates.io/contrib/tests/index.html.

**Comment by horacimacias** [comment]
I can give it a try for sure.

Thanks,

H

**Comment by horacimacias** [comment]
added test; let's see if this is of use.

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
