### PR TITLE
Move string interning to util

### PR DESCRIPTION
**Pull request by est31**
Code that handles string interning is rather an util functionality than
a core functionality.

### CODE REVIEW

**Comment by Eh2406** [comment]
I have been seeing advice lately not to name a mod "misc" because "in a year it will be completely unclear what belongs in it". Thank you @est31 for starting to talk about this long standing teck det, What belongs in "util"? The status quo is not really ok. I know Eric had opinions, so I am glad he is the reviewer.

My prior belief is that we should be reorganizing to not have a "util" but to have things is mods that describe what they do. On the other hand if this helps untangle our mods, "don't let the perfect be the enemy of the good", we can move interning if it is helpful.

**Comment by est31** [comment]
IMO interning fits to be next to mods like `canonical_url` or `queue`... basically self contained generic helper code not containing any logic that's too specific to cargo, but still too tailored to cargo's needs/too small/too undocumented to become its own indepedent crates.io crate.

Of course there's plenty of stuff in util that contains very cargo-specific stuff, like the config and toml modules. IMO those two should be put into a separate newly created module called defs which would collect most *pure* datatypes that just need serde and nothing much else. The command prelude can be put into the bin directory. And suddenly most dependencies of util on the core module are gone, and util can be put into its own crate. The defs module then can be crate-ified as well, and depend on util. The main cargo crate would depend on all of them and be a bit leaner. I need to experiment how this affects compile time. Hopefully serde-using stuff being moved out has a large effect.

**Comment by ehuss** [comment]
One thing I would eventually like to reach is to remove the cyclical dependency with `cargo-test-support`.  I sorta envisioned something like a `cargo-util` crate that would contain whatever is necessary to make that happen. This helps move towards that direction, since `InternedString` is used all over.

I'm :+1: for doing this.  @alexcrichton / @Eh2406 are you OK with this?

**Comment by Eh2406** [comment]
I am convinced by @est31's vition for how to get untangled. So I am 👍.

**Comment by alexcrichton** [comment]
I don't have too many preferences about Cargo's internal organization, we've never really put too much effort into organizing it any particular way. I don't really think it's worth it to try to micro-optimize one way or another because we don't really have an overall vision for the crate.

I'm not really against nor in favor of this, it's just moving code around which is fine by me so long as we don't have a preexisting style saying the code shouldn't be moved (and we don't have a such a preexisting style in this case)

**Comment by ehuss** [comment]
OK, I think this is fine for now. I think it may help with creating separate crates in the future.

@bors r+

**Pull request merged**
