### PR TITLE
Reordered rustc arguments.

### PR DESCRIPTION
**Pull request by ibabushkin**
This adresses #3276 .

Some tests I can't run locally might still fail, I'm fixing those.

The core change is rather trivial, simply reorder some existing code, and update tests to match the new results.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me! As soon as the tests are green I'll r+

**Comment by ibabushkin** [comment]
Some of the tests were failing because of the SSL regression, some are still underway. I'll write here when I think all the regressions introduced by my changes are fixed.

**Comment by ibabushkin** [comment]
Tests pass now, including the nightlies.

**Comment by alexcrichton** [comment]
@bors: r+ 

Thanks!

**Pull request merged**
