### PR TITLE
Allow passing a registry index url directly to `cargo install`

### LINKED ISSUE #8318: Allow passing a registry index url directly to `cargo install`
**Describe the problem you are trying to solve**
If a binary is published to an alternative registry then installing it requires first editing `.cargo/config` to add an alias for the alternative registry, then calling `cargo install foobar --registry alias` to install it.

**Describe the solution you'd like**
Be able to pass the index url directly to `cargo install`, some ideas on how to do so:

 * Add a new `--registry-index` flag that takes an index url instead of a registry alias (this matches with the undocumented(?) `dependencies.*.registry-index` config used in published crates).
 * Have a prefix like `--registry index:https://github.com/rust-lang/crates.io-index` to identify this is an index-url instead of a registry alias.
 * Autodetect that it is a url instead of an alias since aliases must be identifiers, so cannot contain `/` characters. (Though whether this is an index url or api url may be ambiguous).

The rationale for requiring global aliases was:

> A previous RFC proposed having the registry information completely defined within Cargo.toml rather than using .cargo/config. This requires repeating the same information multiple times for multiple projects, and encourages checking in credentials that might be needed to access the registries.

Neither of these apply to the `cargo install` usecase. The registry itself is already repeating the registry information multiple times in the `Cargo.toml` it stores so that the user doesn't have to, and this is a command invocation that won't be checked in anywhere. (And supporting transient calls like this does not preclude the user creating an alias for the registry if they're using it often).

### PR DESCRIPTION
**Pull request by kellda**
Fixes #8318

### CODE REVIEW

**Comment by Eh2406** [comment]
Thank you! I'm happily surprised that the diff is so small! It definitely needs a test or three, and a review from someone that knows the intricacies.

**Comment by kellda** [comment]
Could you please tell me where to add tests (integration or unit) and if possible tell me if there are similar tests for other commands that I can look at ?

**Comment by Eh2406** [comment]
Most of the install tests are in tests\testsuite\install.rs or in tests\testsuite\install_upgrade.rs

**Comment by ehuss** [comment]
Thanks!  I think instead of modifying existing tests, it would be best to add a new one.  It can probably be more or less just like `simple`, minus the uninstall step which isn't really necessary.

**Comment by kellda** [comment]
Well I tried to do something like what's done for `update` and `search`.
Currently no command have tests for `--install` on its own, so I'm not really sure what / how to test it properly.

Also I have some trouble testing locally right now, that doesn't help to write tests that passes

**Comment by ehuss** [comment]
The current errors are due to the use of `{reg}`.  It needs the `format!` macro to pass in the value, similar to [this](https://github.com/rust-lang/cargo/blob/5eb53f7d3f5ba398d273f7ce9de7bfe8027f34c8/tests/testsuite/alt_registry.rs#L31-L41).  

Otherwise, I would just copy the `install::simple` test as a new test, and add the `--index` flag.

If you're having trouble running tests, feel free to post what issues you're running into, I may be able to help.

**Comment by kellda** [comment]
> The current errors are due to the use of {reg}. It needs the format! macro to pass in the value.

Yes I figured it out but didn't fixed it yet.

> If you're having trouble running tests

Not sure you can help, here's my issues anyway:
Last things I tryed:
- ``argo build` then `cargo test --no-run` -> `error: could not compile cargo` (says `rustc` failed because `(signal: 9, SIGKILL: kill)`)
- rerun `cargo test --no-run` -> compiled fine
- `cargo test` -> most tests run fine, but testsuite fails: `(signal: 4, SIGILL: illegal instruction)`

So not really related to the test framework, I dunno if I messed up with apt-get or if it's some regression in rustc, or if something else went wrong with my linux install...

**Comment by ehuss** [comment]
Oh, that's a tough one.  I would try to get a core dump or attach a debugger for the situation that causes SIGKILL.  Which rustc are you using?  Did you install it with rustup?

SIGILL happens when there is a panic inside a panic.

**Comment by kellda** [comment]
I use rust stable 1.44.0 via rustup

**Comment by kellda** [comment]
Ok now it works, sorry for the multiples pushes and CI runs. I'll make sure I can run tests locally before my next PR

**Comment by ehuss** [comment]
Thanks!  However, as I mentioned, I think it would be ideal just to add a new test case instead of modifying the existing ones.  I think one new test, based on `simple`, should be sufficient.

**Comment by kellda** [comment]
Is it OK now ?

**Comment by ehuss** [comment]
Looks great, thanks!  I pushed a small commit to update the man page.
@bors r+

**Pull request merged**
