### PR TITLE
Pass --crate-type to rustdoc

### PR DESCRIPTION
**Pull request by Aaron1011**
This supports the [corresponding rustc PR](https://github.com/rust-lang/rust/pull/62855). To enable rustdoc to properly
document macros, we pass a new flag '--proc-macro-crate' when
documenting a proc-macro crate. This causes rustdoc to enable the
proc-macro compiler logic that runs when rustc is building a proc-macro
crate.

This flag is essentially a more restricted version of
'--crate-type=proc-macro'. I didn't think it was necessary to pass the
full '--crate-type' flag to rustdoc, when only two options would ever be
used (proc-macro vs anything else).

### CODE REVIEW

**Comment by Aaron1011** [comment]
The test failure is caused by cargo passing `--proc-macro-crate` to the current `rustdoc`, which doesn't understand it.

**Comment by alexcrichton** [comment]
Thanks for the report! For our own CI some version detection or feature detection will need to be done to get the test working on stable, but otherwise seems fine to add as soon as this is stable in rustdoc!

**Comment by Aaron1011** [comment]
As discussed on the corresponding rustc PR, we are now using the `--crate-type` flag instead of a new `proc-macro-crate` flag.

Unfortunately, this causes an enormous number of CI failures, since every test involving rustdoc will try to pass the (currently unsupported) `--crate-type` option. This will remain an issue until my rustc is merged and makes its way to stable.

@alexcrichton: What do you think is the best way of dealing with this?

**Comment by Aaron1011** [comment]
As suggested by @eddyb, I've modified this PR to only pass `--crate-type` to rustdoc if it's supported. However, I may have added the check in the wrong place - I'm not quite sure where the best place to put it is.

**Comment by Aaron1011** [comment]
This PR is no longer blocked - in fact, it is blocking the rustc PR.

**Comment by Aaron1011** [comment]
@alexcrichton: Fair enough. I've changed the rustc PR to emit a warning when `--crate-type proc-macro` isn't passed for a proc-macro crate.

**Comment by Aaron1011** [comment]
@alexchrichton With the corresponding rustc PR merged, this PR should now be ready to merge.

**Comment by Aaron1011** [comment]
The 'S-Blocked' flag can be removed

**Comment by alexcrichton** [comment]
Thanks for the update! Could this avoid using `Rc` and do `rustdoc` detection where `rustc` detection already happens? Also could a test be written for this?

**Comment by Aaron1011** [comment]
@alexcrichton: The only rustc-specific detection I could find was in [target_info.rs](https://github.com/rust-lang/cargo/blob/531c4bff7f0ecb036b60bc0d4421ff50fae148d8/src/cargo/core/compiler/build_context/target_info.rs#L105-L115), which seems like the wrong place for rustdoc logic.

**Comment by alexcrichton** [comment]
@Aaron1011 yes that's where detection currently happens, and it'd be great if rustdoc detection would also happen there. It's all cached to make subsequent runs faster as well.

**Comment by Aaron1011** [comment]
@alexcrichton: That's the approach I took in commit https://github.com/rust-lang/cargo/pull/7159/commits/1b66df9ff16cb8579e631a944713f265f8fa6417

However, @ehuss requested that I change it

**Comment by ehuss** [comment]
`TargetInfo` isn't the thing doing the caching.  It's the `Rustc` structure.  That would all need to be changed to also handle rustdoc.  I don't think it will be an easy change, and this feels like it is getting very complicated all to handle a scenario where cargo is running with an old rustdoc, which in reality doesn't happen often (Cargo's CI, cargo developers not using nightly, some rare situations like cargo-bisect-rustc).  Might there be a simpler solution?

**Comment by Aaron1011** [comment]
@ehuss: If we don't need to support a 'new cargo, old rustdoc' scenario, then we could skip doing detection entirely. The only tricky case would be CI - the current Cargo source will be tested against stable and beta, where `rustdoc --crate-type` is not available.

We could add an unstable CI-only build flag/env-var for Cargo, which completely disables passing `--crate-type` to `rustdoc`. This would also cause any rustdoc-related tests to be adjusted to not check for the `--crate-type` flag when `rustdoc` is enabled.

**Comment by alexcrichton** [comment]
The alternative would be to switch all tests that execute `rustdoc` to nightly only (we have a bunch of `is_nightly` checks already in the test suite). That way we'll run them on Cargo's CI but not on rust-lang/rust or anywhere else.

**Comment by Aaron1011** [comment]
@alexcrichton: There are around 10 tests that test for rustdoc flags. I think it would be better to allow them to continue to run and stable and beta, since they're testing things other than the `--crate-type` flag.

**Comment by alexcrichton** [comment]
I was responding to "Might there be a simpler solution?", but if you'd prefer to not implement such a solution then that's ok as well. Running tests on beta/stable won't get any more simple than what it is right now though, it's simplest to only run tests on nightly where we can pass the flag.

**Comment by ehuss** [comment]
I think for most of the tests that now fail on nightly would be fine to add `[..]` to ignore the `--crate-type` flag.  The tests don't check all flags (usually they are looking for just one or two), so I think it would be fine to ignore it.

I think it would be nice to have 1 new test that verifies the new behavior this is trying to fix that includes a check for the flag and is marked nightly only.  The nightly check can then be removed once 1.39 hits stable.

It's also not clear to me from the most recent discussion if @alexcrichton still wants the `Rc` removed or not.  I don't feel strongly one way or the other. If it is left in, we can just revert it once 1.39 hits stable.

**Comment by Aaron1011** [comment]
@ehuss @alexcrichton I've updated the PR to always pass `--crate-type` unless a CI-only env var is set. I've also updated the tests to ignore the `--crate-type` flag, and added a nightly-only test to ensure that the flag gets passed on nightly.

**Comment by alexcrichton** [comment]
Hm ok so to reiterate, I think this needs to land in one of two ways:

* First we could unconditionally pass `--crate-type`. This will require updating all tests that run `cargo doc` to become nightly-only temporarily. This isn't great because it's probably a lot of tests.

* Otherwise we can detect whether `rustdoc` supports `--crate-type`. To do this though we need to cache the output reasonably of `rustdoc` so it's not run on every invocation.

In both scenarios a test needs to be added actually exercising `--crate-type` on nightly. This part is crucial because I think this PR is actually buggy right now, it's passing `--crate-type "--crate-type lib"` as an option. (or it's passing `--crate-type ""`, which is equally invalid)

**Comment by Aaron1011** [comment]
> First we could unconditionally pass --crate-type. This will require updating all tests that run cargo doc to become nightly-only temporarily. This isn't great because it's probably a lot of tests.

That's exactly what I've done. To ensure that the tests pass on beta and stable on CI, I've added a special environment variable to disable passing `--crate-type` at build time.

> In both scenarios a test needs to be added actually exercising --crate-type on nightly.

I've already done that [here](https://github.com/rust-lang/cargo/blob/ef8b8cda32b5cc3a3d317ef4817856b4f5516fab/tests/testsuite/rustdoc.rs#L165). Cargo is correctly passing `--crate-type proc-macro`

**Comment by alexcrichton** [comment]
Ah I think I misread this (I think `rustdoc_crate_flags` is now a dead function?), but I'm wary to merge this with a magical environment variable because it breaks any developer running `cargo test` locally with stable?

**Comment by Aaron1011** [comment]
@alexcrichton: Based on @ehuss's suggestion, I thought that this would be a minor issue - it only affects using a nighty cargo with an older rust.

**Comment by alexcrichton** [comment]
For built versions of Cargo, yes, but for developers of Cargo (like me) I tend to run `cargo test` inside of the cargo source code, and that will fail unless we all export this env var now.

**Comment by alexcrichton** [comment]
Thanks! Looks good to me, but instead of an `Rc` could the flag be calculated at construction of `Compliation` instead? (that way we're just storing a `bool`, not an `Rc`

**Comment by Aaron1011** [comment]
@alexchrichton That would cause us to run `rustdoc` even when we're not running `cargo doc`

**Comment by alexcrichton** [comment]
Because it's cached I think that's fine, and this should be gracefully handling errors already if it turns out that rustdoc has issues.

**Comment by Mark-Simulacrum** [comment]
Ah, so one concern with running rustdoc where we weren't before is that e.g. in rustbuild we'll not always have a rustdoc around; to be clear that's not really a blocking concern here though since we can work around that (probably by faking --version output or so), just wanted to give a brief heads up. I think there's no platform today where we do ship a rustc and don't ship rustdoc so we should be fine in that respect.

**Pull request merged**
