### PR TITLE
fix #4746 and add test

### LINKED ISSUE #4746: `cargo package` cannot call `cargo metadata`
I hit this issue trying to [publish a crate](https://github.com/mozilla/mp4parse-rust/issues/129) from inside a workspace.

The [mp4parse](https://github.com/mozilla/mp4parse-rust/) repo has a virtual manifest referring to two subcrates, one of which depends on the other. The depending crate, `mp4parse_capi`, calls [`cbindgen`](https://github.com/eqrion/cbindgen) from a build script to generate headers. This in turn [calls](https://github.com/eqrion/cbindgen/blob/58d3178dc538af317cdfffe7de79e1420e1db293/src/bindgen/cargo/cargo_metadata.rs#L105) `cargo metadata` on the crate to obtain the dependency graph. So far so good.

But when running `cargo package` this fails, because the test build of the package invokes `cargo metadata` on the version in `target/package/` which isn't listed in the `workspace.members` key of the top-level manifest.

```
$ cd mp4parse_capi
$ cargo package
[...]
error: failed to verify package tarball

Caused by:
  failed to run custom build command for `mp4parse_capi v0.9.0 (file:///home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0)`
process didn't exit successfully: `/home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/target/debug/build/mp4parse_capi-2a4c3b58d340bafe/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/lib.rs

--- stderr
thread 'main' panicked at 'Could not generate header: "couldn\'t execute `cargo metadata` with manifest \"/home/giles/mp4parse-rust/mp4parse_capi/target/package/mp4parse_capi-0.9.0/Cargo.toml\"."', /checkout/src/libcore/result.rs:906:4
```

### PR DESCRIPTION
**Pull request by gibix**

### CODE REVIEW

**Comment by gibix** [comment]
how the paths should be formatted for windows?

**Comment by alexcrichton** [comment]
Ah in the test suite you should be able to use `[/]` as a placeholder for "insert the platform's expected identifier here"

**Comment by gibix** [comment]
thanks! fixed!

**Pull request merged**
