### PR TITLE
Support inheriting jobserver fd for external subcommands

### LINKED ISSUE #10477: Don't close jobserver fd when executing external subcommand
### Problem

I tried to use [`cargo-fuzz`](https://github.com/rust-fuzz/cargo-fuzz) from a Makefile, expecting it to use make's jobserver to limit concurency.
When running it as `cargo-fuzz`, it worked as intended, but when running it as `cargo fuzz`, it did not seem to acknowledge make job count.
I found `cargo-fuzz` environment variables contained `--jobserver-auth=3,4` as expected, but these file descriptors are closed.

### Steps

- create a script called `cargo-sleep` and put it into your $PATH
```bash
#!/bin/bash
sleep $2
```
- write a simple Makefile calling this command with jobserver passing
```Makefile
all:
        +cargo sleep 10
```
- run the makefile with jobserver
```sh
make -j2
```
- look at the environment of `sleep`. It contains `MAKEFLAGS= -j2 --jobserver-auth=3,4` (actual number may vary)
- look at open file descriptors of `sleep`, 3 and 4 (in my case) are not open.

### Possible Solution(s)

_No response_

### Notes

As stated there is a simple workaround, calling the sub-command directly instead of through cargo

### Version

```text
cargo 1.59.0 (49d8809dc 2022-02-10)
release: 1.59.0
commit-hash: 49d8809dc2d3e6e0d5ec634fcf26d8e2aab67130
commit-date: 2022-02-10
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Arch Linux [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

If cargo detects the existence of a jobserver, cargo should pass the
jobserver down to the external subcommand. Here are the reasons:

1. The existence of jobserver implies the user "expects" the amount of
   job is under control. However, before this commit, external
   subcommands cannnot benefit from the global view of the jobserver.
2. `cargo-clippy` as an external subcommand migth also love to respect
   the jobserver protocol.
3. There are several well-known external subcommands calling "cargo"
   interally (cargo-fuzz, cargo-tarpaulin, etc.)

Fixes #10477 

[zulip stream](https://zulip-archive.rust-lang.org/stream/246057-t-cargo/topic/external.20subcommand.20inherits.20jobserver.20fd.html)

### How should we test and review this PR?

A new test `jobserver::external_subcommand_inherits_jobserver` is added.

You can also execute cargo-clippy from `make -j2` to test the behaviour 
(I usually run [`procs -w rustc`] to observe the amount of rustc invocations):

```make
# Makefile
all:
	+./target/debug/cargo clippy --release
```

### Caveats

Job without special prefix `+` might still be considered as a sub-make
and would inherit the jobserver, though I don't see it as an issue.

According to GNU Make Manual ["13.1.1 POSIX Jobserver Interaction"],
if `--jobserver-auth` option is available in `MAKEFLAGS` but the file
descriptors are closed, it means that the calling `make` didn't consider
our tool awas a recursive `make` invocation. I make an assumption that
if those fds are still open, we are happy to use those jobserver tokens.

["13.1.1 POSIX Jobserver Interaction"]: https://www.gnu.org/software/make/manual/make.html#POSIX-Jobserver
[`procs -w rustc`]: https://github.com/dalance/procs

### CODE REVIEW

**Comment by weihanglo** [comment]
As a side note, I found that cargo doesn't respect `make -j1` because GNU make won't set any value in `MAKEFLAG` if job count equals 1. I cannot see any way that cargo can tell the difference between `-j1` and no `-j` specified. Actually make defaults to run jobs sequentially, which is the opposite of cargo's behaviour, so I don't think this can be fixed easily (and probably won't fix?).

**Comment by petrochenkov** [comment]
So I've encountered a very similar situation with `cargo run`.

I try to use `cargo run -p my_tool_that_uses_cbindgen_as_a_library` (and cbindgen will recursively call cargo one more time).
Such a tool also wants to inherit the jobserver.

If the descriptors are closed, they later may be reopened by something unrelated, which will ICE rustc or cargo because they will still attempt to read/write something jobserver-like from those descriptors. (That's what happen in my build environment at least.)

Maybe cargo needs some kind of explicit option to avoid closing jobserver descriptors in such cases.

**Comment by weihanglo** [comment]
@petrochenkov, thanks for sharhing the interesting case. I feel like `cargo run` should not implicitly pass jobserver down to the executable. What `cargo run` runs is not always an external subcommand. Making that assumption might be a bit overkill I guess? Anyway, if the closed descriptors do cause problems for you, could you open a new issue for that?

**Comment by ehuss** [comment]
Sorry for the long delay. I think this makes sense. There's a tiny risk that it might interfere with some existing tools or workflows, but I think on balance it is the right behavior.

@bors r+

**Pull request merged**
