### PR TITLE
Split resolver module to make it more manageable

### PR DESCRIPTION
**Pull request by djc**
The `core::resolver` module is currently the largest in Cargo, at some 2000 lines. Here's an attempt at splitting it into more reasonable parts and reordering the code in it for better comprehensibility.

Splitting is done in three major steps:

* Move the `Resolve` type and its dependencies into a separate module (~220 lines)
* Move utility data types into a separate module (~400 lines)
* Move the `Context` type and its dependencies into a separate module (~400 lines)

This halves the size of the root module, which is then reordered to make it more readable.

(This is a yak-shaving expedition of sorts, in preparation for #1286.)

### CODE REVIEW

**Comment by Eh2406** [comment]
I love the Iday! Thank you for doing this. Is there anything in particular I should look out for in reviewing?

**Comment by alexcrichton** [comment]
Ah no worries, I figured you'd like to at least look it over!

@bors: r+

Thanks @djc!

**Comment by Eh2406** [comment]
Looked it over, assuming that the `copy/paste` s did not hide changes then this looks good.
I think of `Activations` as being a detail of `Context` but that is just my opinion.
Also this needs a `cargo fmt` to pass CI.

**Comment by Eh2406** [comment]
Ya, just figured that out.
@bors: r+

**Comment by Eh2406** [comment]
Do you want to try a manual merge or a rebase?

**Comment by djc** [comment]
@Eh2406 I'm completely confused now. #5261 hasn't landed on master yet... I guess it got canceled because I removed my branch, or something? I suppose this PR will have to wait until that is landed.

**Comment by Eh2406** [comment]
opps, ya that can happen. If you dell the branch while bors is testing then you cancel the merge.

**Comment by djc** [comment]
Once #5261 is finally merged, I'll rebase this on top of master again.

**Comment by Eh2406** [comment]
One more time:
@bors r+

**Pull request merged**
