### PR TITLE
Respect Cargo.toml `[package.exclude]` even not in a git repo.

### LINKED ISSUE #9054: `cargo vendor` vs `cargo package` inconsistency
**Problem**
When using `cargo vendor`, I end up with fewer files than expected compared to if I used `cargo package` 
instead.

More specifically, I expected the `exclude` of `Cargo.toml` to be handled consistently in the `package` and `vendor` commands. For the deno project, the exclusions are listed here (note: there are inverted exclusions too. aka: `!somefile` = include somefile):

https://github.com/denoland/rusty_v8/blob/54a72d7628028063f82802f11e48c7eac89f96bf/Cargo.toml#L11-L50

I expected the vendor folder to contain a file named `.gn`, which is required for building the project.

**Steps**
```sh
$ cd path/to/denoland/deno
$ cargo vendor
$ ls  -la ./vendor/rusty_v8/

# The problem here is that we are not seeing .gn,
# and a few other files that are required for the
# deno build. This means the ./vendor cannot be used
# to build.
# 
# But if we "cargo package"
# instead that seems to work.
```

See the original report to https://github.com/denoland/rusty_v8/issues/566 for more logs and other info.

**Possible Solution(s)**
Maybe the vendoring and publishing code paths are divergent somewhere?

**Notes**

Platform info

```
❯ uname -o
❯ uname -r
❯ cargo version
❯ rustc --version
GNU/Linux
5.10.3-1-default
cargo 1.47.0 (f3c7e066a 2020-08-28)
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

### PR DESCRIPTION
**Pull request by weihanglo**
May resolves #9054 

This bug (or feature?) has been lingering for a while. #7680 fixed the `cargo package` part but `cargo vendor` is still affected by the heuristic rule of ignoring dotfiles. ~~I propose to drop the rule and include dotfiles by default even if the package is not under git-controlled~~. See below.

## Updated: Changes Summary

`cargo vendor` vendors dependencies without git-controlled but `cargo package` often runs under a VCS like git. [These lines](https://github.com/rust-lang/cargo/blob/1ca930b/src/cargo/sources/path.rs#L161-L168) are where they diverges: `fn list_files_walk_except_dot_files_and_dirs` builds [its own ignore instance], which cannot merge with other filter rules from `[package.exclude]`. This causes some patterns to not work as expected, such as re-including file after ignoring dotfiles `[.*, !negated_file]`.

To make re-include (negate) rule works, this patch adds the excluding dotfiles rule directly into the `package.exclude` ignore instance if **_no include option nor git repo exists_**. Other old behaviors should not change in this patch.

[its own ignore instance]: https://github.com/rust-lang/cargo/blob/1ca930b6/src/cargo/sources/path.rs#L364-L366

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Unfortunately it's been basically forever since I last looked at any of this and at this point I don't really remember much about what's going on here. I tried to read this for awhile and piece together what's going on, but I wasn't really able to get very far unfortunately.

You say that this may solve #9054, but does it?

The body of this looks like it's basically just reverting #7680, which I'm not sure why that works or the interactions it has with other parts of the systems. I'm surprised that at a high-level vendor/package are different since in theory they should both be using the same code paths now that they're both bundled in Cargo.

**Comment by weihanglo** [comment]
If I got it correctly, [`cargo::sources::path::list_files`](https://github.com/rust-lang/cargo/blob/2cc13b30c3583529e2f76a5c57658f80a83e6920/src/cargo/sources/path.rs#L98) has these scenarios (similar to https://github.com/rust-lang/cargo/pull/7680#issuecomment-562950814):

- **In a git repo + without `[package.include]` field:** respecting git status, .gitignore and `exclude` field from manifest.
- **Not in a git repo + without `[package.include]` field:** respecting .gitignore, but skipping dotfiles, which [builds its own gitignorer](https://github.com/rust-lang/cargo/blob/37055199b2290b5d1831ce7604efc939ab4ed79d/src/cargo/sources/path.rs#L364-L366) and may accidentally overrides `exclude` field from manifest.
- **With `[package.include]` field:** respecting .gitignore and `exclude` field from manifest.

We can see that #9054 is under the second scenario (unpacked sources in `registry/src` without git controlled). Since an unpacked source is downloaded from a registry, and that means files in the source are all necessary for building the crate (author must exclude unnecessary files explicitly while uploading it to a registry). So, in my opinion all files in an unpacked source are safe to be vendored.


As far as I can think of, the only exception that would be affected by this change is a cargo project using version control tools other than git. Considering this is somewhat a breaking change, maybe we can disable skipping dotfiles functionality for `cargo vendor` instead. Though personally I prefer to remove the strong rule of skipping all dotfiles.

**Comment by alexcrichton** [comment]
I wonder if this could apply a similar change but basically try to fix just the use case mentioned? For example the default "exclude" builder could, even if not mentioned in the manifest, have a rule that says `.*` and then that can be overridden by subsequent rules?

**Comment by weihanglo** [comment]
Updated. Add `.*` in advance when no `include` nor git repo exist. 

Note that it is still impossible if someone want to negate (include) a file inside a dot directory. This is the limitation of [gitignore rule](https://git-scm.com/docs/gitignore#_pattern_format).

> It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

**Comment by weihanglo** [comment]
@alexcrichton Updated. Please help review at your pace 😁

Note that it is still impossible to negate (include) a file inside a dot directory. This is the limitation of [gitignore rule](https://git-scm.com/docs/gitignore#_pattern_format).

> It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

**Comment by weihanglo** [comment]
Hi @alexcrichton! Sorry for pinging you. Just let you know this PR is ready to review. 😀
Is there anything need to revise please tell me! Thanks.

**Comment by alexcrichton** [comment]
Ok sorry for the delay in getting to this, but I'm looking at this again. Would you be up for writing a summary of the change that this is now updated to doing? I think I have it in my head but I want to make sure I'm right. After that I'll get a sign-off from the rest of the team that this behavior is ok to change.

**Comment by weihanglo** [comment]
@alexcrichton Thank for you review!
A changes summary is added to PR description. 😄

**Comment by alexcrichton** [comment]
Ok thanks!

@rfcbot fcp merge

**Comment by ehuss** [comment]
Thanks!

@bors r=alexcrichton

**Pull request merged**
