### PR TITLE
Add more options for cargo test zsh completion

### PR DESCRIPTION
**Pull request by tmccombs**

### CODE REVIEW

**Comment by matklad** [comment]
r? @alexcrichton 

I don't really know how zsh completion works :( 

By the way, @tmccombs how do I actually enable these completion? I do use `zsh`, but I don't have any special completions for Cargo. Is there any docs for this?

**Comment by alexcrichton** [comment]
@bors: r+

@matklad oh I'm not sure myself how they work, I just r+ things that don't look blatantly unreasonable :)

**Comment by tmccombs** [comment]
@matklad with rustup I add "~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/zsh/site-functions" to my fpath variable in .zshenv. I don't know of any documentation about it. I'd be willing to write something up though. Where would the best place be to put it?

**Comment by matklad** [comment]
@tmccombs looks like this is documented in the `rustup` readme: https://github.com/rust-lang-nursery/rustup.rs#enable-tab-completion-for-bash-fish-or-zsh. However it seems to work only with completion for `rustup` itself, and not for Cargo.

**Pull request merged**
