### PR TITLE
Resolve some Clippy warnings

### PR DESCRIPTION
**Pull request by dwijnand**
I'm not sure how these popped up since my PR 8 days ago.

My current hypotheses:
* changes in latest nightly rust/clippy
* new or changed cargo code
* I missed these as I was only touching `src/bin/cargo/main.rs`

For future reference I now iterate with:

    touch src/bin/cargo/main.rs src/cargo/lib.rs && cargo +nightly clippy

### CODE REVIEW

**Comment by dwijnand** [comment]
Feedback welcome 🙂

**Comment by alexcrichton** [comment]
FWIW I'm personally not a huge fan of `#[cfg]` annotations all through for various clippy lints, it's sort of the exact reason why I'm not a fan of clippy in general (it's too overzealous in linting). This certainly isn't specific to this PR though! In general I'm not a huge fan of clippy, so nothing against this PR itself :)

Is there perhaps a different location (not in the source code) that lints could be turned off?

**Comment by dwijnand** [comment]
Maybe after https://github.com/rust-lang/cargo/pull/5728 is merged and we're dogfooding that? Though that would only work for the ones we're happy to toggle "globally".

**Comment by dwijnand** [comment]
Fixed up a commit where I'd forgotten to adapt the test sources too.

**Comment by dwijnand** [comment]
Now that I think of it, @alexcrichton, clippy configuration is also being discussed in the Clippy 1.0 RFC (https://github.com/rust-lang/rfcs/pull/2476), if you want to get stuck in. 😄

**Comment by alexcrichton** [comment]
Perhaps for now the lints could all be applied globally in `src/cargo/lib.rs` and grouped there? It will turn off unnecessarily in some circumstances but I think that's fine.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
