### PR TITLE
Suggest the best matching target for cargo run

### LINKED ISSUE #2266: cargo run  --example checking
User mistypes, leaves the computer, comes back to nothing. `Cargo` should do the check at the start.

````
$  cargo run --example helloworld.rs 
    Updating git repository `https://github.com/arthurprs/nix-rust.git`
    Updating git repository `https://github.com/arthurprs/tendril.git`
 Downloading encoding-index-japanese v1.20141219.5
 Downloading encoding-index-korean v1.20141219.5
 Downloading encoding-index-tradchinese v1.20141219.5
 Downloading promising-future v0.1.6
 Downloading twox-hash v0.1.1
 Downloading spin v0.3.4
 Downloading threadpool v0.1.4
 Downloading futf v0.1.1
 Downloading encoding-index-singlebyte v1.20141219.5
 Downloading redis v0.5.2
 Downloading url v0.5.2
 Downloading fnv v1.0.0
 Downloading miow v0.1.1
 Downloading linked-hash-map v0.0.7
 Downloading cfg-if v0.1.0
 Downloading debug_unreachable v0.0.6
 Downloading slab v0.1.3
 Downloading net2 v0.2.20
 Downloading encoding_index_tests v0.1.4
 Downloading void v0.0.5
 Downloading encoding v0.2.32
 Downloading fs2 v0.2.2
 Downloading mio v0.5.0
 Downloading encoding-index-simpchinese v1.20141219.5
 Downloading nix v0.4.2
 Downloading mac v0.0.2
 Downloading unreachable v0.0.2
 Downloading bytes v0.3.0
 Downloading sha1 v0.1.1

no example target named `helloworld.rs`
````

Has to be restarted with:
`$  cargo run --example helloworld`

 Maybe `cargo` could strip the trailing `.rs` automatically?

### PR DESCRIPTION
**Pull request by ryanq**
Targets passed to cargo compile are validated against the package. If
the target exists, it is compiled. If not, cargo will bail and offer a
suggested target name if there is a close match.

The tests create and build/run binaries and examples using filenames
that are close (or not so close) to the target names to verify that
close matching names are suggested to the user.

Sample output attached.
screen shot 2016-03-14 at 12 32 59 pm

Closes #2266

### CODE REVIEW

**Comment by ryanq** [comment]
r? alexcrichton

**Comment by ryanq** [comment]
Build failure is due to an erroneous `pub use` in libgit2-sys. It's been fixed in the latest version of the library, should I update the version number in Cargo.toml as part of my PR?

**Comment by alexcrichton** [comment]
Sure! If you want to just do `cargo update -p libgit2-sys` that should do the trick.

**Comment by alexcrichton** [comment]
Looking better! It'd be good to continue to centralize where this happens, however. For example this would perhaps be a good candidate to replace [this logic](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_compile.rs#L361-L367)?

**Comment by petevine** [comment]
The second diagnostic in the screenshot is misleading. Provided the example named `cargo` exists (file named cargo.rs) it should either say `cargo.rs.rs` is missing or suggest stripping the last `.rs`

**Comment by ryanq** [comment]
In this case, though, there is no example file cargo.rs.

**Comment by petevine** [comment]
If it existed we'd get the same error, right? To get the source file `cargo.rs` to compile and run as an example, you had to invoke `cargo run --example cargo` - is it any different now?

**Comment by ryanq** [comment]
@petevine The gist of the change is that when the name supplied for the `--bin` or `--example` option doesn't match one of the target names, it will suggest the closest target name. In the test cases I added, when `foo.rs` (the filename of an existing example source file) is given as the argument for `--example`, cargo would suggest `foo` as the name. If `foo.rs.rs` existed, there would be no warning.

**Comment by alexcrichton** [comment]
@bors: r+ 68f993a74a3ba55c07389be5122f53b43ab4b33a

Awesome, thanks @ryanq!

**Pull request merged**
