### PR TITLE
Differentiate the warning when an alias (built-in or user-defined) shadows an external subcommand

### LINKED ISSUE #11149: built-in alias is shadowing external subcommand but Cargo warns "user-defined alias is shadowing"
### Problem

During the integration of `cargo-rm`, [we found that](https://github.com/rust-lang/cargo/pull/11099#issuecomment-1257098520) if a user already got `cargo-edit` installed, they will get an error

```
warning: user-defined alias `rm` is shadowing an external subcommand found at: `/home/user/.cargo/bin/cargo-rm`
This was previously accepted but is being phased out; it will become a hard error in a future release.
For more information, see issue #10049 <https://github.com/rust-lang/cargo/issues/10049>.
```

which is confusing since `rm` is actually not a user-defined alias but a built-in one.

### Steps

Create an external subcommand conflicting with the name of a built-in alias

1. `touch $HOME/.cargo/bin/cargo-t`
2. `chmod +x $HOME/.cargo/bin/cargo-t`
3. `cargo t` and you will see the warning.

### Possible Solution(s)

A simple fix I can see is [differentiating the warning](https://github.com/rust-lang/cargo/blob/abf6b4e4474658fb4c90978a15c38e8e27f37b1e/src/bin/cargo/cli.rs#L270-L277) based on where the alias comes.

### Notes

Not directly related but we will in peril when the warning becomes a hard error. The built-in alias such as `cargo rm` won't work anymore if user got `cargo-edit` installed. This is really a thorny problem because Cargo favors user-defined aliases over built-in (see [here](https://github.com/rust-lang/cargo/blob/abf6b4e4474658fb4c90978a15c38e8e27f37b1e/src/bin/cargo/main.rs#L56-L82)). Giving built-in aliases higher priority might fix the issue, though it might break others aliases as well. 

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by basile-henry**
Fixes #11149

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Looks great!

Could you add a test case under `tests/testsuite/cargo_alias_config.rs` to exercise this behaviour? Thank you!

**Comment by ehuss** [comment]
My intent with the concern at https://github.com/rust-lang/cargo/pull/11099#issuecomment-1257098520 is to just not warn at all for a built-in alias. Cargo doesn't warn about built-in commands shadowing a user-installed command. Why would a built-in alias be different? There isn't much the user can do to squelch the warning other than uninstall the command, which would prevent usage in older toolchains.

**Comment by weihanglo** [comment]
Oops. That's my fault. I understood it wrong. I agree with ehuss, and we might follow what ehuss suggests.

**Comment by epage** [comment]
> My intent with the concern at [#11099 (comment)](https://github.com/rust-lang/cargo/pull/11099#issuecomment-1257098520) is to just not warn at all for a built-in alias. Cargo doesn't warn about built-in commands shadowing a user-installed command. Why would a built-in alias be different? There isn't much the user can do to squelch the warning other than uninstall the command, which would prevent usage in older toolchains.

I thought we do warn when shadowing aliases
```rust
            (Some(_), Ok(Some(_))) => {
                // User alias conflicts with a built-in subcommand
                config.shell().warn(format!(
                    "user-defined alias `{}` is ignored, because it is shadowed by a built-in command",
                    cmd,
                ))?;
            }
````

**Comment by ehuss** [comment]
The situation that doesn't warn today is when an installed third-party subcommand is being shadowed by a built-in command. The expected scenario where this happens is when cargo subsumes an existing command, and is more of a transition (like cargo-tree moving from external to internal).

That's a warning for a user alias (something configured in `config.toml`) being shadowed by a built-in command. The expected scenario there is that the user is trying to change the default behavior of an existing command, something we generally don't want them to do.

The scenario for this PR is a third-party subcommand being shadowed by a built-in alias. That's more like the former scenario, where cargo is internalizing that third-party command. There is nothing the user can do to remove that built-in alias, and from their perspective there isn't much difference from a "built-in command" and a "built-in alias" as they are mostly indistinguishable.

**Comment by epage** [comment]
@basile-henry do you expect to have time to apply @ehuss feedback soon or would you be ok with someone else taking over?  #11149 was deferred out of #11099 and I think we'd like to get all changes for #11099 committed before the beta branch that happens in November.

**Comment by basile-henry** [comment]
Sorry @epage, I had forgotten about this PR. I have pushed a commit following @ehuss' suggestion.

> There is nothing the user can do to remove that built-in alias

I think if you're the author of that third-party command that is being shadowed by a built-in alias, you might consider naming your third-party command something else. But I see your point, they would likely notice the issue fairly quickly anyway. :+1:

**Comment by basile-henry** [comment]
Should I squash/rebase the commits? What's the usual cargo policy?

**Comment by epage** [comment]
@basile-henry I don't think we are too strict on commits, otherwise we'd have bors squash or we'd have a tool to help enforce commits were somewhat in shape.

For me personally, I clean up my commits so that they are atomic and clearly communicate the intended change.  Let us know if you'd like to do that and I'll hold off on merging

**Comment by basile-henry** [comment]
I'm not sure how to fix the failing tests. The two tests that are failing have nothing to do with this PR. It looks like the difference is around which type of quotes are emitted in an error message. And these tests pass on my machine :sweat_smile:

**Comment by epage** [comment]
https://github.com/rust-lang/cargo/pull/11235 fixed the failing test.  A new release of clap came out and we have tests that are sensitive to text output but don't have a lock file to hold us to a specific version, so the tests failed.

**Comment by basile-henry** [comment]
I can rebase and remove my workaround once #11235 goes in :+1:

**Comment by epage** [comment]
Its merged

**Pull request merged**
