### PR TITLE
Warn/error when cargo installing the cwd in 2015/2018

### LINKED ISSUE #5327: In 2018 edition, warn about `cargo install`ing the current crate
Running `cargo install` installs the binaries for the project in current working directory. This might be a surprising behavior for people coming from other ecosystems, especially the node one. The confusion here is that, in Cargo, you don't need to "install" a library to actually use it. At the same time, installing local crates seems like a niche use-case, one typically installs crates from crates.io. 

So let's fix confusion by printing a warning, in the next edition, when a user invokes `cargo install`.  The warning should say:

* If you care coming from other ecosystems, you probably have meant `cargo build`
* If you really want to install current package, run `cargo install --path .`

The code for install command is here:

https://github.com/rust-lang/cargo/blob/d8b20310217e5e2bc515c13111ab9a7789709e42/src/bin/commands/install.rs#L81

To check the current edition, one can use this method:

https://github.com/rust-lang/cargo/blob/d8b20310217e5e2bc515c13111ab9a7789709e42/src/cargo/core/manifest.rs#L409

The tests for install are here:

https://github.com/rust-lang/cargo/blob/d8b20310217e5e2bc515c13111ab9a7789709e42/tests/testsuite/install.rs

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #5327

submitted for early review. feedback very welcome, I'm happy to iterate (and learn).

### CODE REVIEW

**Comment by dwijnand** [comment]
my test is failing (on AppVeyor) on nightly. I thought something was wrong with my local setup. is nightly Rust meant to be edition 2018?

**Comment by ehuss** [comment]
> is nightly Rust meant to be edition 2018?

No, you have to opt-in to an edition, even on nightly.  See [unstable docs](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/unstable.md#edition), `Cargo.toml` needs a `rust` key and `cargo-features` since editions are unstable.

**Comment by dwijnand** [comment]
I see! thanks @ehuss

that seems to have fixed the test for me locally.

**Comment by dwijnand** [comment]
I had tried another encoding to preserve the knowledge that the package source was from the cwd, so I'd be interested to know if there's a better approach that what I went with.

**Comment by matklad** [comment]
Oh no, I was sure that one can just handle this at the argument parsing level, but of course one needs to load a manifest to figure out which edition we are in....

I think a slightly better approach to thread the cwd information, instead of adding a specialized field to the SourceId, which is a core data-structure and is used everywhere, is to add an argument to the `install` and `install_one` functions.

**Comment by dwijnand** [comment]
of course! I like it.

**Comment by matklad** [comment]
LGTM!

Anyone, and @rust-lang/cargo specifically, if you have any objections, please speak up! We've discussed this change at yesterday's meeting, but not everyone was present, and this change could potentially upset *some* people, so I'd rather double-check with you all :) 

The TL;DR here is that we deprecate `cargo install` in favor of `cargo install --path .`, because the first form might be wrongly used instead of `cargo build`, especially if you come from Ruby or JS ecosystems, where `bundler install` and `npm install` do completely different things. At the same time, installing the local crate seems to be an extremely niche use-case. So it's better to require slightly more verbose syntax for niche use-case, to be able to provide a targeted warning for common miss use.

@bors r+

**Comment by dwijnand** [comment]
> So it's better to require slightly more verbose syntax for niche use-case, to be able to provide a targeted warning for common miss use.

:+1: the https://en.wikipedia.org/wiki/Pareto_principle (iiuc)

**Comment by withoutboats** [comment]
I'm a bit confused by this. A warning isn't a breaking change, why is this gated on 2018?

I would expect this to warn in 2015 and stop working in 2018 if we were doing anything connected to the edition change.

**Comment by matklad** [comment]
It could work either way, we can start warning in this edition, and remove in 2018, or we can start warning in 2018, and remove in the next edition. 

If we start to warn today, that risks causing a few warnings, if someone uses `cargo install` in some scripts. If we start to warn in 2018, than those warnings will appear only opt-in into the new edition. 

The letter seems slightly less invasive, but now that I think of it, I slightly prefer just to warn regardless of the edition: the implementation would be simpler, and presumably only few scripts are doing `cargo install`?

**Comment by dwijnand** [comment]
> and presumably only few scripts are doing `cargo install`?

indeed. how many scripts are there that call `cargo install` (n.b _not_ `cargo install <some crates.io package>`) and would be negatively affected by a new warning message?

**Comment by alexcrichton** [comment]
I agree that if we warn only in 2018 then we can't actually remove it until the next edition, and I'd personally be ok starting to warn in the 2015 edition and we can evaluate whether it's reasonable to remove from the 2018 edition

**Comment by dwijnand** [comment]
> we can evaluate whether it's reasonable to remove from the 2018 edition

pushed a commit to aid evaluation 😄

**Comment by dwijnand** [comment]
(btw happy to cleanup the git history if you'd like)

**Comment by dwijnand** [comment]
note I had to adapt 3 tests, which I think is fine seeing as it's fair to assume that cargo's test suite is bound to be more likely to be sensitive to the sudden appearance of new warnings.

**Comment by matklad** [comment]
@bors r+

Thanks @dwijnand !

**Pull request merged**
