### PR TITLE
Pass RUSTDOCFLAGS to rustdoc spawned through cargo test (fixes #4738)

### LINKED ISSUE #4738: rustdoc invoked by cargo test isn't passed RUSTDOCFLAGS
As you can see, there is no `--cfg terminated_unstable` passed to `rustdoc`:

```
± RUSTDOCFLAGS="--cfg terminated_unstable" RUSTFLAGS="--cfg terminated_unstable" cargo test -vv --features terminated_macros --doc
       Fresh unicode-xid v0.0.4
       Fresh synom v0.11.3
       Fresh syn v0.11.11
   Compiling terminated_macros v0.1.0 (file:///Users/nox/src/terminated/macros)
     Running `rustc --crate-name terminated_macros macros/src/lib.rs --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 --cfg 'feature="enable"' --cfg 'feature="syn"' -C metadata=4bf8ef1fdd669eae -C extra-filename=-4bf8ef1fdd669eae --out-dir /Users/nox/src/terminated/target/debug/deps -L dependency=/Users/nox/src/terminated/target/debug/deps --extern syn=/Users/nox/src/terminated/target/debug/deps/libsyn-ff78f13b598cbdb7.rlib --cfg terminated_unstable`
   Compiling terminated v1.0.0 (file:///Users/nox/src/terminated)
     Running `rustc --crate-name terminated src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="terminated_macros"' -C metadata=3b6cd4efb0424983 -C extra-filename=-3b6cd4efb0424983 --out-dir /Users/nox/src/terminated/target/debug/deps -L dependency=/Users/nox/src/terminated/target/debug/deps --extern terminated_macros=/Users/nox/src/terminated/target/debug/deps/libterminated_macros-4bf8ef1fdd669eae.dylib --cfg terminated_unstable`
    Finished dev [unoptimized + debuginfo] target(s) in 0.86 secs
   Doc-tests terminated
     Running `rustdoc --test /Users/nox/src/terminated/src/lib.rs --crate-name terminated -L dependency=/Users/nox/src/terminated/target/debug/deps -L dependency=/Users/nox/src/terminated/target/debug/deps --cfg 'feature="terminated_macros"' --extern terminated=/Users/nox/src/terminated/target/debug/deps/libterminated-3b6cd4efb0424983.rlib --extern terminated_macros=/Users/nox/src/terminated/target/debug/deps/libterminated_macros-4bf8ef1fdd669eae.dylib`
```

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is currently duplication the logic (buggily) of the normal compliation process and doesn't currently include any tests, could both of those be fixed before merging?

**Comment by nox** [comment]
If you explain which duplication you mean, and in which way it is buggily done, yes.

**Comment by alexcrichton** [comment]
Out of curiosity did you attempt to understand how `RUSTDOCFLAGS` works today? Or `RUSTFLAGS`? I would have thought that even a cursorty investigation would have pointed you at [the definition](https://github.com/rust-lang/cargo/blob/6a1aee06680d8f074a25431c938c42d7e8d0ab4e/src/cargo/ops/cargo_rustc/context.rs#L1125-L1230) which has all manner of features such as loading directly from `Config` as well.

**Comment by nox** [comment]
Yep I looked at it, but I couldn't really make heads of how that ends up get called, compared to the codepath for cargo invoking rustdoc, so I just took the bits specific to `RUSTFLAGS`. Is there an easy way to just reuse `build_env` from that code?

**Comment by alexcrichton** [comment]
In the code you are modifying the rustdoc invocation is configured in large part from the `compilation` local variable, such as when `--cfg` [flags are passed](https://github.com/nox/cargo/blob/de088f026366744d681b1b27715fea0e81e02fdc/src/cargo/ops/cargo_test.rs#L175-L179). The [`Compilation`](https://github.com/nox/cargo/blob/de088f026366744d681b1b27715fea0e81e02fdc/src/cargo/ops/cargo_rustc/compilation.rs) type, tracing backwards, is mostly filled in [after the compilation finishes](https://github.com/nox/cargo/blob/de088f026366744d681b1b27715fea0e81e02fdc/src/cargo/ops/cargo_rustc/mod.rs#L181-L250), such as [filling all the cfgs](https://github.com/nox/cargo/blob/de088f026366744d681b1b27715fea0e81e02fdc/src/cargo/ops/cargo_rustc/mod.rs#L237-L239).

What you'll probably want to do is add another field to the `Compilation` which represents custom flags, in this case rustdocflags. You'll then be able to call one of the functions that calls `env_args`, [`rustdocflags_args`](https://github.com/nox/cargo/blob/de088f026366744d681b1b27715fea0e81e02fdc/src/cargo/ops/cargo_rustc/context.rs#L1109-L1111) to fill in the `Compilation`.

Does that help?

**Comment by nox** [comment]
Yes! Thank you, I'll try to fix the patch with these new details.

**Comment by nox** [comment]
I'm still confused by something: the current call to `Context::rustdocflags_args` in `cargo_rustc::rustdoc` is passed the unit for which we are building the documentation, right? If I fill a new `Compilation::rustdocflags` field in `cargo_rustc::compile_targets`, how do I know which unit I should use?

**Comment by nox** [comment]
I just realised I am supposed to store a map from packages to rustdoc-specific flags. All that remains is a test, I guess.

**Comment by nox** [comment]
I added a test.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
