### PR TITLE
Add 'fmt' and 'clippy' to 'cargo' output to aid discoverability

### PR DESCRIPTION
**Pull request by elo-siema**
Hopefully solves https://github.com/rust-lang/cargo/issues/8680
Would also be nice to add description to `fmt` and `clippy` in `cargo --list`, but I'm not sure how to achieve that (first contribution to Cargo).

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! I'm not sure how this interacts with non-rustup ways to install Cargo, however. I don't think they're all guaranteed to have cargo-clippy or cargo-fmt in PATH? This may need to do some system detection to see if these commands should be included.

**Comment by elo-siema** [comment]
Makes sense, didn't think about that case. 
I looked a bit into the ways to check if they're available when showing the message in `.template(...)`. I think we have to call `cli::list_commands(&config)` to get that information, and I see 2 options for doing that:

1. Call `cli::list_commands(&config)` in every call to `cli(&config)` (we would need to pass &config to `cli()`), but that would be wasteful for 99% of Cargo calls except for `--help` or no args

2. Try to evaluate that lazily. I noticed that clap's `.template(...)` accepts an `Into<&str>` and hoped that it might be the case, but it's not - I ran an experiment by creating a struct and implementing `From<[that struct]> for &str` and it looks like `thing.into()` is called right when '.template(thing)' is called. Something like:

```rust
struct CliTemplate<'a> {
    template_generator: Box<dyn FnOnce() -> &'a str>,
}

impl<'a> CliTemplate<'a>{
    fn new(template_generator: Box<dyn FnOnce() -> &'a str>) -> CliTemplate<'a> {
        CliTemplate{ template_generator: template_generator }
    }
}

impl<'a> From<CliTemplate<'a>> for &'a str {
    fn from(item: CliTemplate<'a>) -> Self {
        (item.template_generator)()
    }
}
````

and

```rust
App::new("cargo")/*...*/.template(CliTemplate::new(Box::new(|| {"test"})
```

I'm out of ideas that would not result in significant changes to the codebase for now :/

**Comment by elo-siema** [comment]
> ```rust
> App::new("cargo")/*...*/.template(CliTemplate::new(Box::new(|| {"test"})
> ```

... and even if that worked, `config` would need to be accessed inside the closure, and thus outlive the `cli::cli()` function, which opens another can of worms.

**Comment by alexcrichton** [comment]
Sorry for the late response, but unfortunately I don't know a ton about clap, so I'm not sure of how much help I'll be there. I mostly just wanted to point out the possibility of this and how we may not be able to unconditionally include them always.

**Comment by jyn514** [comment]
@elo-siema is there a reason you need to return a borrowed string? I think either a `&'static str` or `String` would fix the lifetime issue; the copy shouldn't be a big deal since it's only once in an error path.

**Comment by ehuss** [comment]
Closing due to inactivity.  I suspect this may not be easy or feasible to due with clap in a dynamic fashion.

**Pull request closed without merging**
