### PR TITLE
Test for issue #2064

### PR DESCRIPTION
**Pull request by pornel**
I've tried to reproduce the problem from #2064, but to my surprise the test passes reliably :)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Yeah in this specific case the largest version of `util` satisfies all dependencies and Cargo will always choose the largest first. I think that #2064 shows up more so when there are multiple solutions that span major versions, so Cargo doesn't always select the right major version to go with a particular crate (e.g. it doesn't minimize major versions).

I'm ok adding this as a test case though if you'd like!

**Comment by pornel** [comment]
I see. I've recreated structure of packages that caused me headaches, but I didn't realize my versions were `0.x`, which are "major".

Yes, please merge it.

**Comment by alexcrichton** [comment]
@bors: r+

Ok, sounds good to me.

**Pull request merged**
