### PR TITLE
Remove Compilation.libraries

### PR DESCRIPTION
**Pull request by dwijnand**
Actioning https://github.com/rust-lang/cargo/pull/5651#issuecomment-402825950

### CODE REVIEW

**Comment by ehuss** [comment]
For context, I left that in when I removed its use in #5651 because it was used by [cargo-bloat](https://github.com/RazrFalcon/cargo-bloat) and [semverver](https://github.com/rust-lang-nursery/rust-semverver).  It looks like cargo-bloat has since been rewritten to no longer use cargo.

**Comment by dwijnand** [comment]
The failure looks spurious btw.

**Comment by ehuss** [comment]
> So what should rust-semverver use now to find the path of rlibs from a `PackageId` now that `libraries` has been removed ?

The issue is that there is not a simple, correct mapping anymore.  There might be multiple lib targets with different settings.

I took a look at the semverver code for a bit.  I'm wondering if it really needs to use cargo as a library.  Would it be possible to just call the cargo cli, and get the rlib path from the JSON output?

**Comment by gnzlbg** [comment]
>  I'm wondering if it really needs to use cargo as a library. Would it be possible to just call the cargo cli, and get the rlib path from the JSON output?

`rust-semverver` compiles the current crate as an rlib, as well as the previous version of it from crates.io (which has often to be downloaded, and then also compiled), and then compares both rlibs. The compilation is done by calling `cargo::ops::compile`. 

I've opened an issue about this on `cargo_metadata`: https://github.com/oli-obk/cargo_metadata/issues/60 , there is some discussion there about how to tackle some of these issues.

**Pull request merged**
