### PR TITLE
Only load `~/.cargo/config` for `cargo install`

### LINKED ISSUE #6025: `cargo install` should read `$HOME/.cargo/config` only
The `cargo install` command should read configuration from `$HOME/.cargo/config` but not from other configuration files.

Normally cargo looks for configuration in `$PWD/.cargo/config`, `$PWD/../.cargo/config`, etc., and in `$HOME/.cargo/config`.  For `cargo install`, however, the tree walking behavior is surprising.  `cargo install foo` should work the same regardless of the directory from which we run it.

This surprising behavior resulted in #5850 and PR #5874.  That PR causes `cargo install` to ignore any configured `build.target` value from a configuration file.

However, that change does both too little and too much.  It does too much because we don't want to ignore configured values in `$HOME/.cargo/config`.  Values set there make sense for `cargo install`.  E.g., we might use that to set musl as our default build target.  On the other hand, the change does too little because we want to ignore all configuration values from `$PWD/(../)*/.cargo/config`, not just `build.target`.

The correct behavior is that `cargo install` should load only `$HOME/.cargo/config` and should apply all values found there.

cc @alexcrichton @japaric

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit tweaks how configuration is loaded for `cargo install`, ensuring
that we only load configuration from `$HOME` instead of the current working
directory. This should make installations a little more consistent in that they
probably shouldn't cover project-local configuration but should respect global
configuration!

Closes #6025

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Yeah we'll need to wait for that PR to merge, but if it doesn't happen in the next few days I'll figure out another strategy

**Comment by Mark-Simulacrum** [comment]
I would (loosely) expect that cargo install with a `--path` argument should use the cargo config from that path since you're probably installing a local package. I could see us warning about that (rare, I believe) case when we detect a local cargo config though.

(Generally it seems like I want an option to override this PR and say "no use this cargo config")

**Comment by dwijnand** [comment]
I agree, best fix the regression in #6025 before stretching for Mark's use case, imo.

**Pull request merged**
