### PR TITLE
use $EMAIL environment variable as fallback

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Out of curiosity is there precedent for this? A variable like `$USER` is pretty standard, but I've never seen anything set `EMAIL` before.

**Comment by tshepang** [comment]
It's standard for anyone who creates and/or builds signed Debian packages.

**Comment by alexcrichton** [comment]
Ok! Can you add a test for this as well?

**Comment by tshepang** [comment]
We should also maybe read `$NAME` as well, which is also used by Debian packagers? If it exists, it should be used in preference to `$USER`. It's advantage is that it contains the full name.

**Comment by alexcrichton** [comment]
I'd prefer not to find every environment variable that any system uses and put them all into Cargo, sticking to a few well-known ones seems like the best way forward.

**Comment by tshepang** [comment]
I added a test

**Pull request merged**
