### PR TITLE
Disable dependabot

### PR DESCRIPTION
**Pull request by alexcrichton**
I don't think this has ever actually sent a meaningful version bump PR
we weren't already aware of, so unless someone else wants to be in
charge of these I'm going to go ahead and disable dependabot.

### CODE REVIEW

**Comment by ehuss** [comment]
👍 

@bors r+

**Comment by ehuss** [comment]
@alexcrichton Any idea why github would return 429?

```
 fatal: unable to access 'https://github.com/rust-lang/crates.io-index/': The requested URL returned error: 429
thread 'main' panicked at 'failed to run git command: fetch origin 85f7bfd61ea4fee08ec68c468762e886b2aebec6', benches/resolve.rs:101:13
```

Is running `git fetch` with a specific SHA a bad thing to do?

Hm, and I just realized that now that they are deleting the snapshot branches, as soon as snapshot-2021-12-21 is deleted, the current snapshot at 85f7bfd61ea4fee08ec68c468762e886b2aebec6 will get deleted.  Perhaps it should switch to fetching from https://github.com/rust-lang/crates.io-index-archive/?

**Comment by alexcrichton** [comment]
Oh I didn't dig in much I figured I'd just retry and see if it persisted, but looks like you're right and we'll need to switch to the archive repo, if this bounces again I'll add that here

**Pull request merged**
