### PR TITLE
Bump semver version

### LINKED ISSUE #2337: Prereleases cannot be selected
I can't currently use expat-sys 2.1.1-really.0 from anywhere.

```
version required: = 2.1.1-really.0
versions found: 2.1.0
```

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #2337

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you add the cargo test case as well?

**Comment by steveklabnik** [comment]
Yes, which file should it go in?

**Comment by alexcrichton** [comment]
`test_cargo_registry.rs` should be fine

**Comment by steveklabnik** [comment]
updated!

**Pull request merged**
