### PR TITLE
Handle man pages better on Windows.

### LINKED ISSUE #9197: Cargo can't run help sub-command in command line mode.
I don't know whether it's Cargo's bug or something wrong with my setting. Here is error in detail:
`$ cargo help bench`
//or other sub-command
And an error like this pop out:
`No manual entry for ~\AppData\Local\Temp\cargo-manGE7Y90`
Hope for help ,thanks a lot.

### PR DESCRIPTION
**Pull request by ehuss**
If a user has `man` installed on Windows via msys/mingw/etc, then `cargo help <subcommand>` would fail with `No manual entry for C:\Users\User\AppData\Local\Temp\cargo-manlSKwTQ`.  This is because the cygwin universe does not handle windows-style paths and does not auto-translate in this scenario. 

The solution here is to run the command from within the temp directory and use a relative path which *should* work on all platforms and environments. I tested on windows (powershell, cmd, and mingw), macos, and linux. 

Fixes #9197

### CODE REVIEW

**Comment by HerbM** [comment]
@Dylan-DPC  @bors @ehuss 

### Mostly FYI: 

Using "cargo help clean" this problem is occurring 4 days after "Closed" day on above message referencing the commit to master while using **Rust nightly from 3 days post Close**:

However, cargo is still a week old which would predate the merge.

Apparently rustup didn't fetch the most recent cargo with the nightly fetch yesterday.
(Don't now if that is by design or not.)

    Default host: x86_64-pc-windows-msvc
    nightly-x86_64-pc-windows-msvc (default)
    rustc 1.54.0-nightly (770792ff8 2021-05-07)

    cargo 1.53.0-nightly (f3e13226d 2021-04-30)

Syncing rustup update again (just now) shows up to date as above:

    nightly-x86_64-pc-windows-msvc unchanged - rustc 1.54.0-nightly (770792ff8 2021-05-07)

And yes, my issue is due to a copy of "man.exe" on the path in PowerShell. 
(And it's just the simple "gnu Win32" version so probably stupid about paths.)

My solution is currently to just rename that man.exe, which may not be a solution for everyone.

**Thanks for all your hard work and how well Cargo (and most of the rust infrastructure works on Windows.)**

**Comment by ehuss** [comment]
The date in the version string is the last git commit, not the date when it was built. That is the latest version.

Can you file a new issue with the exact error message that is displayed?  And, can you clarify, what is a "simple gnu Win32 version"?  Where did you get it?  What is the version of man that you are using?

**Comment by HerbM** [comment]
Exact error with that man.exe on path (see below for source of program):
```
#> cargo help build
/usr/local/lib/man.config: No such file or directory
Warning: cannot open configuration file /usr/local/lib/man.config
No manual entry for ./cargo-build.60m2LW
```

The only reason for mentioning it was to alert you if this meant the 'fix' either didn't work fully or perhaps had somehow not made the release (when it should have done so.)

I thought that this man.exe came from GNU utilities for Win32 UnxUtils http://unxutils.sourceforge.net/ but man but there is no "man" in the zip available there now.   It lists itself as: "version 1.4h".  

It's very old and almost certainly of little value (I didn't mind renaming it.) Definitely not from CygWin or one of he modern sources like MSys2.  It's only on my machine because I've long been a user of Unix and Linux utilities available for Windows and was acquired with other items like grep or sed that were of more common use to me.

**Pull request merged**
