### PR TITLE
Fixed info about default edition

### PR DESCRIPTION
**Pull request by humancalico**

### CODE REVIEW

**Comment by ehuss** [comment]
The default is 2015.   Perhaps there is some confusion because `cargo new` auto-populates it with the latest edition?

**Comment by humancalico** [comment]
@ehuss So if I am understanding this correctly? If I don't add the "editon" label in the Cargo.toml file it will be set to '2015' by default and if I use cargo new/init without any flags would add the '2018' label itself.

**Comment by ehuss** [comment]
Correct.

**Comment by humancalico** [comment]
@ehuss Thanks for clearing it up!

**Pull request closed without merging**
