### PR TITLE
Allow publishing with dev-dependencies without a version.

### PR DESCRIPTION
**Pull request by ehuss**
This change allows dev-dependencies without a `version` key to be published.  If a dev-dependency is missing the `version`, it will be stripped from the packaged manifest.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

I've personally always wanted this! Curious what others think though

**Comment by Eh2406** [comment]
cc Previous discussion at https://github.com/rust-lang/crates-io-cargo-teams/issues/46 & https://github.com/rust-lang/crates.io/issues/1789.

I thought the consensus was that we wanted the `.crate` file to still work and have crates.io except the dev-dep?

**Comment by Mark-Simulacrum** [comment]
One potential concern is that this means that downloading a crate file, like e.g. Crater does, and running `cargo test` is presumably much more likely to not work, which isn't great.

However, maybe we can get around this by requiring that the dev-deps are still present in the .crate file (obviously, this can be bypassed with `--no-verify`, but that's not particularly interesting).

**Comment by alexcrichton** [comment]
@ehuss can correct me, but while it doesn't look like there's an explicit test the `Cargo.toml` inside the `*.crate` file still has `[dev-dependencies]` so long as they have a `version` listed. It's just the blob we send to crates.io that has them filtered out. They won't show up in the crates.io UI any more.

**Comment by Mark-Simulacrum** [comment]
Ah, then that seems fine to me. Maybe good to add a test if it's relatively simple though.

**Comment by Eh2406** [comment]
+1 on a test! Also since we repeatedly took time at the crates.io meetings, should we ask for there checkmarks?

**Comment by ehuss** [comment]
> but while it doesn't look like there's an explicit test the `Cargo.toml` inside the `*.crate` file still has `[dev-dependencies]` so long as they have a `version` listed. It's just the blob we send to crates.io that has them filtered out. They won't show up in the crates.io UI any more.

Sorry for the confusion.  If a dev-dependency does not specify `version`, it is filtered from both crates.io and the generated `Cargo.toml` file.  If it does include `version`, there is no change in behavior.

I can actually remove the generated `Cargo.toml` stripping. I was initially thinking it might cause problems if the registry `Summary` was out of sync with `Cargo.toml`, but I did some tests and it seems fine.  Essentially just remove all the changes to `toml/mod.rs` in this PR.  Do people think it would be a good idea to make that change?  The only purpose would be to support these path-only deps for a `build-and-test` run on crater.  I think if we do that, we should also have some checks that the dependency is actually included in the package, and deal with `..` (I'm not sure how complex that will be).  It seems like a bit of effort for a marginal benefit, though.

I can work on better tests. I'm thinking of writing something that will actually commit the publish to the local registry.

**Comment by joshtriplett** [comment]
I'd like to have some verification that the referenced dev-dependency not only has a path inside the crate, but that the referenced path actually will get included in the crate and contains a `Cargo.toml` file.

**Comment by Eh2406** [comment]
@rfcbot concern continue discussion with crates.io

Previous discussion at https://github.com/rust-lang/crates-io-cargo-teams/issues/46 & https://github.com/rust-lang/crates.io/issues/1789 let's continue the discussion in one of those threads.

**Comment by alexcrichton** [comment]
Ok, the crates.io [has discussed](https://github.com/rust-lang/crates.io/issues/1789#issuecomment-535674870) my [rationale](https://github.com/rust-lang/crates.io/issues/1789#issuecomment-530860962) and concluded that they're willing to defer to us. @Eh2406 I think that resolves your concern?

At that point I would still like to propose that we merge this PR as-is, which strips `dev-dependencies` from the manifest when publishing when they don't have a `version` listed.

**Comment by Eh2406** [comment]
@rfcbot resolve continue discussion with crates.io

**Comment by alexcrichton** [comment]
Also ping @Eh2406, @joshtriplett, and @withoutboats for checkboxes

**Pull request merged**
