### PR TITLE
Add "build-finished" JSON message.

### LINKED ISSUE #7978: Difficult to know when to stop parsing JSON messages.
**Describe the problem you are trying to solve**
It is currently difficult when parsing JSON messages to know when Cargo is finished.  With `cargo test` or `cargo run`, additional things will be printed to stdout.  Tools should scan for lines that start with `{` to detect JSON, but that doesn't help if the subsequent process also emits `{`.  

**Describe the solution you'd like**
I think Cargo should emit some JSON message to indicate that it is finished.  Tools can use this to know when to stop parsing.  Or perhaps the message should be structured to indicate that Cargo is running an external process (with the path to the process).  This may be complicated with tests since multiple tests will run (and would be good to have a story for how JSON test output works).

Either way, tools need some way to know when Cargo stops, and something else begins.

### PR DESCRIPTION
**Pull request by ehuss**
This adds a JSON message when a build is finished.  This is useful for tools to know when to stop parsing JSON, which is particularly useful for commands like `cargo test` or `cargo run` where additional output may follow.

Closes #7978

### CODE REVIEW

**Comment by ehuss** [comment]
@alexcrichton I thought some more about the comment you left, but I really think it is better just to have a single message.  I wouldn't want tools to have to listen for N messages to know when things are done.  And generally I don't need to know when something launches.

We can add "launched" messages in the future if it looks like people want it.  Also, I think the libtest JSON message already has a separate message for "starting", so test frameworks may already cover that need.

**Comment by matklad** [comment]
Seems reasonable for me to add, it's not like this will burden us with backward compatibility, and it does seem useful. 

However, I do have a gut feeling that a "proper" solution here is allowing clients to split Cargo's command in two phases, building and running. Sort-of like a universal `--no-run` argument, so that clients can do `cargo run --example foo --no-run` and then either `cargo run --example foo` again or just run the binaries themselves. But it seems unlikely that we actually add such a `--no-run` flag, and, even if we do, such addition wouldn't be precluded by the `BuildFinished` message. We might even want to have `BuildFinished` message anyway, to, for example, convey the `[optimized + debuginfo] in 60 seconds` info in machine-redable form.

**Comment by ehuss** [comment]
`cargo build --example foo` I think is 100% identical to a hypothetical `cargo run --no-run`.  The JSON even gives you the path to the executable, so a tool can just run it directly (there might be some rare dylib path issues, but programs probably shouldn't rely on those, or the tool can just execute `cargo run` if it wants to be safe/simple).  My tool just executes `cargo run` and once it sees the text `^\s*Running ` it stops looking for JSON messages.  I can switch to looking for "build-finished" with this PR.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

I'm personally ok doing this, and it also seems plausible to take the strategy that @matklad mentions but I don't think there's any reason they need to be mutually exclusive!

**Comment by alexcrichton** [comment]
That's enough of sign-off for me, and we can always back out if there are other objections!

@bors: r+

**Pull request merged**
