### PR TITLE
Refactor BuildContext

### PR DESCRIPTION
**Pull request by ehuss**
This restructures the "front end" of the compile process so that the `UnitGraph` can be accessed by API users. Essentially, the `BuildContext` contains the result of generating the `UnitGraph`, and other bits of information collected along the way. This logically separates the build process into two phases: (1) generate the `UnitGraph` and `BuildContext` and (2) pass the `BuildContext` to `Context` which performs the actual compilation.

The main challenge here is dealing with the references and lifetimes. The old code kept a bunch of things on the stack with various layers of references. Beside reorganizing things, the big change is to wrap `Package` and `Target` in `Rc`. This still requires the `UnitInterner` to be passed in and kept alive. It is possible to avoid that by placing all `Unit`s in `Rc`, but that had a roughly 5% performance hit (on fresh builds) because Units are very optimized to be used as hashable keys, and `Rc` loses those optimizations.

### CODE REVIEW

**Comment by ehuss** [comment]
I don't know if we should actually merge this.  I made this a while ago, but I no longer need it.  But Alex said I should post it anyways, so here it is.

Some parts I think are a little cleaner.  But this is a large PR, touching lots of stuff.  It is separated in 2 commits.

**Comment by djc** [comment]
FWIW (as someone who did a bunch of refactoring in this area before), it looks pretty nice to me.

**Comment by alexcrichton** [comment]
@ehuss can you remind me the benchmark you're using? I'm curious to test out a few things and see what the perf looks like

**Comment by ehuss** [comment]
Any project with a lot of crates should work.  Cargo itself is a smallish example, servo or something else big works too.  The playground's [base project](https://github.com/integer32llc/rust-playground/blob/master/compiler/base/Cargo.toml) is also good as it gets 100 popular crates or about 300 deps total (generated by [this script](https://github.com/integer32llc/rust-playground/tree/master/top-crates)).  I also have something similar in cargo-prefetch called [make-top](https://github.com/ehuss/cargo-prefetch/tree/master/make-top) which will list the top 1000 crates (pass it a path to a crates.io-index clone).  It's a little finicky because of `links` collisions, so it takes some manual work.

I also use an artificial workspace (though it isn't great because it doesn't have dependencies):

```bash
#!/bin/sh

set -e

for (( i=0; i<$1; ++i))
do
    cargo new --lib dep${i}
done

cat << EOF > Cargo.toml
[workspace]
members = ["dep*"]
EOF
```

Run `cargo check` once to build everything, then `hyperfine "cargo check"` ([link](https://crates.io/crates/hyperfine)).

**Comment by alexcrichton** [comment]
Ok thanks!

So here's [some things I've tried](https://github.com/alexcrichton/cargo/commit/28cf4c2d96c992138e9fcfb2da62f2f5bff8cba0):

* Stylistically I'd prefer to avoid `Rc<Package>` and instead use `Package { inner: Rc<Internals> }` which is how `Dependency` and `Summary` work today -- https://github.com/alexcrichton/cargo/commit/3476f536e091b5da2c4d90059b297fa32e49f8eb
* Similarly I'd prefer to do the same for `Target`, but `Target` actually needs to move across threads so it'd be `Target { inner: Arc<Internals> }`. I did it in https://github.com/alexcrichton/cargo/commit/28cf4c2d96c992138e9fcfb2da62f2f5bff8cba0 but forgot to separate out the changes.
* Finally I tried to replicate [making `Unit { inner: Rc<Internals> }`](https://github.com/alexcrichton/cargo/commit/28cf4c2d96c992138e9fcfb2da62f2f5bff8cba0) to make it a completely owned value that needs no lifetime parameter (making the `UnitInterner`'s lifetime irrelevant. I was able to also see a small perf hit, but it feels like it's very negligible. If `Rc` refcount management is a perf hit then I think we need to figure out how to architect things to clone less rather than avoid the `Rc` in the first place. For example we could try switching to `struct UnitId(usize)` and then you just always need a `Context` to learn about the `UnitId` itself (and store everything in a `Vec`)

Overall I feel like we can take this a step further (afterwards if you'd prefer) to make `Unit` an owned value. Did you have a similar implementation though and conclude that the perf hit was too much?

**Comment by ehuss** [comment]
Those changes sound fine.  The Arc is a little unfortunate, but if it doesn't have much performance impact, seems good!

I couldn't tell, but it looks like you didn't commit your final experiment removing the Unit lifetime.

Here is my old branch where I wrapped Unit in Rc: https://github.com/ehuss/cargo/commit/c053288e3df14f6b875a070e7ecc1d8182efa864.  Doing some more testing, I guess in absolute terms the performance hit isn't too bad.  For me, on the playground project, a fresh build goes from 250ms to 270ms.  I guess most people won't notice 20ms, although this is a fast-ish machine.

If you want, you can push changes to this branch/PR.

**Comment by alexcrichton** [comment]
> Here is my old branch where I wrapped Unit in Rc

ah ok this explains a bit to me. The `Hash for Unit` subtly changed in your PR where previously it just hashes the pointer to the unit (very fast) but with your PR it's actually hashing the *contents* of the unit (since `Hash for Rc<T>` forwards to `T`). In my changes I left `Unit` with an `Rc` internals so the hash should still be just a pointer. In light of that yeah I'll push these changes up and try to clean up a bit too.

I didn't go through the actual removal of the lifetime since it seemed like it would be hard, but I'll go ahead and do so now :)

**Comment by alexcrichton** [comment]
Ok I've pushed up the commits I had, in addition to the removal of a lifetime from `Unit`. Holy cow that was a lot of lifetimes removed.

**Comment by alexcrichton** [comment]
I suppose in terms of next steps, @ehuss want to review what I've done and then we can land this and continue to make progress in-tree?

**Comment by ehuss** [comment]
OK, looks good!  I did some testing and didn't see any performance differences. 🤞

@bors r+

**Pull request merged**
