### PR TITLE
Cache index files based on contents hash

### PR DESCRIPTION
**Pull request by Eh2406**
Since #10507 Cargo has known how to read registry cached files whose index version starts with the hash of the file contents. Git makes it very cheap to determine the hash of a file. This PR switches cargo to start writing the new format.

Cargoes from before #10507 will not know how to read, and therefore overwrite, cached files written by Cargos after this PR.

Cargos after this PR can still read, and will consider up-to-date cached files written by all older Cargos.

As I'm writing this out I'm thinking that there may not be any point in writing a file that has both. An alternative implementation just writes the file contents hash. 🤔

### CODE REVIEW

**Comment by Eh2406** [comment]
I like the alternative implementation better. So added it as a second commit.

**Comment by Eh2406** [comment]
No. Unfortunately, this is a very targeted change at the index files for registries like crates.io.
Sorry that the title of this PR was overly broad.

**Comment by woss** [comment]
> No. Unfortunately, this is a very targeted change at the index files for registries like crates.io. Sorry that the title of this PR was overly broad.

Is there a way now or in the future when we can have dependencies resolved properly? 
As far as i can see that the `CrateA` is the same so why is cargo treating it differently? Especially when it is required from the same URL and commit?

**Comment by Eh2406** [comment]
> Especially when it is required from the same URL and commit?

That sounds like a bug. If you are specifying the dependency as coming from the same place, it should be unified. Please open an issue with a reproducible example.

More generally the request to change how resolution works, or even discussion of a particular bug with resolution, should happen on a dedicated issue and not some random PR.

**Review by weihanglo — COMMENTED** [review]
That's how I understand the `index_version` format compatibility matrix. 

- ✅: Read side understands `index_version` from that cargo version and is able to hit the cache.
- ❌: Read side cannot understand `index_version`. Cache is always invalid under that circumstance.

| Read\Write | old | #10507 | e24222e |
| ---------- | --- | ------ | ------- |
|  old       | ✅  |  ✅    | ❌      | 
|  #10507    | ✅  |  ✅    | ✅      |
|  e24222e   | ✅  |  ✅    | ✅      | 

If that is correct, this patch only affects a small portion of users (e.g. use 1.65 to generate cache index and read it from 1.61 or older). I won't concern with that, especially the old `index_version` was only based on git commit hash, which was too restricted and not much useful than the new one.

**Comment by Eh2406** [comment]
I believe your analysis is correct.

**Review by weihanglo — APPROVED** [review]
Based on the consensus from the last Cargo team meeting, this change really makes sense. A cache miss for the old version of Cargo doesn't harm much. It will then just get an object from the local index repo.

I am going to merge it. Thank you all for helping this!

**Pull request merged**
