### PR TITLE
Prevent rustc stderr/stdout from being duplicated.

### LINKED ISSUE #4223: Cargo prints rustc's stderr twice
This is primarily a problem for those who use this output and pipe to editors to jump from error to error. The cause of this is the fact that Cargo uses `exec_with_streaming` inside `exec_json`, and passes [this stderror handler](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_rustc/mod.rs#L370) in. That prints out stderr upon receiving each line, which is fine -- we should do this. However, exec_with_streaming also saves this data [here](https://github.com/rust-lang/cargo/blob/abf01e1eddb3145c83f71b469ea7bee37141e5e1/src/cargo/util/process_builder.rs#L165). This output is later printed in "process didn't execute successfully," leading to duplication of the stderr for the compiler.

Arguably, none of these individually are bad, but together they don't lead to optimal behavior. I think the easiest and most straightforward fix here is to add a flag to exec_with_streaming that prevents printing stderr when the command fails and pass it in from cargo_rustc.

cc @alexcrichton 

cc @eddyb -- you asked on IRC about this

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Please review carefully. I've not submitted patches to Cargo before, I think, so this may be flawed in some way I haven't detected yet. Tests are green locally, though.

Fixes #4223

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good! Would it be possible to add a test for this?

**Comment by Mark-Simulacrum** [comment]
I'd guess it'd be somewhat hard -- I'd have to check for a lack of output. I worry that that would make the test too specific; but if you'd like I can look into adding one -- I believe I'd probably edit `test/rustc.rs` and add a test case?

**Comment by alexcrichton** [comment]
Oh yeah most Cargo test caes exhaustively match the output, so it shouldn't be too hard to test for a lack of output (just don't write it down but be sure to add *some* assertion). Anywhere's fine by me!

**Comment by Mark-Simulacrum** [comment]
Added a test, and confirmed it doesn't pass on master and does pass on this branch.

**Pull request merged**
