### PR TITLE
ci: Run cargo fmt on all workspaces

### PR DESCRIPTION
**Pull request by lzutao**

### CODE REVIEW

**Comment by Eh2406** [comment]
We have tried this before and did not like it, but fmt is much more stable now. @alexcrichton thoughts?

**Comment by ehuss** [comment]
I'm generally in favor of this.  I think rustfmt is stable enough it probably shouldn't be a problem.

The main issue is the churn it causes on PRs, but I personally don't feel it is too bad.  It would be nice if we had a bot that would leave a message when CI fails, particularly for this case, with nice instructions on what to do.  We could also use a pre-existing bot like https://www.travisbuddy.com/.  I suspect [rust-log-analyzer](https://github.com/rust-lang/rust-log-analyzer) isn't geared towards working on other repos, but maybe that could be used.  I don't think that should gate the decision.

For more context, here is the draft RFC for doing the same for rust-lang/rust which mentions adding bot support for pushing rustfmt changes: https://github.com/Centril/rfcs/pull/21.  I would think that is more trouble than it's worth.  Issuing a command, waiting for it to finish, pulling the changes — sounds more complex than just running `cargo fmt` locally and then pushing.

**Comment by alexcrichton** [comment]
I'm willing to try this out now that rustfmt is more stable. I don't think it's a "perfect solution" but anything going more in depth in this is a huge amount more effort. I'd prefer though that the formatting check was a separate job in Travis rather than tacked onto an existing one

**Comment by lzutao** [comment]
Done.

**Pull request merged**
