### PR TITLE
Loosen the dependency versions in Cargo.toml

### PR DESCRIPTION
**Pull request by jakub-**
I don't think they were ever intended to be specific to the patch version but were accidentally made so in https://github.com/rust-lang/cargo/commit/a1faa7cb14b4549ca395c1d62c9cd2b3f56c13dd.

This upgrades `docopt.rs` to a version that supports typo suggestions for flags:

```
$ cargo build --jobz 64
Unknown flag: '--jobz'. Did you mean '--jobs'?
```

Closes #1546.

### CODE REVIEW

**Comment by huonw** [comment]
I was under the impression that a `0.x.y` dependency is satisfied by any `0.x.z` with `z >= y`.

**Comment by alexcrichton** [comment]
@bors: r+ eff8491660ce95fca362552d6eb7945712e2a348

I agree with @huonw that the tweaks to `Cargo.toml` aren't strictly necessary, but it's fine to have them anyway!

**Comment by alexcrichton** [comment]
Unfortunately it looks like we can't upgrade Rust just yet due to a recently introduced bug in process spawning: https://github.com/rust-lang/rust/pull/24873/files

**Comment by jakub-** [comment]
@alexcrichton I see, thanks for investigating!

**Comment by alexcrichton** [comment]
Ok I picked up a bunch of updates as part of #1564 (needed to update curl which needed to update openssl), but I wasn't able to update everything. As https://github.com/rust-lang/rust/pull/24873 just landed as well tonight's nightly should be the next available which can build Cargo!

**Comment by tamird** [comment]
This is probably ready for a rebase now

**Pull request merged**
