### PR TITLE
Fixes #3814

### LINKED ISSUE #3814: Unable to find appropriate src/main.rs if it's in src/bin/main.rs
According to https://github.com/rust-lang/rust/issues/40185, the following test case should pass:

```rust
#[test]
fn run_proper_binary_main_rs() {
    let p = project("foo")
        .file("Cargo.toml", r#"
            [package]
            name = "foo"
            authors = []
            version = "0.0.0"
            [[bin]]
            name = "foo"
        "#)
        .file("src/lib.rs", "")
        .file("src/bin/main.rs", r#"
            fn main() {
            }
        "#);

    assert_that(p.cargo_process("run").arg("--bin").arg("foo"),
                execs().with_status(0));
}
```

The problem appears to be that cargo should look for `src/bin/main.rs` as well as `src/main.rs` for defaults when named binaries are not found in `src/bin/<name>.rs`. This was introduced in e3edc064761b75a0d9a8dfcd4ce46e9294e43f06.

### PR DESCRIPTION
**Pull request by jmatraszek**

### CODE REVIEW

**Comment by jmatraszek** [comment]
An `if` inside an `if` is not the pretties thing in the world, but I couldn't figure out how to do that using `else if` without creating `Path` twice, so decided to go with this.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great to me, thanks @jmatraszek!

**Pull request merged**
