### PR TITLE
Doc migration

### PR DESCRIPTION
**Pull request by istankovic**
This is (the last) part of rust-lang/rust#39588.

Docs are moved into a submodule (currently under my account, should probably be in nursery).
Content-wise, it's basically the same, with the following differences:
- completed migration to mdbook
- expanded the part on new project creation
- initial attempt to improve content organization

r? @steveklabnik @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! @steveklabnik just to clarify, this was the intention to have a separate submodule? I was wondering if we may want to have the files included directly because Cargo's CI is much easier (lightweight) than rust-lang/rust and may not deter contributors?

**Comment by steveklabnik** [comment]
Oh, so I was imagining this would be a part of `rust-lang/rust` like all the other bookshelf books. I would also be okay with keeping them in-tree if they're gonna stay in the Cargo repo. 

If we do keep them in the cargo repo, then I think the submodule makes less sense; I may have misled you @istankovic !

**Comment by alexcrichton** [comment]
Just to make sure I understand, when you say "like all the other bookshelf books" that means a git repo in rust-lang and a submodule in rust-lang/rust, right?

**Comment by steveklabnik** [comment]
> Just to make sure I understand, when you say "like all the other bookshelf books" that means a git repo in rust-lang and a submodule in rust-lang/rust, right?

Yes.

Thinking about it though, given that we _already_ include Cargo as a sub-repo, I bet we could leave the docs in the cargo repo, and then have the build system look there instead. It'd be slightly weird as it'd be the only thing out of place, but would save us a repo + submodule.

**Comment by alexcrichton** [comment]
Yeah that's what I figured. If that's ok @istankovic would you be ok moving over to that? (leaving docs in-repo here)

**Comment by istankovic** [comment]
Sure. I guess it's also better in the sense that Cargo devs may have easier time updating the docs. I'll update the PR.

**Comment by carols10cents** [comment]
Wait, I think we want to leave the old docs around and continue publishing them to github pages until the new docs have ridden the trains to rust stable, right?

**Comment by carols10cents** [comment]
Also there are some error messages and man pages that reference docs.crates.io:

- https://github.com/rust-lang/cargo/blob/ffab51954ec32d55631c37a8730bb24915fc090b/src/cargo/ops/registry.rs#L170
- https://github.com/rust-lang/cargo/blob/45148e0efdc1ea23a2e46b44cae51b746751412a/src/bin/owner.rs#L43
- https://github.com/rust-lang/cargo/blob/3751e6897020a08cbc1b082f4c7157ce66adecab/src/cargo/ops/cargo_install.rs#L355
- https://github.com/rust-lang/cargo/blob/03c0a41f97c25fc5595584bdefc38b530b4d68c3/src/cargo/ops/cargo_package.rs#L120
- https://github.com/rust-lang/cargo/blob/ffab51954ec32d55631c37a8730bb24915fc090b/src/cargo/core/registry.rs#L281

So these URLs need to remain valid indefinitely (so people stuck on old versions of cargo can still follow them and get the docs they need)-- so we should continue serving the docs from those URLs for now, change them to redirects once this PR rides the trains to stable, and this PR should also update the URLs (and the URLs should have stable/beta/nightly in them????? or not, in which case we can't update the URLs in the code until the docs are on stable?)

**Comment by istankovic** [comment]
@carols10cents:

> Wait, I think we want to leave the old docs around and continue publishing them to github pages until the new docs have ridden the trains to rust stable, right? So this PR should only add new files and not delete the old docs?

Hmm, what about doc updates during that time? One would basically have to maintain the docs in two places. That does not sound optimal to me.

**Comment by carols10cents** [comment]
> Hmm, what about doc updates during that time? One would basically have to maintain the docs in two places. That does not sound optimal to me.

Breaking URLs doesn't sound optimal to me :)

**Comment by istankovic** [comment]
Rust has broken more important things than URLs so far so... 😃 

Seriously, there has to be a nicer solution.

**Comment by carols10cents** [comment]
> Seriously, there has to be a nicer solution.

It'll only be for like 12 weeks.

**Comment by behnam** [comment]
Based on discussion on <https://github.com/rust-lang/cargo/issues/4040>

So I'm taking over from @istankovic the migration for Cargo's docs to mdBook. Now I'm confused if we're expected to have a separate repo (`cargo-book`, based on <https://github.com/istankovic/cargo-book/>) or want to go along the approach in this PR, that creates a mdBook root under `cargo` repo.

@alexcrichton, @istankovic, @carols10cents?

(If we're going with a separate repo, we should close this PR and keep the discussion on #4040. If not, I'll try to rebase this work in a new PR.)

**Comment by steveklabnik** [comment]
I personally don't see the need to make a new repo.

**Comment by istankovic** [comment]
@behnam, thanks a lot for taking over!
The cargo-book repo contains basically the same thing as the doc-migration branch in my cargo fork. The latter is just a squashed form of the former and the book was put under doc/ (I did not think of a better place, feel free to move it). Note that the idea is to have both the mdbook and the current docs coexisting for some time in cargo, per discussion above.

**Comment by behnam** [comment]
All sounds good! I'll add a note to `/src/doc/README` about the migration and keeping them in sync during it.

**Comment by alexcrichton** [comment]
Thanks for taking this on @behnam! And yeah keeping it all in this repo sounds good to me.

Feel free to ask with any questions!

**Comment by behnam** [comment]
We can close this PR in favor of https://github.com/rust-lang/cargo/pull/4453 which has more updates, and the tracker issue https://github.com/rust-lang/cargo/issues/4040 .

**Comment by behnam** [comment]
#reminder This can be closed now. :)

**Comment by alexcrichton** [comment]
Indeed thansk @behnam!

**Pull request closed without merging**
