### PR TITLE
Fix wrong SDK being used for the host on macOS

### LINKED ISSUE #7283: Build scripts fail on macOS if the target SDK is not the same as the host
**Problem**

Invoking `cargo build` from an Xcode project targeting iOS or iOS Simulator fails to build any crate with a custom build script, because the wrong linker is invoked for the custom build script. This is because Xcode sets `SDKROOT` for the target platform (the build script must be built for the host platform instead)

**Steps**

1. `git clone git@github.com:rust-lang/libc.git && cd libc`
2. ```SDKROOT=`xcrun --sdk iphonesimulator --show-sdk-path` cargo +nightly build --target x86_64-apple-ios -vv```
    *or*
    ```SDKROOT=`xcrun --sdk iphoneos --show-sdk-path` cargo +nightly build --target x86_64-apple-ios -vv```
3. The custom build script is built with the iPhoneSimulator SDK linker instead of the MacOSX SDK linker, which causes the build to fail with undefined symbols

**Possible Solution(s)**

Invoking `rustc` for the custom build script should always use the SDK for the host platform instead of the target platform (that is, ignore the `SDKROOT` environment variable set by the user or Xcode). This can be achieved, for example, by Cargo prepending the `rustc` invocation with `SDKROOT=""`

**Notes**

Output of `cargo version`: cargo 1.37.0 (9edd08916 2019-08-02)

### PR DESCRIPTION
**Pull request by aleksijuvani**
Closes #7283

### CODE REVIEW

**Comment by Eh2406** [comment]
I am sorry I don't use mac things so I will have a hard time testing,
@bors r? @ehuss

**Comment by aleksijuvani** [comment]
I had to set up a Linux virtual machine to figure out why the tests weren't passing, and rewrite this a couple of times in order to wrap my head around it, but I'm confident that it's correct now. Should be good to review!

**Comment by aleksijuvani** [comment]
It should be noted that `SDKROOT` is used in many parts of the build process to locate the correct SDK, e.g. by `rustc`, `ld`, etc. It appears to be possible to work around this by undoing the changes made by Xcode to the `PATH` and `SDKROOT` environment variables with `unset SDKROOT` and `PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` before invoking `cargo build`, but this doesn't feel like a great solution. It seems to me like this will break later on if a different SDK needs to be used from the one that it happens to default to.

**Comment by aleksijuvani** [comment]
If `-isysroot` or `-Wl,-syslibroot` are not explicitly specified, they will be set to the `SDKROOT` environment variable. In order to fix this in the compiler, I believe this would involve specifying the `-isysroot` and `-Wl,-syslibroot` pre-link args to the "macosx" SDK on the x86_64-apple-darwin and i686-apple-darwin targets. Then the `SDKROOT` environment variable would not be used anymore when building for the host. This is equivalent to what this pull request does, but with the functionality moved to the compiler. It looks like cc already specifies `-isysroot` so no changes are required there.

**Comment by aleksijuvani** [comment]
There may be a case in which the user would want to explicitly specify the SDK path with  the `SDKROOT` environment variable (rust-lang/rust#62903), in which case ignoring the user's preference by always setting `-isysroot` is not desired. I feel like the correct thing may be to only set `-isysroot` for custom build scripts, which would enable the user to still override the SDK path, but also allow custom build scripts to be built for the correct platform. This comes back to putting target-specific build logic in cargo.

**Comment by aleksijuvani** [comment]
I'm not sure what that would look like. I'm not confident it's possible to solve this problem given these parameters. I understand the desire to avoid target-specific logic in cargo, but I can't see an alternative in this case—unless in rustc we always specify `-isysroot` to match the target platform and ignore the requested `SDKROOT`, but I'm not totally happy with this solution. I'll think about it a bit more, but I might have to keep working around this for now.

**Comment by alexcrichton** [comment]
We could add logic to `rustc` to detect that `SDKROOT` is set, a cross compilation is happening, and the `SDKROOT` is clearly not for the host and/or target. The compiler itself could then automatically not use `SDKROOT` for the host and only use it for the target, and I think that would fix this?

**Comment by aleksijuvani** [comment]
I had the same thought earlier, but I'm usually a bit vary about adding heuristics such as these, since it has the potential to be confusing and unexpected for the user. Perhaps it's not an issue in this case, as building with the wrong SDK is almost certainly a mistake and will cause the build to fail anyway. Maybe we should notify the user when we do this, by outputting a warning or some such?

**Comment by alexcrichton** [comment]
Well the heuristic seems like it needs to be somewhere at this point. It's either in Cargo or rustc, and the logic is already in rustc and there's no logic at all in Cargo for this so it seems like this should go in rustc, not Cargo.

**Comment by alexcrichton** [comment]
This is making progress at https://github.com/rust-lang/rust/pull/64254, so I'm going to close this in favor of that.

**Comment by comex** [comment]
I've been working on refactoring rustc's Apple OS target code (to support more OSes and generally be more orthogonal), and while rebasing on master I noticed the rustc change corresponding to this.  I really don't think it's the right solution.  Semantically, it makes a lot more sense to me that when Cargo decides to switch targets from the one the user specified, Cargo should handle correcting target settings for the new target.  It shouldn't be rustc's job to guess when the target settings it's been given are wrong.

Practical reasons it would be better to do it in Cargo:
- To properly handle the case where build dependencies try to compile C code, you would need to replicate the same logic in `cc-rs`.  A Cargo-side fix could apply equally to build scripts and rustc invocations.
- Also, ideally there would be a way to specify "SDKROOT/DEPLOYMENT_TARGET when building for host", but "building for host" is a Cargo concept.
- Detecting that the SDK root is for a different platform will not work if you're cross compiling from one version of macOS to a different version of macOS.  If the target SDK is an older version than the host, the resulting binaries will probably work on the host anyway (although they might fail to build if a build dependency depends on something only available in a newer version).  But it definitely won't work if you're building for a *newer* version of macOS than the host.  That's admittedly a bit of an edge case, but it's actually something I do regularly.

**Comment by comex** [comment]
Going back to the previous discussion:

> Well the heuristic seems like it needs to be somewhere at this point. It's either in Cargo or rustc, and the logic is already in rustc and there's no logic at all in Cargo for this so it seems like this should go in rustc, not Cargo.

If it's in Cargo, there's no need for a heuristic.  The logic would be simply "drop the user's target settings when building for host instead of the user-specified target"; in fact, that's exactly what this closed PR does.  The rustc solution that was adopted instead *is* a heuristic, because rustc doesn't have a concept of "building for host instead of the user-specified target", so it has to guess based on whether the SDK looks like it's compatible with the current build machine (i.e. macOS).

**Comment by alexcrichton** [comment]
@comex this is following the precedent set by MSVC and selecting visual studio and `cl.exe` and such there. I didn't want to accidentally fall into a different pattern with respect to macOS just because it was a little easier to implement. If there's good reasons for doing this in Cargo then there's good reasons for doing this in Cargo, and PRs are welcome!

**Pull request closed without merging**
