### PR TITLE
[beta] Backport #6771 

### PR DESCRIPTION
**Pull request by sgrif**

### CODE REVIEW

**Comment by ehuss** [comment]
I think this will fail for multiple reasons. @sgrif can you cherry-pick some other PRs to get the 1.34 branch working?  I think it will need #6807. It looks like there is another unused item in `src/cargo/util/paths.rs` (build with the 2019-04-01 nightly, with `build --features=deny-warnings --tests`).

Also, it looks like the minimal versions CI entries are failing.  Just delete the entire entry from .travis.yml and appveyor.yml.

Let me know if you want me to do it or have any questions.

**Comment by sgrif** [comment]
Cherry picked #6807 and deleted the minimal version entries from travis and appveyor

**Comment by sgrif** [comment]
Fixed the errors from `cargo +nightly-2019-04-01 build --features=deny-warnings --tests`

**Comment by ehuss** [comment]
Thanks!  Sorry, the beta branches always seem to have problems since they are so rarely built.

@bors r=alexcrichton

**Comment by sgrif** [comment]
No worries. This is mostly on me for letting this sit for so long.

**Pull request merged**
