### PR TITLE
Doc specific features

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This will allow gtk-rs and gstreamer-rs to remove some unneeded features. :)

I made this implementation flexible enough so we can add more build specific thing (like "test" or even "doctest").

cc @sdroege

r? @ehuss

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks for taking a look!  I'm not really sure that looking into the package metadata is really the right option, since that is a free-form area intended for external tools.

I think this will probably deserve a more general solution. There are some open issues along this line (like #2911) and a postponed RFC (https://github.com/rust-lang/rfcs/pull/1956).  This may require more design and planning.  I think something like this will probably want to go through an RFC process.

Also, just FYI, some team members are going to be away for a while due to the holidays, so it may be a while before we can provide any more feedback.

**Comment by GuillaumeGomez** [comment]
An RFC seems a bit too much for such a thing from my point of view. However I agree that metadata might not be the best place for it. Open to suggestions!

**Comment by ehuss** [comment]
I'm going to close this for now, since this isn't an approach we want to take.  In particular, we don't think Cargo should be using the package metadata.  I don't have any particular suggestions for how it should work.  I think the issue and RFC linked above might be a good starting point, but the relationship between command and profile is a little awkward (and the `doc` profile was deprecated, which we would need to resurrect).  Maybe posting on internals may drum up some discussion?  Or feel free to follow up on the issue tracker.

**Comment by GuillaumeGomez** [comment]
All the links you gave are stuck so I have to admit that I have lost all motivations on this... I'm surprised that profiles aren't already a thing, it's something strongly needed in a lot of places and I was hoping that since `doc` and `doctest` features were finally stabilized (even though the second needs actions on cargo that won't happen once again)...

**Pull request closed without merging**
