### PR TITLE
Fix `cargo update` with unused patch.

### PR DESCRIPTION
**Pull request by ehuss**
If you end up with an unused patch in `Cargo.lock`, then you try to update the patch to a version that does not match the original unused patch, and run `cargo update`, Cargo refuses to update it with the error "patch for `bar` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates".  At this point, Cargo seems to be permanently stuck with no way to update it (unless you manually edit `Cargo.lock`).

The solution here is to add the unused patches to the "to_avoid" list, so that `cargo update` is allowed to update them.

I am uncertain if this is the best way to fix it, but seems to match my intuition of how `cargo update` is implemented.

### CODE REVIEW

**Comment by ehuss** [comment]
Note: The error points to #4678. It may be possible that some of the reports in that issue are due to this, though it is unclear.

**Comment by alexcrichton** [comment]
@bors: r+

Nah this makes sense to me, this mirrors where other packages are ignored but unused patches aren't part of iteration so it makes sense to include them there to.

#4678 is a super old issue at this point and I still run into it every now and then, so I'm not sure if it fixes it. If I don't see it for awhile seems worthwhile to close it though!

**Comment by ehuss** [comment]
I think the error message still shows up if you run `cargo build` at [this line](https://github.com/rust-lang/cargo/pull/8243/files#diff-2d5c5a7086fc4680dbde430de03a9c39R1497) instead of running `cargo update`. 

I probably should have addressed that as well, but I was a little unclear what scenarios hit that error. I'll try to follow up with another PR to try to improve the error message.

**Comment by jdm** [comment]
Thanks for fixing this!

**Pull request merged**
