### PR TITLE
test(travis): Test build with minimal versions

### PR DESCRIPTION
**Pull request by klausi**
We should make sure that cargo itself builds successfully with minimal dependency versions. Not sure this is the correct place in the Travis config, let me know if this should be added somewhere else.

This should currently fail because

```
$ cargo update -Z minimal-versions
...
$ cargo build
error: multiple packages link to native library `curl`, but a native library can be linked only once

package `curl-sys v0.4.0`
    ... which is depended on by `libgit2-sys v0.7.0`
    ... which is depended on by `git2 v0.7.0`
    ... which is depended on by `cargo v0.27.0 (file:///home/klausi/workspace/cargo)`
links to native library `curl`

package `curl-sys v0.3.10`
    ... which is depended on by `curl v0.4.6`
    ... which is depended on by `crates-io v0.16.0 (file:///home/klausi/workspace/cargo/src/crates-io)`
    ... which is depended on by `cargo v0.27.0 (file:///home/klausi/workspace/cargo)`
also links to native library `curl`
```

This is not good because `cargo update -Z minimal-versions` should produce a setup that is always able to be built. This can have 2 causes:
* `cargo update -Z minimal-versions` is broken and should work differently
* Dependencies in Cargo.toml are not specified correctly and need to be updated

### CODE REVIEW

**Comment by klausi** [comment]
The first build error with competing curl versions can be solved by bumping the curl version.

Now I'm falling a bit into a rabbit hole with lots of dependencies that need to yank their broken old versions from crates.io. Started with https://github.com/alexcrichton/libz-sys/issues/36

**Comment by matklad** [comment]
@klausi I think that rather than yanking, we should probably just bump minimal dependencies across the board? 

For example, we can say `= "1"` here: https://github.com/alexcrichton/curl-rust/blob/a15e3e35a2f5c7b9bbc83c59768b1d12fbd05506/curl-sys/Cargo.toml#L23

**Comment by klausi** [comment]
The counter argument to that is then that all libraries across the Rust ecosystem need to update their minimum requirements for old package versions that are broken anyway.

In https://github.com/servo/rust-url/pull/441 @SimonSapin decided to rather yank broken packages from crates.io, which makes a lot of sense to me.

**Comment by matklad** [comment]
Probably!

Personally, I wouldn't be too worried about checking with `--minimal-version`: because Cargo always tries to pick the latest versions, it doesn't really help that much. 

That said, `libz-sys = ">= 0"` constraint in curl-sys definitelly seems weird  :)

**Comment by SimonSapin** [comment]
For what it’s worth, those versions were published before Rust 1.0.0 and relevant changes to the crate were accounting for breaking changes in the language. Today this would be similar to a crate that requires unstable features, where the ecosystem’s convention is to update to new Rust in non-SemVer-breaking version nubmers.

**Comment by klausi** [comment]
Agreed that fixing their weird minimal versions in curl-rust also makes sense, opened https://github.com/alexcrichton/curl-rust/pull/205

We can tackle this on multiple fronts :)

In the future every Rust library should add something like `cargo update -Z minimal-versions && cargo build` to their CI configuration. That way a library can ensure that it does not only build with maximum dependency versions (cargo default) but also with the minimum. Makes it easier to detect breaking API changes and to ensure that the library works over a spectrum of dependency versions.

**Comment by alexcrichton** [comment]
Thanks for the PR @klausi! I think though that this PR is mostly showing that we're not quite ready for this option.

One of the reasons we considered adding this was to ensure that everyone's "lower bound" in their Cargo.toml was correct as our suspicion was that it *wasn't* correct for many many projects. Clearly that appears to be the case!

I'm not so sure that we should test this for Cargo itself, but rather fix issues as they come up. Perhaps one day we may be able to do this on Cargo's own CI but I think for now we won't be able to.

I'll comment on some of the assorted issues as well, but I think that yanking probably isn't the right approach here but rather the intended solution to this was updating the minimum version required in `Cargo.toml` manifests.

**Comment by Eh2406** [comment]
Note that as part of the "multiple fronts" this `multiple packages link to native library` can also be fixed by retroactively adding a "links" attribute to the index.

@alexcrichton I agree we should work on things as they come up. As crates try and use this feature, that should demand that their dependencies do it to, that is just how these things will come up. Also cargo as a library should be using this feature.  I.E. this PR may take a long time to land but it should get implemented.

@klausi thanks for thinking of this!

**Comment by Eh2406** [comment]
To remove the dep on libc:0.1.0
filetime = "0.1.7"
git2-curl = "0.8.1"

**Comment by alexcrichton** [comment]
> I.E. this PR may take a long time to land but it should get implemented

makes sense to me!

**Comment by klausi** [comment]
I managed to compile cargo now with minimum dependency versions, yay! I modified the Travis config to test that with my registry index fork.

I had to use version ranges for some dependencies because for example "0.1.2" means that only this version can be installed, not "0.1.3" nor "0.2.0". This is special behavior for pre 1.0 versions, see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html for background info.

If this passes then I think we can spin out the Cargo.toml dependency changes to a separate pull request and leave this for automating the minimal version check with Travis CI.

**Comment by matklad** [comment]
>I had to use version ranges for some dependencies because for example "0.1.2" means that only this version can be installed, not "0.1.3" nor "0.2.0".

I believe `0.1.3` could be installed! Quoting the linked docs:

> The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.

**Comment by klausi** [comment]
Oh, you are totally right! I misunderstood how the version ranges work below 1.x and we should be good with specifying "0.x.y" in all cases.

I also had to bump tar because earlier versions want to use winapi 0.0.x which does not compile anymore.

**Comment by Eh2406** [comment]
You're not the first person to be confused by that, if you have ideas for what would make it clear since that might make a good PR. :-)

**Comment by matklad** [comment]
Hm, I think I've found an interesting use case for `--minimal-versions`, while discussing [this LALRPOP issue](https://github.com/lalrpop/lalrpop/pull/366#discussion_r183211817). 

The issue is about library compatibility with older versions of `rustc`. I am pretty sure that bumping a minimal required `rustc` version for a library is **not** a semver breaking change. Ultimately, the leaf crate with Cargo.lock is responsible for picking a particular version of all libraries, and it can pick a lower version if it must be compiled with old `rustc`. 

There are two practical problems with this approach. 

For the leaf crate, there's no tool to do dependency resolution, subject to a particular `rustc` version. We can't solve this problem without implementing "specify rustc in Cargo.toml" feature.

For the library crate, the problem is CI: you probably test that you are actually compatible with old Rust, and this will fail if your dependencies publish updates, which bump minimal rustc version. A simple solution here is to just check rustc compat with `--minimal-versions` flag. 

An actionable item here, I think, would be to add "Continuous Integration" section to Cargo guide, which explains that you generally should have two CI config: one with stable rustc and latest dependencies, and one with the oldest rustc you support and `--minimal-versions`.

**Comment by klausi** [comment]
Yay, the Travis output looks good and we got a successful build with the new minimal versions!

I will create another PR with just those versions now.

**Comment by klausi** [comment]
Cool, that one was merged! The remaining task here is now to establish a Travis CI config that ensures Cargo's minimal dependency versions keep compiling successfully in the future. In order for that to happen we need:

1. `cargo publish` always needs to send the `links` key to the registry. This needs to be stabilized as default behavior in stable cargo.
2. Mass update the crates.io registry to add the `links` key where it is missing right now.
3. Stabilize the `-Z minimal-versions` flag into `--minimal-versions` on Cargo stable

After that all crates should be able to throw this into their CI config:
```
cargo build --minimal-versions
```

**Comment by SimonSapin** [comment]
> cargo publish always needs to send the links key […]
> Mass update the crates.io registry to add the links key where it is missing right now.

You can’t assume everyone uses the latest version of Cargo. Some people will keep using older versions, and those versions still need to be able to read the index and publish new crates.

**Comment by matklad** [comment]
@klausi I am trying to understand what needs to be done to move this forward. 

I see we use custom registry here, to work around the `links` problem. Could we instead just bump some requirements to versions which include the `links` key?

After that we should be ready to merge it?

**Comment by klausi** [comment]
Unfortunately I think this will take some time until we can finish this. We need to do the steps 1. -3. I mentioned above.

That will not stop people from still publishing crates without the "links" attribute. 2 options to solve this:
1. Forbid people from publishing with old cargo versions on the crates.io server
2. Live with the fact that the "links" field on crates.io will always be inconsistent. We could refactor cargo's compile step: if a compilation fails because of a "links" clash then restart the dependency resolution process with the gained knowledge that a crate meta info is missing the "links" attribute. cargo could solve this locally by restarting itself as soon as it learns that "links" is missing.

**Comment by matklad** [comment]
>Forbid people from publishing with old cargo versions on the crates.io server

Hm, my understanding that only *ancient* (pre-Rust 1.0) versions of Cargo don't set `links` on publish, so this is really not a problem in practice. Nobody should depend on crates without `links`, because they are likely not even build with modern rust. 

That is, I still don't think we need to change anything in Cargo to move this forward, we only need to make sure that Cargo dependencies don't depend on ancient stuff like `libz-sys 0.0.1`. Am I missing something?

**Comment by alexcrichton** [comment]
@matklad oh FWIW publishing `links` to the registry is quite recent, *supporting* `links` in a crate graph already downloaded is pre-1.0.

**Comment by alexcrichton** [comment]
Should we perhaps close this PR in favor of the tracking issue for now?

**Comment by Eh2406** [comment]
I think they are separate, this is on adding minimal-versions to cargos CI, the tracking issue is on stabilizing the flag and messaging around that.

**Comment by alexcrichton** [comment]
True! But this is also testing the ability for a published Cargo to build with this flag rather than the in-tree version? Additionally I figured we may want to close until the standard registry has been fixed up

**Comment by matklad** [comment]
>What makes the sys crates issue so difficult is that it breaks this roul. Eche of my dependents can build with minimal-versions but they pick different compatible versions of cul-sys.  I can not build, 

This happens because old versions of `curl-sys` were published with old Cargo's right? In that case, I think the fix is:

* get the maintainer of `curl-sys` to publish a new minor version with a new Cargo, so that the registry has `links`. 
* Send PR to your dependencies which bump minimal `curl-sys` requirements to the newly published version, with comment along the lines "although `--minimal-versions` works for you, it doesn't work for your reverse-dependencies because a problem in an old version of Cargo with which the old version of curl-sys was published". After PR is merged, ask the maintainer to make a new minor release
* Bump minimal versions of said dependencies in your Cargo.toml.

That is, I think the problem **is** solvable by sending some PRs upstream, without modifying the registry?

**Comment by Eh2406** [comment]
You are technically correct. The best kind of correct.
So your solution involves every reverse dependency of all well established sys crates bumping requirements to the "post links in registry" version? That feels to me like a lot of chern, and a very long tail of things to be fixed.

**Comment by matklad** [comment]
>So your solution involves every reverse dependency of all well established sys crates bumping 

Hm, yeah... Like, every *transitive* rev-dep should be bumped, which I think in practice means every crate. At least, we can't have worse churn :-) 

OTOH, I think the amount of churn will be massive even if we somehow fix the links issue: https://github.com/rust-lang/cargo/issues/5657#issuecomment-401305099 says that anything that depends on `log 0.3` is broken, and that alone I think is a very significant chunk of the ecosystem.

**Comment by Eh2406** [comment]
But for non sys crates like log, there are workarounds. If *anything* in my dependency tree uses a `log 0.3.4` then I can build, no matter how many dependents incorrectly claim `log 0.3`. If somehow all of my dependency tree uses a problematic formulation then I can just add a dependency on `log-that-works-with-minimal-versions` which is a crate (that I have not yet published) that has one dep `log 0.3.4`.

**Comment by alexcrichton** [comment]
I think I've published enough crates now that if libgit2-sys's dependency version is updated to 0.7.5 in Cargo that should do the trick and we can build with minimal-versions

**Comment by Eh2406** [comment]
You claim the sys mess can be fix by new releases, I am sceptical so you demonstrate that it works. 😄 Well the proof is in the pudding. If it works it works and I am convinced. 😄 

I was also thinking, how can a dependency tree depend on two semver versions of an sys crate? Why can that build at all? The answer the sys crates needs to be imported by a non semver respecting version_req. So this problem should be much smaller than I was thinking. So ya if you dep on an sys don't do it like `0.*`, and if you have in the past then release a new version. 😄

**Comment by Eh2406** [comment]
@klausi want to push the update @matklad tested and let's get this merged!

**Comment by Eh2406** [comment]
With that change `cargo build -Z minimal-versions` worked but it did not do what I intended. There was a lock file so it did not need to update it. `cargo +nightly generate-lockfile -Z minimal-versions && cargo test` did not bild do to `winapi 0.0.1` not working. I am working on identifying where to make PRs upstream.

**Comment by alexcrichton** [comment]
Ah yeah I was just testing on Linux, it may still be broken on Windows!

**Comment by Eh2406** [comment]
adding `gcc = "0.3.23"` looks to have fixed it!

**Comment by klausi** [comment]
Thanks for taking this over @Eh2406 ! Let's continue in #5757

**Pull request closed without merging**
