### PR TITLE
Add some failing tests around targeted dependencies

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
ping @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for this! We can't merge failing tests, though, so perhaps this can be cc'd on the relevant issues and left as good tests for when they're fixed?

**Comment by wagenet** [comment]
@alexcrichton I referenced it on #3195. Guess I should have pinged you there.

**Comment by dwijnand** [comment]
Closing for now..

**Pull request closed without merging**
