### PR TITLE
Update to new rustdoc --test output

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems like it's dropping too many assertions for what's getting printed? Can we still assert that various tests are run?

**Comment by GuillaumeGomez** [comment]
That's what I'm trying to do. Expect multiple squash/push. :)

**Comment by GuillaumeGomez** [comment]
Seems to work now. I had to add a new method to check if stdout contains the expected string. I intend to update the output once the related PR in rustdoc is merged.

Does it seem ok to you @alexcrichton?

**Comment by alexcrichton** [comment]
@GuillaumeGomez just use `[..]`, there's no need to add redundant features or relax test so drastically here.

**Comment by GuillaumeGomez** [comment]
Mac tests didn't run...? Apparently it's what causes travis to say tests failed.

**Comment by alexcrichton** [comment]
@bors: r+

I think travis is just having some issues right now

**Pull request merged**
