### PR TITLE
clarify default behavior of `documentation` field

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/rust-lang/cargo/issues/11777, https://github.com/rust-lang/crates.io/issues/1484

### CODE REVIEW

**Comment by epage** [comment]
For myself, I feel like its a bug in the system that we have to add so much nuance here. If that bug isn't being fixed, should we just not reference this and encourage people to set the links?

**Comment by ehuss** [comment]
Yea, I would agree this seems like weird bug to document. I'm also a little confused, as it seems like the accepted solution should be relatively trivial (something like `documentation.or_else(|| format!("https://docs.rs/{name}/latest/{name}"))` in the search code).

**Comment by RalfJung** [comment]
Yeah, [agreed](https://github.com/rust-lang/crates.io/issues/1484#issuecomment-2022690205).

**Comment by weihanglo** [comment]
If we agree on seeing a fix on crates.io or other services, should this be closed?

**Comment by weihanglo** [comment]
Close as it is more like a buggy behavior in crates.io that we don't want to document. Thanks everyone for the discussion.

**Comment by RalfJung** [comment]
Does the cargo team define whether this is a bug in crates.io? That seems like a crates.io decision to me. https://github.com/rust-lang/crates.io/issues/1484 is marked as "enhancement".

Meanwhile, we are doing our users a disservice by having documentation that actively contradicts reality.

**Comment by RalfJung** [comment]
Even if this *is* a bug in crates.io, it is clearly a long-standing issue and hard to fix. So telling users in the cargo docs that they can just leave the docs field empty if they use docs.rs (which is effectively what the docs are doing) is not helping.

I have to say I am quite disappointed with how this has been handled -- we have docs that actively confuse users and lead them in the wrong direction, and instead of trying to fix this we're squabbling about whether this is a bug or not?

**Comment by epage** [comment]
> Meanwhile, we are doing our users a disservice by having documentation that actively contradicts reality.

Its fairly close to reality

> Even if this is a bug in crates.io, it is clearly a long-standing issue and hard to fix. So telling users in the cargo docs that they can just leave the docs field empty if they use docs.rs (which is effectively what the docs are doing) is not helping.

While its long standing, there has been recent progress to fixing it.  iiuc the blocker for fixing it is on docs.rs's side and the PR for that was started this summer (rust-lang/docs.rs#2533).

I mentioned that I was fine with removal if this was going to the status quo but that doesn't appear to be the case, so I lean towards keeping the documentation.

**Comment by RalfJung** [comment]
It's far enough from reality to cause actual problems: many crates have no "Documentation" link in the search results, adding an entirely unnecessary extra click for the quite common flow of "go search some crate to find its docs".

**Comment by epage** [comment]
If the concern is about browsing crates.io, at this point, it would be a major undertaking to get people to notice the documentation change to specify `package.documentation` and for people to act on it.  It doesn't seem worthwhile to make that shift when we'll just switch back again.

**Pull request closed without merging**
