### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by shuoer86**

### CODE REVIEW

**Comment by weihanglo** [comment]
Thanks!

@bors r+

**Comment by weihanglo** [comment]
Please follow the instruction to fix CI issue: <https://github.com/rust-lang/cargo/actions/runs/6560766831/job/17819088079#step:6:227>

> Please run `cargo build-man` to rebuild the man pages
> and commit the changes.

**Comment by weihanglo** [comment]
Usually you edit files under `src/doc/man`, run `cargo build-man` and you're all set.

The file you'd like to update is <https://github.com/rust-lang/cargo/blob/8537dffa1e4b74804e4af26cc4cb0c50e868df30/src/doc/man/includes/options-profile.md?plain=1#L3>

**Comment by shuoer86** [comment]
@weihanglo I find the solution based on your guide. Thank you very much.

**Comment by shuoer86** [comment]
It is finally finished.

**Comment by shuoer86** [comment]
@weihanglo It is finished finally based on your guide. Thank you very much.

**Review by weihanglo — APPROVED** [review]

**Pull request merged**
