### PR TITLE
[doc/book] Move section content to */index.md

### PR DESCRIPTION
**Pull request by behnam**
This gives a better over-all structure to the book, which we can also
follow for other books on <doc.rust-lang.org>.

Also, confirming fix for broken links with the latest (0.0.24) `mdbook`
release.

### CODE REVIEW

**Comment by behnam** [comment]
Live test: http://code.behnam.es/rust-cargo/book/

**Comment by alexcrichton** [comment]
Ah this is [in the queue](https://buildbot2.rust-lang.org/homu/queue/cargo), the queue's just moving a bit slowly :(

**Pull request merged**
