### PR TITLE
Bump cargo to 0.2.0

### LINKED ISSUE #808: Make cargo repo compatible with homebrew formulae
A colleague is interested in trying to help write a homebrew formula for installing cargo, so that `brew install cargo` will work.

 * [Opening Homebrew PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md#how-to-open-a-homebrew-pull-request-and-get-it-merged)
 * [Homebrew Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md)

One hurdle that my colleague pointed out is that the homebrew policies for acceptable formulae requires that stable versions be tagged in the upstream project repository.  I'm not a cargo developer, so perhaps the plan is indeed to start using the tag mechanism once we have hit a version beyond `0.0.1-pre`, but we have not yet hit a stable version, and thus no tags yet exist.

Anyway, I figured I would open this ticket to track any effort towards homebrew compatibility, with the intention that this ticket be closed once `brew install cargo` does something plausible.  :)

### LINKED ISSUE #1178: Cargo version
I didn't see the cargo version process specified but cargo is currently version 0.0.1 and rust version 1.0 alpha. Will cargo go 1.0 with rust? If this is undecided, it might be useful to specify somewhere.

### PR DESCRIPTION
**Pull request by alexcrichton**
Closes #808
Closes #1178

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

I'll tag this in git once it's merged

**Comment by lloeki** [comment]
Thanks for this!

**Comment by fiag** [comment]
:+1:

**Pull request merged**
