### PR TITLE
Less duplication in activate

### PR DESCRIPTION
**Pull request by Eh2406**
One of the "background context" things I re-explained in https://github.com/rust-lang/cargo/pull/6919#issuecomment-493219120 is why we have checks in `RemainingCandidates::next` and in `flag_activated`.  "Why the duplication? Because cloning a `BacktrackFrame` is more expensive than doing the work twice." But thanks to a lot of work, and `im.rs`, the clone is now not so bad.

This PR attempts to go all in on removing this duplication. Anything to simplify the resolver is good! But, this removes or hamstrings several important optimizations that make NOP builds fast. Specifically #5132 will kick in far less often. Alex, can you look at the times after/before this PR on some larger projects? You have seen this be slow with `perf record ./x.py build` before, but servo or cargo may be easy and interesting.

Note that Master is at "Fast but duplicated" and this PR may be at "Slow but clean", the best solution may be somewhere in between.

### CODE REVIEW

**Comment by Eh2406** [comment]
This is waiting on someone with a fairly powerful and idle computer doing a comparison of `time cargo generate-lockfile` with a build of master vers a build with this PR on some large project like servo or like rustc. I don't have access to the compute and @alexcrichton appears not to have the time. But anyone is open to step in!

**Comment by ehuss** [comment]
Did some quick measurements on my laptop (2.6GHz i7), average of 10 runs, with `--offline`:

Project | master | 6967
-|--|--
2000 crate stress test | 2.127s | 2.671s
rust-lang/rust | 0.246s | 0.270s
servo | 0.620s | 0.641s
cargo | 0.106s | 0.112s

**Comment by Eh2406** [comment]
Thanks for doing the work! Adding a % column,

Project | master | 6967| %
-|--|--|--
2000 crate stress test | 2.127s | 2.671s|25%
rust-lang/rust | 0.246s | 0.270s|9%
servo | 0.620s | 0.641s|3%
cargo | 0.106s | 0.112s|5%

That is a pretty significant cost. :-(

**Comment by Eh2406** [comment]
@ehuss Can you share the `2000 crate stress test` I'd love to experiment with that. If I don't find anything in that to change things, this should probably be changed to just adding a comment explaining the connection between `RemainingCandidates::next` and in `flag_activated`.

**Comment by ehuss** [comment]
Here you go: https://gist.github.com/ehuss/757952b83a239b37cb8811f90e45c6d6

**Pull request closed without merging**
