### PR TITLE
implement default-run option to set default binary for cargo run

### LINKED ISSUE #2200: It is not possible to specify a default binary
I think it would be really great if one would be able to specify a default binary in `Cargo.toml`, so `cargo run` could be used without `--bin` argument when there are more binaries in a crate.

### PR DESCRIPTION
**Pull request by RalfJung**
The implementation is not pretty but as good as I could make it. The fact that all this logic in `cargo_run` is for diagnosis only and essentially just re-implements the filtering done elsewhere really threw me off.

Fixes #2200

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could this be placed behind a Cargo feature though to avoid it being insta-stable?

**Comment by RalfJung** [comment]
All right, I will look into how to do that.

**Comment by RalfJung** [comment]
Done.

**Comment by RalfJung** [comment]
Fixed conflicts.

**Comment by dhbradshaw** [comment]
Is this feature intended to go live on stable?  If so, what needs to happen before it does?

**Comment by ehuss** [comment]
@dhbradshaw I just filed a tracking issue at #7032, and nominated it for stabilization.

**Pull request merged**
