### PR TITLE
re-enable previously nightly-only tests

### PR DESCRIPTION
**Pull request by froydnj**
These tests all play nicely with Rust 1.16.

### CODE REVIEW

**Comment by froydnj** [comment]
The AppVeyor build failure is due to the following error:

```
failures:
---- message_format_json_forward_stderr stdout ----
	running `C:\projects\cargo\target\i686-pc-windows-msvc\release\cargo.exe rustc --bin foo --message-format JSON -- -Zno-trans`
thread 'message_format_json_forward_stderr' panicked at '
Expected: execs
    but: expected to find:
[WARNING] the option `Z` is unstable [..]
did not find in output:
   Compiling foo v0.5.0 (file:///C:/projects/cargo/target/i686-pc-windows-msvc/cit/t65/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.7 secs
', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    message_format_json_forward_stderr
test result: FAILED. 91 passed; 1 failed; 0 ignored; 0 measured
```

I can push an updated patch with this test switched back to nightly, of course, but I'm curious why it fails for this particular config ("rust 1.17 nightly") and not on my local machine with an older Rust version.

**Comment by alexcrichton** [comment]
Oh that test was actually the inverse, only running on *not* nightly. In that case yeah want to just back out the changes related to that test?

**Comment by froydnj** [comment]
> Oh that test was actually the inverse, only running on not nightly.

Doh!  Thanks for pointing that out.  Pull request rebased and that test left unaltered.  🤞

**Pull request merged**
