### PR TITLE
Metadata: Add changelog field

### LINKED ISSUE #2188: Add "changelog" to Cargo.toml and crates.io
Inspired by [this blog post](https://blog.dbrgn.ch/2015/12/1/rust-crates-keep-a-changelog/), I think it would be a great idea for the `[package]` section in the Cargo.toml to contain a changelog option (as it contains a readme option), and for crates.io to recognise this and have it as a link under "Links", or to somehow reference it under the "versions" links.

### PR DESCRIPTION
**Pull request by dbrgn**
Fix #2188.

This PR adds a "changelog" field to the crate metadata.

There are two ways this field could be used: With a file path (like the README) or with an URL (like the documentation).

I think a changelog is more like documentation than like a README. It contains historic information about the crate. The changelog can be updated later on, if we send the file contents to crates.io these changes won't be integrated. Using an URL would show that it's a "living document".

Sending the file contents to crates.io might be interesting in the future, but it can still be added if there's a need for it.

### CODE REVIEW

**Comment by dbrgn** [comment]
Locally 11 tests fail (even on master). Not sure if I'm doing something wrong.

**Comment by alexcrichton** [comment]
We may want to verify that the changelog file exist for now (like we do with the readme), but I'm somewhat hesitant to move on this just yet without further plans. You can already write down a `changelog = "foo.md"` in your manifest and the only difference after this patch is that it'll not warn when you run `cargo build` by default.

**Comment by dbrgn** [comment]
I would put a link to the changelog below the links for docs and repo on crates.io. I already have a separate pull request for that, but I wanted to wait for this one to become accepted first.

Other links like documentation are not checked for existence either :) (Although they probably should...)

**Comment by alexcrichton** [comment]
In theory though we'd want to treat the README and the CHANGELOG the same way, but today we don't actually do anything with the readme except index it. If a changelog is stored as a file (which I would expect it to traditionally be) then to display it we'd have to start rendering markdown on crates.io which is its own can of worms.

**Comment by alexcrichton** [comment]
I had a change to talk with @wycats about this and the conclusion we came to was:

* We probably don't want to add this yet unless we do something with it. Just adding a key and hoping we manage it later probably isn't what we want to do right now.
* There's often been a desire for custom metadata in Cargo.toml, but Cargo will insist on warning about unused keys. A compromise here might be something like:

```toml
[package.metadata]
foo = "bar"
changelog = "..."
```

Cargo wouldn't warn about anything in `package.metadata`, it'd just opaquely upload it to crates.io and pass it along (for interpretation by other tools). That'd add the ability to add changelogs for now in a way that could be ready by tools if available.

Does that make sense?

**Comment by dbrgn** [comment]
> We probably don't want to add this yet unless we do something with it. Just adding a key and hoping we manage it later probably isn't what we want to do right now.

I agree. But what's the downside of simply showing an URL on crates.io that points  to the changelog?

**Comment by alexcrichton** [comment]
Unfortunately we don't really have a URL to show. The field, if officially supported, probably wants to look like `changelog = "CHANGELOG.md"` except that means that Cargo will have to reconstruct a URL to find the changelog at (or render it on the server), both of which are relatively difficult

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with the `[package.metadata]` section changes!

**Pull request closed without merging**
