### PR TITLE
Fix misspelling of environment variable

### PR DESCRIPTION
**Pull request by AnthonyMikh**

### CODE REVIEW

**Comment by ehuss** [comment]
The man pages need to be rebuilt.  Go to the `src/doc` directory and run the `./build-man.sh` script (documented [here](https://github.com/rust-lang/cargo/tree/master/src/doc#building-the-man-pages)).

**Comment by AnthonyMikh** [comment]
@ehuss Thank you for your guidance.

@rustbot modify labels: -S-waiting-on-author

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
