### PR TITLE
assure broken symlinks don't stop walkdir when cleaning target dirs

### PR DESCRIPTION
**Pull request by Byron**
This issue was encountered in the `git::recompilation()` test which failed as `foo.dSYM` was a link whose target was deleted already.

When passing it to `WalkDir` as root, the expectation is that it is returned as entry, even if it's not a directory, from where it can then be deleted.

Even though `follow_symlinks` is off by default, when the passed in root (which is assumed to be a directory) is a symlink, it tries to obtain its meta-data, and following this broken symlink fails which causes the only returned entry to be an error.

Now we check for this case, which should cost us only in the few cases where files are symlinks, and remove the symlink specifically.

### Motivation

After rebasing onto the latest `master`, the `git::recompilation()` test failed due to this when running tests for #11448 . With his fix all tests work and it seems like a legitimate possibility that `cargo` chokes on broken symlinks (even though this actually happening is new to me).

### Alternatives considered

I thought about raising this as issue for `WalkDir` but thought that given the documentation for [WalkDir::new(...)](https://docs.rs/walkdir/2.3.2/walkdir/struct.WalkDir.html#method.new) this behaviour seems to be intended. The [source here](https://github.com/BurntSushi/walkdir/blob/abf3a15887758e0af54ebca827c7b6f8b311cb45/src/lib.rs#L841-L843) could certainly be adjusted to account for this case, maybe @BurntSushi can chime in.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Yes, it's intended behavior from the perspective of `walkdir`. I think there are two alternatives:

1. Never follow the root as a symlink when `follow_links` is disabled, which would result in `WalkDir` always returning a single `DirEntry` corresponding to the link and nothing else regardless of whether it is broken or not.
2. `WalkDir` still attempts to follow a symlink if it's the root even when `follow_links` is disabled, but if the link is broken is returns a `DirEntry` for the link instead of an error, as if it didn't attempt to follow it at all.

I think the status quo is better than both of those alternatives. Other than (1) being a clear breaking change (which I'm not inclined to do), it is inconsistent with how I think most folks will expect `WalkDir` to behave. Namely, if one _explicitly_ gives it a symlink directly, that in and of itself can be interpreted as the user saying, "yes, please follow it." (Incidentally, `find` has the behavior where if you do `find foo` and `foo` is a symlink, then it won't follow it by default. But if you do `find foo/`, it _will_ follow it. But such a thing is rather subtle.)

For (2), I'm not a fan of that behavior because it covers up the error, and can be difficult to distinguish between an empty directory because of the typical behavior of following the link.

A third possibility is to introduce a `follow_root_link` option and enable it by default, representing the status quo. But when disabled, if the root is a symlink, then it wouldn't be followed. It's backwards compatible and probably a small patch. I'm not a huge fan of it though because it's a rather subtle config knob, but I suppose the behavior is subtle in the first place. Given that such a knob would eliminate some of the extra case analysis here, I think I'd be open to it.

**Comment by Byron** [comment]
Thanks for chiming in and for the thorough analysis! 

> Given that such a knob [(introduction of `follow_root_link` option)] would eliminate some of the extra case analysis here, I think I'd be open to it.

If @ehuss seconds this, I would be submitting such a PR to `walkdir` and adjust this one to bump the version of the `walkdir` crate (or close it if there is a regular dependency update anyway).

Thanks everyone.

**Comment by ehuss** [comment]
If you and @BurntSushi want to go that route, seems fine to me!

**Comment by Byron** [comment]
Great, thank you. I will submit a PR for `WalkDir` and be back with a patch-update of the `walkdir` crate here.

**Pull request closed without merging**
