### PR TITLE
Add git2-curl as a dependency

### LINKED ISSUE #636: Cargo behind a proxy
I am using trying to use Cargo from behind a proxy, and it is unable to fetch external repositories despite having all the appropriate environment variables and configurations.

More specifically, I have the following environment variables set:
```bash
export HTTP_PROXY=proxy.example.com:8000
export HTTPS_PROXY=proxy.example.com:8000
export FTP_PROXY=proxy.example.com:8000
```
along with their lowercase counterparts.  Git and Cargo both have in their configuration:
```ApacheConf
[http]
proxy = proxy.example.com:8000

[https]
proxy = proxy.example.com:8000
```
and `git` from the command line works fine; however, when Cargo attempts to fetch a repository, I encounter
```shell-session
$ cargo build
    Updating git repository `https://github.com/pistondevelopers/piston`
Unable to update https://github.com/pistondevelopers/piston

Caused by:
  failed to fetch into /home/user/.cargo/git/db/piston-10111ca7958cf505

Caused by:
  [2] Failed to connect to github.com: No route to host
```
yet if I run git on its own, it works fine:
```shell-session
$ git clone https://github.com/pistondevelopers/piston
Cloning into 'piston'...
remote: Counting objects: 1959, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1959 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1959/1959), 2.19 MiB | 575 KiB/s, done.
Resolving deltas: 100% (1252/1252), done.
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Due to libgit2 not supporting HTTP proxies, the custom transport API of the
library must be used to reimplement the HTTP transport with proxy support. The
git2-curl crate implements this transport on top of the curl-rust crate. By
using libcurl we gain all sorts of proxy support for free.

This transport is not used by default, however, as it is not well battle tested
and the architecture is not currently ideal (download the entire repo into
memory on a clone). Only when an HTTP proxy is present is the new transport
used.

The other drawback of git2-curl is that it does not currently support
authentication. If a private git repository is cloned or authentication is
required then it will generate an error instead of correctly asking for
credentials.

Closes #636

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @wycats, @brson

**Comment by huonw** [comment]
Maybe you could add a config option to enable this without a proxy? (I'd be happy to enable it to help test, but setting up a proxy is annoying...)

**Comment by alexcrichton** [comment]
Unfortunately if you have a proxy then Cargo doesn't work at all because we use git for the index (which even the registry needs). In that sense this is a strict improvement over what we currently have!

I've been currently testing with:

```
$ ssh -vgND 3128 some-host-with-internet
$ HTTP_PROXY=socks5a://localhost:3128 ./target/x86_64-unknown-linux-gnu/cargo build
```

(using `ssh` as a SOCKS proxy isn't so bad)

**Pull request merged**
