### PR TITLE
Multiple search params

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by jespino** [comment]
This depends on the #2444 PR changes, wait until this PR is finished and merged and then I will rebase it.

**Comment by alexcrichton** [comment]
Looks good to me! Can you add a test for this as well?

**Comment by jespino** [comment]
Ready to merge :smile:

**Comment by jespino** [comment]
Tests works on my machine, I have to review it.

**Comment by alexcrichton** [comment]
@bors: r+ 6b7c2a8144ce060a6cb01eb06eb0e5dd20729b29

Thanks!

**Pull request merged**
