### PR TITLE
--workspace flag for locate-project to find the workspace root

### PR DESCRIPTION
**Pull request by dtolnay**
<pre>
<i>/git/serde/serde_derive</i>$ <b>cargo locate-project</b>
{"root":"<a href="https://github.com/serde-rs/serde/blob/master/serde_derive/Cargo.toml">/git/serde/serde_derive/Cargo.toml</a>"}

<i>/git/serde/serde_derive</i>$ <b>cargo locate-project --workspace</b>
{"root":"<a href="https://github.com/serde-rs/serde/blob/master/Cargo.toml">/git/serde/Cargo.toml</a>"}
</pre>

### CODE REVIEW

**Comment by alexcrichton** [comment]
Seems reasonable to me!

FWIW `cargo locate-project` was probably one of the very first commands added to Cargo (I didn't even add it, it was already there when I started!) and has basically been untouched ever since then, so there's a huge amount of room for improvement I would imagine.

@rfcbot fcp merge

**Comment by ehuss** [comment]
Thanks!
@bors r+

**Comment by dtolnay** [comment]
- Rebased to resolve conflict with #8707

**Pull request merged**
