### PR TITLE
Update lockfile for gcc and cmake crates to pick up MSVC 2017 fixes

### PR DESCRIPTION
**Pull request by brson**
Seems to work.

### CODE REVIEW

**Comment by brson** [comment]
I'm going to keep investigating problems on x86

**Comment by brson** [comment]
I guess it's worth trying to land this.

**Comment by brson** [comment]
For some reason I cannot build either rustup or cargo inside a vs2017 "x86 Native Tools Command Prompt" using curl-sys 0.3.11. If I override it with curl-sys from git both build. The error is 'module machine type 'x64' conflicts with target machine type 'X86'.

FWIW [here](https://github.com/rust-lang-nursery/rustup.rs/pull/1136) is the rustup pr that is failing on i686.

**Comment by brson** [comment]
I'm surprised this succeeded on i686-msvc...

**Comment by alexcrichton** [comment]
Eh let's see what CI says:

@bors: r+

**Pull request merged**
