### PR TITLE
add default implementations

### PR DESCRIPTION
**Pull request by danieleades**
this will need a review.
i guess it's a matter of taste whether the `Default` implementation should *replace* a "new-without-args" method, or whether the `new` method should *delegate* to the `Default` implementation.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you expand on the rationale for this change? I personally find `::new` more idiomatic where it's already implemented.

**Comment by danieleades** [comment]
> Could you expand on the rationale for this change? I personally find `::new` more idiomatic where it's already implemented.

The motivating case here is the simplification in `src/cargo/ops/cargo_config.rs` (`unwrap_or_default`).

Other than that, you save a couple of lines by deriving Default for trivial cases.

I can reinstate the 'new' methods, and have them delegate to the Default implementations.

**Comment by alexcrichton** [comment]
Could this perhaps just fix that one instance in that case? I don't think it's necessary to remove existing code and switch to `Default`

**Comment by danieleades** [comment]
> Could this perhaps just fix that one instance in that case? I don't think it's necessary to remove existing code and switch to `Default`

done

**Comment by ehuss** [comment]
I'm going to close, as I don't see this as a particular improvement. I would prefer to not have two ways of doing the same thing.

**Pull request closed without merging**
