### PR TITLE
Delete Cargo.lock from this repo

### PR DESCRIPTION
**Pull request by alexcrichton**
There's now a lock file upstream in rust-lang/rust so the one here isn't
actually used, and otherwise this crate is used as a dependency so the lock file
isn't respected anyway!

### CODE REVIEW

**Comment by matklad** [comment]
Ok, so this is how it works now, right?

1) In rust-lang/rust repo, cargo is included as a submodule under tools/cargo.
2) It is also included as a workspace member, which gives it the actual lockfile.
3) When filing a PR against rust-lang/rust, Cargo test suite is executed. Also, RLS, which depends on Cargo, is tested as well. 
4) When filing a PR against rust-lang/cargo, RLS **is not** tested. Only when the Cargo submodule is updated we'll learn if it actually works.

I am a bit worried about two things:

1) Looks like CI for Cargo now is not actually complete, because ideally we'd want to test with rust-lang/rust lockfile.

2) Including Cargo as a workspace member does not seem entirely right for me because in theory Cargo should be a complete separate piece of software, with its own lockfile, and it could be a workspace itself even.


Not that I think there will be any real significant problems because of this, so r+ from me! (but there's a merge conflict).

**Comment by alexcrichton** [comment]
@matklad you're correct on all counts! It's true that Cargo's CI is less comprehensive than Rust's, and it's true that different versions of dependencies are used. That being said though I think it's an undesriable goal for the two to exactly match up. The Rust CI is *very* comprehensive and trying to match it on Cargo likely mostly just amount to a waste of resources. 

It's true that from time to time we'll have a bug sneak in that will make updating the submodule in rust-lang/rust more difficult (especially with the RLS) but so far it hasn't been too much of a problem in practice and I'd probably expect that to stay mostly the same over time.

**Comment by alexcrichton** [comment]
Oh also note that we use a workspace with Cargo to ensure that we only build Cargo once with one the same version of all deps between the RLS and Cargo itself.

**Pull request merged**
