### PR TITLE
Bugfix/crt static in config

### PR DESCRIPTION
**Pull request by ohadravid**
I ran into an issue when compiling xz2 crate under Windows, where .cargo/config RUSTFLAGS does not set the correct env vars in the build (full details can be found at 
https://github.com/alexcrichton/xz2-rs/issues/46).

The problem seems to be that an empty env var will take precedence over the config file.

Cargo version is:
cargo 1.34.0-nightly (5c6aa46e6 2019-02-22)

I added a test for this and a small fix.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this @ohadravid!

I'm gonna run this by others on @rust-lang/cargo since this is a beahvioral change, but I think this is a reasonable semantics for Cargo to implement. Cargo doesn't necessarily uniformly handle empty env vars though, so I'd be curious about others' thoughts on that

@rfcbot fcp merge

**Comment by Eh2406** [comment]
So how do you override a config file and use the defaults after this change?

**Comment by ohadravid** [comment]
I can change the code so it's possible to differentiate between an empty string and some whitespace and treat whitespace as the 'default', but this would be very confusing for users (breaks the common expectations around environment variables).

Also as a user, I think of whatever's in the config file is the 'default'. If I want something else I'll probably grab whatever in there and add something. For example I have a crate which is built against a static lzma.so file, and trying a 'default' (==empty) flags will break the build.

It's worth noting that the current behavior for the 'build.rs' file is inconsistent: cfg(crt-static) is enabled (respects the config file), but CARGO_CFG.. is not set.

**Comment by ohadravid** [comment]
@Eh2406 @alexcrichton something wasn't quite right, since the bug I saw didn't actually allow for the default flags to be passed.
I created a [test](https://github.com/rust-lang/cargo/pull/6736/commits/d6942804e524d1419c99a619f4754149ecea7fdb#diff-ef01b055e60dc8e7369538de948ccf93R1439) which reproduces this (but which is NOT fixed by my change). 
This actually has nothing to do with empty env args.

If you run it, it will actually fail in the [second assert](https://github.com/rust-lang/cargo/pull/6736/commits/d6942804e524d1419c99a619f4754149ecea7fdb#diff-ef01b055e60dc8e7369538de948ccf93R1473).

```rust
fn main() {
    // The crt-static feature should be enabled.
    #[cfg(not(target_feature = "crt-static"))]
    assert!(false);
    
    assert!(std::env::var("CARGO_CFG_TARGET_FEATURE").unwrap().contains("crt-static"));
}
```

(Changing the `[target(cfg...)]` to `[target]` will not trigger the bug).


I'm not really sure what to do, since `requested_target` in `build_context/mod.rs:env_args` seems to be set, but this seems like a contradiction (either both feature and env var should be set, or both shouldn't).

**Comment by alexcrichton** [comment]
Sorry I don't know off the top of my head what's going on, so I'd have to dig in, but I don't have time right now to do so

**Pull request closed without merging**
