### PR TITLE
update to recent rust changes

### PR DESCRIPTION
**Pull request by suhr**
A story about how I just wanted to build fresh cargo.

Question about errors.rs: implementation of `fmt::Display` for `Box<CargoError>` uses `self.description()`, but `detail()` method uses `(**self).detail()`. Since `detail()` is deprecated in favor of `fmt::Display`, what exactly should be used?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! This will also need to update `src/rustversion.txt` to update the pinned version of the compiler. I believe this can also remove `fn detail` entirely and just rely on `Display` for the detail aspects.

**Comment by suhr** [comment]
No `Display` implementation changes required?

**Comment by suhr** [comment]
I've got a strange error:
```
cargo/util/errors.rs:15:41: 15:51 error: explicit lifetime bound required [E0228]
cargo/util/errors.rs:15 pub type CargoResult<T> = Result<T, Box<CargoError>>;
                                                                ^~~~~~~~~~
```
Lifetime bounds on boxed trait objects? Why? And... how?

**Comment by alexcrichton** [comment]
Ah it's ok, I'll put these commits in and take over from here, there may be some deeper changes involved here.

**Pull request merged**
