### PR TITLE
Add missing warning handling flag to cargo build

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by killercup** [comment]
@spacekookie notified me [earlier](https://twitter.com/spacekookie/status/980431373122129921) that this was missing from cargo. I hope this helps align cargo's CLI interface with that of rustfix.

**Comment by matklad** [comment]
I am we can’t accept the patch as written, because it does not handle [RFC2378](https://github.com/rust-lang/rfcs/pull/2378).

**Comment by killercup** [comment]
Looks like we've missed the merge window this year. Will try again in 364 days.

**Comment by spacekookie** [comment]
Nooooooooooooooooooooooooooooooooooooooooooo! :sob:

**Pull request closed without merging**
