### PR TITLE
Disable RUSTC_BOOTSTRAP in build.rs

### LINKED ISSUE #7088: Forbid setting `RUSTC_BOOTSTRAP` from a build script
Currently, crates can set environmental variables, including `RUSTC_BOOTSTRAP`, from a `build.rs` file, thus subverting **current** stability guarantees. Cargo and, if that's feasible, crates.io additionally should forbid doing so.

This was originally discussed in https://github.com/rust-lang/cargo/pull/6608 and https://github.com/rust-lang/cargo/issues/6627, both of which are closed, so I thought it would be helpful to create this issue!

### PR DESCRIPTION
**Pull request by notriddle**
Closes #7088

### CODE REVIEW

**Comment by notriddle** [comment]
Never mind. Sorry for the noise. I didn't realize there was already a commit for this [made by a Cargo team member](https://github.com/jyn514/cargo/commit/dd7dff9b55c8ae5cd02fbe47474bcb3cc9b7670f).

**Comment by RalfJung** [comment]
There's such a commit but it does not seem to be in any PR or branch?

**Comment by RalfJung** [comment]
Cc @jyn514

**Comment by jyn514** [comment]
I am not a cargo team member and I am not comfortable making a change like this. Feel free to reuse my code, but I won't be making a PR with it.

See https://zulip-archive.rust-lang.org/233931tcompilermajorchanges/42684RequireuserstoconfirmtheyknowRUSTCcompilerteam350.html#208403654 for more discussion.

**Pull request closed without merging**
