### PR TITLE
Update to rust-url 1.0

### PR DESCRIPTION
**Pull request by SimonSapin**
**Do not merge yet:** rust-url 1.0 is not published yet and may still get breaking changes.  The goal of this PR for now is to demonstrate API usage.

Depends on https://github.com/servo/rust-url/pull/176 and https://github.com/alexcrichton/git2-rs/pull/115

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks @SimonSapin!

**Comment by alexcrichton** [comment]
Thanks again for the PR @SimonSapin! I'm gonna close this for now but we can reopen/resubmit once rust-url 1.0 is out

**Comment by lilianmoraru** [comment]
@alexcrichton `rust-url` is at version `1.0.0`(`1.0.1` in master)

**Comment by SimonSapin** [comment]
This depends on functionality that I ended up removing from url 1.0 and plan to add back in 1.1 soon: https://github.com/servo/rust-url/issues/188 

I’ll resubmit this PR once that’s done.

**Pull request closed without merging**
