### PR TITLE
Better error message for `cargo rustc` in a workspace.

### LINKED ISSUE #5371: `cargo rustc` in root of workspace gives wrong error
If you run `cargo rustc` (or `cargo rustdoc`) in the root of a workspace, you get the following error:

```error: manifest path `/path/to/ws` contains no package: The manifest is virtual, and the workspace has no members.```

However, the workspace does have members!  I think it should instead show something like the error message from `Workspace::current` (```manifest path `{}` is a virtual manifest, but this command requires running against an actual package in this workspace```).

I can fix this if you'd like.

### PR DESCRIPTION
**Pull request by ehuss**
Fixes #5371

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by ehuss** [comment]
@alexcrichton Do we know why the test failed?

**Comment by alexcrichton** [comment]
@ehuss oh the appveyor failure is a known spurious failure we just haven't gotten around to diagnosing yet

**Pull request merged**
