### PR TITLE
[doc/book] Add introduction page and other enhancements

### PR DESCRIPTION
**Pull request by behnam**
Preview: http://code.behnam.es/rust-cargo/book/

* Reorganize files to use folders instead of numbered files. This will allow us to add new sections and pages without breaking a numbering system or the URLs.

* Rename "Cargo In Depth" to "Cargo Reference", as those pages are considered *the* reference for cargo behaviors.

* Add `introduction.md`, as the landing page with the book title and Cargo logo on top.

* Expand `installation.md`: Import install text and links from <https://crates.io/install>, as we
want to drop that page and redirect it to here. (See <https://github.com/rust-lang/crates.io/issues/1029>)

* Sync `SUMMARY.md` titles (and sub-pages lists in section pages) with page titles and fix some wordings and casings.

* Expand Introduction and section pages with some intro text.

* Set lang for some of the code blocks.

* Add `book.toml` to get the title in HTML head title, etc.

Tracker: <https://github.com/rust-lang/cargo/issues/4040>

### CODE REVIEW

**Comment by behnam** [comment]
cc @alexcrichton, @carols10cents, @istankovic, @steveklabnik.

**Comment by steveklabnik** [comment]
This is so awesome, thank you so much for working on this stuff!

**Pull request merged**
