### PR TITLE
fix: add space to comments

### PR DESCRIPTION
**Pull request by Rustin-Liu**

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks! Looks like some tests need to be updated?

**Comment by Rustin-Liu** [comment]
> Thanks! Looks like some tests need to be updated?

Fixed it. PTAL~ Thanks!

**Comment by Rustin-Liu** [comment]
@ehuss Ping~

**Comment by ehuss** [comment]
@bors retry
```
Err:34 https://storage.googleapis.com/bazel-apt stable/jdk1.8 amd64 Packages
  Writing more data than expected (28234 > 27800)
```
Which I think means the apt repos are out of sync.

**Pull request merged**
