### PR TITLE
Disable LTO for host (plugin, build script) builds

### PR DESCRIPTION
**Pull request by cyndis**
When building host code, -C prefer-dynamic is passed, but that option
is mutually exclusive with -C lto. Thus when LTO is specified, rustc
errors out.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you add a test for this as well?

**Comment by cyndis** [comment]
Here's a test. Travis failure doesn't seem related.

**Comment by alexcrichton** [comment]
@bors: r+ a79c7ea 

Thanks!

**Comment by cyndis** [comment]
Thanks :)

**Pull request merged**
