### PR TITLE
Add --reinstall argument to the install option

### PR DESCRIPTION
**Pull request by vityafx**
The --reinstall option simply uninstalls the package before installing
it so the user need not run uninstall and then install. This also updates the
package since install always look for a new version.

### CODE REVIEW

**Comment by vityafx** [comment]
Tired of doing the same work.
#2082 
https://stackoverflow.com/questions/48438783/is-there-a-way-to-update-a-binary-package

**Comment by sfackler** [comment]
How is this different from `cargo install --force`?

**Comment by vityafx** [comment]
@sfackler Good question. I have told by many people that the `--force` and uninstall and then install is different. Is not that true?

**Comment by sfackler** [comment]
How were they claiming it was different?

**Comment by vityafx** [comment]
[No way](https://github.com/rust-lang/cargo/pull/2405). I should go and sleep. I read an old answer on the stackoverflow yesterday which told that there is no such a way and then the other guy told the same but it seems he did not know the answer himself. Sorry for bothering :)

**Pull request closed without merging**
