### PR TITLE
Support relative paths for registries

### LINKED ISSUE #2252: Support relative paths for registries
I have a use case where I need a local registry. I currently do this by editing `.cargo/config` and specifying the absolute path to the registry:

``` toml
[registry]
index = "file:///Users/me/blah/registry/git"
```

Because the path is absolute, this means I can't really check in `.cargo/config` since the paths may differ for my peers. This has a couple of problems:
1. Without this file present, cargo doesn't work (because it won't have the custom registry). Cargo has become a standard integration point for editors, so this means that people can't even edit the project without having errors.
2. http://doc.crates.io/config.html - there are some options there I might want to check in that are specific to the project.

If I specify a relative path, e.g.:

``` toml
[registry]
index = "registry/git"
```

Then I get:

```
$ cargo build --verbose
failed to parse manifest at `/Users/..../Cargo.toml`

Caused by:
  invalid url `registry/git`: relative URL without a base
```

According to https://github.com/servo/rust-url/blob/2aa249b5bbc462e5582735bdae76a27acc9d70fd/src/lib.rs#L115, this can be fixed by adding a `base_url` to the `UrlParser` that is used in cargo/src/cargo/util/to_url.rs

---

Instructions to fix this added by @carols10cents:

- Check out the code from [this PR](https://github.com/rust-lang/cargo/pull/2253) 
- Rebase it on master, fix any git merge conflicts and make any updates to code that's changed a lot in the meantime
- Add some tests around the behavior in that PR 
- Resubmit!

### PR DESCRIPTION
**Pull request by fluffysquirrels**
Closes #2252

I haven't finished the tests for this yet as I wasn't sure what was necessary. Is it OK to just test through `registry_configuration()` in `src/cargo/ops/registry.rs` or are integration tests required? If integration tests then I'm not sure what cargo sub-command I can run without a real remote registry to play with; any thoughts?

### CODE REVIEW

**Comment by fluffysquirrels** [comment]
I wrote a few integration tests for this.

**Comment by ehuss** [comment]
I'm a little concerned about changing the definition of `registry.index` to a URL *or* file path.  Can we keep it strictly URLs only?  I think `file:` URLs should work with relative paths (for example `file:alternative-registry`, which seems to work as-is in this PR).  Perhaps just do `Url::parse()` on the value just to verify that it is a url before passing it to `Url::options()`.

**Comment by fluffysquirrels** [comment]
@ehuss ,

OK, makes sense to me, I'll push an update.

Today I learned about relative URLs with a `file:` protocol prefix!

**Comment by fluffysquirrels** [comment]
@ehuss, I've pushed a new version with your suggestions.

**Comment by ehuss** [comment]
Thanks!
@bors r+

**Pull request merged**
