### PR TITLE
Revert template until after rfc

### PR DESCRIPTION
**Pull request by ehiggs**
As discussed in #3860, templates was merged without going through the RFC process. @ssokolow has raised some useful comments which need to be settled before the template system can be put back in.

#3859 was another relevant issue.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @ehiggs for staying on top of this! If you need any help writing an RFC please just let me know, I'd be eager to see this in Cargo :)

**Comment by alexcrichton** [comment]
@ehiggs oh so some further steps we'll need to take on this are:

* Send a PR to the `rust-1.17.0` branch of this repo with these same contents
* Send a PR to rust-lang/rust to update the cargo submodule on rust's `master` branch
* Send a PR to rust-.ang/rust for the `beta` branch as well

I certainly don't mind doing these as well, but if you're interested in learning the process it's just a few PRs and I'd also be more than happy to r+!

**Comment by ehiggs** [comment]
Ok, I'll take a look at doing this.

**Comment by ehiggs** [comment]
homu job failed with `error: component download failed for rust-std-mipsel-unknown-linux-gnu`. Seems a transient failure.

**Comment by ehiggs** [comment]
Is this number of retries normal?

**Comment by alexcrichton** [comment]
Not really, sometimes @bors just really doesn't like us :(

**Comment by ehiggs** [comment]
Pre-rfc thread is [here](https://internals.rust-lang.org/t/pre-rfc-cargo-templates/5056)

**Pull request merged**
