### PR TITLE
beta: revert #8640 - rustdoc versioning checks

### PR DESCRIPTION
**Pull request by ehuss**
#8640 has been causing some problems with rustbuild (see https://github.com/rust-lang/rust/issues/83914 and https://github.com/rust-lang/rust/pull/83530#issuecomment-813522824).  In order to give more time to figure out a solution, this reverts the change on beta.  Will need to take some time to figure out what to do on master.

Also cherry picked the following to get tests passing:
* #9316 — Fix semver docs for 1.51.
* #9307 — tests: Tolerate "exit status" in error messages

### CODE REVIEW

**Comment by ehuss** [comment]
cc @CPerezz FYI.

**Comment by CPerezz** [comment]
Thanks for the ping @ehuss. It's pretty unfortunate.. Anything I can help on?

**Comment by jyn514** [comment]
@CPerezz a less invasive version of https://github.com/rust-lang/cargo/pull/8640 would be to use `--resource-suffix` by the toolchain instead.https://github.com/rust-lang/cargo/issues/8461#issuecomment-813259223

**Comment by ehuss** [comment]
I'm concerned that `--resource-suffix` may have its own issues.  It would cause resource files to accumulate in the doc directory with a myriad of different suffixes. It would also mean that when different packages are documented with different versions, they won't know about each other (like the search indexes will be wrong on one side or the other).  I'm also uncertain how that works with `crates.js`, which would mean the crates listings could be out of sync.

None of those are deal breakers on their own, but I'd like to consider other options if possible.

**Pull request merged**
