### PR TITLE
fix name escaping issue in Cargo.toml (#1635)

### PR DESCRIPTION
**Pull request by Roysten**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I think this may not be the best place to fix this, however, as it's only relevant for [writing out the TOML file](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs#L152). I also think there's a number of other characters which need to be escaped as well.

This functionality also exists in [toml-rs](https://github.com/alexcrichton/toml-rs/blob/master/src/display.rs#L41-L56), so it may be good to leverage that support as well (e.g. via `toml::Value::String(val)`)

**Comment by alexcrichton** [comment]
Ah, and could you also add a test for this change?

**Comment by Roysten** [comment]
@alexcrichton I addressed your remarks. Not sure why the build failed though... (works on my end).

**Comment by alexcrichton** [comment]
Ah travis is occasionally a little flaky, so a failure in one of the two builds there typically doesn't mean much. Could you also squash these commits together? Other than that looks great to me, thanks!

**Comment by Roysten** [comment]
Done! Thanks for your help :)

**Pull request merged**
