### PR TITLE
Stabilize fix --clippy

### PR DESCRIPTION
**Pull request by yaahc**
follows https://github.com/rust-lang/cargo/pull/7382

### CODE REVIEW

**Comment by yaahc** [comment]
Possibly blocking on https://github.com/rust-lang/rust-clippy/issues/3630

**Comment by Manishearth** [comment]
cc @oli-obk @phansch @flip1995 What do y'all think we should do to get to a stage where we can stabilize this? An easy answer is to remove MachineApplicable from most lints in https://github.com/rust-lang/rust-clippy/issues/3630 , which I don't like but I don't hate it either.

I'm going to slowly work my way through the list.

**Comment by oli-obk** [comment]
CI is only failing due to an unused import in tests/testsuite/fix.rs

> What do y'all think we should do to get to a stage where we can stabilize this? 

Yea, having `MachineApplicable` only on lints we know to be good seems like the right choice.

**Comment by phansch** [comment]
> What do y'all think we should do to get to a stage where we can stabilize this?

Yeah, I also think that would be the best solution in the short term. I'd very much like to see `cargo clippy --fix` being a pleasant experience from the start. I think even if we only start with a handful of selected lints as `MachineApplicable` that would be much better than incorrect suggestions.

**Comment by Manishearth** [comment]
Okay, how about we punt on this until after the next rust release (sept 26)? That way this doesn't make it into beta in a broken state.

By then, _hopefully_ I'll have that list burned down quite a bit, and we can mark any stragglers as inapplicable.

**Comment by Manishearth** [comment]
(Beta is cut early so we may be able to merge before sept 26)

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust-clippy/issues/3630 is now closed, so this is unblocked from the clippy side.

r? @ehuss

**Comment by alexcrichton** [comment]
Ah if this is ready to be stabilized, perhaps it's best included in https://github.com/rust-lang/cargo/pull/7382?

**Comment by Manishearth** [comment]
I'm okay with either, both of these changes are theoretically independent release-wise, they just share a ton of code (and releasing one will require small tweaks to the PR for the other). It might be worth releasing this separately.

**Comment by Manishearth** [comment]
@ehuss should we try and get this stabilized first? There may be fewer UX requirements and these actually seem pretty independent.

**Comment by ehuss** [comment]
The Cargo team discussed this, and we'd like to propose the following alternative, considering some of the concerns in #7382.

A change would be made to Cargo to allow `cargo fix` to use an alternate `rustc`. I'm not sure, but I believe the fix would be small (updating [this line](https://github.com/rust-lang/cargo/blob/3a9abe3f065554a7fbc59f440df2baba4a6e47ee/src/cargo/ops/fix.rs#L133) to call something like `get_tool("rustc")` instead). I haven't deeply considered the implications, but seems plausible.

The `cargo-clippy` plugin could then add a `--fix` flag. In this mode, `cargo-clippy` would set the `RUSTC` environment variable to itself and call `cargo fix` instead of `check`.

Due to the recent fixes @yaahc implemented, I think this should work, and clippy will only run for the "primary" crates. In my quick tests, it seems to work.

How does this plan sound to everyone?

**Comment by Manishearth** [comment]
This plan sounds fine provided:

 - it indeed only runs for the primary crates
 - it doesn't clobber metadata

**Comment by Manishearth** [comment]
presumably by RUSTC you meant PRIMARY_RUSTC. that works.

**Comment by ehuss** [comment]
> presumably by RUSTC you meant PRIMARY_RUSTC. that works.

Nah, it would just be `RUSTC`.  The fix code already is restricted to the primary units [here](https://github.com/rust-lang/cargo/blob/3a9abe3f065554a7fbc59f440df2baba4a6e47ee/src/cargo/ops/fix.rs#L138).

**Comment by Manishearth** [comment]
@ehuss won't that affect the normal metadata builds of previous crates, though? I guess I should poke at the impl, if you say it won't break things that's fine by me :smile:

**Comment by ehuss** [comment]
In @yaahc's work, it was changed so that `cargo fix` does a normal "check" for all dependencies, and then only engages the "cargo as rustc wrapper" for the primary crates.  That's what the linked line does, and I *think* it should be ok.

**Comment by jyn514** [comment]
> The `cargo-clippy` plugin could then add a `--fix` flag. In this mode, `cargo-clippy` would set the `RUSTC` environment variable to itself and call `cargo fix` instead of `check`.

This seems rather unfortunate - it means the interface for `fix` is different for clippy than for everything else. Can you expand a little more on why the cargo team chose to have clippy implement it that way?

**Comment by ehuss** [comment]
Sorry for the late response on the reasoning: Cargo doesn't know that clippy exists, or how to run it. We have somewhat intentionally kept these separate since it is a separate project.

**Comment by jyn514** [comment]
What makes clippy different from rustfmt here?

**Comment by ehuss** [comment]
I'm not sure I understand the question. `cargo fmt` is also a separate tool, independent of cargo.

**Comment by jyn514** [comment]
Ok then, what makes clippy different than rustdoc?

**Comment by ehuss** [comment]
Because for rustdoc to work, cargo needs intimate knowledge of how to integrate with it (there are multiple dependency edges within a package, different fingerprinting requirements, special rules specified in `Cargo.toml`, etc.). Clippy does not, since its interface is identical to rustc, and does everything rustc does.

**Pull request closed without merging**
