### PR TITLE
Cargo book nitpick in Manifest section

### LINKED ISSUE #8541: Cargo book documentation nitpick in Manifest-Edition section
Currently in the Cargo Book, precisely in https://doc.rust-lang.org/cargo/reference/manifest.html#the-edition-field, the edition of the example is correct (`2018`) but the text above has the previous one (`2015`) which as far as I know is no longer the default used when you use `cargo new`.

### PR DESCRIPTION
**Pull request by CPerezz**
The Manifest section states on the example that the
default edition is 2018, but the lines of text above
state that the default is `2015` which is not correct.

Closes #8541

### CODE REVIEW

**Comment by ehuss** [comment]
This is incorrect, would you mind reverting it?  The [default is 2015](https://github.com/rust-lang/cargo/blob/d3360add8aee9fdc0cfb8f4be4fc344241a0be96/src/cargo/util/toml/mod.rs#L1040).  The examples aren't there to show the defaults (for example, the `description` doesn't default to `"A short description of my package"`), they are just there to show an example.

**Comment by CPerezz** [comment]
If you create a new lib with the latest stable with `cargo new --lib whatever` it comes wifh the edition 2018. 

That's why I did the change@ehuss

**Comment by ehuss** [comment]
Yes, the default for `cargo new` is 2018 (and specified in the [docs](https://doc.rust-lang.org/cargo/commands/cargo-new.html)).  The default in the manifest if the edition is not specified is 2015.

**Comment by CPerezz** [comment]
My apologies then. 
Sorry for the inconvenience.

**Comment by Eh2406** [comment]
I to apologize, I should have read more carefully before reviewing.

**Comment by Eh2406** [comment]
@CPerezz do you want to make a PR fixing it back or would you like me to?

**Comment by CPerezz** [comment]
I'll do it!
And again, sorry for the inconvenience.

El dl., 27 de jul. 2020, 21:10, Jacob Finkelman <notifications@github.com>
va escriure:

**Pull request merged**
