### PR TITLE
Add tests for ignoring symlinks

### PR DESCRIPTION
**Pull request by jonhoo**
This adds tests for the expected behavior in https://github.com/rust-lang/cargo/issues/10032. Interestingly, these tests pass (🎉). Will update that issue with more details shortly, but figured these tests were worthwhile to add to the testsuite anyway now that I've written them.

### CODE REVIEW

**Comment by jonhoo** [comment]
The Windows failure here is surprising. It suggests that on Windows, Cargo considers the symlinks files, not directories, and thus they don't match `/symlink/`. Probably around here
https://github.com/rust-lang/cargo/blob/b74705419e39b206b326ce1e6187ad7c383dcb0e/src/cargo/sources/path.rs#L395-L396

Even though the [docs for `Path::is_dir`](https://doc.rust-lang.org/std/path/struct.Path.html#method.is_dir) pretty clearly state
> This function will traverse symbolic links to query information about the destination file.

🤔 

Given that I don't have a Windows computer handy to debug with, I think this has me stomped for now.

I'll just add that the fix I had originally intended for #10032 is
```rust
        let is_dir = path.is_dir();

        // Symlinks that point to directories are a little odd because they are both directories
        // _and_ files for the purposes of matching. At least as far as Cargo is concerned, since
        // we never include symlinks directly in the pacakge. The actual rules are:
        //
        //  1. A pattern of `/symlink` should match the symlink itself.
        //  2. A pattern of `/symlink/` should match the symlink's target's contents.
        //
        // But for us, this means that if a directory symlink is excluded as either a directory
        // _or_ a file, it should be skipped.
        if !is_root && is_dir {
            let is_symlink = path.symlink_metadata()?.file_type().is_symlink();
            // See if the symlink is filtered out when viewed as a file -- if so, skip it.
            // The directory case is handled by the regular logic below.
            if is_symlink && !(*filter)(path, false)? {
                return Ok(());
            }
        }

        if !is_root && !(*filter)(path, is_dir)? {
```
which _may_ come in handy for whoever decides to try tackling this.

**Comment by ehuss** [comment]
I believe the issue here is with libgit2.  When creating the repository, the [`add_all`](https://docs.rs/git2/latest/git2/struct.Index.html#method.add_all) function ends up adding the symbolic links to the repo. There is something about libgit2's gitignore implementation that is not honoring symlinks as directories.  I have opened https://github.com/libgit2/libgit2/issues/6250 with a reproduction.

If you want to just disable these tests on Windows, I think it would be fine.

**Comment by jonhoo** [comment]
Pushed a change that ignores the test on Windows 👍

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
