### PR TITLE
Add more missing `strip` info to docs.

### PR DESCRIPTION
**Pull request by nnethercote**
This is a follow-up to #12748.

### CODE REVIEW

**Comment by nnethercote** [comment]
The default values in #12748 were `strip = false` but the pre-existing entry moved here has `strip = "none"`. I don't know which is preferable, but consistency would be good.

**Review by hi-rustin — APPROVED** [review]
LGTM Thanks!

**Review by weihanglo — COMMENTED** [review]
> The default values in #12748 were `strip = false` but the pre-existing entry moved here has `strip = "none"`. I don't know which is preferable, but consistency would be good.

If there is a pre-existing `strip = "none"`, could you help update change in <https://github.com/rust-lang/cargo/pull/12748> to `"none"`?

**Comment by nnethercote** [comment]
> If there is a pre-existing `strip = "none"`, could you help update change in #12748 to `"none"`?

Done. I also added a tiny new commit that changes some `* default: ...` entries to `* Default: ...` for consistency with other such entries.

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Thank you!

@bors r+

**Pull request merged**
