### PR TITLE
Show new version of package on overwrite error

### LINKED ISSUE #3587: `cargo install` should tell the available version when already installed
Currently, when trying to install an already-installed crate, we get:
```
$ cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: binary `cargo-fmt` already exists in destination as part of `rustfmt v0.4.1`
```
This tells me the currently installed version of rustfmt, but not which version it would be replaced with when I specify `-f`. This would be interesting especially to know if there is an updated version at all.

When the crates cache is not populated with the new version, we get
```
$ cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt v0.7.1
error: binary `cargo-fmt` already exists in destination as part of `rustfmt v0.4.1`
```
which is helpful, but accidental.

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes #3587

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I wonder if this could perhaps use a status message like "Installing ..." like other status messages? This seems like useful information regardless of whether there was an error or not.

**Comment by birkenfeld** [comment]
Good point. Will update the PR later.

**Comment by birkenfeld** [comment]
Updated. The tests seemed to pass (actually, I had a spurious failure in `build_deps_for_the_right_arch`, should I open an issue?) without modification. Are the `shell()` outputs checked somewhere?

**Comment by alexcrichton** [comment]
Looks like the failures on Travis may need fixing? I don't think we have any currently spurious failures, or at least not that I know of.

**Comment by alexcrichton** [comment]
oops didn't mean to close!

**Comment by birkenfeld** [comment]
Indeed, should be fixed now.

**Pull request merged**
