### PR TITLE
Fix typos “a”→“an”

### PR DESCRIPTION
**Pull request by steffahn**
See rust-lang/rust#88230

### CODE REVIEW

**Comment by steffahn** [comment]
I don’t understand this test failure.

**Comment by Eh2406** [comment]
Looks good.

@bors r+

**Comment by ehuss** [comment]
I'm investigating the test error.  There is some strange issue with serde deserialization, and I'm not sure what changed.

**Comment by steffahn** [comment]
Am I simply misinterpreting [the bors queue](https://bors.rust-lang.org/queue/cargo) or is this PR indeed for some reason not on there?

**Comment by steffahn** [comment]
> I mean it is on there, but not as "approved"

Haha, of course it wasn’t since I’ve added more commits since the last r+.

**Pull request merged**
