### PR TITLE
ensure libressl compatibility

### PR DESCRIPTION
**Pull request by Keruspe**
It looks like master still isn't compatible with libressl.

With this patch it builds and runs fine and all tests pass here.

### CODE REVIEW

**Comment by sfackler** [comment]
Looks like there's a failing test: https://ci.appveyor.com/project/rust-lang-libs/cargo/build/1.0.1090/job/e46hxokw069u5kc8

**Comment by Keruspe** [comment]
The failing test is *really* awkward and looks like a problem on the appveyor side somehow.

This seems to be the only place where User-Agent is constructed in libgit2 and the commit that changes form Git/1.0 to Git/2.0 doesn't make it conditionally: https://github.com/libgit2/libgit2/commit/fafafb1f37 (this commit is part of libgit2-sys 0.6.6).

It's rather suspicious that out of 4 tests on appveyor, 1 gets that weir error and the 3 others consider that nothing needs actual testing, isn't it?

**Comment by alexcrichton** [comment]
The three other entries in the AppVeyor matrix are skipped for PRs, which is why they passed. We'll need to update this PR somehow to allow it to land by passing tests on AppVeyor

**Comment by Keruspe** [comment]
Ok, I actually found the problem, alongside "http.c" in libgit2 there is a "winhttp.c" which has the 1.0 in it.

**Comment by Keruspe** [comment]
Is there a way to get this backported as well? Should I open other pull requests for the other branches?

**Comment by alexcrichton** [comment]
Sure yeah, you can just send a PR to the rust-1.16.0 branch

**Pull request merged**
