### PR TITLE
refactor(job_queue): docs and move types around

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Refine module-level documentation for `job_queue`, and trying to move types to proper places.

- `job_queue.rs` -> `job_queue/mod.rs`
- `job.rs` -> `job_queue/job.rs`
- `JobState` -> `job_queue/job_state.rs`

### How should we test and review this PR?

Run `cargo doc --document-private-items --no-deps --open` to proofread the doc.

This shouldn't affect anything. Only one thing need to make sure it doesn't go wrong. The major logic of [`doit`](https://github.com/rust-lang/cargo/blob/7ddcf0fe3348b7e0f4ad4a730eab60a20638ef28/src/cargo/core/compiler/job_queue.rs#L1122-L1168) closure is moved into `JobState::run_to_finish`. It shouldn't change the behavior, though.

### Additional information

Does anyone think it beneficial to have a graph explaining how job queue works? Something like this (from `puma/puma`)

https://bit.ly/2zwzhEK

### CODE REVIEW

**Comment by epage** [comment]
> Does anyone think it beneficial to have a graph explaining how job queue works? Something like this (from puma/puma)

Any thoughts on how we write the diagram?  I know github has mermaid integration but I think rustdoc is pretty limited in what it can do with code fences.

**Comment by weihanglo** [comment]
> > Does anyone think it beneficial to have a graph explaining how job queue works? Something like this (from puma/puma)
> 
> Any thoughts on how we write the diagram? I know github has mermaid integration but I think rustdoc is pretty limited in what it can do with code fences.

I am thinking about ASCII arts. They are great for terminal users. However, I think pictures like what I posted above are more helpful for normal users. Does it make sense to provide both? In terms of pictures, mermaid or other tools are all great to me if we can keep source code and generated pictures side by side with the Rust files.

**Comment by epage** [comment]
> > > Does anyone think it beneficial to have a graph explaining how job queue works? Something like this (from puma/puma)
> > 
> > 
> > Any thoughts on how we write the diagram? I know github has mermaid integration but I think rustdoc is pretty limited in what it can do with code fences.
> 
> I am thinking about ASCII arts. They are great for terminal users. However, I think pictures like what I posted above are more helpful for normal users. Does it make sense to provide both? In terms of pictures, mermaid or other tools are all great to me if we can keep source code and generated pictures side by side with the Rust files.

I've tended to avoid ASCII art because I didn't want to manage the exactness needed to get everything lined up (and staying aligned) but if you want to do it, go for it.

The challenge with anything else is then its not in with the code unless we had fancy code fence support, so I figure it isn't worth it.

**Pull request merged**
