### PR TITLE
Add support for release branches in Cargo

### PR DESCRIPTION
**Pull request by alexcrichton**
Follow the same strategy as the compiler for now in basically every respect:

* Add new `--release-channel` configure option, defaulting to `dev`
* Remove old `--enable-nightly`
* Add `--enable-build-openssl` as an orthogonal option
* Hook up Travis/AppVeyor to stable/beta/master branches to do the right
  channel builds.

### CODE REVIEW

**Comment by alexcrichton** [comment]
My plan is to, if we want this, land this on master, backport it to freshly created stable/beta branches, get the builds working, then start doing testing to get those builds working.

Afterwards I think we could maybe just change how `rust-packaging` fetches Cargo to fetch from the new archives instead of the buildbot archives.

**Comment by steveklabnik** [comment]
Nice.

It's a minor papercut that cargo reports itself as `nightly` even when you install rust stable; we get questions on `#rust-beginners` probably like once a monthish.

**Comment by alexcrichton** [comment]
Yep! that's fixed here too!

**Comment by steveklabnik** [comment]
@alexcrichton minor question about this: docs will still be built from nightly, right?

**Comment by alexcrichton** [comment]
Yes

**Comment by steveklabnik** [comment]
Cool. I don't think that's a problem at the moment, as it's the same as we've always had. Just wanted to make sure.

**Comment by durka** [comment]
This seems to have broken the nightlies.

**Comment by alexcrichton** [comment]
Yeah that was the intention (obsoleting buildbot). We'll have new "nightlies" shortly. A build of Cargo with the fix everyone's waiting for is already available and will go out as soon as rustc has a successful build.

**Pull request merged**
