### PR TITLE
Improve about information of `cargo search`

### PR DESCRIPTION
**Pull request by hi-rustin**
### What does this PR try to resolve?

Since it supports multiple registries, it's better to mention that it's not limited to just crates.io.

### How should we test and review this PR?

- [x] See the docs changes.

### Additional information

None

### CODE REVIEW

**Comment by hi-rustin** [comment]
Wried. I supposed I needed to update the man page, but it seemed we didn't check it.

**Review by weihanglo — CHANGES_REQUESTED** [review]
Thanks for the contribution!

> Wried. I supposed I needed to update the man page, but it seemed we didn't check it.

Guess we might want to update manpage here as well?
<https://github.com/rust-lang/cargo/blob/master/src/doc/man/cargo-search.md>

**Comment by hi-rustin** [comment]
> Guess we might want to update manpage here as well?
> [`master`/src/doc/man/cargo-search.md](https://github.com/rust-lang/cargo/blob/master/src/doc/man/cargo-search.md?rgh-link-date=2023-11-12T16%3A13%3A46Z)

I see. We only check if we generate it from markdown correctly.

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check

**Review by weihanglo — APPROVED** [review]

**Pull request merged**
