### PR TITLE
Fix documentation for package.readme option.

### PR DESCRIPTION
**Pull request by dethoter**
Fix for #4620.

### CODE REVIEW

**Comment by matklad** [comment]
LGTM!

But I am not sure if this has to be updated in both paces :(

@behnam  could you explain a bit how this whole mdBook thing works for Cargo docs, and what files should be modified when one wants to update the docs?

**Comment by behnam** [comment]
Uh, sorry for the delay. Just got to this in the inbox queue.

The diff looks good, as have edited both copies of the doc, which is what we need right now. (Until we drop the non-mdBook copies and kill `docs.crates.io`.)

@matklad, I've tried to explain the current situation in `src/doc/README.md`:

> NOTE: Cargo documentation is under migration to mdBook-based structure. All the
> `*.md` files here shall be kept in sync with the `*.md` files under `book/src/`.
> See `MIGRATION_MAP` file here and <https://github.com/rust-lang/cargo/pull/4453>
> for details.

Do you think there's a need to add more details to the note to help with future patches/reviews?

**Comment by matklad** [comment]
@behnam thanks, I'vecomoletelly missed the whole thing, including src/doc/read me!


@bors r+

**Comment by kbknapp** [comment]
@dethoter or @matklad 

I'm trying to find out about kbknapp/clap-rs#1186 if I have a large README.md and it's listed in the cargo `readme = "..."` but *also* listed in the `exclude = [...]` array, will my readme still get rendered on crates.io?

**Comment by behnam** [comment]
I don't think so, @kbknapp, because the `README.md` file won't be in the package submitted to crates.io. So, crates.io will be trying to access your readme file, but would fail.

You should be able to test it by `cargo package` and then see if the file is included.

Do you think the file assigned by `package.readme` setting, and similar files like `Cargo.toml` itself, should be exceptions in exclusion and always included?

/cc @alexcrichton

**Comment by sfackler** [comment]
The easiest thing to do is to symlink the readme into the subdirectory. The readme will be inlined when the crate is packaged.

**Pull request merged**
