### PR TITLE
Don't fail if we can't acquire readonly lock

### LINKED ISSUE #7147: cargo --frozen requires the cargo home to be writable
Before whatever change #6940 was undoing, a non-existing `CARGO_HOME` worked with `--frozen`. But despite #6940, upgrading cargo to 1.36/0.37 on Debian broke Firefox builds on Debian builders, where they now fail with:
```
ERROR: Couldn't execute `cargo metadata` with manifest "/<<PKGBUILDDIR>>/toolkit/library/rust/Cargo.toml": Metadata(Output { status: ExitStatus(ExitStatus(25856)), stdout: "", stderr: "error: failed to acquire package cache lock\n\nCaused by:\n  failed to open: /sbuild-nonexistent/.cargo/.package-cache\n\nCaused by:\n  Permission denied (os error 13)\n" })
ERROR: Couldn't generate bindings for /<<PKGBUILDDIR>>/toolkit/library/rust.
```

`/sbuild-nonexistent` comes from `HOME` being set to that value, and not existing, which ensures building packages doesn't rely on doing anything with `$HOME`.

A minimal reproducer:
```
$ cargo new foo
     Created binary (application) `foo` package
$ cd foo
$ CARGO_HOME=/forbidden cargo build --frozen
error: failed to acquire package cache lock

Caused by:
  failed to open: /forbidden/.package-cache

Caused by:
  Permission denied (os error 13)
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates support from #6940 to not only gracefully handle
situations where the lock can be acquired in readonly but not read/write
mode but also handle situations where even a readonly lock can't be
acquired. If a readonly lock can't be acquired (and the read/write
failed) then we likely can't touch anything in the directory, so there's
no value gained from locking anyway.

Closes #7147

### CODE REVIEW

**Comment by nbp** [comment]
I can still reproduce this issue on stable, beta and nightly when the `HOME` environment variable is set to a non-existing directory, and that the file `.package-cache` does not exists.

**Comment by ehuss** [comment]
@nbp nightly hasn't been updated, yet.  It is updated around once a week, I'll probably do it today, and it may show up in a couple days after that.

**Comment by nbp** [comment]
Thanks for the notice, I did not saw that this was only fixed 4 days ago.

Would it be possible to backport it to stable once it is checked on Nightly?

**Comment by ehuss** [comment]
It may be difficult to backport to stable.  Generally stable point releases are only made for very critical issues, and AFAIK there isn't anything queued to justify a stable release.  I realize that breaking the build for Debian is painful, though.  I think that's a call for the release team.  I'm not sure what the official process would be, but I would just ask them on `#release` on Discord if you want to make a case for it.  I've only ever backported something to stable once, and that was opportunistic because a stable point release was being made for other reasons.

I'll prepare a beta backport now, though.

**Pull request merged**
