### PR TITLE
Cache the query result.

### PR DESCRIPTION
**Pull request by Eh2406**
Small performance gain.

In a test on https://github.com/rust-lang/cargo/issues/4810#issuecomment-357553286
Before we got to 1700000 ticks in ~97 sec
After we got to 1700000 ticks in ~92 sec. I just reran and got ~82, so it seems to be unstable.
And query disappears from the flame graph

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Upon seeing this though I wonder if we could perhaps do something like:

```rust
struct CachingRegistry<'a> {
    inner: &'a mut Registry + 'a,
    cache: HashMap<...>,
}

impl<'a> CachingRegistry<'a> {
    fn query(&mut self, ...) -> ... {
        // ...
    }
}

```

and then pass that around instead of `&mut Registry`?
and then pass t

**Comment by Eh2406** [comment]
That would be cleaner. But would `CachingRegistry` inpl `Registry`? Becues `Registry.query` takes a `&mut FnMut(Summary)` as its second arg so I don't see how to cache that. Also I'd guess that allocating all the `vecs` is not free. I like that this caches that. (This is a hunch Not backed by a detailed look at the profile results.)

Mabe all the `Context` can gane a shared attribute `registry_cach` of type `Rc<RefCell<BTreeMap<Dependency, Rc<Vec<Candidate>>>>>`?

We will need a cleaner strategy, looks like multiple test are run on the same thread.

**Comment by alexcrichton** [comment]
Oh for sure yeah it can't implement `Registry`, but I don't think it needs to b/c it doesn't escape resolution?

**Comment by Eh2406** [comment]
Ok I will play with that tomorrow. :-)

**Comment by Eh2406** [comment]
Dose that look better?

**Comment by alexcrichton** [comment]
Nice! As one final thing, is the `BTreeMap` required here or would `HashMap` work?

**Comment by Eh2406** [comment]
I had gotten the impression that impl hash was not possible for dep. Now I don't know why. It is fixed.

**Pull request merged**
