### PR TITLE
Testssuite

### PR DESCRIPTION
**Pull request by rochamatcomp**
Reorganize integration tests as one crate with many modules #4867.

### CODE REVIEW

**Comment by matklad** [comment]
Excellent @rochamatcomp! 

Could you do some measurements to test that it actually improves things instead of making them worse? 

I think the following metrics are interesting (before and after this change):

1) the size of `/target` directory after `cargo test --no-run`
2) the time to compile the tests (first, `cargo build --lib && cargo build --bin` to build cargo itself, then actually measure `cargo test --no-run`)
3) the time to recompile a single test after Cargo library is edited
4) the time to recompile a single test after the test itself is edited

**Comment by matklad** [comment]
Oh, because we'd want to take advantage of incremental compilation, I think it makes sense to do the measurements using the current beta.

**Comment by rochamatcomp** [comment]
rustup show
beta-x86_64-unknown-linux-gnu (default)
rustc 1.24.0-beta.11 (03f456d3c 2018-02-03)

1. the time to compile the tests (before cargo build);
2. the time to compile the tests (after cargo build);
3. the time to recompile a single test after Cargo library is edited;
4. the time to recompile a single test after the test itself is edited.

The time in seconds.

| Test | Command                    | Original | Testsuite  | Absolute diff | Relative diff (%)|
| ---- | -------------------------- | -------- | ---------- | ------------- | ---------------- |
| 1    | cargo test --no-run        | 125.64   | 73.40      | -52.24        | -41.58           |
| 2    | cargo build --lib          | 56.15    | 55.83      | -0.32         | -0.57            |
|      | cargo build --bins         | 9.41     | 9.42       | +0.01         | +0.11            |
|      | cargo test --no-run (after cargo build)       | 68.87    | 19.95      | -48.92        | -71.03           |
|      | **TOTAL**                  | 134.43   | 85.20      | -49.23        | -36.62           |
| 3    | cargo test build --no-run (after Cargo library edit) | 56.33    | 11.62      | -44.71        | -79.37           |
| 4    | cargo test build --no-run (after test build.rs edit) | 3.38     | 4.96       | +1.58         | +46,75           |

1. The size of /target directory in gigabytes.

| Test | Command                    | Original | Testsuite  | Absolute diff | Relative diff (%)|
| ---- | -------------------------- | -------- | ---------- | ------------- | ---------------- |
| 1    | du -hs target/             | 5.8      | 1.1        | -4.7          | -81.04           |

**Comment by matklad** [comment]
Awww, awesome, @rochamatcomp !

@alexcrichton seems like a massive win overall to me, what would you think?

**Comment by alexcrichton** [comment]
Thanks for getting those numbers! I'm game for merging.

**Comment by matklad** [comment]
@rochamatcomp could you rebase the PR so that it merges cleanly?

**Pull request closed without merging**
