### PR TITLE
you we distinction

### PR DESCRIPTION
**Pull request by KGrewal1**
Cleaning up the usage of we vs you in the guide section of the book for greater consistency and clarity.

You should now refer to the reader and we to the authors of the book

### CODE REVIEW

**Comment by Rustin170506** [comment]
I'm not sure which one is better, but using "we" is also quite common in tutorial or guide-type documents. Anyway, thanks for your contribution. Also, you need to squash your second commit. Since Cargo merges code using the `merge` method, it seems like the second commit could be merged into the first one!

**Comment by KGrewal1** [comment]
> I'm not sure which one is better, but using "we" is also quite common in tutorial or guide-type documents. Anyway, thanks for your contribution. Also, you need to squash your second commit. Since Cargo merges code using the `merge` method, it seems like the second commit could be merged into the first one!

Squashed into one commit now - aim was to make this more consistent between pages / paragraphs - advantage of 'you / we' is greater clarity in who is being referred to, but agree that we for everything is also common - just ideally whichever choice should be consistent

**Comment by ehuss** [comment]
Microsoft's style guide suggests [Avoid plural first person](https://learn.microsoft.com/en-us/style-guide/grammar/person#avoid-plural-first-person-we-us), which I agree with.

**Review by weihanglo — COMMENTED** [review]
https://github.com/rust-lang/cargo/blob/e858736b561805af163ad9dbe0dbd30aa889701f/src/doc/src/guide/working-on-an-existing-project.md?plain=1#L6

This also need a tweak?

**Comment by KGrewal1** [comment]
Couldn't think of a non clunky way to remove the pronoun here, "you'll use" sounds imperative and worse, "let's use" is still 1st person plural, and removing the pronoun (In this example, using `regex`) I thought was subjectively worse

**Comment by weihanglo** [comment]
That's true. Let's merge this now, as people seem to like this :)

**Pull request merged**
