### PR TITLE
Fix compilation on more platforms

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by kennytm** [comment]
The BSDs do have `TIOCGWINSZ`. The constants are just defined as `c_int` on some platforms and `c_ulong` on others. The error on rust-lang/rust#45692 is actually about rust-lang/libc#704.

**Comment by alexcrichton** [comment]
@kennytm yeah I just didn't want to deal with all the portability stuff here, for me it was easier to just ignore on other platforms as it's a new feature anyway.

**Pull request merged**
