### PR TITLE
Clean only release artifacts if --release option is set

### LINKED ISSUE #6339: cargo clean --release removes entire target directory without warning
**Problem**

Running `$ cargo clean --release` seems to silently remove the entire target directory. I would expect at least a warning that this would happen when passing the '--release' flag since the intention was to only clean the release build.

### PR DESCRIPTION
**Pull request by collin5**
Fixes #6339

### CODE REVIEW

**Comment by dwijnand** [comment]
Seems good to me.  Could you try and add a test for this fixed behaviour, please?

**Comment by dwijnand** [comment]
I think we'd want a test that also built non-release, and assert that running `clean --release` doesn't remove those artefacts.

**Comment by collin5** [comment]
Updated! Thank you.

**Comment by dwijnand** [comment]
Nice one, thank you!

@bors: r+

**Pull request merged**
