### PR TITLE
remove clones made redundant by Intern PackageId

### PR DESCRIPTION
**Pull request by Eh2406**
This is a follow up to #6332. I used clippy to find all the places we called `.clone()`  on a `PackageId` or where we passed `&PackageId`. Yes that touches 44 files and 400+ lines, that is way we wanted `PackageId` to be `copy`.

### CODE REVIEW

**Comment by dwijnand** [comment]
Awesome!  r=me, but looks like something needs fixing up.

**Comment by Eh2406** [comment]
That was a lot harder to track down then I expected, but the tests are passing now.

**Comment by Eh2406** [comment]
and CI is green.

**Pull request merged**
