### PR TITLE
Add owner subcommand to cargo's man page

### PR DESCRIPTION
**Pull request by munyari**
Addresses #2789

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I don't think this may quite be enough to close out the referenced issue, though, as we'll want to also add an associated man page in `src/etc/man`. Would you be interested in doing that as well?

**Comment by munyari** [comment]
I probably should have said WIP, as I only did the first part. Yes, I'll take on the actual man page for `owner` later

**Comment by alexcrichton** [comment]
Ok, thanks! I'll hold off on merging until we've got that in place as well.

**Comment by munyari** [comment]
The first man page I've ever written :tada:

**Comment by alexcrichton** [comment]
@bors: r+ 607e9fda2ad0ee9851a494667986bc018635bbfb

awesome, thanks!

**Pull request merged**
