### PR TITLE
Backport of #4551 - owner-invite-messages

### PR DESCRIPTION
**Pull request by carols10cents**
And *just* this change this time, I think :)

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me, but I think you may have to fight the nightly Travis builder

**Comment by carols10cents** [comment]
there we go!

@bors: r=alexcrichton

**Comment by carols10cents** [comment]
nooo i fixed that :(

**Comment by alexcrichton** [comment]
@bors: r+

Oh I think I forgot to deploy... I'll do that soon!

**Pull request merged**
