### PR TITLE
restructure `Activations` for better clone

### PR DESCRIPTION
**Pull request by Eh2406**
This builds on the work in #5121 When we last met we had:
5000000 ticks in ~48 sec, 0r 104k ticks/sec
This small change brings us to:
5000000 ticks in ~21 sec, 0r 238k ticks/sec
Edit: sorry for the large diff only the last commit is new. The rest are from #5121

### CODE REVIEW

**Comment by alexcrichton** [comment]
😲 

auto-r+ from me as soon as #5121 is sorted out

**Comment by Eh2406** [comment]
Rebased so that the diff only shows the one relovent commit.

**Comment by alexcrichton** [comment]
@Eh2406 oh I think the branch was deleted before this was merged?

**Comment by Eh2406** [comment]
Oops, sorry. What is the best way to fix this, should I post a new PR?

**Comment by alexcrichton** [comment]
Yeah that's probably best, and no worries!

**Comment by Eh2406** [comment]
Github claims this PR can be reopened, and that it is redundant to post a new one.

**Pull request closed without merging**
