### PR TITLE
Sort native library paths for deterministic builds

### LINKED ISSUE #3800: LD_LIBRARY_PATH order is non-deterministic
```toml
# Cargo.toml
[dependencies]
openssl-sys = "0.7"
pq-sys = "0.4"
```
```rust
// main.rs
fn main() {
    println!("{:#?}",std::env::var("LD_LIBRARY_PATH").unwrap().split(":").collect::<Vec<_>>());
}
```
Running this program with `PQ_LIB_DIR=/test cargo run` will result in either of the following outputs:
```
[
    "/usr/lib/x86_64-linux-gnu",
    "/test",
    "/tmp/ctest/target/debug",
    "/tmp/ctest/target/debug/deps",
    "/home/jethro/.multirust/toolchains/nightly-2016-10-03-x86_64-unknown-linux-gnu/lib"
]
```
```
[
    "/test",
    "/usr/lib/x86_64-linux-gnu",
    "/tmp/ctest/target/debug",
    "/tmp/ctest/target/debug/deps",
    "/home/jethro/.multirust/toolchains/nightly-2016-10-03-x86_64-unknown-linux-gnu/lib"
]
```
This can lead to very confusing intermittent problems, especially with crates such as openssl-sys 0.7 which include the system lib directory.

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #3800 by using a `BTreeSet`, which guarantees a deterministic iteration order. 

Since the order was previously arbitrary, a sorted order is just as good. The list is so small, that any performance difference between `BTreeSet` and `HashSet` is negligible.

### CODE REVIEW

**Comment by alexcrichton** [comment]
As I commented on #3800 there is no correct ordering here I believe, but do you think differently? In that sense it seems like using a sorted set will just allow everyone to accidentally depend on what is otherwise a bug?

**Comment by pornel** [comment]
The ideal solution would be linkers getting smarter and having proper diagnostics for ambiguities and/or more precise ways to specify linking, but AFAIK that's not going to happen anytime soon.

So lacking ability to fix the root cause, I'd like to at least make the bug less painful. My hope is that it turns intermittent linking problems into deterministic linking problems.

Other options I considered are:

* Leave as-is. That's not good, because builds that work may stop working at any time, and Cargo can't help diagnose the problem. Without warnings that's not help, but punishment.

* Completely randomize every time. It prevents relying on any order, but then running Cargo a couple of times may "fix" it. I worked on projects that ran buggy `rm -rf node_modules; npm` a few times until it worked, and that wasn't good.

* Some other deterministic order that isn't alphabetical. It would be an extra deterrent against trying to "configure" linking order by renaming directories, but I don't think that's big enough problem to justify complexity.

* Try to preserve some "original" order these paths were set in. As far as I understand such order doesn't really exist because of parallel builds, so it'd have to be invented (e.g. by simulating what the order would have been without parallel builds), but then it would still depend on build scripts and dependencies-of-dependencies which aren't easy to control, so in practice it wouldn't be under control anyway.

**Comment by alexcrichton** [comment]
I agree that deterministic errors are better than intermittent ones, but my point is that any deterministic order will create a silent reliance on the order by accident which will then inevitably fail later and cause bug reports. I don't think there's anything we can do here?

**Comment by pornel** [comment]
I think allowing an accidental dependence is less bad than Cargo being flaky and annoying. Hashmap breaking builds intermittently is the worst "user interface" for this. Intermittent failures make it harder to diagnose the problem.

If Cargo was deterministic then breakage would come only from changes to the build or environment, like addition of paths or installation of new libraries, which makes it easier to notice what caused it.

If user finds that a crate builds on one machine, but not another, it's much easier to diagnose the problem by having two deterministic builds to compare.

So Cargo is not equipped to prevent this failure in a reliable user-friendly way, so I think it should not try to prevent it, and let the failure happen for its "natural" reasons, which make the root cause easier to diagnose, and let Cargo be a reliable component of the build process.

**Comment by alexcrichton** [comment]
That's sort of my point though in that I disagree. If Cargo were deterministic then it has no recourse for ever changing, and because there's no "right answer" here it seems like we should ensure that we have the freedom to change this in the future.

**Comment by pornel** [comment]
I think it's fair if you change that between releases. The main problem is that it currently changes at random, but in an annoying way that is neither guaranteed to be random, nor stable enough to allow debugging of the problem.

**Comment by alexcrichton** [comment]
I think at this point we're just talking past each other and saying the same thing? To maybe help out a bit can you provide an example of where the build breaks for you and only succeeds with one ordering?

**Comment by nathanaeljones** [comment]
> To maybe help out a bit can you provide an example of where the build breaks for you and only succeeds with one ordering?

* OpenSSL from #3800 would be one example. 
* Trying to use a custom version of libjpeg would be another.

Anytime there are multiple answers to a link search, this becomes a nightmare.

@aturon explains this well in https://github.com/rust-lang/cargo/issues/3800#issuecomment-286273221

> @alexcrichton I feel like you and the others on this thread are talking past each other a bit.

> I think everyone is in agreement that non-determinism can sometimes reveal the existence of a bug.

> However, as @nathanaeljones points out (rightly IMO), finding out that there's a bug when you can't reproduce it is usually worse than the bug being hidden. And in particular, the bugs we're talking about here, AIUI, will tend to result in very visible failures when they're triggered. So "masking" them doesn't mean that there's problems lurking in production code, but rather that your build could fail if something gets perturbed.
@alexcrichton, you say that it's OK for the build system to have "controlled" nondeterminism (and you cite parallel builds as an example). I think that's probably true at a fundamental level, since build scripts can observe arbitrary machine state.

> However, I think a basic goal of reducing the amount of nondeterminism over time is a good one for Cargo. This isn't about blindly sorting in an effort to fix bugs, but rather about systematically making builds easier to reproduce, so that you have some hope of debugging things when they do go wrong. So, in particular, I don't think we should choose to be nondeterministic when there's an easy way around it.
Finally, @alexcrichton you've mentioned a couple times that there's no "right" order for these items to appear in. But that seems beside the point, to me. What we're after is just determinism, so we can choose any order as long as its consistent. Sorting seems totally reasonable to me.

The only solution I'm aware of that can fully eliminate reliance on link path order is to implement linker search for each platform and fail the build if there are multiple possibilities. Otherwise, it's up to developers to ensure that the wrong library version breaks the build (either through missing symbols or version checks in unit tests). Given that this is not going to happen anytime soon, we'd like to slow the bleeding here.

I've abandoned Cargo wherever possible, but I'd prefer to not have to do that.

**Comment by lucab** [comment]
I may be wrong, but I think that what you'd want to have here is a LinkedHashSet, not a BTreeSet.
That is, you'd want to cargo to deterministically preserve the original insertion order (i.e. input vector order), not to enforce its own lexicographic reordering.

This is because:
 * as @nathanaeljones said above, search path order is relevant to the linker
 * build script knows the proper ordering, and this information is relayed to cargo
 * any kind of re-ordering (either random or deterministic but custom) could introduce a bug

**Comment by pornel** [comment]
@lucab AFAIK original user-specified insertion order is non-deterministic, because dependencies are compiled in parallel and any dependency can add a path at any time.

**Comment by lucab** [comment]
Yes, I'm aware of https://github.com/rust-lang/cargo/issues/3800#issuecomment-284749188. I'm also aware that there are cases where a correct order does not exist.

What I'm pointing out is that:
 * in cases without an existing correct order (e.g. the MozJPEG-OpenSSL example above), this PR does not matter. Solution does not exist, whatever the order we try
 * in simple cases with a solution (e.g. a single library returning multiple paths), this PR has (correctness) bugs due to the arbitrary reordering which may change relative order
 * in more complex cases (e.g. a DAG with multiple -sys crates), a fix at an higher level is due anyway if you are aiming for both correctness and determinism

**Comment by aturon** [comment]
I'm nominating this for discussion at the next Cargo team meeting, since it's come up a few times in the past.

cc @rust-lang/cargo

**Comment by withoutboats** [comment]
Is this important for reproducibility? Does the nondeterminism show up in the compiled artifact?

I think its valuable for builds to be reproducible using the same version of cargo, but that we should not provide any backwards compatibility guarantee that the determinism will be the same between versions of cargo (in other words, as Alex is saying, people should not rely on a *particular* ordering).

**Comment by aturon** [comment]
@withoutboats the problem as I understand it is not cross-version; even within the *same* Cargo version the order is non-deterministic.

**Comment by nathanaeljones** [comment]
> Is this important for reproducibility? 

Yes

> Does the nondeterminism show up in the compiled artifact?

Yes

> not provide any backwards compatibility guarantee that the determinism will be the same between versions of cargo

We'll take anything to get reproducible builds. 

> people should not rely on a particular ordering

There's often no way around it if you're using more than one *-sys crate, or using pkg-config. The only way I know around it is to eliminate -sys crates and exclusively use Conan.io, which isolates each linked artifact in its own folder. 

We need to be able to combine multiple -sys crates safely.

Linkers rely on order. Link paths offer multiple solutions for each artifact. It's kind of hard to audit a app when it's built against a different version of dependencies every time you hit enter. Even Docker can't help us with this until we end the randomization. 

There's also no working mechanism for users to test, modify, or fixup the merged set of link paths before they're passed to rustc (AFAICT, and I looked for months, then [suggested one](https://internals.rust-lang.org/t/cargo-support-for-build-script-filters-lints-and-link-path-providers/4563)). 

Alphabetical (or smarter - like pushing system folders down the list) sorting helps a ton. Far better than the status quo.

Preserving order - such that  users *have* some level of control over the order - would be ideal.  I do think this is solvable, and I can't envision a concrete example of how it would paint us into a corner.

**Comment by withoutboats** [comment]
@nathanaeljones Thanks for the info! The core of what I'm asking I guess is this: is it sufficient to guarantee that the order will be deterministic within a version? So if you're relying on the ordering being any particular way (e.g. alphabetic), an upgrade might break it, but if you're just relying on it being the same between 2 different builds with the same version of cargo, we should never break that.

**Comment by nathanaeljones** [comment]
It's sufficient for me.

**Comment by alexcrichton** [comment]
This was discussed at a cargo triage meeting awhile back (sorry for the delay in posting the results!). Our conclusion was that we'd like to basically apply a blanket policy that cargo should be "reasonably deterministic" in the sense of going out of our way to ensure that all builds are always the same, unconditionally. (within reason, of course)

In that sense we agree to accept this PR. @kornelski would you be willing to update it with a test? After that I think it would be good to merge.

**Comment by kornelski** [comment]
Done

**Pull request merged**
