### PR TITLE
Implement the `panic` profile option

### PR DESCRIPTION
**Pull request by alexcrichton**
This is the Cargo half of the implementation of [RFC 1513] which adds a new
`profile.*.panic` option to customize the `-C panic` argument to the compiler.
This is not passed by default and can otherwise be specified as `abort` or
`unwind` on the nightly compiler.

[RFC 1513]: https://github.com/rust-lang/rfcs/pull/1513

The `profile.*.panic` option is *only* used from the top-level crate, not each
crate individually. This means that applications should customize this value as
they see fit, and libraries will only use their own value when they're being
tested.

Cargo also has specific knowledge that when *testing* a crate it can't pass
`-C panic=abort` for now as the default test harness requires `panic=unwind`.
This essentially just means that `cargo test` will continue to work for crates
that specify `panic=abort` in Cargo.toml.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Any chance we can get this merged sometime soon? Eagerly awaiting :smile:

**Comment by alexbool** [comment]
Seems like there's a bug in your implementation.
When I build my crate with
```
[profile.dev]
panic = "abort"
```
I get an error if my crate depends on any crate that builds using a `build.rs`.
The failure looks as following:
```
$ cargo build --release --verbose
...
   Compiling kernel32-sys v0.2.2
     Running `rustc /Users/alexbool/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/build.rs --crate-name build_script_build --crate-type bin -g --out-dir /Users/alexbool/Documents/IdeaProjects/rust/mycrate/target/release/build/kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=/Users/alexbool/Documents/IdeaProjects/rust/mycrate/target/release/deps -L dependency=/Users/alexbool/Documents/IdeaProjects/rust/mycrate/target/release/deps --extern build=/Users/alexbool/Documents/IdeaProjects/rust/mycrate/target/release/deps/libbuild-493a7b0628804707.rlib --cap-lints allow`
error: the crate `build` is compiled with the panic strategy `abort` which is incompatible with this crate's strategy of `unwind`
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `kernel32-sys`.
```

**Comment by alexcrichton** [comment]
Thanks for the report @alexbool! I unfortunately can't seem to reproduce easily, could you open an issue with some instructions about how to reproduce as well?

**Comment by tomaka** [comment]
@alexcrichton I didn't test a lot, but I think the issue appears when you have a different value for `panic` for the dev and release profiles.

**Comment by alexbool** [comment]
@alexcrichton the issue is #2726 :)

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
