### PR TITLE
[rust-1.16.0] Update OPENSSL_CC_powerpc64-unknown-linux-gnu

### PR DESCRIPTION
**Pull request by cuviper**
With the new `rust-slave-linux-cross:2017-02-02`, powerpc64 no longer
uses gcc-5.  I updated the `Dockerfile` at the time to reflect this, but
missed `OPENSSL_CC_powerpc64-unknown-linux-gnu` in `Makefile.in`.

### CODE REVIEW

**Comment by cuviper** [comment]
Same as #3648, just on the beta branch.

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/cargo/pull/3652 should fix those errors, I'll r+ after it lands.

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
