### PR TITLE
Release a jobserver token while locking a file

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a possible solution to #6747, but we'll ideally get some testing
in before landing!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm ok I've had to push up a commit which removes the minimal-versions build on Windows. Unfortunately if you create a new project, add `rand = "0.6.5"` and build it for Windows it fails with a similar error. I feel like we're not really getting a lot of benefit from testing minimal versions on our CI so I figured it might be best to not hold this up on that. @ehuss mind taking another look though? @Eh2406 I suspect you'll want to weigh in on this as well.

**Comment by ehuss** [comment]
I suspect this is the same issue found in #6636.  

I can take a look at fixing rand's minimal versions. 

I think switching to a direct-dependency-only minimal versions might be the better long-term solution (https://github.com/rust-lang/cargo/issues/5657#issuecomment-463422001).  But I have not thought much about how it could be implemented or what complications may arise.

**Comment by Eh2406** [comment]
Given that #6636 and this are stuck on fixing rands minimal version, I think declaring the minimal-version experiment dead is justified, or at least suspending it until someone fixes rand. I have had only enough time to determine that it won't be trivial.

**Comment by ehuss** [comment]
It looks like the fundamental rand issues in 0.6 have been fixed (via https://github.com/rust-random/rand/pull/703), but new versions of some of the subcrates (like `rand_hc`) have not been published.  It's not clear to me from the last comment in that PR what is blocking publishing new versions.  Additionally, the root Cargo.toml in the rand project will need to set the patch version for every sub-crate, and push a new update as well.  Then any crate depending on 0.6 will need to set their minimum version to that new version (in this case, I think it is just `jobserver`, and `proptest` for the other situation).

Given the comments (https://github.com/rust-random/rand/issues/741#issuecomment-468909963) I'm not sure if they'd be receptive to doing the work to accommodate this.  I can open an issue on rand, but I don't really want to police the entire ecosystem to keep this working.

**Comment by Eh2406** [comment]
So this is the logjam as I see it:

1. People are using `--minimal-versions` and it generally works, sometimes they ask for fixes from upstream. This is awkward to ask or not fixed upstream because it is not approved/stabilized by the Cargo Team. (for example https://github.com/rust-random/rand/issues/741#issuecomment-468909963)
2. The Cargo Team is not ready to stabilize it as everyone who has used it has hit some case that does not work.

There are 2 nash-equilibrium. We stabilize it and the ecosystem adapts or we officially give up on it. Maybe we find some smaller version that can get us out of the jam. But the current state of affairs is not stable.

**Comment by alexcrichton** [comment]
Yeah I definitely agree the direct-dependency-only version would likely solve this, but @ehuss I wouldn't necessarily take this as a signal that we need to fix `rand` (moreso that the direct-dependency version is more plausible!).

Are y'all ok though temporarily at least removing this from Windows CI?

**Comment by ehuss** [comment]
> Are y'all ok though temporarily at least removing this from Windows CI?

I'm OK with this.

**Comment by Eh2406** [comment]
I am ok with it.

**Comment by alexcrichton** [comment]
Ok!

@bors: r=ehuss

**Comment by ehuss** [comment]
> Anyone know why we only hit this on windows, but hit it on travis for #6753 ?

Jobserver only uses [rand on windows](https://github.com/alexcrichton/jobserver-rs/blob/0cc0028be85fca95324875c71adb2b8afa8ff76b/Cargo.toml#L19-L20).

**Pull request merged**
