### PR TITLE
Add the build date to the reported version

### PR DESCRIPTION
**Pull request by brson**
```
cargo 0.0.1-pre (9404539 2015-02-09 20:54:26 +0000) (built 2015-02-11)
```

### CODE REVIEW

**Comment by brson** [comment]
cc https://github.com/rust-lang/rust/pull/22201

**Comment by brson** [comment]
Needs to merge with the corresponding Rust PR.

**Comment by huonw** [comment]
r=me, but travis failed. (I'll let you coordinate merging.)

**Pull request merged**
