### PR TITLE
Blanket rename rustc-macro to proc-macro

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Not quite sure how this is going to be coordinated, but https://github.com/rust-lang/rust/pull/36945 should land first regardless.

**Comment by brson** [comment]
r=me

**Comment by alexcrichton** [comment]
cc @dtolnay @sgrif 

Ideally this is all the support necessary for the rustc-macro => proc-macro rename. If all the stars align correctly tonight everything will be ready tomorrow morning. Let me know if anything is awry though!

**Comment by dtolnay** [comment]
Thanks, I will release the required serde_derive changes as soon as rustup starts giving me the new nightly. I filed https://github.com/serde-rs/serde/issues/575 to track.

**Comment by sgrif** [comment]
Thanks. I was going to release Diesel with macros 1.1 compat tonight but I'll wait for this.

**Pull request merged**
