### PR TITLE
[WIP]: Add cargo-add (from cargo-edit) to cargo proper 

### PR DESCRIPTION
**Pull request by ibaryshnikov**
Implements #5586 

The work is at early stage and contains mostly code copied from `cargo install` command. But it compiles and it is possible to call the subcommand: `./target/debug/cargo add some_crate`

I've opened this pr to discuss the key decisions during the implementation process.

### CODE REVIEW

**Comment by killercup** [comment]
Thanks for opening this! Let me know as soon as you want feedback or have questions!

**Comment by ibaryshnikov** [comment]
@killercup inside cargo the data structure for Cargo.tom file is [TomlManifest](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/toml/mod.rs#L213)
Is it a good idea to add to_string method to this structure and use it instead of [Manifest](https://github.com/killercup/cargo-edit/blob/master/src/manifest.rs#L17) from cargo-edit?

**Comment by ibaryshnikov** [comment]
After some research I found that cargo own toml parser doesn't preserve file structure. It needs to move [toml_edit](https://github.com/ordian/toml_edit) here in addition to cargo-edit. In case to have only one parser.

But currently I'm stuck with error kinds while moving [manifest](https://github.com/killercup/cargo-edit/blob/master/src/manifest.rs) file from cargo-edit to cargo. Can you give me an advice how to update these errors to be more appropriate for cargo?
And what is the best place for manifest.rs? I chose utils/toml because it represents the data type for a toml file.

**Comment by alexcrichton** [comment]
Thanks for opening this @ibaryshnikov and sorry for the delay! I'm pretty excited to see this start moving and I'm also excited that cargo-edit has come so far!

It looks like some of the integration points are still missing here in terms of being a mergeable PR, but in general it may also be worthwhile to discuss integration strategies. First off I'm personaly in favor of merging cargo-edit into Cargo now if it has a style-preserving TOML parser, that's all we were waiting for! Second, though, I think we'll want to integrate the project into Cargo's codebase in an idiomatic fashion with Cargo's own code (aka errors and such).

I think for integration though we'll also want to try to avoid having two TOML parsers (if we can). I'd ideally like to keep everything on the same parser if we can to help reduce bugs and such. For example it looks like `toml_edit` is using a nom-based parser, but perhaps [`tokens.rs`](https://github.com/alexcrichton/toml-rs/blob/master/src/tokens.rs) could be exported and/or extracted to a crate and shared between the two?

**Comment by ibaryshnikov** [comment]
Thank you for the explanaitions, @alexcrichton !

I've just replaced ErrorKind errors with format_err macro. The next step is to find a way to replace chain_err.

**Comment by alexcrichton** [comment]
Ok, great!

**Comment by alexcrichton** [comment]
ping @ibaryshnikov, have you had a chance to work on this recently?

**Comment by ibaryshnikov** [comment]
not yet (
I'm going to hack into it once more this weekend.
it would be great if someone could help me with this issue

**Comment by ibaryshnikov** [comment]
Found out how to deal with chain_err. Now I'm going to find how to use tokens.rs here

**Comment by ordian** [comment]
Hello, author of [toml_edit](https://github.com/ordian/toml_edit/). I'm happy to help to make this happen.

> For example it looks like toml_edit is using a nom-based parser, but perhaps tokens.rs could be exported and/or extracted to a crate and shared between the two?

Actually `toml_edit` uses `combine`-based parser. I can hack over this weekend to extract and reuse tokens.rs if it helps.

**Comment by alexcrichton** [comment]
@ordian ok that'd be great yeah! That would deduplicate some of the most complicated parts of TOML parsing which would work well. Currently the `toml` crate doesn't expose its tokens as a public module, but I think it would be fine to either extract what's there to a separate crate or just make it public

**Comment by ordian** [comment]
Also I would suggest using more recent version of `cargo-edit`, where we support specifying both `git` and `version` at the same time (see https://github.com/killercup/cargo-edit/pull/214).

**Comment by ibaryshnikov** [comment]
Thank you for your comments, @ordian ! I picked the latest code from **cargo-edit** for [dependency.rs](https://github.com/killercup/cargo-edit/blob/master/src/dependency.rs)
Tried to test it,
```
cargo run add toml --git=https://github.com/alexcrichton/toml-rs --version=0.4.6
```
produces
```
toml = { version = "0.4.6", path = "https://github.com/alexcrichton/toml-rs#8181a7e6" }
```

**Comment by alexcrichton** [comment]
Ok this has been a bit stale for quite some time now, so I'm going to close this at this time. The Cargo team very much wants to add this, however, and we'll be looking into allocating resources to implement this change in early 2019 hopefully!

**Comment by ibaryshnikov** [comment]
@alexcrichton have you had a chance to look through the code before closing it? I was waiting for your comments. I mean, allocating some resources would be helpful, but may be some changes from this PR could be used, too.

**Comment by alexcrichton** [comment]
@ibaryshnikov unfortunately no I didn't have time to do a thorough review (and it looks like no others did either). Reviewing this will likely require a pretty significant investment from someone on the Cargo team because it's a very highly-desired and relatively large piece of new functionality. There's quite a lot of code to review here not only in this repository but in the crates.io dependencies.

**Comment by ibaryshnikov** [comment]
@alexcrichton do you know anyone who can do the review?
The #5586 was created as a part of the impl days in Paris this summer. It supposed to be an easy task to help people start contributing. Also I was going to continue working on it during the impl days in Rome in several weeks. I hoped there would be someone who can help with my questions.

**Comment by alexcrichton** [comment]
@rust-lang/cargo would others be able to help out in reviewing this? @ibaryshnikov is requesting a review.

Ah sorry @ibaryshnikov but this probably should definitely not be classified as an easy task, that was a mistake :(

**Comment by cup** [comment]
https://github.com/rust-lang/cargo/issues/1917
https://github.com/rust-lang/cargo/issues/2179
https://github.com/rust-lang/cargo/issues/4
https://github.com/rust-lang/cargo/issues/5586
https://github.com/rust-lang/cargo/issues/6457
https://github.com/rust-lang/cargo/issues/6488
https://github.com/rust-lang/cargo/issues/651

https://github.com/rust-lang/cargo/pull/5611

**Comment by shirshak55** [comment]
any status?

**Pull request closed without merging**
