### PR TITLE
Add proc-macro to index, and new feature resolver.

### PR DESCRIPTION
**Pull request by ehuss**
This adds the "pm" field to the index so that Cargo can detect which packages contain a proc-macro without downloading the package. 

The second commit builds on that to support proc-macros in the new "de-unification" of the new feature resolver. This prevents dependencies shared between proc-macros and other dependency kinds from having features unified.

cc #7915

### CODE REVIEW

**Comment by ehuss** [comment]
NOTE: This modifies `cargo publish` without a feature gate. I can add one, but I figure this could be generally useful independent of the new resolver. crates.io will ignore the field for now. The patch to crates.io is relatively trivial.

**Comment by ehuss** [comment]
I think it should be OK.  I'm not super confident this is the right decision, but I just can't get around the potential difficulty, risk and complexity of trying to rebuild features while packages are downloaded.  The main drawback here is the slow rollout since proc-macros will need to be published with a new version to get the new behavior (and that may not be obvious to the proc-macro author, since it is the proc-macro *users* who care about this).

I just realized I forgot to update the registry documentation, so I just pushed a fix for that.

**Comment by alexcrichton** [comment]
@bors: r+

Ok I think in that case let's go ahead and try to get this in the works, and we can adapt the roll-out as time progresses.

**Comment by ehuss** [comment]
@alexcrichton I wanted to discuss a concern I had about this.

If a proc-macro is published with an older Cargo where the `pm` field is not in the index.  Then, some time in the future, they publish with a new Cargo that updates the `pm` field.  This means when they publish, it may cause feature resolution to change for anyone using that proc-macro with the new resolver.  That may be surprising, especially if the proc-macro author doesn't know about or use the new feature resolver.  There's a bit of "spooky action" going on.

Do you think that is enough of a concern that this is maybe a bad idea to move forward with?

I was initially thinking of just "update all proc-macros in the index" to avoid that, but then I was thinking, after doing that, old Cargo's would keep putting old data into the index. So maybe that isn't such a good solution.

**Comment by alexcrichton** [comment]
Hm no that's actually a really good point and I would indeed be worried about that.

I do think though that a "rewrite the index" strategy would still work. The main gotcha there though would be that we'd have to update crates.io to work whenever Cargo doesn't send a proc-macro field. crates.io itself would have to parse `Cargo.toml`, for example, looking for `proc-macro = true` (or something like that).

I agree though that if we *can't* fix this we should probably back this out to prevent the action-at-a-distance from happening.

**Comment by ehuss** [comment]
Yea, I thought about the option of having crates.io parse `Cargo.toml`.  I was hoping it already did that, but it doesn't. I'm not sure how difficult or expensive that would be. I know that the crates.io team would prefer to have the actual `.crate` upload go through a separate channel (to deal with the heroku 30-second upload timeout), and needing to parse the crate might make that more difficult. 

I'll ponder this a bit.  I think the only other option is to have Cargo do feature resolution after downloading, and that would require some significant changes to how the code is structured that I would prefer to avoid.  I could maybe hack together some prototypes to see how difficult it would be.  Another thought I had was to have a simple pre-pass that would determine the minimum set of crates to download, and then build the unit graph.  If that could be done in a relatively small amount of code, that might be another option.

**Comment by alexcrichton** [comment]
I do agree that the ideal would be doing feature resolution after all the downloads so we have full manifest information, but I thought that you tried that earlier and said it would be an extremely large undertaking. That being said I think it's fine to download extra crates even if we don't end up using them in a few corner cases.

**Comment by sfackler** [comment]
Another option to avoid the action-at-a-distance concern is to have the proc-macro authors opt into the new behavior - maybe by setting `[package] proc-macro = 2` or something like that. Then you still get the advantage of having the information in the index without a magic change whenever a crate is next released.

**Pull request merged**
