### PR TITLE
Provide extra context on a query failure.

### PR DESCRIPTION
**Pull request by ehuss**
This adds error context when a query fails, primarily to tell you which parent package included the dependency that failed. For example, imagine deep within your dependency graph you have a `git` dependency, and it fails to download. The current error doesn't tell you where in the graph that `git` dependency was included.

I also slightly tweaked the `failed to load source` error message. I felt like the existing wording could be misinterpreted that it was an error loading the dependency *for* the given package. I felt like there were multiple ways to interpret it, so I tried to simplify it to avoid that possibility.

### CODE REVIEW

**Comment by ehuss** [comment]
This is just an experiment, and I wanted to get feedback if anyone thinks it looks like a good idea. I'm also open to changing the wording.

**Comment by Eh2406** [comment]
seems reasonable.

**Comment by alexcrichton** [comment]
It sounds like the goal here is to sort of figure out *why* a package was included, right? If so I think 1 package as a parent helps a lot, but perhaps we could go all the way and do the `path_to_root` method which prints everything?

**Comment by ehuss** [comment]
A full path might be nice, but I don't know how to do that at this location.  I assume you're referring to `path_to_bottom`?  It looks like that requires Context.parents?  It looks like I could maybe pass something in, but I'm very unfamiliar with this, so I'm not clear on the relationship of the "candidate" and the parents.

**Comment by Eh2406** [comment]
Yes, I think something like 
```rust
describe_path(
                &cx.parents.path_to_bottom(&parent.package_id()),
            )```
Will make a message that matches our other errors. Looks like we can pass `cx` from the `activate`.

Or perhaps that can be added as part of a `chain_err` on the result of `build_deps` in `activate`, I don't know the capabilities of `anyhow`.

cc #6199

**Comment by alexcrichton** [comment]
I think that if the error context was shifted to [around here](https://github.com/rust-lang/cargo/blob/a07fec1b7b530e5a12fabf64db6b6e652dcabb93/src/cargo/core/resolver/mod.rs#L658-L659) it may be easier to call that `describe_path` method perhaps? (poking a bit in the dark myself here)

**Comment by ehuss** [comment]
Hm, I pushed a change that moves the context up so that it can get the path.  Unfortunately `build_deps` also handles feature validation, and the error messages in those cases were worse off (that's not necessarily an error loading a dependency).  So I added a special variant to `ActivateError` to detect that case.

I'm not really sure it's worth it, it seems to complicate things a little.  What do you think?

**Comment by Eh2406** [comment]
Hmmm, I was more thinking of the smaller change like https://github.com/rust-lang/cargo/compare/master...Eh2406:pull/7934#diff-995a0a0a73b467f7c6b0cb34d8fba39d (I did not fix the tests.)

**Comment by ehuss** [comment]
> I was more thinking of the smaller change like

That looks good.  (The link is broken, but I think this link works: https://github.com/Eh2406/cargo/commit/d3f712ac8f2d714cbe2c04c86ec496b1047f6577)  I'll try it out tomorrow.

**Comment by ehuss** [comment]
Thanks, updated with @Eh2406 suggestion, it looks much better.

**Comment by Eh2406** [comment]
Looks great! Thanks for adding the new test!
@bors r+

**Pull request merged**
