### PR TITLE
Strip features which is owned by dev dependencies only

### LINKED ISSUE #12225: Cargo should strip features of dev dependencies
### Problem

https://github.com/rust-lang/cargo/pull/7333 added stripping of dependencies, but did not strip features pointing to those dependencies.

This causes a rather unintuitive error where cargo says the dependency does not exist. Which one would only understand if they knew about the stripping that cargo does.

### Proposed Solution

Cargo should also strip these features from the manifest before publishing.

If `foo` is a dev-dependency being stripping then `a = ["foo/a"]` should be transformed to `a = []`.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by eval-exec**
### What does this PR try to resolve?
This PR want to close #12225

### How should we test and review this PR?
I added a unit test.

### CODE REVIEW

**Comment by eval-exec** [comment]
I forget strip features for `cargo package`. fixing it

**Comment by ehuss** [comment]
@rustbot author
When you're ready for review, please use `@rustbot ready`.

Just taking a quick peak at the current code, it looks like it may be unconditionally stripping dev-dependency features. I believe they should only be stripped for dev-dependencies that don't specify a version (see `is_version_specified`). Also beware that dev-dependencies can also be in the `target` table. If you have any questions, please let us know.

**Comment by eval-exec** [comment]
> Also beware that dev-dependencies can also be in the `target` table.

What's the `target` table?

**Comment by eval-exec** [comment]
Consider there is a `Cargo.toml`:
```toml
[package]
name = "foo"
version = "0.1.0"
authors = []
license = "MIT"
description = "foo"
documentation = "foo"
homepage = "foo"
repository = "foo"

[dependencies]

[dev-dependencies]
byte-unit = {version = "4.0.19", features = ["alloc"]}

[features]
foo_feature = ["byte-unit/alloc"]
```

Do you agree that `cargo package` should strip `foo_features = ["byte-unit/alloc"]` to `foo_features = []`?

**Comment by ehuss** [comment]
> What's the `target` table?

The `[target]` table is used for specifying [platform-specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies). It has its own set of dependencies, dev-dependencies, and build-dependencies.  See `TomlManifest.target`.

> Do you agree that `cargo package` and `cargo publish` should strip `foo_features = ["byte-unit/alloc"]` to `foo_features = []`?

No. `byte-unit` is still a valid dependency. For example, [crater](https://github.com/rust-lang/crater/) is a tool the rust-lang org uses to download all crates from crates.io, and it needs dev-dependencies in or to run tests. In some situations, the features may need to be kept. It is otherwise harmless to keep them there.

It only really needs to strip the features when the dependency is completely removed via the `is_version_specified` filter. Also, it needs to consider if the dependency is specified in both `dev-dependencies` and one of the other dependency tables.

**Comment by ehuss** [comment]
@eval-exec Just checking in if you are still interested in working on this, or if you have any questions.

**Comment by ehuss** [comment]
I'm going to close due to inactivity. If you are interested in continuing on this, feel free to reopen (just beware that due to a quirk in GitHub, if you push to your branch before reopening that you'll need to open a new PR instead).
Thanks for your contribution.

**Pull request closed without merging**
