### PR TITLE
Update git2 crates for libgit2 0.28

### PR DESCRIPTION
**Pull request by cuviper**
See https://github.com/rust-lang/git2-rs/pull/425

### CODE REVIEW

**Comment by alexcrichton** [comment]
It looks like the error message for auth failures was teaked a bit on Windows perhaps?

**Comment by ehuss** [comment]
It's not just a change in the message.  This is #4591 resurrected.  There is a very subtle distinction here where the expected error is what happens when the credentials are retrieved, but rejected by the server.  The (new) error that is popping up is what happens when the credentials are **not** successfully retrieved.

I haven't looked specifically, but I suspect maybe newer versions of libgit handle `sh` on windows differently?  See the linked issue (and the upstream git2-rs issue) for more details on what can cause this.

**Comment by alexcrichton** [comment]
Ah that's a good point, I've confirmed locally that this is caused by https://github.com/rust-lang/git2-rs/pull/402, although I'm not sure why yet.

**Comment by alexcrichton** [comment]
Ok I think that change to git2-rs is ok and this is just a bug in the test.

I think that https://github.com/rust-lang/git2-rs/pull/429 plus https://github.com/rust-lang/cargo/pull/7018/commits/c35c90028e5d6926ad7cbe0fdcdda286853b0307 should do the trick.

**Comment by cuviper** [comment]
Great, thanks for figuring it out!

**Pull request merged**
