### PR TITLE
Add `no-stack-check` manifest option

### PR DESCRIPTION
**Pull request by koute**

### CODE REVIEW

**Comment by koute** [comment]
I would very much like to be able to pass the `-C no-stack-check` to the compiler. I'm writing an emulator in Rust and I would like to:

   - squeeze as much performance as I can - it's probably not much, but always something, and I don't care too much about safety in this project,
   - not crash; I implemented an extremely lightweight userspace/green threads library for my emulator in assembly, and while it works fine when called from C it crashes when called from Rust due to stack checks; I don't really feel like unnecessarily complicating my code supporting a feature I don't even need, and it's not even possible to support it without copy-pasting the code from rust's stdlib, since `sys` is private; I don't want that kind of maintenance burden in case you'll decide in the future to store the stack bounds in a different TLS slot or something,
   - still use cargo for building my project (otherwise I'll just be forced to make a `Makefile` wrapping `cargo` and panic in my `build.rs` when the user uses `cargo` directly; ugh...)

**Comment by alexcrichton** [comment]
Thanks for the PR! Right now, however, Cargo is not currently trying to expose all the options of the compiler at the top-level configuration. There's definitely a real use case here of configuring the codegen options of the entire compile, but we'd want to think about this in a more principled fashion than adding all the options at the top-level.

For now I'd recommend using the `RUSTC` environment variable or the `build.rustc` config option to specify your own custom compiler, and you can then customize various flags through that.

**Comment by koute** [comment]
I expected as much; it was worth a shot though. (:

Sorry for asking a vaguely related thing, but - if I'd make a pull request exposing `record_os_managed_stack_bounds` from [`libstd/sys/common/stack.rs`](https://github.com/rust-lang/rust/blob/c21fd9a34f763c532ded7bf141b90a01cef76c43/src/libstd/sys/common/stack.rs) under `std::rt` would it have a chance to be accepted?

At first I thought that `no-stack-check` would be enough, but upon further investigation I've discovered that any userspace threading implementation (mine and [coroutines-rs](https://github.com/rustcc/coroutine-rs) included) needs access to `record_os_managed_stack_bounds` to not crash - while you can use the `no-stack-check` codegen option for code you compile the standard library crates still have `__morestack` calls embedded in them. The only thing you can do right now is to copy-paste the `stack.rs` from Rust into your own crate (e.g. [see here](https://github.com/rustcc/coroutine-rs/blob/master/src/sys.rs)) which is not ideal for obvious reasons.

**Comment by alexcrichton** [comment]
Yeah feel free to send a PR! We're unlikely to stabilize the interface any time soon (we'd prefer to move to stack probes on all platforms), but intermediate changes are fine :)

**Pull request closed without merging**
