### PR TITLE
Address autobins warning.

### PR DESCRIPTION
**Pull request by ehuss**
Removes the large warning displayed if you build Cargo with itself (but adds a warning if you build with an older Cargo).  Not sure which approach you prefer to address it, or if you want to do this later.

### CODE REVIEW

**Comment by matklad** [comment]
>Yea, I just realized that this will cause a lot of test failures when run with an older version.

Hm, perhaps we then should hold off issuing the warning until we have a stable Cargo which supports `autobins = false`?

That way, projects, which use both nightly and stable, could fix the warning without much of a hassle. On the other hand, the fix of "reshuffle directory structure so that conventions just work" seems to be better anyway.

**Comment by matklad** [comment]
@bors r+ 

Thanks!

**Comment by ehuss** [comment]
> Hm, perhaps we then should hold off issuing the warning

I was mistaken in my previous comment.  However, I do foresee this affecting a lot of projects (I've already seen it in the handful that I've tested with).  I agree the renaming approach is much better.

**Comment by ehuss** [comment]
Hm, I don't fully understand the error.  It looks like the rustc error message got interleaved with cargo's output:
```
Compiling error: Unrecognized option: 'edition'
foo v0.0.1 (...)
```
Where that should say:
```
Compiling foo v0.0.1 (...)
Running ...
error: Unrecognized option: 'edition'
```

Is that a known issue?

**Comment by alexcrichton** [comment]
@bors: r+

Hm that looks like a werid spurious error, somehow a race but I'm not entirely sure how?

**Comment by dwijnand** [comment]
Just saw this PR (because of the merge conflict fallout it's had), and wanted to say: feel free to ping me if tweaks are required to `autobins` (and friends) - I'm going to be AFK for a week, but I'm particularly happy to try to help around changes I've made (and therefore code paths I've somewhat learnt).

**Pull request merged**
