### PR TITLE
Fix listing of untracked files to not include tracked but modified ones

### LINKED ISSUE #2199: Cargo.toml is sometimes included twice in the .crate when packaging
e.g. packaging https://github.com/sfackler/rust-postgres/commit/9cb5cad656c19081ec71a55c54f6acf005d5c56f
```
 ❯ cargo clean
 ❯ cargo package
   Packaging postgres v0.10.2 (file:///home/sfackler/rust/rust-postgres)
   Verifying postgres v0.10.2 (file:///home/sfackler/rust/rust-postgres)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.2
   Compiling winapi-build v0.1.1
   Compiling byteorder v0.4.2
   Compiling hex v0.1.0
   Compiling winapi v0.2.5
   Compiling phf_shared v0.7.9
   Compiling bufstream v0.1.1
   Compiling cfg-if v0.1.0
   Compiling advapi32-sys v0.1.2
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.1
   Compiling log v0.3.4
   Compiling phf v0.7.9
   Compiling rand v0.3.12
   Compiling net2 v0.2.19
   Compiling phf_generator v0.7.9
   Compiling phf_codegen v0.7.9
   Compiling postgres v0.10.2 (file:///home/sfackler/rust/rust-postgres/target/package/postgres-0.10.2)
 ❯ tar tzf target/package/postgres-0.10.2.crate
postgres-0.10.2/Cargo.toml
postgres-0.10.2/LICENSE
postgres-0.10.2/README.md
postgres-0.10.2/THIRD_PARTY
postgres-0.10.2/build.rs
postgres-0.10.2/src/error.rs
postgres-0.10.2/src/io/mod.rs
postgres-0.10.2/src/io/openssl.rs
postgres-0.10.2/src/io/security_framework.rs
postgres-0.10.2/src/lib.rs
postgres-0.10.2/src/macros.rs
postgres-0.10.2/src/md5.rs
postgres-0.10.2/src/message.rs
postgres-0.10.2/src/notification.rs
postgres-0.10.2/src/priv_io.rs
postgres-0.10.2/src/rows.rs
postgres-0.10.2/src/stmt.rs
postgres-0.10.2/src/types/bit_vec.rs
postgres-0.10.2/src/types/chrono.rs
postgres-0.10.2/src/types/mod.rs
postgres-0.10.2/src/types/rustc_serialize.rs
postgres-0.10.2/src/types/serde.rs
postgres-0.10.2/src/types/serde_json.rs
postgres-0.10.2/src/types/slice.rs
postgres-0.10.2/src/types/time.rs
postgres-0.10.2/src/types/uuid.rs
postgres-0.10.2/src/url.rs
postgres-0.10.2/src/util.rs
postgres-0.10.2/Cargo.toml
```

Packaging an fresh `cargo new`'d crate doesn't do it so I'm not sure what the exact conditions are.

### PR DESCRIPTION
**Pull request by felixc**
The logic in `sources/path.rs` that finds files that are untracked by the version control system was incorrectly including files that *are* tracked, but had been modified without the modification being committed to Git.

This manifested itself as strange duplications of files (e.g. in `cargo package --list`), since they were listed once as tracked files, and once more as allegedly "untracked" ones. It also caused failures when trying to package the crate when files had been deleted, but the deletion was not yet committed to Git.

Fixes #2199

### CODE REVIEW

**Comment by felixc** [comment]
Build failure appears to be an upstream problem with https://github.com/rust-lang-nursery/rand not compiling with the latest nightlies, and affects all PRs as well as HEAD.

**Comment by alexcrichton** [comment]
Thanks! Could you also add a test for this? Also feel free to `cargo update -p rand` to fix the breakage on travis.

**Comment by felixc** [comment]
Thanks for the prod to add the test :) I felt it needed one but didn't bring myself to poke at the existing test code to figure out how it worked. A bit of extra motivation did the trick, and the code is better now there's a test in place!

(That said, I found the git helper test utility a bit mystifying, so suggestions for how to do this better would be appreciated)

**Comment by alexcrichton** [comment]
@bors: r+ e2cd4cdb52ecdefeae4b451d7316ac8f82606a3f

Looks good to me, thanks!

**Pull request merged**
