### PR TITLE
Upgrade env_logger

### PR DESCRIPTION
**Pull request by sfackler**
0.4 depends on log 0.3 and so misses out on module names.

### CODE REVIEW

**Comment by alexcrichton** [comment]
We've unfortunately gotten bitten in the past because of prerelease versions. I think Cargo will consider it semver compatible with 0.5.0 for example? (which sometimes has API breaking changes).

@KodrAus out of curiosity, do you know if 0.5.0 will happen soon?

**Comment by sfackler** [comment]
I can switch it to an equality constraint, but a full 0.5.0 release would be best, yeah.

**Comment by alexcrichton** [comment]
@KodrAus [mentioned](https://github.com/rust-lang/rust/pull/47161#issuecomment-358105849) that `env_logger` is close to an 0.5 release (like in the next day or two), so r=me if we hold out for that and then update here.

**Comment by sfackler** [comment]
👍

**Comment by KodrAus** [comment]
Thanks @sfackler! Yep, I'm pushing out `0.5` today, just checking the docs now for typos and broken links. There are a few differences between the versions you might be interested in for `cargo`:

- `env_logger` now depends on `chrono`
- `env_logger` now include a timestamp in the format by default. If this is too noisy we can tweak the format to remove it
- `env_logger` now writes colours, read from an environment variable by default

I spiked out an upgrade that tried to maintain the cargo command's own colour choice [here](https://github.com/rust-lang/cargo/compare/master...KodrAus:chore/env-logger-0.5). If you ignore the fact that it leaks it's a lot of machinery for coloured output, but if folks want coloured logs from cargo using `env_logger` I think we'll need _something_ like that.

The simpler approach would be something like:

```rust
env_logger::Builder::from_env(env_logger::Env::default())
    .write_style(env_logger::WriteStyle::Never)
    .init();
```

So that we never write coloured logs.

**Comment by alexcrichton** [comment]
Looks like a new version is out! @sfackler want to update this PR?

**Comment by alexcrichton** [comment]
Thanks @KodrAus!

**Comment by sfackler** [comment]
Updated!

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @sfackler!

**Pull request merged**
