### PR TITLE
Append only git checkouts

### LINKED ISSUE #3209: cargo run can cause blocked waiting for file lock on git checkout
If you have git based crate dependencies in your `Cargo.toml` and you run `cargo run` in that project. You will not be able to do another `cargo build` until after the original `cargo run` has exited. Once the build step for the `cargo run` has completed their should be no need for a source lock.

ref #2627

### PR DESCRIPTION
**Pull request by matklad**
Ok, so this should fix #3209 by using a full git revision as the name of the checkout path. 

I don't fully understand the code here, and I haven't thought about backwards/forwards compatibility hard, but the approach should be viable, and maybe even the implementation here is OK?

### CODE REVIEW

**Comment by matklad** [comment]
I've looks through this once again and it looks reasonable. 

suppose you have `libc = {git="https://github.com/rust-lang/libc"}` in your cargo toml. 

Previously the layout was

```
.cargo/
  git/
    db/
      libc-url_hash/
    checkouts/
      libc-url_hash/
        master/
```

Now it is

```
.cargo/
  git/
    db/
      libc-url_hash/
    checkouts/
      libc-url_hash/
        commit-hash/
```

**Comment by alexcrichton** [comment]
Nice! This is definitely a great way to get rid if the global lock on git dependencies, and also operates very similarly to registries.

@wycats I'm curious, though, I feel like this is something that bundler explicitly avoided in the past? Or perhaps am I misremembering? The tl;dr; here is that we still have a git database but git checkouts are now per-revision instead of per-branch. That means that if you `cargo update` you'll create a whole new checkout each time the git repo is updated, but it conversely means that we can have parallel builds with git repos as everything is immutable once checked out.

**Comment by alexcrichton** [comment]
Ok, I remember talking with wycats a bit about this offline, so I'm going to go ahead and r+. Thanks @matklad!

@bors: r+

**Pull request merged**
