### PR TITLE
Implement install --all

### LINKED ISSUE #4101: Suppport `cargo install --all`
There seems to be no easy way currently to install all binaries from all crates in a given workspace. Instead, `cargo install` has to be called for all of them separately. It would be nice if `cargo install` supported a `--all` flag to recurse into all crates of the workspace.

Does this seem to make sense?

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This patch tries to implement `cargo install --all` for installing all
"bin" crates from a workspace project.

Signed-off-by: Matthias Beyer <mail@beyermatthias.de>

---

I doubt that it is this simple, but I guess this is the first step.

Closes #4101 

---

My `cargo test` fails, but I guess that's not because of my changes but rather because I cannot crosscompile:

```
test linker_and_ar ... FAILED

failures:

---- linker_and_ar stdout ----
	thread 'linker_and_ar' panicked at 'Cannot cross compile to i686-unknown-linux-gnu.

This failure can be safely ignored. If you would prefer to not see this
failure, you can set the environment variable CFG_DISABLE_CROSS_TESTS to "1".
', tests/cargotest/support/cross_compile.rs:88:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    linker_and_ar

test result: FAILED. 18 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test cross-compile'
```

### CODE REVIEW

**Comment by matklad** [comment]
cc https://github.com/rust-lang/cargo/pull/4943#issuecomment-363268607, @withoutboats

**Comment by alexcrichton** [comment]
Thanks! Could you be sure to add a test for this as well?

@matklad this may end up being somewhat orthogonal to that as "install the package/workspace at cwd" I think may just become a flag rather than being implicit

**Comment by matklad** [comment]
I am also unsure how this should interact with `--bins` and `--examples`... 

For example, I believe that if you have a crate which contains an example, but does not contain a binary, than `cargo install --all --examples` **will not** install this example, which does seem surprising. 

My gut feeling (which might be totally wrong! :) ) is that we should try do use the same semantics for `--all` which we use for all other commands. That is, to add an `--exclude` flag as well, and do something like this: https://github.com/rust-lang/cargo/blob/ed8dfce4c119dca307c428e879a075bd24ab51b8/src/bin/build.rs#L103-L105.

**Comment by alexcrichton** [comment]
Hm true yeah! I agree we should add `--exclude` for consistency if we add `--all`, but it's a good point about `--bins` and `--examples`... I dunno how to rationalize that without adding this though :(

**Comment by alexcrichton** [comment]
I'm gonna close this for now as it's pretty out of date at this point, but it can of course be resubmitted!

**Pull request closed without merging**
