### PR TITLE
Target-specific features reimplemented #1197

### PR DESCRIPTION
**Pull request by plyhun**
r? @alexcrichton

### CODE REVIEW

**Comment by plyhun** [comment]
```
failures:

---- build::deterministic_cfg_flags stdout ----
running `/home/vsts/work/1/s/target/debug/cargo build -v`
thread 'build::deterministic_cfg_flags' panicked at '
Expected: execs
    but: differences:
  3 - |[RUNNING] `rustc --crate-name foo [..] --cfg[..]default[..]--cfg[..]f_a[..]--cfg[..]f_b[..]--cfg[..]f_c[..]--cfg[..]f_d[..] --cfg cfg_a --cfg cfg_b --cfg cfg_c --cfg cfg_d --cfg cfg_e`|
    + |     Running `rustc --crate-name foo src/main.rs --color never --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="f_a"' --cfg 'feature="default"' --cfg 'feature="f_b"' --cfg 'feature="f_c"' --cfg 'feature="f_d"' -C metadata=135da3956bdec8cb -C extra-filename=-135da3956bdec8cb --out-dir /home/vsts/work/1/s/target/cit/t219/foo/target/debug/deps -L dependency=/home/vsts/work/1/s/target/cit/t219/foo/target/debug/deps --cfg cfg_a --cfg cfg_b --cfg cfg_c --cfg cfg_d --cfg cfg_e`|
```
Happens because of `features_sorted()` replaced with `features()`. Will fix ASAP.

**Comment by Eh2406** [comment]
Thanks for the submission! I don't have time to give this the review it deserves. I am sorry.
Currently the lockfile that is generated is completely independent of the system it is built on, does this PR maintain that property?
The metadata output is stable so we need to be careful to include the new info in a way that doesn't break anyone.

(cc #1197)

**Comment by plyhun** [comment]
I was relying on the unit tests to keep the existing functionality alive, did not pay a specific attention to the lock files (though no new information should be added to the lockfile, as far as I have inspected several of the live projects that I need the platform features for). Perhaps if you find a need to check the lockfile stability, I may try implementing it as a unit test.
In principle, my change replaces the `str/String/InternedString` that replesents a feature, with a tuple `(str/String/InternedString, Option<Platform>)`, and `Set<String>` with `Map<String, Option<Platform>>`, for the places where the parser interacts with the input Cargo.toml and the platform triple.

**Comment by Eh2406** [comment]
The tricky case I see is 
 `root` depends on `a` and `c="1.1.0"`
`a` depends on `b` and on OSX depends on `b`'s flag `maybe`
`b` depends on `c="=1.0.0"` if `maybe` is active.
`c v1.0.0` and `c v1.1.0` has no dependency

On OSX we get an error "can not have two semver compatible versions of `c`". Do we get that error on Windows?

**Comment by plyhun** [comment]
Something utterly terrible had happened during the upstream merge.

**Pull request closed without merging**
