### PR TITLE
Disable `frozen_flag_preserves_old_lockfile` test

### PR DESCRIPTION
**Pull request by nrc**
r? @alexcrichton cc @matklad

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Before we do this, I'd want some confirmation that we haven't actually somehow regressed behavior here. This test is critical to Rust today: we cannot run crater due to lockfile differences if it fails.

In general, this (IMO) is P-high to re-enable if we do disable it IMO.

**Comment by nrc** [comment]
> Before we do this, I'd want some confirmation that we haven't actually somehow regressed behavior here

Whether we've regressed behaviour or not, this test is still buggy and having the buggy test present isn't preventing any behaviour regressing, it's just blocking other code landing (which would fix an important regression).

**Comment by Mark-Simulacrum** [comment]
Yeah, that's true. I think we can actually mark the test as `#[ignore]` instead of commenting it out. Unfortunately, this can't land until https://github.com/rust-lang/rust/issues/46271 is fixed AFAICT.

I guess I'm okay with landing even without confirming, but I'd prefer that we confirmed. Either way, I guess, it's a high priority thing to fix this test.

**Comment by alexcrichton** [comment]
I've found the failure, will submit a fix shortly.

**Comment by alexcrichton** [comment]
Ok I've opened up https://github.com/rust-lang/cargo/pull/4762 with what I believe is the fix. I'm gonna close this for now but if that doesn't fix it we can reopen an temporarily disable!

**Pull request closed without merging**
