### PR TITLE
Don't accumulate feature and rustdoc flags twice (fixes #4790)

### LINKED ISSUE #4790: RUSTDOCFLAGS passed twice in 'cargo test'
```sh
cargo new foo
cd foo
RUSTDOCFLAGS="--document-private-items" cargo +nightly test -v
```
```rust
       Fresh foo v0.1.0 (file:///tmp/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/tmp/foo/target/debug/deps/foo-347a4c2a546f5546`

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests foo
     Running `rustdoc --test /tmp/foo/src/lib.rs --crate-name foo -L dependency=/tmp/foo/target/debug/deps -L dependency=/tmp/foo/target/debug/deps --extern foo=/tmp/foo/target/debug/deps/libfoo-01aa8301b833d22c.rlib --document-private-items --document-private-items`
rustdoc: Option 'document-private-items' given more than once
Try 'rustdoc --help' for more information.
error: test failed, to rerun pass '--doc'
```

Regression range https://github.com/rust-lang/cargo/compare/5bb478a5...930f9d94 includes https://github.com/rust-lang/cargo/pull/4740, CC @nox

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
@alexcrichton Not sure this is the right way to do it, but that loop over *units* which accumulates *package*-specific things in `Compilation` doesn't seem correct to me.

**Comment by alexcrichton** [comment]
Unfortunately it's sort of the best we can do right now :(. The abstraction of `Unit` in the compilation phase doesn't always match up exactly to the outside requirements (as the backend can often be quite subtle). 

Looks like the previously added test may no longer be passing?

**Comment by nox** [comment]
This is weird, hah.

@alexcrichton What do you think of just not updating the entries in `cfgs` and `rustdocflags` if they already exist, in the loop over units?

**Comment by alexcrichton** [comment]
Yeah that could work I think, especially if the data that's being loaded is keyed off just the `package_id` itself.

**Comment by nox** [comment]
@alexcrichton Amended commit is amended, the two tests pass, but maybe I broke others, hah.

**Comment by nox** [comment]
@alexcrichton I made the test use `display-warnings` instead of `document-private-items`, given the latter isn't yet in stable. r?

**Comment by alexcrichton** [comment]
Looks like tests may still be failing?

**Comment by alexcrichton** [comment]
@bors: r+

Oops sorry, didn't see the update!

**Pull request merged**
