### PR TITLE
Package lock files in published crates

### LINKED ISSUE #2263: Packages for binary crates should include Cargo.lock
`Cargo.lock` is always excluded from packages generated by `cargo package`.  This means that it can't be used by `cargo install` when installing from crates.io.  Should this be changed for crates that contain binaries, in order to make `cargo install` more reproducible for these binaries?

### PR DESCRIPTION
**Pull request by alexcrichton**
Previously we had logic to explicitly skip lock files but there's actually a
good case to read these from crates.io (#2263) so let's do so!

Closes #2263

### CODE REVIEW

**Comment by matklad** [comment]
The changes look good to me, however I am not sure that literally pushing the lock file would do what we want here...

Specifically, I believe this fails for workspaces, which have the lockfile only for the root, which may be virtual and not published at all.

**Comment by alexcrichton** [comment]
Hm do you think we should always copy in the workspace's lock file unconditionally? That should cover that issue I think?

**Comment by alexcrichton** [comment]
Inclusion is currently based on gitignore so if you've got a library crate then `Cargo.lock` shouldn't be included w/ this PR. 

I'm not really sure? If we don't know how to do this I'll just close it...

**Comment by matklad** [comment]
>If we don't know how to do this I'll just close it...

Yeah, I am not really sure, for the following reasons:

* It's not clear what to do with workspaces.
* Lockfile is added based on "is it in gitignore" and not on "is it a binary crate". Granted, most commonly these are equivalent, but they are not guaranteed to be equivalent. 

On the other hand, this literally just removes ignoring "Cargo.lock", and can't possible do any harm, and will be compatible with any fancier solution we can invent. 

Yeah, I guess it's fine to r+ it as is (module a failing on windows), because it does solve the problem in 80% of the cases!


Hm, wait... Is it correct that publishing a lockfile won't break a binary? What if a binary is a workspace root, and it has path dependencies? We rewrite Cargo.toml, but we don't rewrite Cargo.lock. Would installing a binary in this situation fail with some kind of lockfile mismatch, or will we just generate a new lockfile? If the letter, let's r+, if the former, let's think about how to solve the workspace problem in a more principle way :)

**Comment by alexcrichton** [comment]
Ok I've updated with a few heuristics:

* Lock files are only included in packages with binaries/examples (those that can be cargo-install'd)
* Lock files are always copied in from the workspace root
* Including a lock file is now a nightly feature

That means that `cargo publish` should work wherever you are in a workspace and always include the lock file regardless of vcs settings. Upon thinking more about this as well it seems like a bad default as it means if you ever want your users to get updated versions of dependencies you've got to publish a new version. In that sense I felt that we'd want this opt-in which requires a new manifest key, hence starting as a nightly feature.

**Comment by phil-opp** [comment]
How do I use this functionality. With the default settings, there is no `Cargo.lock` on crates.io. With the nightly `publish-lockfile` manifest key set to true, I can no longer publish my crate:

```
error: cannot publish crates which activate nightly-only cargo features to crates.io
```

What am I missing?

**Comment by alexcrichton** [comment]
@phil-opp heh I think you've discovered a bug! The tests here only test packaging, not actual publication, which is why that hasn't been exercised before.

**Comment by phil-opp** [comment]
@alexcrichton Should I open an issue for this? What would be the best way to resolve this?

**Comment by alexcrichton** [comment]
@phil-opp yes, please do!

**Pull request merged**
