### PR TITLE
Display the name of the unknown subcommand.

### LINKED ISSUE #2825: no such subcommand doesn't print the command, which hinders troubleshooting
When `cargo` is run with a command that is not recognized, it prints *suggestion* of a valid command, but doesn't print the actual command that was rejected.

This is fine when cargo is run from an interactive shell. However, when cargo is run as part of a script or — in my case — [Sublime Linter plugin](https://github.com/oschwald/SublimeLinter-contrib-rustc/issues/25), this becomes a problem, because the command line is not visible. When only the printed output is available in the log, it's impossible to see what command was really meant.

> SublimeLinter: rust output:
> error: no such subcommand
>
>	Did you mean `clean`?

### PR DESCRIPTION
**Pull request by KaivoAnastetiks**
?r @alexcrichton 
Fixes #2825

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks @KaivoAnastetiks! Can you be sure to add a test for this as well?

**Comment by KaivoAnastetiks** [comment]
@alexcrichton, I'll check it out tonight and let you know if I have any
question. Thanks!

**Comment by KaivoAnastetiks** [comment]
@alexcrichton I added a test while also correcting the two other tests for find_closest. I also found out that I missed the case where we don't find a closest.

**Comment by alexcrichton** [comment]
@bors: r+ 1671630b6142912c2813266e6550a0b717e66e76

Thanks!

**Pull request merged**
