### PR TITLE
don't build/run doctests when target != host

### PR DESCRIPTION
**Pull request by japaric**
fixes rust-lang/rust#31907

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ fa341342538240b98ef53193770a1b30aec47ee0 

Thanks!

**Comment by japaric** [comment]
Pushed a commit fixing the cross_tests test

**Comment by japaric** [comment]
(I don't think I have r+ rights here, but worth a shot)

@bors: r=alexcrichton

**Comment by japaric** [comment]
Pushed a commit fixing my previous fix

**Comment by alexcrichton** [comment]
but who fixes the fix of the fix?!

@bors: r+

**Pull request merged**
