### PR TITLE
missed this important bug

### PR DESCRIPTION
**Pull request by Eh2406**
In the PR #5000 I finished and we merged yesterday I missed a bug and left in an outdated comment.

@alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh nice catch! Out of curiosity, would it be possible to easily add a test for this as well? (if not no worries)

**Comment by Eh2406** [comment]
Looking into it more closely I think activation hits the `MissingFeatures` before it modified cx. So I think I was wrong, and this is not technically a bug. So I can't add a test. It is more a loaded foot gun for anyone adding to the kinds of activation errors. Which is how I came across it, I am working on a performance related PR that involved adding another activation error, and most of the existing test blew up in my face.

I will get ci green in a sec.

**Comment by alexcrichton** [comment]
Ah ok! Sounds good to me to merge when gree nthen

**Comment by Eh2406** [comment]
CI is green except for a spurious network error.

**Comment by alexcrichton** [comment]
@bors: r+

Oh dear, that test should be updated to not hit the real index...

**Comment by Eh2406** [comment]
Added a commit that should help with the spurious network error.
How do I update the test to not hit the real index?
The test timeout I don't understand, the link is https://ci.appveyor.com/project/rust-lang-libs/cargo/build/1.0.3765 I think. but that seems unrelated to my change.

**Comment by alexcrichton** [comment]
@bors: r+

Oh I've generally used `Pakage::new("foo", "0.1.0").publish()` which rewrites the test's home directory to use a per-test index instead.

**Pull request merged**
