### PR TITLE
fix(test): Distinguish 'testname' from escaped arguments 

### LINKED ISSUE #11191: cargo runs disabled unit tests when arguments are pased via `--`
### Problem

In a crate with
```
[lib]
test = false
```
usually cargo does not build and run the unit tests for the lib crate. However when doing `cargo test -- x`, they *do* get built and run. This seems to be a recent regression.

### Steps

1. `cargo new --lib mylib`, `cd mylib`
2. edit `Cargo.toml` to add
```
[lib]
test = false
```
3. Run `cargo test`. It only runs doctests:
```
   Doc-tests myib

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
4. Run `cargo test -- x`. Now it runs the disabled unittests:
```
     Running unittests src/lib.rs (target/debug/deps/myib-81de13cd7bf5f5d9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
```
It also does *not* run the doctests.
(This only happens with nightly. With stable, it runs the doctests.)

I would expect it to behave like stable, where it runs the doctests (and passes `x` to the test runner as a filter).

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.66.0-nightly (0b84a35c2 2022-10-03)
release: 1.66.0-nightly
commit-hash: 0b84a35c2c7d70df4875a03eb19084b0e7a543ef
commit-date: 2022-10-03
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Debian testing (bookworm) [64-bit]
```

### PR DESCRIPTION
**Pull request by epage**
When working on clap v4, it appeared that `last` and `trailing_var_arg`
are mutually exclusive, so I called that out in the debug asserts in
#4187.  Unfortunately, I didn't document my research on this
as my focus was elsewhere.

When updating cargo to use clap v4 in #11159, I found `last` and
`trailing_var_arg` were used together.  I figured this was what I was
trying to catch with above and I went off of my intuitive sense of these
commands and assumed `trailing_var_arg` was intended, not knowing about
the `testname` positional that is mostly just a forward to `libtest`,
there for documentation purposes, except for a small optimization.

So it looks like we just need the `last` call and not the
`trailing_var_arg` call.

This restores us to behavior from 531ce1321d282d3a975d0799a322e6bd20f4c3c6 which is what I originally
wrote the tests against.

It looks like #11159 was merged after the last beta branch was made, so we shouldn't 
need to cherry-pick this into any other release.

For reviewing this, I made the test updates in the first commit, showing the wrong behavior.  The following commit fixes the behavior and updates the tests to expected behavior.

Fixes #11191

### CODE REVIEW

**Review by weihanglo — APPROVED** [review]
Sorry for my oversight on this behaviour change.

Could you help double confirm that `cargo run`, `cargo rustc`, and `cargo rustdoc` are not affected? From my understanding they should behave as before and just tested by hands them seem fine.

**Comment by weihanglo** [comment]
Feel free to `r=weihanglo` once you've done the confirmation. I may update Cargo in `rust-lang/rust` after this get merged.

**Comment by epage** [comment]
> Could you help double confirm that cargo run, cargo rustc, and cargo rustdoc are not affected? From my understanding they should behave as before and just tested by hands them seem fine.

Those commands are unrelated to the problem.  This is a problem specifically with how I handled the change from `.last(true).trailing_var_arg(true)` which only affected `cargo bench` and `cargo test` (I searched  #11159 multiple times to confirm).  Even then, the only way to observe a problem is if people are relying on the [specialization of logic that exists only in cargo test](https://github.com/rust-lang/cargo/blob/c71f344cbc801af944126806d2da76d5088b8ad5/src/bin/cargo/commands/test.rs#L98)..  This precludes observing a change in behavior in `cargo bench` as it just takes `BENCHNAME` and prefixes it to `args` without any logic conditioned on the existence of `BENCHNAME`; no matter whether `--` is used or not, the same behavior will occur.  It took me several tries to even create a good test case for `cargo test` that clearly showed the problem due to how specific the relevant problem is.

> Sorry for my oversight on this behaviour change.

Responsibility first lies with the author, reviewers can't be expected to catch everything. Unless you knew to check this  exact case, I bet we would have missed it anyways.

r=weihanglo

**Comment by epage** [comment]
@bors r=weihanglo

(of course I forgot to tag bors)

**Comment by weihanglo** [comment]
I should have thought of that, since I did some fixes around it…

Anyway, thanks for your quick patch!

**Comment by CAD97** [comment]
(hi I'm the one that found the behavior change)

It's definitely good to restore previous behavior here, but it's also I think worth discussing whether `cargo test TESTARG` and `cargo test -- TESTARG` *should* be behaving differently.

To me, it seems quite odd that being explicit about which arguments are passed to the test runner should change how the test runner is run.

Plus, in general, due to how rustdoc (ab)uses the test runner, flags can have distinctly different behavior. (The notable one I'm dealing with is `--ignored`.)

**Comment by epage** [comment]
> (hi I'm the one that found the behavior change)
> 
> It's definitely good to restore previous behavior here, but it's also I think worth discussing whether `cargo test TESTARG` and `cargo test -- TESTARG` _should_ be behaving differently.
> 
> To me, it seems quite odd that being explicit about which arguments are passed to the test runner should change how the test runner is run.
> 
> Plus, in general, due to how rustdoc (ab)uses the test runner, flags can have distinctly different behavior. (The notable one I'm dealing with is `--ignored`.)

https://github.com/rust-lang/cargo/issues/6981 is the issue for that.

**Pull request merged**
