### PR TITLE
test: migrate minimal_versions to snapbox

### PR DESCRIPTION
**Pull request by henry40408**
### What does this PR try to resolve?

Part of https://github.com/rust-lang/cargo/issues/14039.

Migrate `tests/testsuite/minimal_versions.rs` to snapbox.

### How should we test and review this PR?

N/A

### Additional information

N/A

### CODE REVIEW

**Comment by weihanglo** [comment]
Is there any reason this stays as a draft?

**Comment by henry40408** [comment]
@weihanglo no particular reason. I selected the wrong one when opening the PR.

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Nice. Thanks for the

**Pull request merged**
