### PR TITLE
_cargo: Make function style consistent

### PR DESCRIPTION
**Pull request by lzutao**
They are mostly white-space changes. I'm planning to bring back Zsh completion
for `-p` (package) option, which was disabled in #1713. This PR is the first 
stepping stone towards that goal.

A disadvantageous is that I am just starting to learn Zsh completion system.
Guess how far can I go?

r? @ehuss

### CODE REVIEW

**Comment by lzutao** [comment]
@ehuss Have you reviewed 2 commits I just push? I think you might skip them.

**Comment by ehuss** [comment]
I'm not sure what you mean.  I see 2 extra commits added 3 hours ago.  Is there something wrong with them?  Or were you intending to add more?

**Comment by lzutao** [comment]
No, I didn't. GitHub displayed 2 extra commits adding 3 hours ago is a lie.
I did some rebase on local and pushed it after I satisfied with the change.
Anyway, never mind if you approved this PR.

**Comment by ehuss** [comment]
Ah, no worries. :)

**Pull request merged**
