### PR TITLE
Bump git2 to 0.15 and libgit2-sys to 0.14

### PR DESCRIPTION
**Pull request by jonhoo**
This will allow cargo to avoid vendored builds of git2 in up-to-date
environments going forward, and brings in the [libgit2 1.4.4 CVE fix].

[libgit2 1.4.4 CVE fix]: https://github.com/libgit2/libgit2/releases/tag/v1.4.4

### CODE REVIEW

**Comment by ehuss** [comment]
I think to move forward with this cargo will need to call `libgit2_sys::set_verify_owner_validation(false)` in order to disable owner validation. We don't need that for security (cargo doesn't do discovery in any way that is a concern) and there are scenarios where it will trigger in typical environments.

**Comment by jonhoo** [comment]
Ah, yes, I remember from the discussion in https://github.com/rust-lang/rfcs/pull/3279. Will update!

**Comment by jonhoo** [comment]
One issue with setting that is that it's a global property. Which means that if someone has a project that uses `git2` separately from `cargo`, but _also_ runs `cargo`, then operations _they_ do with `git2` will also not have the owner check applied, which is probably unexpected. We could set it before each git operation and reset it after, though that feels brittle and racy. I wish it were possible to configure this option per repository...

**Comment by jonhoo** [comment]
There's [`git_repository_open_ext`](https://libgit2.org/libgit2/#v1.1.0/group/repository/git_repository_open_ext), but the [flags it supports](https://github.com/libgit2/libgit2/blob/7f4fa178629d559c037a1f72f79f79af9c1ef8ce/include/git2/repository.h#L98) don't include the owner check.

**Comment by jonhoo** [comment]
Having now dug through the libgit2 PR that introduced the ownership check, https://github.com/libgit2/libgit2/pull/6266, I don't see a way around this. Either we have to disable the check globally in something like `cargo::Config::new`, or we have to surround every call to `git2::Repository::open` (or `::init`? or `::clone`?) with a disable + do + enable dance which still risks racing with _other_ (non-Cargo) code to allow opening a repository there with the check unexpectedly disabled.

**Comment by ehuss** [comment]
I was thinking it can be called from `init_git_transports` or somewhere around there on the binary side.  That shouldn't affect cargo-lib users, and I believe is the only safe place to do it since it is an unprotected global.

**Comment by jonhoo** [comment]
We could do that, although it would mean that anyone using Cargo as a library would need to know to explicitly call that method themselves too. We could perhaps add a method like `Config::globally_disable_git_ownership_verification` so that consumers will at least a) not have to add `git2` as a direct dependency and b) hopefully discover that this is something they _may_ need to call?

**Comment by jonhoo** [comment]
One option might be to set the ceiling directories, which can be done per open, but as far as I can tell from the implementation that doesn't actually bypass the check either?

**Comment by weihanglo** [comment]
> We could perhaps add a method like `Config::globally_disable_git_ownership_verification`

This sounds lovely to me. And I believe people will eventually find it. As Cargo lib users, they must be accustomed to breakages between versions sometimes. (Sorry about that 😅)

**Review by weihanglo — APPROVED** [review]
I am going to merge this. Thanks for the pull request.

If @ehuss or anyone still concerns with this, feel free to comment.

**Comment by weihanglo** [comment]
I feel like this worth mentioning in release note, at least for library user?

**Comment by jonhoo** [comment]
I agree this should be mentioned in relnotes!

**Comment by ehuss** [comment]
fwiw, I always include libgit2 bumps in the Cargo changelog.  But I don't think this needs to be in the Rust release notes, does it? Are you concerned that third-party packages that link to the cargo API might run into problems here?

**Comment by ehuss** [comment]
Ah. Ok, I'll untag the relnotes. That label is only for [RELEASES.md](https://github.com/rust-lang/rust/blob/master/RELEASES.md).

**Comment by ehuss** [comment]
Oh, it was already removed. I was confused. 😄

**Pull request merged**
