### PR TITLE
Stabilize 2021 edition

### LINKED ISSUE #9781: Prepare stabilizing Rust 2021
Rust 2021 will probably be stabilied soon. Cargo also has knowledge of which editions are stable, so should be updated too. It'd be good to prepare that PR, so we can merge it as soon the edition is stabilized in rustc.

Alternatively, can we make it such that Cargo will allow `--edition=2021` but will not pass `-Z unstable-options` when the edition2021 cargo feature is not enabled? Then it'll be usable as soon as rustc allows it, without having to do the cargo change in sync.

### PR DESCRIPTION
**Pull request by ehuss**
This stabilizes the 2021 edition.

Closes #9781

### CODE REVIEW

**Comment by ehuss** [comment]
Opening a draft in preparation for when the 2021 edition is stabilized. This cannot be merged until the rustc side (https://github.com/rust-lang/rust/pull/88100) hits nightly.

**Review by alexcrichton — APPROVED** [review]

**Comment by m-ou-se** [comment]
https://github.com/rust-lang/rust/pull/88100 is merged, but due to some bors failures, it was only merged a few hours after nightly was released. So I guess we'll have to wait for the next nightly, in a bit more than 15 hours from now.

**Comment by m-ou-se** [comment]
If you rebase this on the master branch again, we could already bump the cargo submodule to this branch in the rust repository, if we don't want to wait. I think the tests will pass fine in that repository, without waiting for nightly, right?

**Comment by ehuss** [comment]
@alexcrichton This should be ready to go.

> I think the tests will pass fine in that repository, without waiting for nightly, right?

I would prefer to avoid bypassing the regular route here.  Thanks, though!  I'll take care of getting things merged tomorrow.

**Pull request merged**
