### PR TITLE
Bump to 0.75.0; update changelog

### PR DESCRIPTION
**Pull request by weihanglo**
[rendered](https://github.com/weihanglo/cargo/blob/version-bump/CHANGELOG.md)

### CODE REVIEW

**Comment by weihanglo** [comment]
Can't reproduce the resolver test failure. Could be a flaky test?

@bors try

**Comment by ehuss** [comment]
The resolver issue is #6258. I'm not sure what exactly is going on with that particular test. Maybe it needs more ticks to finish? Unfortunately due to its nature, there are pathological cases that can take an indefinite amount of time to finish, and proptesting can randomly hit those situations.

**Comment by ehuss** [comment]
It also looks like your try build hit another error:

```
---- registry_auth::token_not_logged stdout ----
req: Request {
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Ipv4(
                127.0.0.1,
            ),
        ),
        port: Some(
            39167,
        ),
        path: "/index/config.json",
        query: None,
        fragment: None,
    },
    method: "get",
    authorization: None,
    if_modified_since: None,
    if_none_match: None,
}
req: Request {
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Ipv4(
                127.0.0.1,
            ),
        ),
        port: Some(
            39167,
        ),
        path: "/index/config.json",
        query: None,
        fragment: None,
    },
    method: "get",
    authorization: Some(
        "a-unique_token",
    ),
    if_modified_since: None,
    if_none_match: None,
}
req: Request {
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Ipv4(
                127.0.0.1,
            ),
        ),
        port: Some(
            39167,
        ),
        path: "/index/config.json",
        path: "/index/config.json",
        query: None,
        fragment: None,
    },
    method: "get",
    authorization: Some(
        "a-unique_token",
    ),
    if_modified_since: None,
    if_none_match: None,
}
req: Request {
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Ipv4(
                127.0.0.1,
            ),
        ),
        port: Some(
            39167,
        ),
        path: "/index/3/f/foo",
        query: None,
        fragment: None,
    },
    method: "get",
    authorization: Some(
        "a-unique_token",
    ),
    if_modified_since: None,
    if_none_match: None,
}
thread 'registry_auth::token_not_logged' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `7`', tests/testsuite/registry_auth.rs:498:5
```

I don't think I have seen that before. I'm not really sure what might have caused that. We should consider adding some more debug information to that test.

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Comment by ehuss** [comment]
Proptest error # #6258 again 😦 .

@bors retry

**Pull request merged**
