### PR TITLE
Show how to set license in guide's example

### PR DESCRIPTION
**Pull request by edunham**
I hope that this will gently remind users that it's best practices to license
their code.

### CODE REVIEW

**Comment by steveklabnik** [comment]
So, I like this, but I also don't like the idea of picking a specific license in the example.

The other problem is that this doesn't work: Cargo doesn't generate this, which is how the tutorial works.

Maybe we can address this another way?

**Comment by alexcrichton** [comment]
I agree that choosing one would be nice to avoid, perhaps something like `license = "..."` and then a comment pointing where to get a list from?

**Comment by apasel422** [comment]
This could also incorporate a demonstration of #2013, if it's merged.

**Comment by alexcrichton** [comment]
I'm gonna close this for now (been inactive for awhile), but we'll likely revisit if #2013 is rebased/landed as part of the documentation!

**Pull request closed without merging**
