### PR TITLE
don't write a an incorrect rustc version to the fingerprint file

### PR DESCRIPTION
**Pull request by Eh2406**
In making https://github.com/holmgr/cargo-sweep/pull/14 I noted that some fingerprint files related to build scripts report being built with a rustc that hashes to "0". To work around this I just marked them as still being needed, even though no rustc that hashes to "0" is currently installed.

I believe that this PR just filles in the correct info for the build script fingerprints. This makes it possible for outside tools to more reliably clean up after cargo, at basically no cost.
@ehuss Thanks again for the help.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is actually somewhat intentional in the sense that the fingerprint file here is for a build script's execution rather than the binary itself. That means that the rustc binary isn't actually an input to the execution itself?

**Comment by Eh2406** [comment]
I believe that is technically true. From my experimentation (please correct me if I am wrong) there is no way to reuse the files between invocations involving difrentvertions of rust. I think this is because the hash in the folder name includes the version of rust, and even if that were fixed the hash includes the hash of the dependencies fingerprints which include the rust version. So if (I am correct and) there is in practice no reuse between different versions of rust, then we may as well make it clear.

**Comment by alexcrichton** [comment]
That sounds right to me yeah! In some cases we may too aggrressively include the upstream hashes too...

**Pull request merged**
