### PR TITLE
Fix warning about private types in API.

### PR DESCRIPTION
**Pull request by rbtcollins**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh wow I *just* ran into this, thanks!

@bors: r+

**Comment by alexcrichton** [comment]
whelp

Looks like the time has finally come for some new cargo snapshots. We almost made it a year, but alas!

**Comment by rbtcollins** [comment]
Sounds like the failure isn't my patch per se? If it is, I'm happy to poke around deeper - tomorrow probably, conf is going to go into sociable mode soon :)

**Comment by alexcrichton** [comment]
@bors: retry

Ah yeah this just needed https://github.com/rust-lang/cargo/pull/2352 to land

**Pull request merged**
