### PR TITLE
Implement the --dependencies and --remote-dependencies options for cargo build

### PR DESCRIPTION
**Pull request by vojtechkral**
Implement options for building dependencies only, useful for docker builds.
See discussion in #2644

~~No tests and docs so far, sorry! I'll be sure to add them if folks say this is an ok approach...~~
Edit: Tests & docs added.

Description copied from my [comment](https://github.com/rust-lang/cargo/issues/2644#issuecomment-606898600) in the issue thread:

What is included:

- Option `--dependencies` to build all dependencies, including local ones, basically everything except root packages
- Option `--remote-dependencies` to build all remote dependencies, excluding root packages _and_ local packages.

The naming of the options follows the same logic as the already existing option `--tests`, the command `cargo build --tests` sounds like an english sentence _"cargo, build tests"_. I have named the options similarly, ie. `cargo build --remote-dependencies` sounds like _"cargo, build remote dependencies"_. The two options are mutually exclusive.

- `patch` sections are supported, the semantics are as follows: if a remote dependency is patched with a local one (`path`) and `--remote-dependencies` is used, the dependency is built _iff_ another remote dependency depends on it. Otherwise it is not built.

### CODE REVIEW

**Comment by vojtechkral** [comment]
I'll be adding tests shortly...

**Comment by vojtechkral** [comment]
Tests added and one workspace-related bug fixed...

**Comment by vojtechkral** [comment]
Hm, is an RFC required for this?

**Comment by ehuss** [comment]
It would be helpful to have a clear description of the use case and motivation here.  I'm still unclear, if this is to be used for Docker caching, and you have to construct a skeleton project, how this is much different from a regular `cargo build`.  I'm also not clear why one flag would be used over the other.

**Comment by vojtechkral** [comment]
Ok, @Eh2406 was right, this doesn't really solve the docker problem :-(

**Pull request closed without merging**
