### PR TITLE
Make job queue channel bounded

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Reference: #6197

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I would be wary to merge this though as I'm not sure it wouldn't lead to deadlock and/or unpredictable behavior, and in reality I don't think we'll ever run into the problem where child threads outpace the main thread *that much* to make this that necessary

**Comment by ishitatsuyuki** [comment]
I'd like to note that it definitely can outpace, like when you're using a pipe-based tool that doesn't aggressively drain the output (I remember `less` did that?), which makes the main thread blocked. Thus backpressure is important here.

Regarding deadlocks, I somewhat understand your concern, but I'm not sure if there's a concrete case. In particular, do we communicate back to the child thread? In that case, we may want to visit that to ensure deadlocks don't happen.

**Comment by alexcrichton** [comment]
I could go either way on the "whether this is necessary" part, but to weed out potential deadlock issues I think it'd be best to test this out with a capacity of zero or one and then test this one some large projects (like Servo) with a lot happening in parallel and perhaps with a variety of `-v` flags as well.

These sorts of deceptively small changes have all classically created a lot of headache down the road as bugs are tracked down in one way or another.

**Comment by ishitatsuyuki** [comment]
So yeah, it actually deadlocked with capacity=0 during tests. I'll try to figure out what dataflow is causing this.

**Comment by ishitatsuyuki** [comment]
Closing this: I don't have much time to refactor the code to remove all cases of deadlock.

**Pull request closed without merging**
