### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by dhuseby**
This adds a basic bootstrapping script for cargo.  It is quick and dirty but does the job with a little fiddling.  I have successfully used it to bootstrap a cargo executable on Linux and Bitrig.

### CODE REVIEW

**Comment by dhuseby** [comment]
reset the merge commit away, rebased to upstream/master and force pushed.

**Comment by alexcrichton** [comment]
Nice! Thanks so much @dhuseby!

Perhaps this doesn't belong in the main Cargo repo though? I'd be totally fine with some links over to this script, but it might be somewhat difficult to maintain into the future.

**Comment by dhuseby** [comment]
@alexcrichton maybe I move it to a "contrib" subfolder?

**Comment by alexcrichton** [comment]
Hm perhaps, although I'm worried about bug reports being filed here and getting lost in the noise. How about a section of the README explaining how to bootstrap on a new architecture where cross compilation is not an option?

**Comment by dhuseby** [comment]
@alexcrichton sure.

**Comment by dhuseby** [comment]
closing this PR.

**Pull request closed without merging**
