### PR TITLE
Proptest 0.9.1

### PR DESCRIPTION
**Pull request by Eh2406**
This is a rework of #6636 now possible do to the change in testing from #6748

### CODE REVIEW

**Comment by dwijnand** [comment]
Thanks!

@bors r+

**Comment by dwijnand** [comment]
The rust 1.32 job failed on rand compilation errors.

**Comment by Eh2406** [comment]
darn, I thought we "fixed" that in #6748.

**Comment by ehuss** [comment]
I wouldn't be opposed to disabling minimal-versions on travis as well.

**Comment by Eh2406** [comment]
btw this fixis #6613

I am ok with removing the testing...

**Pull request merged**
