### PR TITLE
Allow configuration of LTO in [profile]

### PR DESCRIPTION
**Pull request by alexcrichton**
This should help give access to ThinLTO when desired!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that this was enabled in https://github.com/rust-lang/rust/pull/47521 so it won't actually pass tests until that lands.

**Comment by alexcrichton** [comment]
(lands in nightly that is)

**Comment by alexcrichton** [comment]
All green now!

**Comment by alexcrichton** [comment]
ping r? @matklad

**Comment by matklad** [comment]
@bors r+

We might  add a test that if the value of `lto` is invalid that we get a reasonable error message from `rustc`, but I don't think that's necessary. 

Should we add docs for this feature somewhere?

**Pull request merged**
