### PR TITLE
Add value OUT_DIR to build-script-executed JSON message

### PR DESCRIPTION
**Pull request by matklad**
The target audience here is IDE authors, who can use this feature to
better support crates which generate code to OUT_DIR

### CODE REVIEW

**Comment by ehuss** [comment]
Looks good.  Can you also update the documentation at https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/external-tools.md#build-script-output?

**Comment by matklad** [comment]
Added docs!

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
