### PR TITLE
fix dynamic search path for build scripts

### PR DESCRIPTION
**Pull request by mcgoo**
fixes https://github.com/rust-lang/cargo/issues/3957

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you refactor this to share an implementation with compilation.rs as well?

**Comment by mcgoo** [comment]
This no longer passes tests. Do you know where to get the correct target directory path from?

`let root_output = cx.layout(Kind::Target).dest().to_path_buf();` 

doesn't seem to be the right thing.

(I assume when you said you wanted to use the same code in both cases you meant that the build script case also should have the "don't add paths outside the target dir" logic.)

**Comment by mcgoo** [comment]
`cargo test --test build-script` gives a nice focussed example.

**Comment by alexcrichton** [comment]
Oh so that bug I believe is because the prefix needs to be with `Kind::Host`, not `Kind::Target`.

Could you actually avoid though making `layout` public and just use the path to `target` as the prefix to test? (that's good enough)

**Comment by mcgoo** [comment]
FYI, it does not work with Kind::Host either, I think because we are relative to 'unit'.

Where do I get the path to `target`?

**Comment by alexcrichton** [comment]
Hm looking back the usage of `.dest()` *should* work. To get the path to `target` you can just add a helper method to `Context` to keep `layout` private.

Looking at the [appveyor failure](https://ci.appveyor.com/project/rust-lang-libs/cargo/build/1.0.1702/job/bgg0vti0j6ruffp5) the [test involved](https://github.com/rust-lang/cargo/blob/bb970dc0dab4ea14b85b33342a8f95727f79269b/tests/build-script.rs#L1132-L11990) is legitimately breaking after this change was applied. Not only is this picking up the `native=` stripping but it's *also* picking up the filtering of everything outside the deps dir. I think the test will need to be updated to get it to work after this is implemented.

**Comment by mcgoo** [comment]
How does this look?

I fixed the test by putting the project that builds the dylib and the project that uses it into a workspace.

I'm kinda shocked that the issue #3366 dylib path filtering is not breaking people's builds. It seems like it should at least give a diagnostic, so I left a debug!() in there.

**Comment by mcgoo** [comment]
I'm not sure what is going on, but I get test failures on cargo master that appear related to the failures in this build. I pulled the known good appveyor commit mentioned below (bors building a nightly) and tried to build it and it failed. The appveyor shows it succeeding. I deleted ~/.cargo ~/.multirust and ~/.rustup before starting. I built in a fresh clone of the cargo tree. I'm not sure if there is some other state or config file that you can think of that I need to clean up on my machine or if this is a real issue.

OS is Windows 10 1703.15063.138

Thoughts?

```
#!/bin/bash

# c.f.
# https://ci.appveyor.com/project/rust-lang-libs/cargo/build/1.0.1715/job/27uuclr522xnv88c
#

set -xe 

# rm -rf ~/.cargo
/c/Users/jim/Downloads/rustup-init.exe --version
/c/Users/jim/Downloads/rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly-2017-03-03 
git checkout -qf 7cfeec1aaac3d1909af8476f66c547619eceb640
got log -n1
rm -rf target
git status
/c/Users/jim/.cargo/bin/rustc -V
/c/Users/jim/.cargo/bin/cargo --version
/c/Users/jim/.cargo/bin/cargo build --target x86_64-pc-windows-msvc --manifest-path /c/Users/jim/src/cargo//Cargo.toml --release
CFG_DISABLE_CROSS_TESTS=1 /c/Users/jim/.cargo/bin/cargo test --target x86_64-pc-windows-msvc --manifest-path /c/Users/jim/src/cargo//Cargo.toml --release    -- --quiet || true

# also
CFG_DISABLE_CROSS_TESTS=1 /c/Users/jim/.cargo/bin/cargo test --target x86_64-pc-windows-msvc --manifest-path /c/Users/jim/src/cargo//Cargo.toml --release --test plugins   -- --quiet
```

```
rustup-init 1.2.0 (70faf07 2017-04-08)

  nightly-2017-03-03 installed - rustc 1.17.0-nightly (c0b7112ba 2017-03-02)

HEAD detached at 7cfeec1a
commit 7cfeec1aaac3d1909af8476f66c547619eceb640
Merge: 6b6dc8e1 5d76dd23
Author: bors <bors@rust-lang.org>
Date:   Sun Apr 30 08:23:23 2017 +0000

    Auto merge of #3980 - Keruspe:master, r=alexcrichton

    update libgit2-sys for libressl compat

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test-plugins.out
	test-plugins.sh

nothing added to commit but untracked files present (use "git add" to track)
rustc 1.17.0-nightly (c0b7112ba 2017-03-02)
cargo 0.18.0-nightly (19ea423 2017-03-02)

running 37 tests
.....................................
test result: ok. 37 passed; 0 failed; 0 ignored; 0 measured


running 60 tests
............................................................
test result: ok. 60 passed; 0 failed; 0 ignored; 0 measured


running 23 tests
.......F...............
failures:

---- bench_dylib stdout ----
	running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\release\cargo.exe bench -v`
thread 'bench_dylib' panicked at '
Expected: execs
    but: exited with exit code: 3221225781
--- stdout

--- stderr
   Compiling bar v0.0.1 (file:///C:/Users/jim/src/cargo/target/x86_64-pc-windows-msvc/cit/t5/foo/bar)
     Running `rustc --crate-name bar bar\src\lib.rs --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C metadata=e10cd8f5ac7d88d8 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps`
   Compiling foo v0.0.1 (file:///C:/Users/jim/src/cargo/target/x86_64-pc-windows-msvc/cit/t5/foo)
     Running `rustc --crate-name foo src\lib.rs --crate-type dylib --emit=dep-info,link -C opt-level=3 -C metadata=70483dbfb6c289a9 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps --extern bar=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps\bar.dll`
     Running `rustc --crate-name foo src\lib.rs --emit=dep-info,link -C opt-level=3 --test -C metadata=296c91290cac987f -C extra-filename=-296c91290cac987f --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps --extern bar=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps\bar.dll`
     Running `rustc --crate-name bench benches\bench.rs --emit=dep-info,link -C opt-level=3 --test -C metadata=a75f89a68520beea -C extra-filename=-a75f89a68520beea --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps --extern bar=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps\bar.dll --extern foo=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps\foo.dll`
    Finished release [optimized] target(s) in 1.85 secs
     Running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t5\foo\target\release\deps\foo-296c91290cac987f.exe --bench`
error: bench failed
', C:\Users\jim\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    bench_dylib

test result: FAILED. 22 passed; 1 failed; 0 ignored; 0 measured


running 7 tests
.F..F..
failures:

---- doctest_a_plugin stdout ----
	running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\release\cargo.exe test -v`
thread 'doctest_a_plugin' panicked at '
Expected: execs
    but: exited with exit code: 3221225781
--- stdout

--- stderr
   Compiling bar v0.0.1 (file:///C:/Users/jim/src/cargo/target/x86_64-pc-windows-msvc/cit/t0/foo/bar)
     Running `rustc --crate-name bar bar\src\lib.rs --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=a6b23aa348e72191 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps`
   Compiling foo v0.0.1 (file:///C:/Users/jim/src/cargo/target/x86_64-pc-windows-msvc/cit/t0/foo)
     Running `rustc --crate-name foo src\lib.rs --emit=dep-info,link -C debuginfo=2 --test -C metadata=87be52aa16cc53e8 -C extra-filename=-87be52aa16cc53e8 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps --extern bar=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps\bar.dll`
     Running `rustc --crate-name foo src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=cf582169413865dc -C extra-filename=-cf582169413865dc --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps --extern bar=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps\bar.dll`
warning: unused `#[macro_use]` import
 --> src\lib.rs:2:13
  |
2 |             #[macro_use]
  |             ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused `#[macro_use]` import
 --> src\lib.rs:2:13
  |
2 |             #[macro_use]
  |             ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.84 secs
     Running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t0\foo\target\debug\deps\foo-87be52aa16cc53e8.exe`
error: test failed, to rerun pass '--lib'
', C:\Users\jim\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- plugin_integration stdout ----
	running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\release\cargo.exe test -v`
thread 'plugin_integration' panicked at '
Expected: execs
    but: exited with exit code: 3221225781
--- stdout

--- stderr
   Compiling foo v0.0.1 (file:///C:/Users/jim/src/cargo/target/x86_64-pc-windows-msvc/cit/t1/foo)
     Running `rustc --crate-name build_script_build build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=5363063d55d7c4d5 -C extra-filename=-5363063d55d7c4d5 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\build\foo-5363063d55d7c4d5 -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps`
     Running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\build\foo-5363063d55d7c4d5\build-script-build`
     Running `rustc --crate-name foo src\lib.rs --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 --test -C metadata=187507dd4dcf5f01 -C extra-filename=-187507dd4dcf5f01 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps`
     Running `rustc --crate-name foo src\lib.rs --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=565f675dce05b118 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps`
     Running `rustc --crate-name it_works tests\it_works.rs --emit=dep-info,link -C debuginfo=2 --test -C metadata=a3a459c991a81bc4 -C extra-filename=-a3a459c991a81bc4 --out-dir C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps -L dependency=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps --extern foo=C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps\foo.dll`
    Finished dev [unoptimized + debuginfo] target(s) in 1.33 secs
     Running `C:\Users\jim\src\cargo\target\x86_64-pc-windows-msvc\cit\t1\foo\target\debug\deps\foo-187507dd4dcf5f01.exe`
error: test failed, to rerun pass '--lib'
', C:\Users\jim\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31


failures:
    doctest_a_plugin
    plugin_integration

test result: FAILED. 5 passed; 2 failed; 0 ignored; 0 measured
```

**Comment by mcgoo** [comment]
I thought it might be because I am building using cargo rather than configure/make, but it appears that using cargo works fine in a modified CI build.

https://ci.appveyor.com/project/mcgoo/cargo/build/1.0.3/job/xrgse4388abpa9ng

The tests that fail are not the same test that fails in the CI for this PR so this may just be a strange coincidence.

Any advice on what I need to do to get the tests working much appreciated.

**Comment by mcgoo** [comment]
Ok, this looks good to me now and the tests pass on the CI server at least.

**Comment by alexcrichton** [comment]
Looks great to me, thanks! Want to squash the commits and I'll r+?

**Comment by alexcrichton** [comment]
Ah sorry if I missed this! Want to resolve the conflicts? Feel free to ping me when the PR is ready as unfortunately github doesn't send out notifications when it's force-pushed :(

**Comment by mcgoo** [comment]
ping @alexcrichton

**Pull request merged**
