### PR TITLE
[beta] hash '__CARGO_DEFAULT_LIB_METADATA' in metadata for rustc

### PR DESCRIPTION
**Pull request by Keruspe**
This is a backport of #4239 for beta

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Mind also cherry-picking https://github.com/rust-lang/cargo/pull/4181 and https://github.com/rust-lang/cargo/pull/4196 to get tests passing?

**Comment by Keruspe** [comment]
I cherry-picked only half of the latter as there was a conflict but looks like that was enough

**Pull request merged**
