### PR TITLE
Asciidoc manpages [man documentation improvement]

### PR DESCRIPTION
**Pull request by alx741**
This is related to #2647 ,  Addresses #2645

The intention is to do with cargo the same thing git does with the sub-commands man pages, it's working and already merged the separate page for `cargo-build`. This ports them to asciidoc (again, just like git does) so it will be more maintainable and easy to keep a larger, multi-page man documentation system.

There is going to be multiple man pages so they are organized in a `man` directory to keep `src/etc` clean.

The list of available commands is keep in a dedicated .adoc file so it would be easier to extend and each sub-command has its own page, so adding a new one is trivial.

The Makefile compiles them properly and introduces asciidoc as dependency for the generation of the Distribution. 

After this the next things to do:
- Add the man pages for the rest of the sub-commands
- Launch the appropriate  man page when `cargo help <command>`
- Write test for the pages to be sure they remain with a consistent style
- Unify this with the documentation cargo drops right now when `--help` to avoid duplication as @alexcrichton suggested: 

> I wonder if we could perhaps unify the documentation with the subcommand --help documentation as well? They probably don't want to all be exactly the same, but they could all be derived from the same source perhaps.

- Use the `src/doc/*.md`  documents to generate *man5* and *man7* man pages so all that information is available to the user in the same `man gittutorial 7` style.

I'll work in all that, but wanted to PR this first to be sure everything is ok and make small changes at a time.

### CODE REVIEW

**Comment by alx741** [comment]
Travis is complaining that:
> a2x: Command is not found

So I think the solution is to add `asciidoc` (wich includes the `a2x` command) in the `.travis.yml` file like this:

    addons:
      apt:
        sources:
          - kalakris-cmake
        packages:
          - cmake
          - g++-multilib
          - lib32stdc++6
          - asciidoc

But I would like some feed back before doing that

**Comment by alexcrichton** [comment]
Thanks for the PR! This is a pretty weighty step to pick up a new system for defining our docs, as we'd likely want to mirror this across the compiler and rustup as well ideally. Just that we should tread lightly :)

Ideally we'd have some asciidoc-like-thing written in Rust or usable with Cargo integration rather than having a separate command, although I'm not entirely sure what that would look like. I will say that asciidoc seems objectionably more readable than raw man pages!

cc @rust-lang/tools 
cc @brson

**Comment by steveklabnik** [comment]
Yeah, asciidoc is nice. It's still not as simple as markdown, so we went against it for most of the docs, but I wouldn't be _totally_ opposed with using it for manpages, though there are some MD -> manpage generators, which might be worth it to only keep one formatting language....

**Comment by alx741** [comment]
> Ideally we'd have some asciidoc-like-thing written in Rust or usable with Cargo integration rather than having a separate command, although I'm not entirely sure what that would look like

The reason I choose asciidoc over markdown was that it has file inclusion between files so its able to keep the man pages bits into multiple files,**but** I now realize that is probably an ability that will have just a tiny impact in the overall result. 

Markdown is currently used for rust, cargo documentation, **rustdoc** currently takes MD files and convert them to HTML or JSON, so it would be nice to continue to use the same markup language instead of introducing another one. 

So, right know because of what **rustdoc** is currently capable, introducing a new tool is inescapable.

> though there are some MD -> manpage generators, which might be worth it to only keep one formatting language....

But if a new tool is needed anyways why not using markdown instead to compile the man pages with **pandoc** (for now), keep all the documentation in Markdown (avoid introducing another markup language), and because **rustdoc** works with MD, it would be possible to replace **pandoc** in the future by giving **rustdoc** the ability to output troff, and thus making all this fully integrated with the rust tools.

I'm trying this right away and will open another PR with the results.

**Comment by alexcrichton** [comment]
Yeah if we need to pick up a build dependency for something like this we may want to do so lightly (e.g. both asciidoc and pandoc will come with their downsides). Perhaps not the worst thing, but just something to consider!

**Comment by alexcrichton** [comment]
Thanks again for the PR @alx741! The tools team discussed this change during triage yesterday and the conclusions were:

* We definitely would prefer markdown to asciidoc as that's the standard across Rust
* For now we don't want to pick up an extra pandoc dependency as it's a pretty weighty addition to the build.

For now we'll unfortunately probably just be sticking to raw troff, but if a Rust tool exists for converting markdown to troff then we'd be more than willing to include it as part of the build!

**Pull request closed without merging**
