### PR TITLE
Add templates for Cargo.toml

### PR DESCRIPTION
**Pull request by torkleyy**
This PR addresses issue #3459.

## New features

This change would add a `--template NAME` option to the `new` and the `init` subcommand where you can specify some template, say `optimized`. Cargo then looks for a file `templates/optimized.toml` in your `.cargo` folder.

These may be the contents of a template file:

```toml
[dependencies]

[profile.release]
lto = true
```

This would create the following `Cargo.toml` file:

```rust
[package]
name = "helloworld"
version = "0.1.0"
authors = ["My Name", "Some other name"]

[dependencies]

[profile.release]
lto = true
```

If you don't specify a the template flag, the `Cargo.toml` stays the same as before.

## What was done already

* I've already managed to add this flag to the USAGE string (I didn't know about docopt so it took me a while to figure out how cargo does the parsing).
* A `resolve_template_content` function has been added
* The template content will be inserted in the `Cargo.toml`

## What has to be done

I'd need some help because I'm not very familiar with how cargo works internally.
Also, please tell me if my code is not idiomatic, I'm using Rust since a month :). 

I think there is still documentation that has to be updated (including the manpages).
Also, is there a string containing the path to the `.cargo` folder?
When the template file does not exist, I get `An unknown error occured`. Is there a simple way to just display the error without getting rid of the nice `?`-Syntax?

### CODE REVIEW

**Comment by torkleyy** [comment]
This may conflict with https://github.com/rust-lang/cargo/pull/3004 because that pull request is using the `--template` flag as well.

**Comment by torkleyy** [comment]
Is there anybody who could help to fix the error message or tell me how to do that? @alexcrichton
As for the cargo directory, I'd use `cargo_home` from `util/config.rs` if that is the right function.

**Comment by alexcrichton** [comment]
Thanks for the PR @torkleyy! I think that to solve https://github.com/rust-lang/cargo/issues/3459 though we may not want to take the route of templates (like in #3004) as I think templates tend to have a different use case and/or connotations.

I don't currently off the top of my head know how to best solve #3459 but I don't think it should be templates.

**Comment by alexcrichton** [comment]
I'm going to close this due to inactivity, but feel free to resubmit!

**Pull request closed without merging**
