### PR TITLE
Scan untracked files in git for packaging/deps

### LINKED ISSUE #797: `cargo package` is not working
The `cargo package` command results in:

```
   Packaging hello_world v0.0.1 (file:///Users/eduardobautista/Projects/hello_world)
   Verifying hello_world v0.0.1 (file:///Users/eduardobautista/Projects/hello_world)
failed to verify package tarball
```

This is on a newly generated cargo project using the October 31st build `492bc86` on OS X.

### LINKED ISSUE #1575: cargo doc ignores changes to files not added to git repository
As the title says really, when I modify a file that git doesn't know about and run `cargo doc`, cargo doesn't realise it has changed and doesn't bother to update the docs.

Reproduction:
* `cargo new`
* Add doc comment to src\lib.rs
* `cargo doc` - docs are built
* Modify doc comment
* `cargo doc` - docs are not built
* `git add src\lib.rs`
* `cargo doc` - docs are built
* Modify documentation
* `cargo doc` - docs are built

### PR DESCRIPTION
**Pull request by alexcrichton**
Closes #797
Closes #1575 

This is a reopening of #1170 but I see the two closed issues as important enough that this needs to land in some form or another, and I'm more comfortable with always taking into account untracked files than only if there isn't a commit yet.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

cc @huonw

**Comment by bluss** [comment]
Using the today's latest rustc+cargo, I see a lot of junk files and Cargo.lock in the generated cargo package. Crates.io thankfully refused the upload.

Is that caused by this?

`cargo 0.2.0-nightly (0d75eb6 2015-05-07) (built 2015-05-08)`

**Comment by Manishearth** [comment]
Can these be printed in the normal `cargo publish` output as a yellow note about "these files are being uploaded" ?

**Comment by shepmaster** [comment]
> Can these be printed in the normal cargo publish

And hopefully in `cargo package` as well, so we can fix the issue *before* our files are uploaded? This scares me that someone might accidentally have a file full of secure information that gets uploaded somewhere...

**Comment by alexcrichton** [comment]
@bluss yes those extra contents were likely caused by this patch, thanks for opening #1597 as well!

---

@shepmaster this change mirrors the behavior for `path` sources and other possible VCSs, so it's just bringing the git implementation more in-line with other repositories. Note that this should still be respecting `.gitignore`, however, which I would expect all credentials of various sorts to be located in.

**Comment by Manishearth** [comment]
> I would expect all credentials of various sorts to be located in.

In situations involving security it's better to assume laziness/incompetence/whatever. Especially when this seems like a nuance in Cargo's functionality that most folks won't know in the first place.

**Pull request merged**
