### PR TITLE
Add a warning when packaging crates with wildcard dependencies

### PR DESCRIPTION
**Pull request by sfackler**
r? @alexcrichton 

Any ideas on how to make a reliable test for this? Making a test with multiple dependencies on stuff off of crates.io seems to make output pretty nondeterministic wrt download and compilation ordering.

### CODE REVIEW

**Comment by achanda** [comment]
Shouldn't we let the end user know as soon as possible (i.e. on a `cargo build`)?

**Comment by sfackler** [comment]
I'd lean towards no. Just like the checks that already exist for missing descriptions, licenses, documentation links, etc, these limitations only really matter when you're about to publish, and they're easy to fix at that point.

**Comment by alexcrichton** [comment]
This actually explicitly *doesn't* want to warn on a `cargo build` because only crates.io will be rejecting `*` dependencies, not Cargo itself. This means that applications and such are free to use `*` still, it's just libraries on crates.io that won't be allowed to use it.

There should be existing instances in `tests/test_cargo_registry.rs` about how to make a fake registry which doesn't do anything on the network, so perhaps one of those could be re-used to add a test?

**Comment by sfackler** [comment]
Cool. Will take a look tonight.

**Comment by sfackler** [comment]
Updated with test.

**Comment by alexcrichton** [comment]
@bors: r+ 28126c1d125e33aa3230f4c4ebea0a0ccb88340f

Thanks!

**Comment by alexcrichton** [comment]
Fascinating! That's the first time I've ever seen that failure outside of rust-lang/rust's bots...

@bors: retry

**Pull request merged**
