### PR TITLE
Various cosmetic improvements

### PR DESCRIPTION
**Pull request by dwijnand**
Resubmit of #6673 which, somehow, broke.
cc @alexreg

### CODE REVIEW

**Comment by alexreg** [comment]
Sorry @dwijnand, I normally would have gotten around to this sooner, but I've been unusually busy the past couple of days. Thanks for sorting this out for me!

**Comment by dwijnand** [comment]
Thanks.  But it was no problem, just a very interesting glitch on GitHub!

**Comment by alexreg** [comment]
@dwijnand Yeah, I've experienced it a few times... I'm not sure of the cause even. Seems non-deterministic.

**Pull request merged**
