### PR TITLE
Add GNU triples for #3186

### PR DESCRIPTION
**Pull request by edunham**
Resources used to take an educated guess at this:
* Servo's appveyor.yml
* Rust's Buildbot config
* Alex
* Some random appveyor config that Alex had sitting around

Let's see if it works!

### CODE REVIEW

**Comment by edunham** [comment]
So, GNU doesn't work because we've never tested it, afaict.

**Comment by edunham** [comment]
GNU didn't work because I made a stupid typo, actually. 

Trying with no MSVC builds over at https://ci.appveyor.com/project/edunham/cargo/build/1.0.17

**Comment by edunham** [comment]
This will pass after #3189 lands

**Comment by alexcrichton** [comment]
@edunham want to rebase this to resend to appveyor?

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

**Pull request merged**
