### PR TITLE
allow adding a "prefix" to the extra-filename rustc parameter

### PR DESCRIPTION
**Pull request by Keruspe**
This would help fixing https://github.com/rust-lang/rust/issues/42483

### CODE REVIEW

**Comment by Keruspe** [comment]
This is the less invasive solution I found as of now.
I don't know if that would be considered too "hackish", I'm open to suggestions.

Another lead would be to somehow pass additional data to the SipHasher in the target_metadata method

**Comment by alexcrichton** [comment]
Hm ideally we wouldn't have to keep adding these sorts of weird env vars for rustbuild! In this situation the intention is that the hash is different every release, but is that not happening?

**Comment by Keruspe** [comment]
Yup, the hash can be the same for different releases.

If I understand correctly the hash depends on
- name
- source
- version
- authors
- description
- homepage
- profile
- target name
- target kind

Unless i'm missing something, if some library doesn't change much, like librustc_bitflags, the hash can remain the same for several different versions of rustc

**Comment by alexcrichton** [comment]
Ah so I believe historically we mixed in the rustc version number into the output but I think we stopped doing that with rustbuild. I think the best solution here would be to do that?

**Comment by Keruspe** [comment]
That would be awesome indeed.
I'll try to do so

**Pull request closed without merging**
