### PR TITLE
Derive Clone whenever deriving Copy

### PR DESCRIPTION
**Pull request by IvanUkhov**
Hello,

Currently Cargo fails to compile on the nightly channel due to the missing `Clone` trait whenever the `Copy` trait is derived.

Regards,
Ivan

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you update `src/rustversion.txt` as well to bring rust as far forward as possible?

**Comment by IvanUkhov** [comment]
@alexcrichton, the current version is

```
rustc 1.0.0-nightly (f207ecbe0 2015-04-03) (built 2015-04-04)
```

I’ve updated `rustversion.txt` to the built timestamp. Thanks!

**Comment by alexcrichton** [comment]
It looks like it's actually failing to build tests due to https://github.com/carllerche/hamcrest-rust/pull/19, so this may want to wait for that to get merged first.

**Comment by IvanUkhov** [comment]
@alexcrichton, yeah, I had to fix `hamcrest-rust` first to run the tests.

**Comment by alexcrichton** [comment]
Ok the PR has been merged so a `cargo update -p hamcrest` should be all that's necessary now!

**Comment by IvanUkhov** [comment]
Looks good, Alex.

**Comment by IvanUkhov** [comment]
@alexcrichton, the same here with forced pushes(

**Comment by IvanUkhov** [comment]
I’ve rebased it to master, if only GitHub could see it.

**Pull request closed without merging**
