### PR TITLE
Allow passing multiple crate names to cargo new

### LINKED ISSUE #9823: Allow passing multiple crate names to `cargo new`
**Describe the problem you are trying to solve**
`cargo new a b c` gives an error:
```
error: Found argument 'b' which wasn't expected, or isn't valid in this context

USAGE:
    cargo new <path> --lib
```

**Describe the solution you'd like**
Allow passing multiple crates at the same time. Right now I do this with xargs, which works but is annoying to remember.
```
$ echo inner middle outer | xargs -n1 cargo new --lib
     Created library `inner` package
     Created library `middle` package
     Created library `outer` package
```

**Notes**
```
$ cargo --version
cargo 1.56.0-nightly (e96bdb0c3 2021-08-17)
```

### PR DESCRIPTION
**Pull request by QiangHeisenberg**
Allow passing multiple crate names to cargo new.

close #9823

### CODE REVIEW

**Comment by QiangHeisenberg** [comment]
Strangely enough, I had to modify the ```test new::no_argument```.
```
error: The following required arguments were not provided:
    <path>
```
to
```
error: The following required arguments were not provided:
    <path>...
```

Should this change be?

**Comment by alexcrichton** [comment]
Thanks for the PR! 

I'd be a bit worried about how this feature would interact with flags like `--name` and such. That flag specifically is intended to apply to just one crate, but it's also imaginable that other flags like `--edition` both may and may not want to apply to all crates. Additionally you may also want some `--lib` and `--bin` crates. I'm not really sure how this can be handled to separately configure each new crate, and it seems like the best solution would be to continue to make one crate at a time.

**Comment by ehuss** [comment]
On a similar note, I would be concerned about the interaction with future changes like https://github.com/rust-lang/rfcs/pull/2922 (#3506), which could add some complexity (especially if it adds interactive prompts).

**Comment by QiangHeisenberg** [comment]
> Thanks for the PR!
> 
> I'd be a bit worried about how this feature would interact with flags like `--name` and such. That flag specifically is intended to apply to just one crate, but it's also imaginable that other flags like `--edition` both may and may not want to apply to all crates. Additionally you may also want some `--lib` and `--bin` crates. I'm not really sure how this can be handled to separately configure each new crate, and it seems like the best solution would be to continue to make one crate at a time.

Thanks for your reply. I understand your concern.

In my intended design, this only adds the ability to create multiple crates at once, whether ```bin``` or ```lib```.

When reading the source code of the Cargo, I found that the ```cargo install``` and ```cargo uninstall``` commands can be used to install and uninstall multiple files at the same time.

This is also required in some scenarios, as suggested by @jyn514 .This does provide a solution.

In addition, the creation command of a single crate and the interaction of flags such as ```--name```  ```--edition``` are not affected.I can add more tests if necessary.

As you said, if there are different requirements for the current crate, for example, different ```lib```, ```bin```, ```edition```, and ```name```  are required, creating a crate each time is the best solution.

**Comment by QiangHeisenberg** [comment]
> On a similar note, I would be concerned about the interaction with future changes like [rust-lang/rfcs#2922](https://github.com/rust-lang/rfcs/pull/2922) (#3506), which could add some complexity (especially if it adds interactive prompts).

Thanks for the reply.

As in the reply above, in my envisioned design, none of the previous commands were affected for the creation of a single crate. It doesn't seem to be very complicated when it comes to adding some complex features in the future.

As you may be concerned, I do not recommend customizing each crate when creating multiple crates at the same time. This increases the operation difficulty and reduces the usability.

**Comment by jyn514** [comment]
> I'd be a bit worried about how this feature would interact with flags like --name and such.

I think it would be reasonable to forbid using --name with multiple crates. I don't think cargo needs to forbid creating multiple crates at all for the user experience to still be good.

**Comment by QiangHeisenberg** [comment]
I'm so sorry, I missed one thing. Applying the ```clap:::multiple``` function to the previous command results in ```cargo new a b c --vcs git fossil```, which creates four crates ```a```, ```b```, ```c```, and ```fossil```. This was obviously not the intent of the order, and the Fosil sign should have been wrong.
The correct output should be:
```
error: Found argument 'fossil' which wasn't expected, or isn't valid in this context

USAGE:
    cargo.exe new <path> --vcs <VCS>

For more information try --help
```
So I used the clap:::use_delimiter function instead.
Also, I added some test cases.

**Comment by jyn514** [comment]
I don't understand - why do you think that behavior is wrong? I would rather be able to use spaces than have to use commas and get slightly better errors in rare circumstances; it seems correct that the command above generated a `fossil` crate.

**Comment by QiangHeisenberg** [comment]
> I don't understand - why do you think that behavior is wrong? I would rather be able to use spaces than have to use commas and get slightly better errors in rare circumstances; it seems correct that the command above generated a `fossil` crate.

Thank you for your reply.
I think this may be confusing, and I think it’s more acceptable to put multiple crates names together to create them.

**Comment by alexcrichton** [comment]
Yes @QiangHeisenberg I agree with your responses and about what this PR does. My point though is that it can be surprising that this PR behaves as it does. For example `cargo new a b c --name d` probably doesn't behave right since I think it names everything `d`. Additionally I think it is likely common enough to want to individually customize each created package that simply saying "you can't pass `--lib`, `--bin`, or other customization flags" isn't a great solution.

Overall I don't know if the use case of initializing multiple crates at once with the exact same configuration except for name is really all that common. Today you can invoke `cargo new` multiple times, and I don't think there's really something compelling as to why that should be changed?

**Comment by QiangHeisenberg** [comment]
Thanks for the reply.
I understand that this feature may not be that useful for most people. It just might be helpful for # 9823 and # 9825. It does provide a little convenience.

I'm just a simple extension of the previous one, and I don't think it's too much trouble with the complexities that follow.

I understand your concern. If the introduction of this feature causes a lot of problems or the cargo doesn't need it, you can always turn it off.

**Comment by alexcrichton** [comment]
I'd like to propose that we do not accept this feature and say that `cargo new` will only create one crate at a time at this time, but I'd like to get others thoughts on this as well:

@rfcbot fcp close

**Comment by joshtriplett** [comment]
Agreed. I think it's reasonable to ask people to use `for x in crate1 crate2 crate3 ; do cargo new $x ; done` in the somewhat unusual case of creating multiple new crates at once.

**Comment by alexcrichton** [comment]
Ok looks like nothing major came up in the meantime, so I'm going to close.

**Pull request closed without merging**
