### PR TITLE
Update cargo to latest rust

### PR DESCRIPTION
**Pull request by gbsf**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! It looks like there's still [a lot of warnings](https://travis-ci.org/rust-lang/cargo/jobs/48935216#L709), could you add the necessary `#![feature]` directives as well?

**Comment by alexcrichton** [comment]
It looks like the tests are still failing, and when locally testing it looks like it's because of 0.21.0 => 0.22.0 in the strings in the `build_auth` tests. Perhaps you have a newer version which is being detected which isn't bundled in `libgit2-sys` just yet?

**Comment by gbsf** [comment]
Since libgit2-sys explicitly asks for at least version 0.22.0 (see [here](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/build.rs#L14)), and I couldn't compile it with version 0.21, I assumed the tests needed an update. But I can revert 05fdb6c79561f99201e4848b17ddcb9bc808fe4f if necessary.

**Comment by alexcrichton** [comment]
Yeah I'm not quite sure what's going on there, but this seems to be the reason that the tests are failing, so it won't be able to land without updating it :(

**Pull request merged**
