### PR TITLE
Fix build-std not honoring patch directives for dependencies of std.

### PR DESCRIPTION
**Pull request by jblazquez**
When building with `-Zbuild-std`, Cargo doesn't honor dependency overrides that you define in the `[patch]` section for dependencies of standard library crates. This appears to be because, when resolving standard library dependencies, Cargo is creating an in-memory virtual manifest that includes [a static set of dependency overrides](https://github.com/rust-lang/cargo/blob/5e11afc1ab334288fef44692f756893349d0d751/src/cargo/core/compiler/standard_lib.rs#L41-L56), ignoring any additional overrides that the real workspace may be setting.

Because Cargo is not honoring the workspace overrides, it doesn't seem to be possible to apply local modifications to crates that are dependencies of the standard library, such as `libc`.

To reproduce the issue:

```
$ mkdir build_std_test
$ cd build_std_test

# Vendor a copy of libc
$ cargo download libc==0.2.85 | tar xvz
INFO: cargo-download v0.1.2
INFO: Crate `libc==0.2.85` downloaded successfully
libc-0.2.85/.cargo_vcs_info.json
libc-0.2.85/.gitignore
...

# Override the crates.io version of libc with our vendored copy
$ cat >Cargo.toml <<EOL
[package]
name = "build_std_test"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "=0.2.85"

[patch.crates-io]
libc = { path = "libc-0.2.85" }
EOL

$ cat >src/lib.rs <<EOL
use libc;
EOL

$ cargo build -Zunstable-options -Zbuild-std --target x86_64-pc-windows-msvc
   Compiling compiler_builtins v0.1.39
   Compiling core v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\core)
   Compiling libc v0.2.85 <=========================================== Cargo is building the crates.io version of libc
   Compiling cc v1.0.60
   Compiling std v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\std)
   Compiling libc v0.2.85 (C:\Temp\build_std_test\libc-0.2.85) <========================== And also the local override
   Compiling unwind v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\unwind)
   Compiling rustc-std-workspace-core v1.99.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\rustc-std-workspace-core)
   Compiling alloc v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\alloc)
   Compiling cfg-if v0.1.10
   Compiling adler v0.2.3
   Compiling rustc-demangle v0.1.18
   Compiling panic_abort v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\panic_abort)
   Compiling rustc-std-workspace-alloc v1.99.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\panic_unwind)
   Compiling gimli v0.23.0
   Compiling hashbrown v0.9.0
   Compiling object v0.22.0
   Compiling miniz_oxide v0.4.0
   Compiling addr2line v0.14.0
   Compiling proc_macro v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\proc_macro)
   Compiling build_std_test v0.1.0 (C:\Temp\build_std_test)
warning: unused import: `libc`
 --> src\lib.rs:1:5
  |
1 | use libc;
  |     ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 1m 02s
```

Note that Cargo is building `libc` twice: once from `crates.io` and once from the local override folder, and the `std` crate will not be linking against the local override.

This PR is an attempt at solving this issue, although I'm not sure if the approach is good or not. I'm pretty new to Cargo and Rust in general, so please bear with me.

With the changes here, Cargo now applies overrides defined in the real workspace and the `libc` override is used when linking `std`:

```
$ cargo build -Zunstable-options -Zbuild-std --target x86_64-pc-windows-msvc
    Updating crates.io index
   Compiling compiler_builtins v0.1.39
   Compiling core v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\core)
   Compiling libc v0.2.85 (C:\Temp\build_std_test\libc-0.2.85) <============ Cargo now only builds the local override
   Compiling cc v1.0.60
   Compiling std v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\std)
   Compiling unwind v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\unwind)
   Compiling rustc-std-workspace-core v1.99.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\rustc-std-workspace-core)
   Compiling alloc v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\alloc)
   Compiling cfg-if v0.1.10
   Compiling adler v0.2.3
   Compiling rustc-demangle v0.1.18
   Compiling panic_abort v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\panic_abort)
   Compiling rustc-std-workspace-alloc v1.99.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\panic_unwind)
   Compiling gimli v0.23.0
   Compiling object v0.22.0
   Compiling hashbrown v0.9.0
   Compiling miniz_oxide v0.4.0
   Compiling addr2line v0.14.0
   Compiling proc_macro v0.0.0 (C:\rust\1.51.0\lib\rustlib\src\rust\library\proc_macro)
   Compiling build_std_test v0.1.0 (C:\Temp\build_std_test)
warning: unused import: `libc`
 --> src\lib.rs:1:5
  |
1 | use libc;
  |     ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 1m 09s
```

### CODE REVIEW

**Comment by Eh2406** [comment]
That is an excellent point, and I don't know how we were thinking of handling it.
@bors r? @ehuss

**Comment by alexcrichton** [comment]
This is currently somewhat by design because the dependencies of libstd are so strict and we haven't really tested much allowing overriding various sources. I imagined that a feature like this would be a separate `[patch]` section where you could also override libstd itself in the future.

At the very least though this needs to be thoroughly tested. There's a lot of integration points to consider which are likely not handled well with the implementation here:

* Resolution info needs to be stored in `Cargo.lock`
* Transitive dependencies of `[patch]` entries need to ensure that the registry isn't unnecessarily updated on each build
* Invoking `cargo vendor` should vendor the appropriate sources
* ...

I don't think I've thought of everything here either...

**Comment by jblazquez** [comment]
Thanks for the feedback, Alex.

Maybe I'm approaching this the wrong way. Here is what I need to do: I need to be able to override [some `libc` constants](https://github.com/rust-lang/libc/blob/bd7e0522f7631a0be106fa3ea3f6f6d8ad514b66/src/unix/linux_like/linux/mod.rs#L1402-L1412) that [`std` uses](https://github.com/rust-lang/rust/blob/5f1aeb52c22e3784928765e34be6dc0d17a350b4/library/std/src/sys/unix/rwlock.rs#L16) because the target platform I'm building for uses different values. This target platform is proprietary and I don't think I could ever upstream those `libc` changes, which is why I was relying on `[patch]` to allow me to change these constants locally.

Is there a better way to do this?

**Comment by alexcrichton** [comment]
Sorry unfortunately I don't know of a better way to manage it. I've thought that this would eventually be supported with  a std-specific `[patch]` section but I've never gone further than "maybe this is an idea at some point". I think it would take more work than is here to fully implement this and get the change working unfortunately.

**Comment by jblazquez** [comment]
OK, that's fine, thanks again. We can live with a custom patch to Cargo for now, because I don't think I'm capable of driving the design and the implementation of the larger change that you mention given how new I am to this ecosystem.

You can probably close this PR now.

**Comment by alexcrichton** [comment]
Ok, sounds reasonable!

**Pull request closed without merging**
