### PR TITLE
Improve verbose console and log for finding git repo in package check

### LINKED ISSUE #5823: No git repo found on windows (only) for package_verbose test
This was discovered with testing for #5786. See that discussion. At present on master, the package::package_verbose test is not engaging, on windows only, the `check_not_dirty` function of `cargo_package` for a sub-package, even though the sub-package *is* in a git repo.  On other platforms the (parent) repo is found and the dirty check occurs.

### PR DESCRIPTION
**Pull request by dekellum**
Third attempt to resolve #5823 by improving logging and tests. This exposes the issue to testing,  via verbose console output and is dependent on alexcrichton/git2-rs#341 as just released in git2 0.7.5 crate. Thus tests *should* now pass on all platforms, incl. windows, but I also intend to bump the minimal git2 release dependency (in a subsequently added commit).

cc: @Eh2406 thanks for your fix and help!

### CODE REVIEW

**Comment by dekellum** [comment]
@alexcrichton this is ready for review and merge.  Tests passing with new git2 0.7.5 release.

**Comment by alexcrichton** [comment]
Thanks for the PR! Just to make sure I understand, there's one new warning for publishing without a crate in git, and there's a different warning for if you're publish a crate where it's ignored in the nearest git repo. The tests then print out this warning because they're in the ignored `target` folder of Cargo?

If so, could these warnings perhaps only be enabled for Cargo's own tests suite? I don't think we want to start warning in general about not having a crate in git at all (or being ignored), as there's not much a user can do to squelch the warnings.

Additionally, we run Cargo's tests suite in the rust-lang/rust repo which futzes a bit with the `target` directory and git repos, so I'm not 100% sure that these tests would pass in the rust-lang/rust repo, but we can always try!

**Comment by dekellum** [comment]
That's correct on the two warnings:  Note that one run of `cargo package` would at most generate one of these warnings, and these are *only displayed* if a user requests `--verbose` output. 

Given that `check_not_dirty` will hard error exit via `bail!` if it finds a dirty repo, soft verbose-only warnings don't seem particularly onerous for conditions that should be rather rare and are quite suspect in a real crate packaging situation, no?   

And yes of course part of the motivation was tying into the testsuite's checking of verbose output, to effectively improve coverage.

Regarding running cargo's testsuite from rust-lang/rust, sounds like this would have come up for #5786 as well.  I'm a little afraid to ask, but is that something I could easily enough try, in short order without having to build rust entirely?  Given windows, is there some way to get rust-lang/rust CI to check this, against this branch?

**Comment by alexcrichton** [comment]
Ah ok thanks for the explanation! I missed the fact that it was verbose-only, and I think it makes sense to have it only in verbose mode for now.

Let's go ahead and land this and we can always fixup the breakage later if it comes up in rust-lang/rust, thanks again!

@bors: r+

**Pull request merged**
