### PR TITLE
Replace existing sources before updating

### LINKED ISSUE #2533: Cargo does not recover from failed git update (File lock issue?)
I'm currently trying to build servo, which uses cargo for this (Current nightly is used afaik).

When updating some git repositories servo depends on cargo fails (not always, but sometimes (I'm puzzled about this, but I think this might be another issue completely)).
After manually restarting the cargo build, cargo continues, but when it again handles the git repository it previously failed on it just prints "Blocking waiting for file lock on the git checkout" and waits there indefinitely. 

I attached a full log of what I did.
[cargo-lock.txt](https://github.com/rust-lang/cargo/files/195982/cargo-lock.txt)

When searching for this in the existing issues I found #2486, which is a quite recent pull request apparently concerning the same message I got. So maybe this might be related to that change.

### PR DESCRIPTION
**Pull request by alexcrichton**
Currently sources may acquire file locks to ensure that they're not tampered
with while they're in use. We may load two sources to the same location,
however, in the case of git repositories which need to be updated. Cargo will
first load a locked version of the source and then may load an unlocked version,
and these two loads currently deadlock.

This commit tweaks the logic when updating a source to only update it after the
previous source has been replaced.

Closes #2533

### CODE REVIEW

**Comment by emilio** [comment]
Should this be retried? Bors hasn't replied :P

**Comment by petevine** [comment]
Hmm, could this be the cause of this [error?](https://github.com/arkpar/rust-rocksdb/issues/4)

**Comment by alexcrichton** [comment]
That looks like https://github.com/rust-lang/cargo/issues/2567 which was fixed by https://github.com/rust-lang/cargo/pull/2579 (and not caused by this)

**Pull request merged**
