### PR TITLE
updated yank error message

### LINKED ISSUE #8695: cargo yank's error message should be clearer
If you try to use `cargo yank` without passing the `--vers` flag, it errors with the message:

```
error: a version must be specified to yank
```

It would be helpful if this message specified that the version must be specified using the `--vers` flag. My prompt just now looks like:

```
> cargo yank
error: a version must be specified to yank
> cargo yank 0.7
error: a version must be specified to yank
> cargo yank 0.7.0
error: a version must be specified to yank
> cargo yank --help
...
> cargo yank --vers 0.7.0
```

### PR DESCRIPTION
**Pull request by Mikastiv**
Fixes #8695

### CODE REVIEW

**Comment by Eh2406** [comment]
I think there will probably need to be tests updated. If not then we will need to figure out how to add a test.

@ehuss What do you think of the new text?

**Comment by ehuss** [comment]
Perhaps `.required(true)` can just be added to the `--vers` flag and let clap handle it. That would make the help text better (it explicitly shows `--vers` is required), and the error would look like this:

```
error: The following required arguments were not provided:
    --vers <VERSION>

USAGE:
    cargo yank [OPTIONS] --vers <VERSION> [--] [crate]

For more information try --help
```

**Comment by Mikastiv** [comment]
This works better and is a good idea, but now the test alt_registry::bad_registry_name fails because it expects the --vers argument. Should I remove yank cmd from this test?

**Comment by Mikastiv** [comment]
It works using .required_unless("registry"). Would this be a good option?

**Comment by ehuss** [comment]
You can just put in a bogus version to fix that test, like this:

```diff
diff --git a/tests/testsuite/alt_registry.rs b/tests/testsuite/alt_registry.rs
index f9129e284..c3ed37633 100644
--- a/tests/testsuite/alt_registry.rs
+++ b/tests/testsuite/alt_registry.rs
@@ -637,7 +637,7 @@ Caused by:
         "owner",
         "publish",
         "search",
-        "yank",
+        "yank --vers 1.2.3",
     ] {
         p.cargo(cmd)
             .arg("--registry")
```

**Comment by Mikastiv** [comment]
Alright I did it.

**Comment by ehuss** [comment]
Thanks!
@bors r+

**Pull request merged**
