### PR TITLE
Detect incorrectly named cargo.toml

### PR DESCRIPTION
**Pull request by hi-rustin**
close https://github.com/rust-lang/cargo/issues/9541

### CODE REVIEW

**Comment by hi-rustin** [comment]
r? @ehuss 

I tried to implement it, but I'm not sure I'm on the right track. When should it be detected and prompted? I'm targeting install now, but that doesn't seem right?

**Comment by ehuss** [comment]
Hm, yea I guess I see that it is tricky to find the right spot since there are multiple places for searching. I might not worry too much about advanced scenarios like installing from a git repository. I think if a user has gotten that far, they've already got it worked out. I believe `read_packages` is only used for a few scenarios where cargo hunts for the right package. For `cargo install`, if there isn't a correctly named `Cargo.toml` given to `--path`, it won't get that far.

I think the spirit of the issue is a beginner starting a new project. I would just check for the basic use cases:

- `cargo build` will search for the nearest `Cargo.toml`. That search is done in `find_root_manifest_for_wd`. There would probably need to be a check there.
- I guess another check for `cargo install --path` wouldn't hurt, since some people might start there. I think that check would go [here](https://github.com/rust-lang/cargo/blob/1fc64069fd3b24c506b607fdc3404cf87014fa1a/src/cargo/ops/cargo_install.rs#L206-L221).

**Comment by hi-rustin** [comment]
@ehuss I think it's ready to review. Thank you for your patient guidance!

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Pull request merged**
