### PR TITLE
[doc] Redirect /policies.html to crates.io/policies

### PR DESCRIPTION
**Pull request by behnam**
This relieves us from migrating the Package Policies document into the
new Cargo Manual mdbook.

Moved the content to `crates.io` repo in
<https://github.com/rust-lang/crates.io/pull/1033>.

NOTE: We should wait until that change goes live before landing this
one. I'll notify here when it's time to land.

Closes <https://github.com/rust-lang/crates.io/issues/1030>

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me as soon as crates.io is ready

**Comment by behnam** [comment]
Redirect destination <https://crates.io/policies> has been live for a few days. We're good to go here.

r? @alexcrichton

**Pull request merged**
