### PR TITLE
_cargo: Add cargo package completion

### PR DESCRIPTION
**Pull request by lzutao**
Continuation of #7060
r? @ehuss

### CODE REVIEW

**Comment by lzutao** [comment]
Ran on cargo repository:
```console
% cargo update -p=<tab>
Completing packages
atty                  clap                  curl                  flate2                glob                  jobserver             log                   openssl               semver                strip-ansi-escapes    unicode-width
bufstream             core-foundation       curl-sys              fs2                   hex                   lazy_static           memchr                pretty_env_logger     serde                 tar                   url
byteorder             crates-io             env_logger            fwdansi               home                  lazycell              miow                  rustc-workspace-hack  serde_ignored         tempfile              url_serde
bytesize              crossbeam-utils       failure               git2                  ignore                libc                  num_cpus              rustfix               serde_json            termcolor             walkdir
cargo-test-macro      crypto-hash           filetime              git2-curl             im-rc                 libgit2-sys           opener                same-file             shell-escape          toml                  winapi
```

**Comment by lzutao** [comment]
Ping @ehuss

**Comment by ehuss** [comment]
This seems kinda buggy.  For example, the completion includes backslashes and whitespace sometimes.

Also, reading the manifest is a poor way to find the valid values for `-p`.

I personally would prefer to avoid spending any time enhancing these completion files (anything beyond trivial changes) and wait for #6645.  If you want to help with #6645, that would be appreciated!  The approach for that will be substantially different, using rust code to drive the completions which should be much easier to implement, test, etc.

**Comment by lzutao** [comment]
Could you give an example how is this bugged?

**Comment by ehuss** [comment]
Doing completion in cargo's own repo: `> cargo build -p=clap\  `.  
This is on macOS: `zsh 5.7.1 (x86_64-apple-darwin18.2.0)`

But as I said, I'd rather not spend time reviewing or maintaining this code, since we intend to remove it.

**Comment by alexcrichton** [comment]
I'm going to close this since it's been quiet for a bit and due to @ehuss's previous comments.

**Pull request closed without merging**
