### PR TITLE
do not compile test for bins flagged as `test = false`

### LINKED ISSUE #10268: Cargo test ignores test flags when testing specific keyword
### Problem

When running `cargo test xyz`, cargo ignores all test flags in the `cargo.toml` file. 

### Steps

1. create project `cargo init xyz`
2. add `#[test] fn random{}` to your `main.rs` 
3. add the following to your `Cargo.toml`
```rust
[[bin]]
name = "main"
path = "src/main.rs"
test = false
```
4. type `cargo test` and then type `cargo test xyz`

Result:
Capture

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.59.0-nightly (358e79fe5 2022-01-04)
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Fixes #10268

#6683 introduced a behavior that compiles all bin targets, but for bins with `test = false` they shouldn't be compiled with `--test` as testbins.

### How should we test and review this PR?

In the first commit of this PR, I refines the test `test_filtered_excludes_compiling_examples` to reflect the current wrong behavior (test passed). The following two commits correct the behavior and the test accordingly. The last few commits encapsulate scattered target selection logic into functions on `CompileFilter`.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! As I read this though I'm sort of confused and wondering if you can help. Why is this filter reset given a test name to run? I would naively expect that by passing in a test name that doesn't affect the filter of what to or not to build at all and the test name is simply passed to all binaries which are built anyway

**Comment by weihanglo** [comment]
IIUC, examples are included with the default target filter, but https://github.com/rust-lang/cargo/pull/6683#issuecomment-465726293 tried to avoid build examples if `TESTNAME` exists. 

https://github.com/rust-lang/cargo/blob/95bb3c92bf516017e812e7f1c14c2dea3845b30e/src/cargo/ops/cargo_compile.rs#L1417-L1420

I also feel a bit confused and unease when seeing this inconsistency. Though I should admit that it's somehow reasonable since cargo actually doesn't run any unittest in example with default target filter. If one passes in a test name without specifying target, the intent is quite straightforward that they wants to filter tests against default targets. Thus cargo can happily skip compiling examples.

**Comment by alexcrichton** [comment]
Perhaps a better way to organize this would be to have a method on `CompileFilter` called `remove_examples` or similar which can perform the desired result in a more targeted fashion?

**Comment by weihanglo** [comment]
Oops. The PR evolves to a refactoring. 🙇🏾‍♂️

Is 9138c35 in a more targeted fashion as you expect?

**Comment by alexcrichton** [comment]
@bors: r+

Seems reasonable to me!

**Pull request merged**
