### PR TITLE
Warn if checking the freshness of build script is slow

### PR DESCRIPTION
**Pull request by matklad**
This how no-op build looks for Servo:

```
λ $cr build
warning: checking freshness of build script for `selectors` took 106ms, consider using `rerun-if-changed`
warning: checking freshness of build script for `servo_atoms` took 105ms, consider using `rerun-if-changed`
warning: checking freshness of build script for `compositing` took 117ms, consider using `rerun-if-changed`
warning: checking freshness of build script for `script` took 172ms, consider using `rerun-if-changed`
warning: checking freshness of build script for `servo` took 106ms, consider using `rerun-if-changed`
    Finished dev [unoptimized + debuginfo] target(s) in 1.95 secs
```

I fear that as is, this feels a bit heavy handed: there's no way to suppress the warning and preserve current behavior (sans of printing `rerun-if-env-changed=RANDOM_STRING`, but that is a hack). Perhaps we should support something like `rerun-if-changed=*`, as an explicit opt-in into default behavior?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice! I agree though that we may not want to do this just yet. At the very least though we could switch it to a `warn!` and offer debugging support for anyone debugging and/or profiling Cargo. Additionally the check here should probably actually check if `rerun-if-changed` was used, right?

**Comment by matklad** [comment]
> At the very least though we could switch it to a warn! and offer debugging support for anyone debugging and/or profiling Cargo

Oh, one can already `CARGO_PROFILE=1` and see the timings, so we can do nothing at all here :-) 

Let's ask some random servo folks as well perhaps? 

@nox, @SimonSapin : no-op builds of servo with Cargo  (without mach overhead) need about one second, which seems unreasonably huge. Are you bothered by this at all?  If you are, one of the major slow-downs happen because various build scripts in servo do not specify conditions for re-running them, and cargo conservatively assumes that they depend on all files inside the respective package. Because the number of files in servo is huge, calculating the aggregate mtime is slow. To fix it, you should modify build script to print `rerun-if-changed=PATH` line. Offending build scripts are listed in the PR description. 

Do you think that Cargo should give some form of heads-up about this situation?

**Comment by SimonSapin** [comment]
> one second, which seems unreasonably huge

Even multiple times that would be on the noise level, since incremental builds (those where rustc runs at all) still take several minutes. This is so insignificant that I would not want to spent time trying to figure out the respective appropriate set of paths for `rerun-if-change` in each of the many crates with build scripts in Servo’s dependency graph. (Even if it’s only `path` dependencies in the repo, we have like 30 of those though I don’t know at hand how many of them have build scripts.)

If this is to warn by default, I’d strongly prefer to have an easy way to silence the warning without changing the behavior.

**Comment by matklad** [comment]
Ok, so looks like it is not something we should try to fix!

**Pull request closed without merging**
