### PR TITLE
Add an unstable option to build proc macros for both the host and the target

### PR DESCRIPTION
**Pull request by Zoxc**
r? @alexcrichton

### CODE REVIEW

**Comment by Eh2406** [comment]
Sorry, can you help me understand when this would be needed?

**Comment by Zoxc** [comment]
This is needed when you want to cross compile a library for a target A which uses a proc macro crate. Currently we'll only compile the proc macro crate for the host, which means the proc macro crate won't be usable if we actually run the compiler on target A and we try to use our cross compiled library. Note that our library can reexport the macros from the proc macro crate, so it needs to be available to run on the target.

**Comment by Eh2406** [comment]
So I think I am still not understanding. You are cross compiling a rust library (not a final artifact) so that the target can use that file as part of a rust build? There is no rust abi. I am surprised that it works at all.

The workflow I would have expected are to:
- Do all development on the host. Cross compile the final artifacts (executables or c compatible libraries) to the target. Copy and run. No need for proc macros to run on the target.
- Do all compilation on the target. Copy source to the target. Compile locally and run. No need for cross compile.

But I do not know much about the uses of cross compiles, can you explain why you are doing this workflow?

**Comment by alexcrichton** [comment]
@Eh2406 I think a missing piece of information is that this is for the compiler itself. The compiler gets a free pass with unstable features because it deals with its own breakage, and I suspect that this feature would be unlikely to ever graduate from unstable status.

@Zoxc I think before merging this it'd be good to get a working build first. This may not be all that's needed on Cargo's end, so could this be used with a local build of Cargo to test out support in rustc?

**Comment by Zoxc** [comment]
@alexcrichton I should be able to test these change locally, but I was hoping to sneak this into the upcoming release since I can't actually land changes in rustc until this is in beta.

**Comment by alexcrichton** [comment]
We can backport this for rustc to unblock work there, so I'm not too worried about the scheduling here

**Comment by alexcrichton** [comment]
@Zoxc is this ready to go for https://github.com/rust-lang/rust/pull/58013? If so I think this is fine to land on this branch and beta to get it in for the compiler

**Comment by Zoxc** [comment]
This should be good to go

**Comment by mati865** [comment]
Friendly ping, branching is going to happen soon.

**Comment by vext01** [comment]
I'm working on a research project where I need to use serde in the compiler.

It'd be neat if this could be merged soon, so that #58013 can be unblocked.

Thanks :)

**Pull request merged**
