### PR TITLE
Remove explicit --bin for getting started doc

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by steveklabnik** [comment]
We probably want to keep this consistent with the book; https://github.com/rust-lang/book/pull/1316 is the PR for it, and I haven't decided yet.

Thank you for this pr! I wonder what others think.

**Comment by pickfire** [comment]
@steveklabnik Oh, thanks a lot for the quick response. I didn't notice that happened in the book as well.

Though, I had also opened up pull request for other communities such as https://github.com/actix/actix-website/pull/10.

**Comment by matklad** [comment]
Random thoughts:

* book and cargo docs are a little bit different in that the book might be printed, and automatic updating of dead-wood books is difficult (although they [did that in USSR](https://en.wikipedia.org/wiki/Great_Soviet_Encyclopedia#Damnatio_memoriae)), and so the book might be out of sync with Cargo. 

* explicitly typing `cargo --bin` provides affordance to say something "we've passed `--bin`, it's a default but you can also use `--lib`"

* if not using `--bin` to speak about `--lib`, I slightly prefer to just use the default, though I have no strong opinion here.

**Comment by pickfire** [comment]
Yes, I know dead-wood books stay the way they are but web is alive and why not change it? I don't see anything with the books being printed with different stuff though.

In my humble opinion, I prefer reading books that updates, I won't really read all the editions, just the latest one.

**Pull request merged**
