### PR TITLE
Treat "proc-macro" crate type the same as `proc-macro = true`

### LINKED ISSUE #5310: document the difference between 'crate-type = ["proc-macro"]' and 'proc-macro = true'
...whatever it is.

All I can really see is that `crate-type = ["proc-macro"]` makes rustdoc die with `proc-macro crate not dylib` when used in a path dependency.

---

*(er... now that I think about it, I wonder if that's a bug in rustdoc)*
*(...or even a bug in cargo)*
*(...or rustc even! On stable, it produces the same error, but as an ICE!)*

### PR DESCRIPTION
**Pull request by ehuss**
Effectively closes #5310 since they are now identical.

### CODE REVIEW

**Comment by ehuss** [comment]
This is a breaking change if you say:
```toml
crate-type = ["proc-macro"]
plugin = true
```

Found this in the https://crates.io/crates/arthas_derive package.  Do you think it is worth detecting this scenario and allowing it with a warning?

**Comment by alexcrichton** [comment]
Nice catch on that regression, yeah let's emit a warning for now for that. Additionally, could a warning be printed to say that `proc-macro = true` is favored over `crate-type = ["..."]`?

**Comment by ehuss** [comment]
Added some warnings.  I also added a check for multiple crate-types, just to assert an assumption, but maybe that's not necessary (rustc has the same check).

**Pull request merged**
