### PR TITLE
Allow for targeted git dependencies

### PR DESCRIPTION
**Pull request by wagenet**
See #3195

### CODE REVIEW

**Comment by wagenet** [comment]
@alexcrichton can you verify that these tests should pass?

**Comment by alexcrichton** [comment]
I don't think that `duplicate_deps_2` can probably pass, unfortunately, (but it'd be nice if it did!). The latter one would be nice to pass, yeah!

**Comment by wagenet** [comment]
@alexcrichton the issue here is that the check for conflicts check for conflicting `source_id` (https://github.com/rust-lang/cargo/blob/master/src/cargo/util/toml.rs#L628). The `dubplicate_deps_2` passes because all crates specified by version always have the same `source_id`, despite being different deps. When specified by `path` or `git` the `source_id`s vary and it's deemed a conflict. What do you think the correct approach to resolving this is?

**Comment by alexcrichton** [comment]
I've always felt pretty uneasy about multiple entries in the list of dependencies with the same name, if those are let through I suspect it will wreak havoc on the backend which wasn't expecting that at all. In that sense this likely won't be an easy bug to fix. Unfortunately I don't know the best way to tackle this right now :(

**Comment by wagenet** [comment]
I have an actual case for this where I'm trying to support both old libc as well as FreeBSD. The versions of libc required for the two cases are incompatible. Because I can't switch between two version of the same library, I've actually had to resort to cloning the respective crates and giving them a different name.

**Comment by alexcrichton** [comment]
I'm going to close this for now due to activity, but please feel free to resubmit of course!

**Comment by wagenet** [comment]
See #6212

**Pull request closed without merging**
