### PR TITLE
Fix formatting issues with cargo fmt

### PR DESCRIPTION
**Pull request by djc**
Noticed these unrelated formatting problems while working on #5258.

### CODE REVIEW

**Comment by matklad** [comment]
Hm, we run `cargo fmt` on CI, so I think this is how this is supposed to be formatted?

@djc how do you get rustfmt to use this other style? Perhaps you version of rustfmt differes?

**Comment by djc** [comment]
@matklad if you look at the failures in https://travis-ci.org/rust-lang/cargo/jobs/359754442, you see that they require these changes.

**Comment by matklad** [comment]
@bors r+

Figured out! We've released 1.25 today, which updated rustfmt as well.

**Comment by Eh2406** [comment]
Bors failed to merge as the branch had bin deleted. @matklad can you r+ again

**Comment by matklad** [comment]
No worries!

@bors r+

**Pull request merged**
