### PR TITLE
fixed workspaces issues due to non-canonical manifest path

### LINKED ISSUE #7686: Workspace path is not fully resolved
# Setup
I have the following (potentially strange) setup:
```
$project
├── a
│  ├── Cargo.toml
│  └── src
│     └── main.rs
├── b
│  ├── Cargo.toml
│  └── src
│     └── main.rs
├── c
│  ├── Cargo.toml
│  └── src
│     └── main.rs
└── Cargo.toml # containing `workspace.members = ["a", "b", "c"]`
```

# Problem
If I'm executing `cargo install --path ../c` in directory `b` the following error occurs:
```
error: package `/home/jfrimmel/git/$project/a/Cargo.toml` is a member of the wrong workspace
expected: /home/jfrimmel/git/$project/b/../Cargo.toml
actual:   /home/jfrimmel/git/$project/Cargo.toml
```
It seems like the paths are not `canonicalize`d before comparison.

# Reproducation
```bash
~ $ mkdir mwe
~ $ cd mwe/
~/mwe $ cargo new a
     Created binary (application) `a` package
~/mwe $ cargo new b
     Created binary (application) `b` package
~/mwe $ cargo new c
     Created binary (application) `c` package
~/mwe $ cat <<EOF > Cargo.toml
[workspace]
members = ["a", "b", "c"]
EOF
~/mwe $ cd b
~/mwe/b $ cargo install --path ../c --force
error: package `/home/jfrimmel/mwe/a/Cargo.toml` is a member of the wrong workspace
expected: /home/jfrimmel/mwe/b/../Cargo.toml
actual:   /home/jfrimmel/mwe/Cargo.toml
~/mwe/b $ 
```

# Metadata
```
$ cargo --version
cargo 1.41.0-nightly (8280633db 2019-11-11)
```

### PR DESCRIPTION
**Pull request by stefanhoelzl**
this PR fixes #7686 

comparisons with the root manifest path failed even if paths were identical.
This was due to a comparison with a non-canonical root manifest path with the canonical one.

This PR canonicalizes the manifest path when a Workspace is created, so that all future comparison are using the canonical manifest path.

Before two identical path, just represented differently, where not equal e.g. `a/../a != a`
With this PR the comparison looks like this `a == a`, which is as expected equal

### CODE REVIEW

**Comment by stefanhoelzl** [comment]
oh, looks like under windows the canonical path is a UNC path, see rust-lang/rust#42869
that's why the tests under windows are failing.

**Comment by alexcrichton** [comment]
Thanks for the PR! Unfortunately though this sort of user-space canonicalization is very tricky and we try to avoid it wherever we can. Can this same issue be solved with syscalls or some other form of path comparison which doesn't require manually interpreting the path?

**Comment by stefanhoelzl** [comment]
like I said `fs::canonicalize` does a normalization, but also creates UNC paths on windows.
There is this [dunce](https://crates.io/crates/dunce) crate which make a regular path out of UNC paths, but this would add another dependency.

I am not aware of other ways, but I am pretty new to rust, so maybe there is another solution

**Comment by ehuss** [comment]
`dunce` looks interesting, though it is a little concerning it is all user-space.  Dealing with this properly is extraordinarily difficult, but I'm not sure if we need to aim for 100% perfection.

One of the fundamental questions is whether or not the normalization should follow symlinks.  I'm not sure I have a good answer to that.  Using symlinks in a workspace seems likely to be problematic.

Cargo has [`normalize_path`](https://github.com/rust-lang/cargo/blame/7059559d71de3fffe8c8cb81e32f323454aa96c5/src/cargo/util/paths.rs#L65-L90), which is a somewhat simplified version.  I suspect it is somewhat wrong in some cases, but again getting perfect is a monumental task.  I would feel more comfortable replacing that with something that is known to be more correct.

One thing I've been curious about is whether or not [`GetFullPathNameW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew) would be a good alternative to `GetFinalPathNameByHandle`.

**Comment by alexcrichton** [comment]
I think in general we've been bitten enough by any form of canonicalization that we want to avoid adding more canonicalization to Cargo. Can we perhaps solve this by not comparing paths? Is there something else we can do in Cargo?

**Comment by stefanhoelzl** [comment]
I was not aware of `paths::normalize_path` in cargo, but I tried it and it does the job, so my `resolve_path` method is not necessary, but we would still do the sanitation in user space.
Still would be the easiest fix and would not introduce some new canonicalization.

Another interesting crate could be [same-file](https://crates.io/crates/same-file) it compares files by comparing their inode-number on unix respectively the file_index on windows.

**Comment by alexcrichton** [comment]
Looking through some paths the normalization logic is actually [already applied](https://github.com/rust-lang/cargo/blob/f6449ba236db31995255ac5e4cad4ab88296a7c6/src/cargo/util/command_prelude.rs#L266) for `--manifest-path` arguments, so I think this may perhaps be only related to `--path` of the `cargo install` command? If that's the case can the fix be applied locally to just that one location to avoid repeated calls to normalization? Ideally we want the normalization to be as far away as possible as well to reduce implicit reliance on it within Cargo.

**Comment by alexcrichton** [comment]
This has been here for quite some time now so I'm going to go ahead and close this, feel free to resubmit though!

**Pull request closed without merging**
