### PR TITLE
Markdown manpages

### PR DESCRIPTION
**Pull request by alx741**
This is related to #2647 and  #2660, Addresses #2645 

I tried an *asciidoc* port (#2660), but markdown has some advantages:

- Rust, Cargo, others use MD for documentation already so avoid introducing a new markup language.
- Introducing a new tool is necessary for *asciidoc* or *markdown* anyways, but is possible to extend **rustdoc** (works with MD input) to output *troff* and thus effectively replace **pandoc** in the future to make the whole ecosystem *rusty*.
- Much more easy to maintain and extend *markdown* than raw *troff*.

All of this would be applicable to **rustc** as well as @alexcrichton suggested.

And of course as mentioned in the other PRs, this aims to make the man page system similar to **git**, having a man page for each sub-command and making `$ cargo help command` to launch the appropriate one.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice! Do you know if there are any Rust-based generators to go from markdown to troff? This'd unfortunately require us to go change our buildbots as well which is somewhat of a PITA, so if this was all handled as part of the makefiles that'd be the best

**Comment by alx741** [comment]
Apparently no, there is a nice parser: [md.rs](https://github.com/netvl/md.rs) but the whole *troff* formatting is required in which case we might extend rustdoc as well for that matter.

No sure what you mean here (?)
> if this was all handled as part of the makefiles

But for now I see no other way for the md -> troff generation unfortunately

**Comment by alexcrichton** [comment]
Ah just that in theory this could be something like a submodule that we build rather than a requirement of a tool to install

**Comment by alx741** [comment]
Yeah, such module would need to be written from scratch tho, apart from the token generator I couldn't find anything that will allow us to do that.

**Comment by alexcrichton** [comment]
Closing for reasons outlined here: https://github.com/rust-lang/cargo/pull/2660#issuecomment-220093591

**Pull request closed without merging**
