### PR TITLE
Man page: Improve build command section

### PR DESCRIPTION
**Pull request by alx741**
Addresses #2645 

This is a proposal for improving the documentation available in the man page about each command; It has been applied to the **build** command only, if it is useful i will do the same with the other ones.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder if we should perhaps add man pages along the lines of `cargo-build.1` and such? I think that's what git and other tools do, and it should allow the page to expand greatly with tons of docs and things.

**Comment by alx741** [comment]
Oh that's a great idea!
I'll checkout how does git make it and will come back here with something on that style.

**Comment by alx741** [comment]
Ok, I made just for **cargo build** as the first try.
It's basically the same that **git** does.

- The main page `cargo(1)` has a *COMMANDS* section like `git(1)` has.
- There is a `cargo-build(1)` as a reference to the sub-page like `git(1)` does.
- Of course there is the `cargo-build(1)` page.

For git we do `$ man git-add`  so here the user can do `$ man cargo-build` for instance. 

An appropriate invocation from cargo is needed:
In git the user can do `$ git help add` and the `git-add(1)` man page pops up. So it would be nice to do the same for `$ cargo help build`.

**Comment by alx741** [comment]
There is another important thing about this:
Writing and maintaining troff pages is not nice, specially if we attempt to improve Cargo documentation man pages in a similar fashion of Git.

Git uses [asciidoc](http://www.methods.co.nz/asciidoc/), which makes it very easy to write and maintain, also avoids repetition, allows auto inserting of commands indexing, and some other neat stuff that the Git repo heavily uses (and take advantage of) apparently.

So before writing more sub-pages for the other commands, I would suggest to port the existing one to *asciidoc* to make it easy to take further.

**Comment by alexcrichton** [comment]
Thanks! I wonder if we could perhaps unify the documentation with the subcommand `--help` documentation as well? They probably don't want to all be exactly the same, but they could all be derived from the same source perhaps.

In any case though this seem like a great improvement, so I'm gonna r+, thanks!

@bors: r+ e78b17dea4bc64cbc1b957bc5347afa5563c0ce1

**Comment by alx741** [comment]
Will port those two pages to asciidoc and make it work with that first.

> unify the documentation with the subcommand --help documentation 

About that I suspect asciidoc will allow it neatly and without duplication, so definitely doing that too.  

I'm not very familiar about how does **bors** operates so I'm wondering if further changes have to be applied in the same branch (and this same PR in consequence)? or using a new branch? new PRs?  Please give me some light about that :smile:

**Pull request merged**
