### PR TITLE
Include rustc version in metadata

### PR DESCRIPTION
**Pull request by Keruspe**
Followup to #4134 
Fixes https://github.com/rust-lang/rust/issues/42483

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by Keruspe** [comment]
Any change to get this backported for rust-1.19?

**Comment by alexcrichton** [comment]
Sure yeah seems fine by me! Want to send a PR to the rust-1.19 branch here?

**Comment by Keruspe** [comment]
Sure, will do

**Pull request merged**
