### PR TITLE
Implement generate-index-metadata command

### PR DESCRIPTION
**Pull request by synek317**
It solves the issue https://github.com/rust-lang/cargo/issues/4497

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Unfortunately now though there's a [soft feature freeze](https://internals.rust-lang.org/t/pre-rfc-complete-cdylib-support-in-cargo/8843/12) in Cargo so it may be some time before the cargo team has bandwidth to review this

**Comment by Eh2406** [comment]
As someone without much of the background context, I would like to see more documentation. What dose it do? How can it be used? How can it be configured?

If my guess about what this does, I'd love to see an extenuation that let us take a resolution bug report and tern it into a reproducible test case.

**Comment by synek317** [comment]
@alexcrichton was it freeze until rust 2018 release or is it freeze to the end of the year?
I've rebased my branch so it is mergeable again.

**Comment by Eh2406** [comment]
cc @ehuss

**Comment by ehuss** [comment]
At this time I think we'd like to experiment with index-related commands out of tree. I'm putting together a new subcommand which provides several options for managing an index, which I'll be posting soon. Do you have interest in running a registry? If so, feedback and testing would be helpful to figure out what features are needed.

**Comment by synek317** [comment]
https://github.com/synek317/cargo-git-registry

This is my subcommand to create registry in a git repository: https://github.com/synek317/cargo-git-registry

 It is _very_ much work in progress but with `generate-index-metadata` it worked well and I've successfully created registry. Maybe the last issue was copy-paste the code from crates.io to create registry directories (e.g. ca/rg/cargo), but this is really small.

With `generate-index-metadata` in master cargo branch I'm going to go back to this project. It would really help me at work.

**Comment by ehuss** [comment]
@synek317 Nice!  I'm trying to make it possible to implement this separately just using `cargo metadata` because linking against Cargo is a pain.  I hit a bit of a roadblock due to some implementation issues, but I hope to have it resolved soon.

**Comment by dwijnand** [comment]
Closing in favour of the conversation in #4497 and the out-of-tree experimentation in https://github.com/ehuss/cargo-index.

**Pull request closed without merging**
