### PR TITLE
Cargo fix --prepare-for should only apply edition fixes

### LINKED ISSUE #5738: Cargo fix --prepare-for should only apply edition fixes
Originally reported as https://github.com/rust-lang-nursery/rustfix/issues/129

---

As per rust-lang-nursery/rustfix#120 it applies all suggestions, which include the builtin lints.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #5738

.. or at least it looks like it does? Please check my test.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I'm not sure though that this strategy will work because I believe the reported lint in the diagnostics is the lint in question (like `async_idents`) rather than the lint group (the compatibility lint group) unfortunately.

We may be able to tweak the compiler to tell us the lint group though!

**Comment by dwijnand** [comment]
I think I see what you mean: see the `fix::fix_overlapping` failure in CI which says:

```
note: `-W absolute-paths-not-starting-with-crate` implied by `-W rust-2018-compatibility`
```

> We may be able to tweak the compiler to tell us the lint group though!

Before you nerd-snipe me into the compiler repo, how maintainable is it to whitelist the list of lints implied by `rust-*-compatibility`?

**Comment by dwijnand** [comment]
That's what I suspected/feared.

Is there an existing ticket in the rust repo for this? Do you think you (or @killercup, or...?) could flesh one out so I know how to get started? 🙏

**Comment by alexcrichton** [comment]
Ah unfortunately I don't thik there's an issue on the rust-lang/rust repo, and I wouldn't actually know where to get started for it :(

@killercup may have more ideas though!

**Pull request closed without merging**
