### PR TITLE
Intern semver::Version/semver::VersionReq

### LINKED ISSUE #6207: Intern more kinds of things
Cargo sometimes makes a lot of copies of data structures. For example the string "serde", was copied for the name of each dependency on that crate, as the name of each version of that package, and for each feature that enables that package. This got fixed by adding a [`InternedString`](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/interning.rs) data type that deduplicates the data and leaks it into a `&'static` reference. We have other data structures which use `Arc/Rc` to make cloning cheaper.

We should experiment with Interning them to see if it is a Speed or Memory or Ergonomic win.

Off the top of my head:

- [x] `PackageId` is already using `Arc`, is copied and hashed and compared all over the place in hot code. 
- [x] `SourceId` is already using `Arc`, has a manual cache for `crates.io` and will probably be leaked anyway by caching `PackageId`.
- [ ] `semver::Version/semver::VersionReq` are used a lot, probably often with the same value, and are bigger structures then they seem.

### PR DESCRIPTION
**Pull request by dwijnand**
Resolves #6207

### CODE REVIEW

**Comment by dwijnand** [comment]
That's the next challenge: "intern" this cache infrastructure :wink:

**Comment by alexcrichton** [comment]
Out of curiosity, do we know a location where we clone these a lot or create a lot of duplicate ones? It's not as clear to me with source/package ids that Cargo would benefit from this

**Comment by dwijnand** [comment]
Paging @Eh2406 😄

**Comment by Eh2406** [comment]
@dwijnand good question why did I say that...

looking back at the original, it is not so much that we cloned it a lot. Rather they are larger structures then they seem, and we probably have the same values menny times. (How many crates have a version `0.1.0`?) So it may save memory by deduping. Also we already are leaking some of them by `PackageId` being interned.

Now that I am saying it I am not entirely convinced. Maybe given that `PackageId` Is Interned it is  redundant to inter this ass well? Or maybe on the  flip side, If we intern this then `PackageId` is just 3 pointers, and maybe it should not be interned?

@ehuss this interning strategy was inspired by internment. Each time we have copied this code we have needed to override the impl of `Hash`, so I don't think we can use something off the shelf. But there is definitely room to remove some of the duplication.

**Comment by dwijnand** [comment]
Sure! How?

**Comment by alexcrichton** [comment]
The "easiest" is probably Valgrind with massif on Linux perhaps?

**Comment by dwijnand** [comment]
I don't have the bandwidth.  The PR is here and it's not going anywhere, so we can always reconsider this change down the line.  I'll salvage some of the diffs in a new PR.

**Pull request closed without merging**
