### PR TITLE
Fix a test.

### PR DESCRIPTION
**Pull request by matklad**
That's the test we've discussed in #3443

### CODE REVIEW

**Comment by matklad** [comment]
r? @alexcrichton 

> consider extending support for discovering the root through hierarchical Cargo.toml later?

I am in general a bit worried that workspaces logic got changed in the ad hoc way form what was proposed in the RFC. I think that current variant is much better, but I am uneasy because it wasn't the result of an RFC process, so not so many people have actually scrutinized it. 


Perhaps this can be discussed at the tools team meeting, just to make sure we don't code ourselves in backwards compatibility corner? I've written a summary of what I think should be the rules here: https://github.com/rust-lang/cargo/pull/3443#issuecomment-272557390

**Comment by alexcrichton** [comment]
@matklad yeah I wouldn't want to tweak the logic without garnering more opinions. Do you want to propose that feature in a separate PR so we can discuss there? (sorry if this is just a runaround on various PRs...)

**Comment by matklad** [comment]
>Do you want to propose that feature in a separate PR so we can discuss there?

https://github.com/rust-lang/cargo/pull/3562 And I have actually realized that one half of the implementation is totally missing from the PR :)  I wonder if this means that we miss some validation?

**Pull request merged**
