### PR TITLE
Adding target support to cargo package and cargo publish

### PR DESCRIPTION
**Pull request by nisargthakkar**
Fixing Issue #4012 

Same as #4077 but couldn't reopen the PR due to force push after rebasing from master

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Looks great to me, thanks!

**Comment by nisargthakkar** [comment]
@alexcrichton is `extern crate url;` not required?

**Comment by alexcrichton** [comment]
Looks to be so!

**Comment by nisargthakkar** [comment]
Sending the updated commit in a bit after tests pass

**Pull request merged**
