### PR TITLE
Prevent packaging a crate if any files are dirty

### LINKED ISSUE #2063: cargo must not package arbitrary files
Today I learned 'cargo package' includes everything in the working directory not explicitly excluded through `.gitignore` or the `package.excludes` directive in `Cargo.toml`. This wasn't what I expected at all, and differs from what, for example, GNU autotools implements as best practice. I expected cargo to only package files which were part of of the build description and its dependent source.

I only discovered this because I copied a few test videos into my working tree and the package was suddenly too large to upload.

In https://github.com/rust-lang/cargo/issues/1597 @bluss suggests a warning for untracked files. That would be an improvement, at perhaps educate people about the default, but I think that doesn't go far enough. Uploading random files from the working directory is a terrible developer experience, and 
makes is very easy to leak confidential or unlicensed data.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit alters Cargo's behavior to prevent publishing a crate by default if
any files in that crate are determined to be dirty, that is either modified or
not part of the working tree.

This can prevent common mistakes like many listed in #2063 and enables features like https://github.com/rust-lang/cargo/issues/841.

Closes https://github.com/rust-lang/cargo/issues/1597
Closes #2063

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

cc @sbeckeriv

**Comment by badboy** [comment]
How does this behave if there _are_ dirty files, but the `Cargo.toml` has an explicit `includes` block, but the dirty files are not included?

**Comment by alexcrichton** [comment]
@badboy this only check that the files that Cargo thinks are part of a package are not dirty, so in that case it'd allow a publish because Cargo doesn't think they're included in the package.

**Pull request merged**
