### PR TITLE
Fix --manifest-path for verbatim paths

### LINKED ISSUE #6198: "Package collision in lockfile" using UNC/root local device/etc paths
**Problem**
When invoking Cargo with the current directory or manifest path given as one of Windows' more "exotic" kinds of paths, such as a `\\?\` "root local device path," internal path comparisons can fail and the build aborts. Ideally, Cargo would be able to handle these paths.

**Steps**
One way to reproduce the bug is with a directory structure like this:
```
bug/
  main/
    Cargo.toml
    src/lib.rs
  dep_a/
    Cargo.toml
    src/lib.rs
  dep_b/
    Cargo.toml
    src/lib.rs
```

`main` depends, via `path = "../dep_a"` and `path = "../dep_b"`, on both `dep_a` and `dep_b`. `dep_a` also depends, via `path = "../dep_b"`, on `dep_b`.

Here is a zip file containing the structure described above: [path-bug.zip](https://github.com/rust-lang/cargo/files/2502476/path-bug.zip)

Then, the bug can be triggered by running this command:

```cmd
cargo build --manifest-path \\?\C:\full\path\to\bug\main\Cargo.toml
```

It produces an error message like this:

```cmd
error: package collision in the lockfile: packages dep_b v0.1.0 (C:\full\path\to\bug\main\../dep_b) and dep_b v0.1.0 (C:\full\path\to\bug\dep_b) are different, but only one can be written to lockfile unambigiously
```

`wasm-pack` hits this issue because it sets the current directory to a canonicalized `.` when invoking Cargo. See https://github.com/rustwasm/wasm-pack/issues/380, https://github.com/rustwasm/wasm-pack/issues/413, and an attempt to work around this problem in https://github.com/rustwasm/wasm-pack/pull/389.

**Notes**
I most recently reproduced this with Cargo version `cargo 1.31.0-nightly (5dbac9888 2018-10-08)`, on Windows 10.

### PR DESCRIPTION
**Pull request by dylni**
This lets `--manifest-path` be a verbatim path (`\\?\C:\full\path\to\manifest`) without causing:

    error: package collision in the lockfile: packages dep_b v0.1.0 (C:\full\path\to\bug\main\../dep_b) and dep_b v0.1.0 (C:\full\path\to\bug\dep_b) are different, but only one can be written to lockfile unambigiously

There are 2 commits:

- The first commit is the minimum required to fix the issue.
- The second commit also improves normalization of that section to resolve `..` correctly on Unix, but it causes some test regressions. They can be fixed by using the original path when normalization fails, [which Cargo does in other cases](https://github.com/rust-lang/cargo/blob/905134577c1955ad7865bcf4b31440d4bc882cde/src/cargo/util/paths.rs#L449-L456).

    Should I keep the regressions or use that fallback for this PR too?

Closes #6198

cc @Eh2406

### CODE REVIEW

**Comment by dylni** [comment]
This is the failing line:
https://github.com/rust-lang/cargo/blob/905134577c1955ad7865bcf4b31440d4bc882cde/tests/testsuite/member_errors.rs#L107

I don't know enough about this test to figure out the right fix.

**Comment by alexcrichton** [comment]
There's some more discussion about this on https://github.com/rust-lang/cargo/pull/7729, but unfortunately path normalization is tricky in Cargo and is something we try to review pretty closely. We primarily try to normalize as little as possible as well as only having one method of normalization rather than multiple.

I think these issues would be great to fix but I haven't investigated them enough myself to know how to best do so. I think it would be good though to add a suite of test if possible. If this is just fixing one issue for Windows UNC paths then the fix can probably be a bit more isolated?

**Comment by dylni** [comment]
@alexcrichton The new function uses the [`GetFullPathNameW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew) syscall on Windows, which normpath provides with [`PathExt::normalize`](https://docs.rs/normpath/0.1.0/normpath/trait.PathExt.html#tymethod.normalize). It should always return a correct normalized path, but others reviewing the code is always welcome. My intention is to eventually remove `normalize_path_legacy` and convert all uses to the safer syscall version.

I can add some tests here if this change is decided to be useful, but I've made sure to test normpath [extensively](https://github.com/dylni/normpath/tree/master/tests) to make sure it can be used in these situations. The test from the bug report has already been added.

**Comment by dylni** [comment]
@alexcrichton @Eh2406 Does this PR require anything else? It's a start to fixing more normalization issues.

**Comment by 64** [comment]
Bump.

**Comment by ehuss** [comment]
Closing as this PR is quite old, and unfortunately it isn't entirely clear on how to proceed with fixing the Windows paths issues (and unfortunately none of us have much time to invest in this). I have opened #9769 as a meta issue to cover this. I understand this can be a frustrating issue to deal with, and this isn't saying we don't want it fixed (we very much do!), but that we want to better understand how to proceed. Thanks!

**Pull request closed without merging**
