### PR TITLE
Use `git gc --auto` in maybe_gc_repo

### LINKED ISSUE #8195: Cargo should not run git gc manually
Saw this on twitter:
https://twitter.com/indygreg/status/1256656752944111616
and it turns out
a) cargo is checking how many packs there are on its own
b) if there are too many, it runs git gc, which is blocking.

There is a git command to do both of that automatically, with b) being done in the background, not blocking anything else: `git gc --auto`. The `maybe_gc_repo` function should just call that unconditionally. This also has the advantage of respecting the various gc.* git config items, instead of a manual __CARGO_PACKFILE_LIMIT.

### PR DESCRIPTION
**Pull request by glandium**
Fixes #8195.

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks!  It looks like it broke some tests, though.

Also, do you have any information about how safe this is to do? Does git work well concurrently with libgit2? The `git gc` man page says "users who run commands concurrently have to live with some risk of corruption", which doesn't instill a lot of confidence. I also have no idea if libgit2 uses the same locking and anti-corruption strategies as the official client. Since Cargo immediately runs a fetch operation afterwards, it seems like it would be risky.

**Comment by glandium** [comment]
> Thanks! It looks like it broke some tests, though.
> 
> Also, do you have any information about how safe this is to do? Does git work well concurrently with libgit2? The `git gc` man page says "users who run commands concurrently have to live with some risk of corruption", which doesn't instill a lot of confidence. I also have no idea if libgit2 uses the same locking and anti-corruption strategies as the official client. Since Cargo immediately runs a fetch operation afterwards, it seems like it would be risky.

git gc --auto will not remove anything from the repo that is not older than 2 weeks by default (although someone could have set gc.pruneExpire to now). It will also only remove unreferenced loose objects. Those don't happen simply by fetching. They happen when you `git add` something, but never commit it, for example, which is not how cargo uses repositories. I don't know whether libgit2 follows the same locking as git (one would sure hope it does), but even if it doesn't, I wouldn't expect corruptions here.

**Comment by glandium** [comment]
I don't know what the remaining rustc_info_cache errors are, but they happen locally even without the patch...

**Comment by alexcrichton** [comment]
This is something I ran into myself recently too, so it's neat to see what git has a feature for this! (running in the background)

I'd echo the same concerns as @ehuss though in that it's not clear to me whether we'd function correctly with a gc happening concurrently in the background. I don't really know how the git gc works myself or how roots are determined. Cargo's management of the index is somewhat nonstandard as well since we don't even have a checkout, and I forget if we have branches/refs/etc tracking commits.

Would it be possible to run `git gc --auto` in the foreground as a stopgap for now? That way we could start respecting global git configuration immediately, and we could figure out in parallel if it's safe to run the gc concurrently.

**Comment by glandium** [comment]
It's quite simple to do so: just use `git -c gc.autoDetach=false gc --auto` instead of `git gc --auto`.

**Comment by glandium** [comment]
An alternative would be to implement gc manually with the git_packbuilder_* API from libgit2.

**Comment by alexcrichton** [comment]
I'd be fine with either route, I think it'd probably just be best to run in the foreground for now until we're sure that this is an operation which can happen concurrently.

**Comment by alexcrichton** [comment]
We discussed this in the Cargo meeting and @joshtriplett spoke  about the concurrency aspect and said that libgit2 is highly likely to work since `git gc` is intended to be extremely defensive about concurrent accesses. To hopefully improve our resilience a little more, we were also thinking that the `git gc` could perhaps be run after the fetch instead of just before?

@glandium would you be up for making that change and we can r+ with it running in the background as well?

**Comment by glandium** [comment]
> @glandium would you be up for making that change and we can r+ with it running in the background as well?

Just to be clear, are you saying the patch as-is + a move of the maybe_gc_repo call to after the fetch?

**Comment by alexcrichton** [comment]
Yeah, @joshtriplett spoke to how it's highly likely to continue to work given the defensiveness of `git gc`, and moving it after the fetch should make it even less likely to not work by accident because we'd only gc after fetching.

**Comment by glandium** [comment]
There's an interesting error in the azure tests, where the panic message seems split between stdout and stderr.

**Comment by glandium** [comment]
Ah, the current code actually relies on reinitializing the repo entirely when git is not available (and thus git gc), and then fetch, so that the number of packs is reduced. Which doesn't work if git gc happens after fetching.

**Comment by alexcrichton** [comment]
Ah right, that's because the function is currently reliant on only running sometimes but it's now being changed to run unconditionally.

We don't want to reinitialize the entire repository on each fetch so if git isn't available I think we'll still want some sort of a guard like we have today, but otherwise what you've written down sounds pretty reasonable to me.

**Comment by ehuss** [comment]
Closing due to inactivity.  We're still interested in improving the automatic garbage collection.  If you want to continue pursuing this, feel free to reopen or post a new PR.

**Pull request closed without merging**
