### PR TITLE
Set environment variable for rustc in custom_build.rs

### PR DESCRIPTION
**Pull request by munyari**
Addresses #2819

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks! Thinking a little more, could you be sure to reexport the `RUSTDOC` variable as well? Additionally, could you add a test for this?

**Comment by munyari** [comment]
Hi @alexcrichton. I've done the first part of what you've asked. I'm wondering where I should add the tests. Should I add `cargo_compile_with_rustc()` and `cargo_compile_without_rustc()` to tests/build.rs? Should I add `RUSTC` and `RUSTDOC` to `custom_build_env_vars()` in tests/build-script.rs? Excuse me if these questions seem naive, I'm new to navigating large codebases and open source contribution in general.

**Comment by alexcrichton** [comment]
Ah yeah no worries! This'd be best to add a new test in `tests/build-script.rs` and you can probably just copy/paste another test to start out. The build script will just want to assert that the two environment variables are defined (and perhaps that they point to real files), and that should be sufficient to test this.

**Comment by munyari** [comment]
Thanks Alex. In this commit, I made the assertion that `RUSTC` and `RUSTDOC` are set both in `custom_build_env_vars`, as well as in a new test `rustc_and_rustdoc_set_correctly`

**Comment by alexcrichton** [comment]
@bors: r+ 7070e3158bbaa7622ff888cb918b46fb34cd278b

Thanks!

**Pull request merged**
