### PR TITLE
WIP: Support target configuration in workspace modules

### LINKED ISSUE #7004: Per crate build target in workspace
**Describe the problem you are trying to solve**

I have a project with two crates in a workspace. The first crate should compile to asmjs with `--target asmjs-unknown-emscripten` and the result is used in the second crate, which should compile to the native binary format (default target).

When I run `cargo build` in the root crate that contains the workspace configuration in `Cargo.toml`, it builds both crates using the default target.

**Describe the solution you'd like**

I'd like to be able to specify the target for each crate. I'm not sure if this belongs in each crates' `Cargo.toml` or in the root crate's `Cargo.toml`.

### PR DESCRIPTION
**Pull request by j16r**
[Fixes #7004]

### CODE REVIEW

**Comment by alexcrichton** [comment]
This has unfortunately been languishing for quite some time now so I'm gonna go ahead and close this. In general we'd reocmmend discussing design and sending a PR once the team is good to go on a new feature, unfortunately starting with failing tests tends to not have a ton of traction :(

**Comment by autodidaddict** [comment]
Does this mean that Cargo still completely ignores the `.cargo/config` files in each of the sub-directories? Because this is still a pretty nasty problem that prevents me from running a cargo build on the entire workspace.

**Comment by j16r** [comment]
I don't believe it completely ignores `.cargo/config`, only the target triple

**Comment by autodidaddict** [comment]
The target triple is the one thing that I need it to honor

**Pull request closed without merging**
