### PR TITLE
Error message for package "depends on itself" lists the packages in the cycle.

### PR DESCRIPTION
**Pull request by gilescope**
I got a cycle while trying to build someone else's code and cargo's error message didn't point me in the right direction, just mentioned there was a cycle. I thought we could be a bit more helpful.

Don't know what you think of {:#?} as the display but it seemed minimal code so I thought I'd start with that. I could compress the output to one package per line if preferred.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I think that using `{:#?}` isn't necessarily what we want here and we'll probably want to expand the cycle and manually pretty print it. Can the test case also be updated to match the output of what's printed?

**Comment by gilescope** [comment]
Sure, more like this? (Let me know if there's a neater way of expressing it in Rust. I tried visited[..].join("\n.   ") but the compiler wasn't convinced.)

(I'm assuming the \n turns into \r\n on a windows platform somewhere else?)

**Comment by gilescope** [comment]
Valid failure- will run the tests on a windows box.

**Comment by Eh2406** [comment]
Does it make sense to reuse the `describe_path` code from the other error messages to get the output to be in order?
https://github.com/rust-lang/cargo/blob/3cd7708774f74b137f0fff76d7f9d0ebd9754485/src/cargo/core/resolver/mod.rs#L996

**Comment by alexcrichton** [comment]
Nice! Could the `with_stderr_contains` functions though stay as `with_stderr` for an exhaustive match?

**Comment by alexcrichton** [comment]
@bors: r+

Awesome, thanks!

**Comment by alexcrichton** [comment]
Ah that looks benign, but want to remove the `#![deny(unused)]`?

**Comment by gilescope** [comment]
Feels like there should be:

   1. A way to identify machine generated code, and 
   2. A way to allow a clippy rule to not apply rule(s) to machine generated code.

(But that's out of scope for this PR.)

**Comment by gilescope** [comment]
thanks again @alexcrichton and @Eh2406 - really appreciated your guidance!

**Pull request merged**
