### PR TITLE
add env variable to retrieve workspace root path

### PR DESCRIPTION
**Pull request by csmoe**
Closes https://github.com/rust-lang/cargo/issues/7036
r? @matklad @alexcrichton

### CODE REVIEW

**Comment by matklad** [comment]
The current work-around for this is to launch `cargo metadata`, which is not to pretty: https://github.com/mitsuhiko/insta/commit/943e7bca885140d6253a0ee97127e0f963403eac

The potential gotcha here is that workspace situation is different between locally developed crate, and crate as it exists on crates.io: in the latter case, we remove all workspace structure and just store a flat list of crates.

**Comment by csmoe** [comment]
@matklad 
tried to build a crate with this patch, output this snippet:
```
CARGO_MANIFEST_DIR=/Users/pengtangjin/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0 
CARGO_WORKSPACE_MANIFEST_DIR=/Users/pengtangjin/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0
```
I thought it was ok, any case dangerous cases I missed?

**Comment by csmoe** [comment]
@matklad
tried to build a crate with this patch, output this snippet:
```
CARGO_MANIFEST_DIR=xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0 
CARGO_WORKSPACE_MANIFEST_DIR=xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0
```
I thought it was ok, any case dangerous cases I missed?

**Comment by alexcrichton** [comment]
Thanks for the PR @csmoe and sorry for the delay in review!

This sort of feature has a bit of history at this point, so I think it's worth paging that in as well. In addition to https://github.com/rust-lang/cargo/issues/7036 there's a lot more discussion on https://github.com/rust-lang/cargo/issues/3946 along with a [closed PR](https://github.com/rust-lang/cargo/pull/4787) and [rationale for why the PR was closed](https://github.com/rust-lang/cargo/issues/3946#issuecomment-359619839). 

Could this perhaps address some of the feedback in those threads to indicate why we would merge this instead?

**Comment by csmoe** [comment]
Thanks for reviewing :), the problems wasn't addressed.
So, closed.

**Pull request closed without merging**
