### PR TITLE
Canonicalize path_args src

### LINKED ISSUE #7078: Canonicalize src path for fingerprint
**Describe the problem you are trying to solve**

When cargo registers information used later on to figure out whether or not to recompile a unit, the path to the source is tracked in the fingerprint:

https://github.com/rust-lang/cargo/blob/83d086da9467edb969d25a1223a902815388eb8c/src/cargo/core/compiler/mod.rs#L684-L697

However this path is not canonicalized, meaning that e.g. symlinks aren't resolved before the source paths are added to the fingerprint.

This causes two kinds of issues:

1. It's convenient to use symlinks to point to a local registry when using [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html). But since the paths are not canonicalized this can cause spurious rebuilds if the symlink _source_ changes (while the symlink _target_ doesn't).
2. Same use case as above, but say the symlink _source_ doesn't change, while the symlink _target_ changes. In this case cargo will reuse outdated build artifacts.

**Describe the solution you'd like**

The paths can be canonicalized before being returned:

``` diff
diff --git a/src/cargo/core/compiler/mod.rs b/src/cargo/core/compiler/mod.rs
index 628ac8bb..dcc668e8 100644
--- a/src/cargo/core/compiler/mod.rs
+++ b/src/cargo/core/compiler/mod.rs
@@ -688,6 +688,7 @@ fn path_args(bcx: &BuildContext<'_, '_>, unit: &Unit<'_>) -> (PathBuf, PathBuf)
         TargetSourcePath::Metabuild => unit.pkg.manifest().metabuild_path(bcx.ws.target_dir()),
     };
     assert!(src.is_absolute());
+    let src = fs::canonicalize(&src).unwrap_or(src);
     if unit.pkg.package_id().source_id().is_path() {
         if let Ok(path) = src.strip_prefix(ws_root) {
             return (path.to_path_buf(), ws_root.to_path_buf());
```

One drawback is that cache miss info (with `CARGO_LOG=cargo::core::compiler::fingerprint=trace`) may confuse the user in the presence of symlinks.

### PR DESCRIPTION
**Pull request by nmattia**
Fixes #7078.

When cargo registers information used later on to figure out whether or not to recompile a unit, the path to the source is tracked in the fingerprint. However this path is not canonicalized, meaning that e.g. symlinks aren't resolved before the source paths are added to the fingerprint.

See #7078 for a full description of the issue.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I don't think I'm entirely clear on the scenarios though of where this causes issues. Could you perhaps include a test which exhibits the behavior that this is fixing?

**Comment by nmattia** [comment]
@alexcrichton sure, will do! Looks like the Windows build is failing; the canonical versions of the paths don't seem to be recognized by cargo. Is this a known issue? Should the canonicalizing step be skipped on Windows?

**Comment by nmattia** [comment]
I wrote a test and rearranged history a bit. I pushed the test and I'll wait for CI to finish (fail) before I re-push the fix.

The test shows that if a crate has a local dependency on crate `a`, and if `a` is removed and replaced with a symlink to another crate `b/` (with `name = "a"`), cargo won't rebuild the dependency. By resolving symlinks first we don't lose much performance but yet work around this edge case.

The use case that interests me more is the other way around: the dependency `a` was already built but the symlink to it changed (before the fix `cargo` will rebuild `a` even though it's the exact same content). I could only reproduce when using source replacement, which I didn't quite manage to figure out in the tests (rust newbie here).

**Comment by nmattia** [comment]
The job indeed failed, see: https://travis-ci.com/rust-lang/cargo/jobs/213020941#L2554

**Comment by alexcrichton** [comment]
Hm ok I think I see what's going on here. The problem is that when detecting whether to rebuild something we're not taking into account any symlinks resolved along the way. Ideally we need to not only take into account the mtime of the file that rustc has read but also the mtime of any symlink inbetween. 

I don't think that this is the right fix since it only handles renames of the project root, and not renames of files underneath the project root which deal with symlinks. That being said this seems like it's very difficult to fix. I'm not really sure if there's a great fix for this other than content-based fingerprinting.

**Comment by nmattia** [comment]
Oh, content-based fingerprinting would be awesome! Is there any reason why this isn't currently implemented? Performance concerns?

**Comment by alexcrichton** [comment]
There's more information about it in https://github.com/rust-lang/cargo/issues/6529, but it wasn't implemented initially due to performance concerns yeah.

**Comment by alexcrichton** [comment]
Haven't heard back from you in awhile @nmattia so I'm gonna close this, but feel free to resubmit with comments addressed!

**Comment by nmattia** [comment]
I ended working around this and forgot to close. Thanks for the feedback!

**Pull request closed without merging**
