### PR TITLE
Remove outdated option to `-Zcheck-cfg` warnings

### PR DESCRIPTION
**Pull request by Urgau**
Forgot to remove those in https://github.com/rust-lang/cargo/pull/12845.

Note: Would it make sense to have feature-gate tests for those? and if so what would be the recommended way?

### CODE REVIEW

**Comment by epage** [comment]
> Note: Would it make sense to have feature-gate tests for those? and if so what would be the recommended way?

We regularly have feature gate tests.  In `check_cfg.rs`, just add a test with a build script and without a feature flag that  verifies the warning is in the output.

**Comment by epage** [comment]
Would you like to add the tests as part of this or should I merge it and you'll add them later?

**Comment by Urgau** [comment]
I can do it in this PR, let's me quickly add them.

**Pull request merged**
