### PR TITLE
Tweak Layout to allow for non json file targets with internal "."

### PR DESCRIPTION
**Pull request by evq**
Per @alexcrichton 's comment in https://github.com/rust-lang/rust/pull/55041#issuecomment-431363683, currently cargo assumes that a target with an internal `.` is a custom json target spec, using the file stem for the build directory name.

This PR changes cargo to only use the file stem for files with a `json` extension.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! To confirm, if you test this against the new target does everything work as expected?

**Comment by evq** [comment]
Sorry for the delay - I had previously tested these changes with the custom json target equivalent of my rustc changes, but I wanted to test end to end with a rustc with my target built in.

I have now tested with custom xargo, custom cargo and custom rustc and everything works as expected up until I get this error:

```
[user@personal:~/source/atsaml11xxx]% LD_LIBRARY_PATH=/home/user/source/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib XARGO_RUST_SRC=/home/user/source/rust/src xargo build --release --target thumbv8m.base-none-eabi --example blink
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v0.4.20
   Compiling unicode-xid v0.1.0
   Compiling rand_core v0.3.0
   Compiling vcell v0.1.0
   Compiling cortex-m-semihosting v0.3.1 (https://github.com/rust-embedded/cortex-m-semihosting?rev=471378bc848172e12e22b9a3b83190747e70bf5c#471378bc)
   Compiling cortex-m v0.5.8 (https://github.com/rust-embedded/cortex-m?rev=b70a2179f4e8ee7908b61a6a97970e0cfcf2f313#b70a2179)
   Compiling cortex-m-rt v0.6.5 (https://github.com/rust-embedded/cortex-m-rt?rev=9cd01176a6a9985c9bc0040801ed593687dd6ab1#9cd01176)
   Compiling aligned v0.2.0
   Compiling atsaml11xxx v0.1.0 (/home/user/source/atsaml11xxx)
   Compiling r0 v0.2.2
   Compiling volatile-register v0.2.0
   Compiling rand_core v0.2.2
   Compiling semver v0.9.0
   Compiling rand v0.5.5
   Compiling rustc_version v0.2.3
   Compiling bare-metal v0.2.4
   Compiling quote v0.6.9
   Compiling panic-semihosting v0.5.1 (https://github.com/evq/panic-semihosting?rev=3d7041af24969f32606e5eb804e23eaac7fb0bfa#3d7041af)
   Compiling syn v0.15.18
   Compiling cortex-m-rt-macros v0.1.3 (https://github.com/rust-embedded/cortex-m-rt?rev=9cd01176a6a9985c9bc0040801ed593687dd6ab1#9cd01176)
thread '<unnamed>' panicked at 'procedural macro API is used outside of a procedural macro', libproc_macro/lib.rs:1314:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: custom attribute panicked
  --> examples/blink.rs:14:1
   |
14 | #[entry]
   | ^^^^^^^^
   |
   = help: message: procedural macro API is used outside of a procedural macro

error: aborting due to previous error

error: Could not compile `atsaml11xxx`.

To learn more, run the command again with --verbose.
[user@personal:~/source/atsaml11xxx]% ls target
release  thumbv8m.base-none-eabi
```

This doesn't seem related to my changes, but maybe something stands out to you?

**Comment by evq** [comment]
I tested various configurations to try to narrow down the source of this issue - it seems to be related to the use of my local rustc build and not my cargo build.

Given that my only change to rustc was to add the thumbv8 baseline target I'm wondering if I'm missing something in my invocation above :/

**Comment by alexcrichton** [comment]
@evq ah ok, perhaps it's be easiest to test if we merge this, integrate it, and see how it works out? We can always revert!

**Comment by evq** [comment]
@alexcrichton turns out the error I was seeing above was because I was using a stage 1 build of rustc instead of stage 2. I missed the note that stage 1 has issues with procedural macros.

Everything is working as expected with a stage 2 rustc so this is good for merge from my end

**Comment by alexcrichton** [comment]
@bors: r+

Ok!

**Pull request merged**
