### PR TITLE
fix(resolver): Remove unused public-deps error handling

### PR DESCRIPTION
**Pull request by epage**
To implement rust-lang/rfcs#3516, we need to decouple the resolver's behavior from the unstable flag.  Since the code path is now dead, I went ahead and removed it.

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
std in `rust-lang/rust` makes use of public-private dependency. Does it affect building std there?

**Comment by Eh2406** [comment]
This looks reasonable. There is more to clean up in `resolver-tests` that needs to be done. The trickiest part of that will be https://github.com/rust-lang/cargo/blob/master/crates/resolver-tests/src/lib.rs#L328C92-L328C92

There may also be follow-up work where some data structures no longer need to be `RC`/`im`, but feel free to leave that for later.

**Comment by epage** [comment]
Noticed resolver-tests and am getting a failure in the aforementioned function,, so going to need to do some more digging.

**Comment by epage** [comment]
> std in `rust-lang/rust` makes use of public-private dependency. Does it affect building std there?

This is used for validation with maybe some backtracking to make things work better.  This shouldn't break anyone immediately and at worst it will make people need to do some more careful `cargo update`s.

**Comment by Eh2406** [comment]
I did a quick review, and it seems like there is still more to be excised. Specifically the code in
SatResolve https://github.com/rust-lang/cargo/blob/master/crates/resolver-tests/src/lib.rs#L328C92-L328C92 and registry_strategy in https://github.com/rust-lang/cargo/blob/master/crates/resolver-tests/src/lib.rs#L812

**Comment by epage** [comment]
The test in question was added in #6980 with public dependency support added in 6454efdd67dfbc426b275a7a1cfc45dd6fc0f392

**Comment by Eh2406** [comment]
Looking good so far! Next to remove https://github.com/rust-lang/cargo/blob/master/crates/resolver-tests/src/lib.rs#L812

**Pull request merged**
