### PR TITLE
test: migrate member_errors, multitarget and new to snapbox

### PR DESCRIPTION
**Pull request by eth3lbert**
### What does this PR try to resolve?

Part of https://github.com/rust-lang/cargo/issues/14039.

Migrate following to snapbox:

- `tests/testsuite/member_errors.rs`
- `tests/testsuite/multitarget.rs`
- `tests/testsuite/new.rs`

### CODE REVIEW

**Comment by epage** [comment]
Test failure is unrelated (see https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Fingerprint.20assert.20in.20tests).  Hoping it was random and not blocking all of CI.

@bors r+

**Comment by eth3lbert** [comment]
Ready for retry bors now!

**Pull request merged**
