### PR TITLE
Simplified Update Multiple Crate Output Formats

### LINKED ISSUE #9408: `cargo update` prints `Adding` + `Removing` lines when multiple versions of the same crate are updated
**Problem**
The more concise `Updating` lines are not printed if multiple versions of the same crate are updated in one command

**Setup**

```console
> cargo new foo && cd foo
> echo 'bs58_02 = { package = "bs58", version = "0.2.0" }' >> Cargo.toml
> echo 'bs58_03 = { package = "bs58", version = "0.3.0" }' >> Cargo.toml
> cargo generate-lockfile
Updating crates.io index

> cargo update -p bs58:0.2.5 --precise 0.2.0
Updating crates.io index
Updating bs58 v0.2.5 -> v0.2.0

> cargo update -p bs58:0.3.1 --precise 0.3.0
Updating crates.io index
Updating bs58 v0.3.1 -> v0.3.0
```

**Current**

```console
> cargo update
Updating crates.io index
Removing bs58 v0.2.0
Removing bs58 v0.3.0
Adding bs58 v0.2.5
Adding bs58 v0.3.1
```

**Expectation**

```console
> cargo update
Updating crates.io index
Updating bs58 v0.2.0 -> v0.2.5
Updating bs58 v0.3.0 -> v0.3.1
```

**Notes**

Output of `cargo version`: `cargo 1.53.0-nightly (65d57e6f3 2021-04-04)`

### PR DESCRIPTION
**Pull request by QiangHeisenberg**
close #9408

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR!

I'm not sure if this is the best fix though since this is just sort of blindly assuming that each pariwise mapping of these lists are the crate verisons that follow the updates. For example it could show 1->2.1 and 2.2->3.2 when in fact the update could be 1->3.2 and 2.1->2.2. I don't know of the best way to solve this, though. One possible solution is to bucket everything based on Cargo's idea of semver compatibility, and then for everything in its own bucket we could basically pair them either arbitrarily or in a sorted fashion.

**Comment by QiangHeisenberg** [comment]
> Thanks for the PR!
> 
> I'm not sure if this is the best fix though since this is just sort of blindly assuming that each pariwise mapping of these lists are the crate verisons that follow the updates. For example it could show 1->2.1 and 2.2->3.2 when in fact the update could be 1->3.2 and 2.1->2.2. I don't know of the best way to solve this, though. One possible solution is to bucket everything based on Cargo's idea of semver compatibility, and then for everything in its own bucket we could basically pair them either arbitrarily or in a sorted fashion.

I'm very sorry, but the reply was too late for some reasons.

I am thinking whether it is complicated to think about the problem? The current cargo update command seems to only upgrade the current version to the latest version in the current major version, but not the latest version in all versions.

for example:
```
PS D:\Rust\temp\update_test> cat .\Cargo.toml
[package]
name = "update_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_1 = { package = "rand", version = "0.1.1" }
rand_2 = { package = "rand", version = "0.8.3" }
```
then:
```
PS D:\Rust\temp\update_test> cargo update -p rand:0.1.4 --precise 0.1.1 > update.txt
    Updating `http://mirrors.tools.huawei.com/rust/crates.io-index/` index
    Removing libc v0.1.12
    Removing log v0.2.5
    Updating rand v0.1.4 -> v0.1.1

PS D:\Rust\temp\update_test> cargo update -p rand:0.8.4 --precise 0.8.3 > update.txt
    Updating `mirror` index
    Updating rand v0.8.4 -> v0.8.3
```
When we execute update, we will only update to the latest version of the current major version, that is, 0.1.1 to 0.1.4 instead of 0.8.4.
When I execute:
```
PS D:\Rust\temp\update_test> cargo update > update.txt
    Updating `mirror` index
      Adding libc v0.1.12
      Adding log v0.2.5
    Removing rand v0.1.1
    Removing rand v0.8.3
      Adding rand v0.1.4
      Adding rand v0.8.4
```
Therefore, after I modified it, it does not seem to affect the final result. The result is what I want.
```
PS D:\Rust\temp\update_test> cargo update > update.txt
    Updating `http://mirrors.tools.huawei.com/rust/crates.io-index/` index
      Adding libc v0.1.12
      Adding log v0.2.5
    Updating rand v0.1.1 -> v0.1.4
    Updating rand v0.8.3 -> v0.8.4
```

**Comment by alexcrichton** [comment]
Yes I understand the purpose of this change, but I believe my comment still applies where the logic of matching what-updated-to-what is not super principled and I think it could be better.

**Comment by alexcrichton** [comment]
Yes to reiterate I understand what this change is doing, and I understand why it's being done. My point is that this is a very simple heuristic being applied that I don't think is solving the underlying issue. I think that a better solution here would be to determine a pairwise "upgrade" for each version of the same crate that changed, and then these pairwise upgrades can be printed as additions if they came from nothing, deletions if they went to nothing, and upgrades if it came from something and went to something.

**Comment by alexcrichton** [comment]
Thanks for the PR, but I'm going to be [stepping down from the Cargo team](https://github.com/rust-lang/team/pull/712) so I'm going to un-assign myself from this. The Cargo team will help review this when they get a chance.

**Comment by ehuss** [comment]
Closing as this has become a bit stale, and it looks like there are some design considerations here.  Unfortunately the Cargo team does not have the capacity to accept changes of this kind at this time.

**Pull request closed without merging**
