### PR TITLE
Add `cargo fmt` to CI and delete `rustfmt.toml`

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit adds CI to run `cargo fmt` over Cargo itself as well as the internal
`crates-io` crate. This should switch Cargo to the "default style" (aka whatever
rustfmt spits out) and ensure that we keep it that way via CI. Hopefully this
won't be too much of a bother to keep up and running in CI as it should just be
a `cargo fmt` away!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Spot checking this it all looks pretty good to me, but it definitely wreaks havoc on the formatting in the tests. I figure we can try to touch things up there as we go along?

**Comment by matklad** [comment]
I've managed to fix horrendous formatting of single line strings with a bit of regex magic and reformatting with rustfmt again, you might want to cherry-pick this commit: https://github.com/matklad/cargo/commit/eb85b793a881e2c329e79a6554e94d3918248105

I have no idea what to do with multiline strings, I am not sure that "we can try to touch things up there as we go along", because every touch-up I've tried didn't produce a satisfactory result. But multiline strings don't look *that* bad. Also, not that our tests were particularly pretty beforehand :) 

Could we remove that sh script that checked for line lengths? Or is still needed for docs?

**Comment by alexcrichton** [comment]
Nice! I'll definitely throw that on before merging.

I also agree that the tests haven't really ever been too too pretty. I'm not too too worried in that tests are quite commonly write-once-read-never, but I'm also totally ok jumping on the "blindly run on `rustfmt` and don't worry" bandwagon.

I had forgotten we had a line-length script, although it looks like it's not actually run anywhere! I'll delete it here

**Comment by matklad** [comment]
r=me with script removed and the patch applied!

Overall, this looks awesome, but that's because I am a 

```
frobnicate(
    spam,
    eggs,
)
```

person myself, rather than

```
frobnicate(spam,
           eggs)
```

:)

**Comment by alexcrichton** [comment]
@bors: r+

Say goodbye to everything in Cargo's queue...

**Pull request merged**
