### PR TITLE
Use the custom HTTP transport when any HTTP settings are present

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
I'll probably need a bit of guidance on how the two failing tests *should* behave.

**Comment by alexcrichton** [comment]
Urgh. So the problem here is that the tests are asserting that the error message looks "mostly correct" but they're being a bit strict about the error message itself.

I'm not 100% sure that this is directly related to this change because in theory on AppVeyor this PR doesn't actually change behavior. Unless maybe AppVeyor has global Cargo configuration installed now? (not sure)

The tests are pretty important to make sure that the right support was compiled in (we want a "failed to connect" error not "ssl not supported" error) but actually matching the error is sort of difficult. Maybe the test assertions could just be tweaked though?

**Pull request merged**
