### PR TITLE
Always hash entire metadata

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Why are we hashing the filename while there are other factors that contributes
to binary difference?

BREAKING CHANGE: backward incompatible public API modification

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Can you describe how you ran into this, or what this is changing? At a glance I can't quite understand what the motivation for the PR is. A test case would certainly be quite useful!

**Comment by ishitatsuyuki** [comment]
I was digging into the rustbuild metadata hack, and filed this as a preparation of removing it. By ensuring all types of crate is hashed properly, we can simply intercept metadata option and pass it as extra-filename if it's​ omitted by cargo, thus the hack can be removed.

**Comment by alexcrichton** [comment]
Hm I'm not quite sure I follow. It looks like this is just passing consistent values of `-C metadata` for a crate regardless of where/how it's compiled, but that wasn't the problem, right? It was that crates like `bitflags` were compiled with the exact same source and the exact same `-C metadata`?

**Comment by ishitatsuyuki** [comment]
No, I'm not talking about that one. I'm trying to get rid of __CARGO_DEFAULT_LIB_METADATA, and to ensure no breakage would happen we should always hash things properly.

**Comment by alexcrichton** [comment]
Hm but this PR leaves that environment variable? How would we remove the env var?

**Comment by ishitatsuyuki** [comment]
Removed the hack. The proposed process is:
1. This is backported to beta.
2. We update stage0 compiler, alongside with rustbuild. We would be hacking this inside rustbuild by making bootstrap/rustc hook into metadata argument and append it as extra-filename if *not passed already*.

**Comment by alexcrichton** [comment]
Sorry but I may not be following. Won't the code as listed break rust-lang/rust because `-C extra-filename` won't get passed?

**Comment by ishitatsuyuki** [comment]
It's fine if we upgrade the bootstrap code and stage0 cargo at the same time. That would break local rebuild, which is why I didn't disable the flag at first.

**Comment by alexcrichton** [comment]
Er my point is that if we land this rustbuild has no way of generating `libstd-$hash.dylib`, which is the purpose of this env var.

**Comment by ishitatsuyuki** [comment]
All we need is the option `-C extra-filename`, which can be easily generated with the rustbuild interceptor.

**Comment by alexcrichton** [comment]
I originally thought we could do that, yes, but unfortunately it does not work. Cargo needs to know the exact output filename, and if we inject `-C extra-filename` behind its back then Cargo is tracking the wrong output artifacts.

**Comment by ishitatsuyuki** [comment]
Yeah, seems you're correct, I'm closing this then.

**Pull request closed without merging**
