### PR TITLE
Refactor so package publishing only determines git root in one place

### PR DESCRIPTION
**Pull request by nipunn1313**
Refactor so package publishing only determines git root in one place

Depends on #9837

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
@bors: r-

carrying over https://github.com/rust-lang/cargo/pull/9837#issuecomment-908401683

**Comment by nipunn1313** [comment]
(probably we should prefer something like #9866 to this)

**Comment by nipunn1313** [comment]
Closing in favor of #9866

**Pull request closed without merging**
