### PR TITLE
Skip extracting .cargo-ok files from packages

### PR DESCRIPTION
**Pull request by steven-joruk**
This is for #8816

I'll look into adding a unit test tomorrow, I'm still familiarising myself with the project.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks pretty reasonable to me, thanks! I think you can write a test for this with `Package` which allows specifying arbitrary files to include as well. I'd be sure to double-check that the test fails before this fix but there should be plenty of examples in `tests/testsuite/*.rs` about how to publish packages in the tests.

**Comment by steven-joruk** [comment]
I also changed the fix when adding the tests, Alex. Now it just creates the lock file after unpacking, rather than skipping extracting a lock file from the package.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great to me, thanks!

**Comment by ehuss** [comment]
FWIW, I was intending for this to skip the `.cargo-ok` file during extraction. That would ensure that if extraction is interrupted, and the package contained a `.cargo-ok` file, that it would still retry to extract it next time.  I think that is extremely unlikely to ever happen, so I don't think this needs to change, but just wanted to leave a note about it.

**Pull request merged**
