### PR TITLE
Support uninstallation of multiple packages

### LINKED ISSUE #4560: Add support for removing multiple packages with cargo uninstall
The ergonomics of `cargo uninstall` would be improved if it supported uninstalling multiple packages at once.

Since many tools (rustfmt included) require nightly to install, it's not uncommon to use nightly with `cargo install`. However, since nightly receives daily updates, the binaries installed with `cargo install` usually stop working with a nightly update (since the underlying dynamic library file names tend to change) which requires frequent `cargo uninstall`/`cargo install` gymnastics.

Furthermore, supporting uninstallation of multiple packages with a single command would mirror the ability to install multiple packages with a single `cargo install` command.

Open question:
- How should specifying `--bin` interact with uninstallation of multiple packages? (I believe this isn't handled in the `cargo install` case, so it may be a moot point here as well.)

### PR DESCRIPTION
**Pull request by nossralf**
This is a WIP pull request with support for uninstalling multiple packages. It mirrors the logic used for `cargo install`.

Fixes #4560

### CODE REVIEW

**Comment by matklad** [comment]
Looks great @nossralf !

One question I have though is what is the interaction between `--bin` and multiple specs? Looks like currently passing `--bin` and several packages will try to remove the binary from all these packages, which does seem surprising...

Perhaps a safe option would be to forbid passing both `--bin` and several specs?

**Comment by nossralf** [comment]
Thanks! Yeah, that's the one thing I was uncertain of (I mentioned it in the issue I, perhaps redundantly, created for this, #4560).

The thing is, `cargo install` doesn't have any special handling for `--bin` in conjunction with multiple packages, which means it will just show errors for any packages that don't have binaries with that name, and install the ones that do.

I guess there is a case to be made for having `install` and `uninstall` effectively be mirrors of each other. Although I'm not sure if that speaks more to leaving `uninstall` like this or changing `install` to also have a check disallowing `--bin` when called with multiple packages?

I'll happily update the PR with such a check here. A question in that case, I suppose the check would happen in `ops/cargo/cargo_install.rs` as opposed to `bin/uninstall.rs`. From what I can tell, validation (besides docopt's automatic validation) happens in `ops/`, and then one uses `bail!` to exit.

**Comment by nossralf** [comment]
Updated the pull request to add an early bailout if `--bin` is given along with multiple packages. Also updated an existing test to use the new functionality, and added a new one to test the bailout.

The wording in the bailout message can probably be better.

**Comment by matklad** [comment]
Oh, sorry, this completely has fallen of my radar :( 

Changes look good to me!

There were some concerns on the issue that we perhaps don't need this option. I personally feel like we should have at at least because install does, but let's ask @withoutboats and @alexcrichton as well.

Question 1: do we need #4650 ?
Question 2: what is the peocedure for such small feature request? How should I decide if I can give an r+? How can a contributor be sure that an issue with a feature lablel is indeed intended to be fixed, and that the PR won't be turned down after the fact?

**Comment by nossralf** [comment]
Oh, no worries! I'm in no hurry.

I realize it's a gamble to submit a PR for a feature suggestion before it has been approved on the feature level. I would understand if the PR was closed without merging if the feature itself isn't approved for good reasons, that makes perfect sense. I think this change has merit, but understand if Cargo maintainers disagree. (I've personally still gotten value out of writing the code, since it's been good practice for me in learning Rust.)

Anyways, I had another test I wanted to add to this, and that's done now.

**Comment by alexcrichton** [comment]
This looks great to me, thanks @nossralf!

@matklad I think this is a fine feature to add, and in general we've been pretty lax about adding features to Cargo. If someone's motivated enough to send a PR that's typically enough to say "sure!". Overall though I tend to just figure that if it's "reasonable" (for whatever definition you'd like) it's good enough, and then canvassing the wider team failing that.

**Comment by withoutboats** [comment]
> If someone's motivated enough to send a PR that's typically enough to say "sure!". Overall though I tend to just figure that if it's "reasonable" (for whatever definition you'd like) it's good enough, and then canvassing the wider team failing that.

I'd like to move away from this :sweat_smile: (esecially since features in cargo have tended to be insta-stable) but I still agree that in this case being symmetrical with install is closer to being a bug fix than a new feature.

**Comment by matklad** [comment]
Excellent, thanks @nossralf 

@bors r+

**Pull request merged**
