### PR TITLE
Check local targets before resolving dependencies

### LINKED ISSUE #2266: cargo run  --example checking
User mistypes, leaves the computer, comes back to nothing. `Cargo` should do the check at the start.

````
$  cargo run --example helloworld.rs 
    Updating git repository `https://github.com/arthurprs/nix-rust.git`
    Updating git repository `https://github.com/arthurprs/tendril.git`
 Downloading encoding-index-japanese v1.20141219.5
 Downloading encoding-index-korean v1.20141219.5
 Downloading encoding-index-tradchinese v1.20141219.5
 Downloading promising-future v0.1.6
 Downloading twox-hash v0.1.1
 Downloading spin v0.3.4
 Downloading threadpool v0.1.4
 Downloading futf v0.1.1
 Downloading encoding-index-singlebyte v1.20141219.5
 Downloading redis v0.5.2
 Downloading url v0.5.2
 Downloading fnv v1.0.0
 Downloading miow v0.1.1
 Downloading linked-hash-map v0.0.7
 Downloading cfg-if v0.1.0
 Downloading debug_unreachable v0.0.6
 Downloading slab v0.1.3
 Downloading net2 v0.2.20
 Downloading encoding_index_tests v0.1.4
 Downloading void v0.0.5
 Downloading encoding v0.2.32
 Downloading fs2 v0.2.2
 Downloading mio v0.5.0
 Downloading encoding-index-simpchinese v1.20141219.5
 Downloading nix v0.4.2
 Downloading mac v0.0.2
 Downloading unreachable v0.0.2
 Downloading bytes v0.3.0
 Downloading sha1 v0.1.1

no example target named `helloworld.rs`
````

Has to be restarted with:
`$  cargo run --example helloworld`

 Maybe `cargo` could strip the trailing `.rs` automatically?

### PR DESCRIPTION
**Pull request by ryanq**
A call to `generate_targets(...)` before calling `resolve_dependencies()`
catches invalid target names before fetching the source for the
dependencies.

Closes #2266

### CODE REVIEW

**Comment by ryanq** [comment]
Ignoring the return value of `try!(generate_targets(...))` feels wrong to me, but I'm not sure of a better way to 'ignore' them. Any thoughts are welcome.

(This PR is related to #2482.)

**Comment by alexcrichton** [comment]
I don't think this is quite right because `generate_targets` is called in a bunch of different ways below (for example if the `-p` argument is passed). I think the only case in which this'll work is if the `-p` argument isn't passed perhaps?

**Comment by ryanq** [comment]
@alexcrichton I'm not sure how the `-p` flag operates, but I took a look through `generate_targets` and I can't find how the `-p` would change it. The function looks like it calculates the relevant profile and then runs through the targets of the root package to check that they match the `CompileFilter` options.

What changes does '-p' make to cargo's operation?

**Comment by alexcrichton** [comment]
Ah the `-p` argument typically changes what the package argument is to `generate_targets`, it selects a package in the dependency graph to operate on.

You'll notice that `generate_targets` is called in a number of ways below, and each one is subtly different in terms of the arguments it takes.

**Comment by petevine** [comment]
Why can't any `local files` related checks be done right after checking for `Cargo.toml`?

**Comment by alexcrichton** [comment]
@petevine I'm not sure I understand your question? In the case of `-p` the `Cargo.toml` in question may need to be downloaded from crates.io, we only know for sure that it's the root package (the one on the filesystem passed in) if there is no `-p` argument.

**Comment by petevine** [comment]
Right, `-p` does complicate things; I meant just the local Cargo.toml and any other files (e.g. examples) that could be checked for locally (not sure which subcommands could also benefit from this).

**Comment by alexcrichton** [comment]
Yes, that is what I meant by my [original comment](https://github.com/rust-lang/cargo/pull/2501#issuecomment-198764775)

**Comment by ryanq** [comment]
I think to accomplish checking the local targets before the dependency resolution, I'd need to *not* use the `generate_targets(...)` function and create a new function to do that task. Is that what you mean?

**Comment by alexcrichton** [comment]
I think that `generate_targets` is still fine to call, you'll just want to only call it in the case that there's no `-p` argument.

For example only some of the calls to `generate_targets` is valid below to lift up, and only those can be lifted up before resolution

**Comment by ryanq** [comment]
I'll add a special case around it and update.

**Comment by alexcrichton** [comment]
Oh oops, thanks for the update @ryanq! Feel free to ping a PR whenever you update it as unfortunately github doesn't send out notifications for that :(

@bors: r+ 10ee610bb7703662d8ee70090a3fe85f48f9a06e

**Pull request merged**
