### PR TITLE
Add proc_macro to the extern prelude.

### PR DESCRIPTION
**Pull request by ehuss**
This makes it so that a proc-macro library can use the `proc_macro` crate without the `extern crate proc_macro;` item on the 2018 edition.  This is the Cargo half of https://github.com/rust-lang/rust/pull/64882.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me, but I think this may need to be gated?

**Comment by ehuss** [comment]
Oops. I assume you mean in the test?

**Comment by alexcrichton** [comment]
Oh! I believe beta/stable are failing because `--extern` isn't stable, so we'll need to do some brief version detection to pass `--extern proc_macro` to proc-macro crates. 

I also see that this is a new language feature, but I believe this has already been signed off by all the requisite teams, so we should be good to go when CI is ready

**Comment by ehuss** [comment]
Sorry, I was being dumb.  I added a dynamic test in the same fashion as the old pipeline test. Does that seem reasonable?

**Pull request merged**
