### PR TITLE
1.44.1 stable backports

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Tried to duplicate https://github.com/rust-lang/cargo/pull/8335, though had to manually adjust 3b9e8dc4c1dc6a6ec714acb6a97b4f7cffda1176 (cherry-pick of #8329) as it had a merge conflict.

Stable backports for:

* #8329 — Don't hash executable filenames on apple platforms. (fix macos backtraces)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
(Do we also need to bump the Cargo version or so? Let me know.)

**Comment by Mark-Simulacrum** [comment]
Hm not sure what's up with the test failures, maybe I broke something?

**Comment by alexcrichton** [comment]
This can happen since nightly features periodically break. I don't think anything is wrong at this time, and those failures look pretty benign. We could merge this as failing (which seems fine by me) or the change that fixed this in Cargo could get hunted down and cherry-picked here too

**Comment by Mark-Simulacrum** [comment]
Okay I tried cherry-picking a fix but that didn't seem to fix the tests fully so I've dropped it now. I'm fine with merging with tests not passing, I agree they look benign.

**Comment by alexcrichton** [comment]
Mind deleting the tests in question and then this should be r+'able?

**Comment by ehuss** [comment]
I'm pretty sure this should not include #8290.  That regression only applied to beta.

**Comment by Mark-Simulacrum** [comment]
@ehuss -- dropped #8290. I had included it per Zulip message but I guess I probably misunderstood.

**Comment by ehuss** [comment]
Ah, sorry for the confusion, I hadn't looked at the exact PR # in zulip.  

As for the version number, I am ambivalent. If you want to publish a new version, that would be fine. But it probably isn't too important, and this will get picked up in the next release next month anyways.

r=me if everyone is ready.

**Comment by Mark-Simulacrum** [comment]
Seems good to issue a new release, and will give us another run at publish.py -- I bumped to 0.45.1 as I believe there's no API breakage involved in this PR. Can you confirm I don't need to bump any other crates?

**Comment by ehuss** [comment]
I don't think any other crates need to be changed.

**Pull request merged**
