### PR TITLE
Delete the old docs, lift up the new

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit deletes the old documentation now that the "official source" is the
main book. The book is now lifted up directly into `src/doc` instead of
`src/doc/book`.

The CI no longer builds documentation and has been updated to just run mdbook to
make sure there's no errors. The documentation will actually get published in
the rust-lang/rust repo

### CODE REVIEW

**Comment by wking** [comment]
This PR seems to have dropped changes which had only been made to the old docs.

For example, 45cc30bc (#4817) added `incremental` to `src/doc/manifest.md` but not `src/doc/book/src/reference/manifest.md`.  After this PR, `incremental` no longer shows up under `src/doc`:

```console
$ git grep incremental a44612f2 -- src/doc/
…no hits…
```

I think we need to audit the renames here to see what was dropped, and file cherry-picks (or something) to recover the lost updates.

**Comment by alexcrichton** [comment]
Good catch @wking! Mind double checking https://github.com/rust-lang/cargo/issues/4906 to make sure it didn't miss anything?

**Comment by wking** [comment]
Ah, sorry.  I hadn't noticed #4906 fixing these.

**Pull request merged**
