### PR TITLE
List available binary names

### PR DESCRIPTION
**Pull request by pornel**
When a project has multiple executables `cargo run` fails, but offers an incomplete solution (suggests `--bin`, but not its arguments.)

This PR adds a list of available binary names to the error message.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Mind adding a test for this as well?

**Comment by alexcrichton** [comment]
The rendering here looks may not be the most obvious perhaps? I wonder if we could do something liek `available binaries: a, b, c, ...` (and also maybe truncate if >3 names or something like that?)

**Comment by pornel** [comment]
The `CargoError` object doesn't seem to have a way to add any structured annotations. 

I've implemented it specifically for gstreamer-rs:

> error: `cargo run` requires that a project only have one executable; use the `--bin` option to specify which one to run (gtkvideooverlay, events, toc, appsrc, playbin, pad_probes, tokio, launch_glib_main, appsink, gtksink, queries, decodebin, player, iterator, launch)

so limiting it to few would eliminate its usefulness, because I'd have to figure out how to get the list some other way.

**Comment by pornel** [comment]
I've updated display format. It'd be OK to add a dedicated command to get the list of binaries, but I think having the list in this error message is ideal: it's in the right place at the right time.

**Comment by alexcrichton** [comment]
@rust-lang/cargo, any thoughts on this?

**Comment by matklad** [comment]
A very nice improvement in usability, +100!

**Comment by matklad** [comment]
I wonder if we should add something like:

```
To add add a binary to cargo project, create an `src/main.rs` file, or add a `[[bin]]` section to Cargo.toml
```

to the case where `bins.len() == 0`.

**Comment by matklad** [comment]
>I also figure that the way of learning a crate's packages probably shouldn't be done through an error message, but probably something more first-class?

We have `cargo metadata` for that :) 

Does this new error message work for the case where user makes a typo?

**Comment by pornel** [comment]
> Does this new error message work for the case where user makes a typo?

No, there's already correction for typos and it's handled separately.

**Comment by pornel** [comment]
Does this PR require any more changes?

**Comment by pornel** [comment]
ping

**Pull request merged**
