### PR TITLE
Reinstate CARGO_PRIMARY_PACKAGE (take 2)

### PR DESCRIPTION
**Pull request by ebroto**
As discussed in [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/RUSTC_WORKSPACE_WRAPPER/near/212461098)

r? @ehuss

### CODE REVIEW

**Comment by alexcrichton** [comment]
Would you be ok adding documentation for this new environment variable as well as a test?

**Comment by ehuss** [comment]
Just a minor note: It might also be worthwhile to consider a more precise name.  This is only set for the root units, and isn't necessarily the root "package".  For example, if you run `cargo test`, any binaries in a package will be built, but they aren't "primary".  Or `cargo build --bin foo`, the binary target will be a root, but the library will not be marked as "primary".

Maybe `CARGO_ROOT_TARGET`?  `CARGO_ROOT_UNIT`?  `CARGO_PRIMARY_TARGET`?  `CARGO_ROOT_CRATE`?  Hm, these terms are a bit overloaded, vague, or potentially confusing.  Any other ideas?

**Comment by ehuss** [comment]
Oh, wait, nevermind, I misread how that is implemented.   `CARGO_PRIMARY_PACKAGE` is good I think.

**Comment by ebroto** [comment]
>Would you be ok adding documentation for this new environment variable as well as a test?

Of course! Besides the doc, I've added the following tests:
- in `build.rs`, make sure it's only set for the primary package and not for deps of any kind
- in `workspaces.rs`, one for "simple" and one for virtual workspaces, trying some combinations of `-p` and `--all`.

Please tell me if I missed some cases or if I put them in the wrong place :)

**Comment by ehuss** [comment]
Thanks!

@rust-lang/cargo This will add a new, stable environment variable set when running `rustc`. `CARGO_PRIMARY_PACKAGE` indicates that this is one of the "root" packages requested on the command-line (via `-p` or the default package).  The use case for this is primarily for clippy, so that it can know if it should emit lints.  In particular, this will help with the `--fix` flag, so that it doesn't attempt to run clippy on other dependencies in a workspace, which can cause errors and problems.  This can also help with solving https://github.com/rust-lang/rust-clippy/issues/3025, though that issue will require some additional UI on the clippy side to determine whether or not it runs for all members. This should help lead towards stabilizing #8143 (`RUSTC_WORKSPACE_WRAPPER`) which will fix the caching problems with clippy.

I think it is OK to go straight to stable for this, though feel free to disagree. I expect that after updating clippy and testing some things out, we can move to stabilize `RUSTC_WORKSPACE_WRAPPER` soon as well.

@rfcbot fcp merge

**Comment by Mark-Simulacrum** [comment]
FWIW perf.rlo is also interested in this and uses a hack (`cargo rustc -- --wrap-rustc-with $prog`) to workaround this today; the extra argument is intercepted with a wrapper script and stripped (some other processing is also done). Once this is added I'd definitely be interested in reworking perf to rely on it over the wrap-rustc-with option.

**Comment by ehuss** [comment]
Oh, I should have paid closer attention to the CI status. @ebroto, the tests can't check the environment variables via the verbose output, since the output is different for different platforms. Can you update the tests to a different approach?  There are a variety of different options. Maybe just use `env!` to capture the value, and use `cargo run` or `cargo test` to run some code the verify the value is correct?

**Comment by ebroto** [comment]
@ehuss I've reworked the tests following your suggestion. I think it helped to simplify the implementation. Thanks!

**Comment by ehuss** [comment]
Thanks!
@bors r+

**Pull request merged**
